### ISSUE TITLE
Can't map the keys to ALT+SPACE.

### ISSUE THREAD

**Issue by Abhinav1217** [Ulauncher/Ulauncher#100]
I tried using settings option but `ALT+Space` Doesn't map, It always go to my DE's mapped option . So I directly changed it in the .config/settings.json file and it still crashes.

All the previous apps I used to use were able to map it to this keyboard combo. I then unmapped this combo from the DE ( I use Gnome ) and then tried to map it, Still doesn't work.

**Comment by gornostal** [comment]
I tried it myself and also got error.
It's coming from Keybinder lib, there is nothing I can do here. Sorry.

**Comment by Abhinav1217** [comment]
Cerebro also have this problem. But there I could manually edit the config file and map it to ALT+SPACE. and it works. Even if GUI mapping is not working because of keybinder lib error, Hacking the config file should be able to do the trick. Is there no other error?

**Comment by gornostal** [comment]
In that case I'll check how Cerebro binds to Alt+Space

**Comment by gornostal** [comment]
Sorry Alt+Space won't work with Ulauncher.

Cerebro app uses totally different tools for key bindings + the most popular Linux DEs already use Alt+Space to show a window menu.

**Comment by suberb** [comment]
Make sure no app is using ALT+SPACE. Open ULauncher Preferences. Map keys to **Alt+Super L** (the order is important) and exit ULauncher. Then, edit *settings.json* in `home/user/.config/ulauncher` and change *Super L* to *space*. You should have sth like this: `"hotkey-show-app": "<Alt>space"`. Save & launch ULauncher.

**Comment by epergo** [comment]
Thx @suberb , super easy solution, this could be in Readme
