### ISSUE TITLE
Error trying to "toggle" v6

### ISSUE THREAD

**Issue by troycurtisjr** [Ulauncher/Ulauncher#1000]
### Environment

Fedora 36

### Bug description

Using the latest v6 code I can't seem to "toggle" the ulauncher window. I keep getting:

```
Failed to register: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib64/python3.10/site-packages/dbus/service.py", line 662, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib64/python3.10/site-packages/dbus/service.py", line 252, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: DescribeAll is not a valid method of interface org.gtk.Actions
```

I haven't been able to nail down yet what is going on, but I'll keep digging tomorrow.

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Latest version

- [X] I am using the latest Ulauncher release.

**Comment by friday** [comment]
You have a customized v5 ulauncher-toggle in ~/.local/bin or something?

`cat $(which ulauncher-toggle)`?

**Comment by friday** [comment]
There's no toggle method listening to the dbus call any more, but there shouldn't be any dbus calls either. It was only used in ulauncher-toggle before.

**Comment by troycurtisjr** [comment]
This is actually just trying to run ulauncher again (via ./ul run in my working copy) to bring up the existing instance. I believe gtk application uses dbus to accomplish that, I just haven't been able to figure out why it isn't working for me now. It did when I played with the branch originally. I thought maybe it was picking up old ulauncher code so I uninstalled my system version and cleaned out everything from .local. so far no luck.

**Comment by friday** [comment]
> I believe gtk application uses dbus to accomplish that

Yes. This is true. It uses dbus internally to call methods on the main instance instead of the remote. So I guess this is a GTK issue. I really hope we can find a way around it.

**Comment by troycurtisjr** [comment]
So after a reboot, it seems to work. It kinda seems similar to what is described here https://bugs.launchpad.net/ubuntu/+source/seahorse/+bug/1154049  On one hand, a reboot got it working, but this comment makes it a bit concerning:

> For me, the crash happens occasionally: after a reboot it works again.
> Apparently it stops working at some point.

I wonder if it is something to do with an early exit condition, I had a couple of errors on one of my runs and maybe it put some things in a bad state. Maybe some hints can be found in that thread as well, like around comment 17. The last comment is a bit ominous:

> searches show that people have been getting this error for almost a decade on all sorts of different apps:

**Comment by friday** [comment]
Yeah, I read this bug report already from googling the error.

#1003 could possibly have provided a workaround for this, assuming the problem is limited org.gtk.Actions.DescribeAll.
If it happens again we could try running

```sh
gdbus call --session \
  --dest net.launchpad.ulauncher \
  --object-path /net/launchpad/ulauncher \
  --method org.gtk.Actions.DescribeAll
```

It outputs `(@a{s(bgav)} {},)` for me now, which I'm sure means... something.

**Comment by troycurtisjr** [comment]
I'm betting with #1003 I won't have this trouble again, so closing. Also it makes my shortcuts a bit nicer/easier to run directly out of my working copy :smile:
