### ISSUE TITLE
Ulauncher does not open in blank desktop (wayland)

### ISSUE THREAD

**Issue by default-303** [Ulauncher/Ulauncher#1010]
### Environment

EndeavourOS (gnome)

### Bug description

Hey, 
So, ulauncher pops up and works perfectly when i have a program (any) opened. But fails to show up when I'm in  a blank desktop(no programs running). This happens only on wayland.

However, ulauncher works perfectly on xorg. Regardless if i have programs opened or not. 

Is there a way to get this working on wayland? 

### Log output

```shell
DBus name already taken. Ulauncher is probably backgrounded. Did you mean `ulauncher-toggle`?
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Latest version

- [X] I am using the latest Ulauncher release.

**Comment by friday** [comment]
Ulauncher runs as a service in the background. You can only run one instance. Follow the troubleshooting to make it work in Wayland

**Comment by friday** [comment]
I re-read and think I misunderstood the issue. Sorry.

**Comment by default-303** [comment]
yeah sure I'm open to diagnosing the issue myself. How do i get started?

**Comment by friday** [comment]
https://github.com/Ulauncher/Ulauncher/blob/v6/CONTRIBUTING.md

**Comment by default-303** [comment]
hey, you may close this issue....https://github.com/Ulauncher/Ulauncher/wiki/Hotkey-In-Wayland this actually fixes the issue.
