### ISSUE TITLE
Malformed desktop entries fails to load in Ulauncher (Gio) although they work in KDE's native launcher(s).

### ISSUE THREAD

**Issue by iwex** [Ulauncher/Ulauncher#1011]
### Environment

Manjaro, KDE

### Bug description

Hi! When I open ulauncher and try to search for Google Chrome or Vivaldi (browser), Ulauncher doesn't see them. In default application launcher menu they are present.
Their .desktop entries are located in $HOME/.local/share/applications

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Latest version

- [X] I am using the latest Ulauncher release.

**Comment by friday** [comment]
Do you see them with the `ulauncher-git` AUR package?

**Comment by iwex** [comment]
That command prints `[['vivaldi-agpmgihmmmfkbhckmciedmhincdggomo-Default.desktop']]`

**Comment by friday** [comment]
Ok. That's good :+1:

Can you upload that file here?

**Comment by iwex** [comment]
Hmm, it points to chrome extension

```
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=Logitech Unifying for Chrome
Exec=/opt/vivaldi/vivaldi --profile-directory=Default --app-id=agpmgihmmmfkbhckmciedmhincdggomo
Icon=vivaldi-agpmgihmmmfkbhckmciedmhincdggomo-Default
StartupWMClass=crx_agpmgihmmmfkbhckmciedmhincdggomo
```

**Comment by iwex** [comment]
So actually that command didn't find correct vivaldi .desktop

**Comment by friday** [comment]
`vivaldi-agpmgihmmmfkbhckmciedmhincdggomo-Default.desktop` definitely seems like a flatpack or snap

This is the method we actually use in v6:
https://lazka.github.io/pgi-docs/Gio-2.0/classes/AppInfo.html#Gio.AppInfo.get_all

It removes invalid entries when `Exec` specifies a path that doesn't exist.
So you should delete the `vivaldi-agpmgihmmmfkbhckmciedmhincdggomo-Default.desktop` one as you don't have any `/opt/vivaldi/vivaldi`. 


The second one `vivaldi-stable.desktop` specifies `Path[$e]=` which is some junk left by an invalid build I think. You need to remoe that. And [`[Desktop Entry] is the header and needs to be first`](https://gitlab.gnome.org/GNOME/glib/-/issues/1987#note_678627) , so move the `[Desktop Action]` lines below. After that it should work if the second file is in the right path and `/usr/bin/vivaldi-stable` exists.

**Comment by friday** [comment]
I have now documented this in the troubleshooting: https://github.com/Ulauncher/Ulauncher/discussions/991#user-content-invalid-entries
