### ISSUE TITLE
Calculator still has floating point errors if you input numbers with 15 decimals

### ISSUE THREAD

**Issue by friday** [Ulauncher/Ulauncher#1013]
### Environment

Any

### Bug description

We already convert the floats to decimals to avoid floating point errors that are introduced in the calculations, but this can already be too late with a very precise input with many decimals.

`.55555444444444444` for example will show as 0.5555544444444444**5**

The ast just assumes that the code is Python code, and in Python this code would be a float unless it says `Decimal('0.55555444444444444')`. 

```py
import ast
print(ast.parse('.55555444444444444', mode='eval').body.value)
```

See https://stackoverflow.com/a/35415702/633921 for a solution, although I don't know if it's really worth this.

Another way could be to just regex all numbers from `N` to `Decimal('N')`

I mostly wanted an issue to document this and use for reference.

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Latest version

- [X] I am using the latest Ulauncher release.

**Comment by iaacornus** [comment]
still need to fix this? i can send a patch

**Comment by friday** [comment]
@iaacornus I have already "fixed" this particular example by reducing the amount of decimals to hide the issue. But I don't know if this fixes all such errors.

Technically what we do now is:

```python
import ast
from decimal import Decimal
value = ast.parse('.55555444444444444', mode='eval').body.value # becomes 0.5555544444444445
decimal_Value = Decimal(value) # becomes Decimal('0.5555544444444444618369516319944523274898529052734375')
Decimal(value).quantize(Decimal("1e-15")) # reduced to 15 decimals, which in this case is the input value
```

I'm not sure reducing to 15 decimals is enough to fix all such errors, but I haven't seen any issues now and 15 decimals is probably more than enough anyway. If you have a better fix  that doesn't add a lot of complexity you're welcome to submit a PR.

**Comment by iaacornus** [comment]
frankly, ulauncher's builtin calc is only used for rapid calculations that require neither such precision nor accuracy. I think it would be fine if we will just round it off and just truncate the output to say, 4 significant figures? or better, I think let's just round the numbers by significant figures based on the given operation, which is what is really done in practical aspect. what do you think?

**Comment by friday** [comment]
Rapid calculations, yes, but that doesn't mean imprecise. You don't know what other people use it for. For example see #1015.

Let's just close the issue and if someone has a real issue with it they can create  a new one.
