### ISSUE TITLE
Possibility to use the "selected by default" option

### ISSUE THREAD

**Issue by Rapha149** [Ulauncher/Ulauncher#1017]
### Description

The class `ResultItem` has an option named `selected_by_default`. I guess using this should set which option is selected when the `RenderResultListAction` is returned.  
Unfortunately the class `ExtensionResultItem` overrides the method that in the class `ResultItem` returns the option and instead checks if the query was previously associated with the name of the item.  
Is there a way to use the option `selected_by_default`? Because subclassing the class `ExtensionResultItem` does not work, as it is also mentioned in the class itself.  
If that is not possible, is there a way to implement this function? Because it would be helpful if you use something like a "Back" button and different submenus and if you go back, the previously pressed item is selected.

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing enhancement requests](https://github.com/Ulauncher/Ulauncher/labels/enhancement) before suggesting this.

**Comment by friday** [comment]
It's not a public property. It's an implementation detail that was [removed](https://github.com/Ulauncher/Ulauncher/commit/81e5fc566e181eaf5e14111ea0a60114c9c08399) in v6 (and not coming back). If you want to add "default" options, why don't you put them as the first result?

**Comment by Rapha149** [comment]
Oh, that's unfortunate.
Well, as shortly addressed in the description, I have made an extension that has certain submenus but changing the order of the elements would be confusing.
I'm going to close this issue if the option wasn't intended for use (in extensions) anyway.

**Comment by friday** [comment]
This was only for remembering which result what the user picked last time given the exact same input query, and pre-selecting that. Even this behavior I think can be argued to hurt users in addition to helping, as it adds another concept and an exception to the rule. I would not have implemented this myself, and think it'd be better and more consistent to move that result to the top.

I'm not saying the feature in itself is unwelcome though. We could add it if there's enough reason to, but you're the only one who asked for it so far and I think what you want to do is manually implement things in the extension that we may want to support/handle in the app like #326 and/or #525

**Comment by Rapha149** [comment]
Yeah, that's understandable.
But, I don't quite get how I would implement this in the extension if it's not implemented in the app - what other options than using the `select_by_default`, which doesn't work for extensions and is not intended for this, do I have? I can't exactly force the users to use a fork of Ulauncher just to be able to use my extension.
