### ISSUE TITLE
About section still shows 2.0.14 as the version number

### ISSUE THREAD

**Issue by GGimenez96** [Ulauncher/Ulauncher#102]

**Comment by gornostal** [comment]
Can you provide more details?
Your OS, where you downloaded the app.

**Comment by GGimenez96** [comment]
Ubuntu 16.04.2 LTS. I downloaded it from the Download section of the official site (http://ulauncher.io/).

**Comment by gornostal** [comment]
Thanks for reporting this issue.
I'll look into it

**Comment by gornostal** [comment]
@GGimenez96 I cannot reproduce this issue.
Try to install this deb package again
https://github.com/Ulauncher/Ulauncher/releases/download/2.0.30.r3/ulauncher_2.0.30.r3_all.deb

**Comment by GGimenez96** [comment]
I don't know why it happened. I noticed that after restarting my PC it was fixed.

**Comment by gornostal** [comment]
OK. Closing this ticket.
