### ISSUE TITLE
ppa for ulauncher and ubuntu 22.04

### ISSUE THREAD

**Issue by sliddjur** [Ulauncher/Ulauncher#1021]
### Environment

22.04 ubuntu

### Bug description

https://launchpad.net/~agornostal/+archive/ubuntu/ulauncher
can you please add ppa in 22.04? 

### Log output

```shell
apt update:

Err:10 https://ppa.launchpadcontent.net/agornostal/ulauncher/ubuntu jammy Release
  404  Not Found [IP: 91.189.95.85 443]
Reading package lists... Done                            
E: The repository 'https://ppa.launchpadcontent.net/agornostal/ulauncher/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Latest version

- [X] I am using the latest Ulauncher release.

**Comment by friday** [comment]
Should be fixed now. Please let me know otherwise.

Interesting username btw (I assume you're Swedish :D)

**Comment by minjaep** [comment]
> Should be fixed now. Please let me know otherwise.

Can I ask the same thing for Ubuntu 23.04?

**Comment by friday** [comment]
> > Should be fixed now. Please let me know otherwise.
> 
> Can I ask the same thing for Ubuntu 23.04?

Should work now
