### ISSUE TITLE
Ulauncher doesn't see a decent part of my applications

### ISSUE THREAD

**Issue by cryptoEcho** [Ulauncher/Ulauncher#1022]
### Environment

Manjaro KDE

### Bug description

I install Ulauncher from two different sources: aur and github, and faced this problem.
For example I have three snaps: Insomnia VScodium and VSCode. Ulauncher doesn't see the latter.
I also can not find konsole or google-chrome via Ulauncher.

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Latest version

- [X] I am using the latest Ulauncher release.

**Comment by cryptoEcho** [comment]
The guy in this thread https://github.com/Ulauncher/Ulauncher/issues/694 had the same issue.

**Comment by friday** [comment]
Do you see them with the `ulauncher-git` AUR package?

**Comment by friday** [comment]
Also see the comments in #1011

**Comment by friday** [comment]
I have now documented this in the troubleshooting: https://github.com/Ulauncher/Ulauncher/discussions/991#user-content-invalid-entries

**Comment by cryptoEcho** [comment]
@friday, you rock. 
My problem have been solved and now I know more about .desktop files.
