### ISSUE TITLE
Improve matching

### ISSUE THREAD

**Issue by skorokithakis** [Ulauncher/Ulauncher#1027]
### Description

I, presumably like most other people, have a list of apps I use most commonly. For example, I open Spotify many times a day. Currently, uLauncher looks like it considers apps for specific combinations of letters. For example, if I type "spot" (my usual), Spotify comes up first, but if I type "spo", it doesn't.

This seems like something that could be improved, as which app I want to launch isn't very correlated to what I type. If I type "spo", I probably want to launch Spotify more than Spot, as I use the former much more often.

Is there a reason why apps aren't ranked by usage first and then matched?

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing enhancement requests](https://github.com/Ulauncher/Ulauncher/labels/enhancement) before suggesting this.

**Comment by friday** [comment]
Already fixed, but not released yet. See #869
