### ISSUE TITLE
ability to scale the icons when specifying GDK_DPI_SCALE or a setting to set the icon size

### ISSUE THREAD

**Issue by rusty-electron** [Ulauncher/Ulauncher#1028]
### Description

Hi,
I was looking for a way to make the UI smaller and ended up using the solution of specifying GDK_DPI_SCALE when launching `ulauncher`. I noticed that the icons in the list (as shown in the image below) do not scale with the text. It will be great to have this feature. Also the list text is not centered when using small fonts, a fix for this would be great too.

![image](https://user-images.githubusercontent.com/22986666/167690764-2bf1d651-0df8-4b87-8db6-3ca7ea593714.png)

Thanks for this amazing application.

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing enhancement requests](https://github.com/Ulauncher/Ulauncher/labels/enhancement) before suggesting this.

**Comment by friday** [comment]
This [wiki entry](https://wiki.archlinux.org/title/HiDPI#GDK_3_(GTK_3)) and this [blog post](https://ricostacruz.com/til/fractional-scaling-on-xorg-linux) kind of says this part is working as it should.

If I run this for example it looks pretty good `GDK_DPI_SCALE=.7 GDK_SCALE=2 ulauncher --verbose` it looks good apart from the icons being very blurry.

There's already two other variables that we use:

https://github.com/Ulauncher/Ulauncher/blob/fe9f613a8764cd0ef2a8d1fe6ab205895e460b2a/ulauncher/utils/wm.py#L34-L40

**Comment by rusty-electron** [comment]
I tried both the options, the UI scaling doesn't seem to be working (text scaling works fine).

![image](https://user-images.githubusercontent.com/22986666/168418320-face0f0d-afce-47b1-8f03-1cf289538fc3.png)

**Comment by friday** [comment]
That doesn't work because GDK_SCALE is not fractional.

**Comment by rusty-electron** [comment]
Yeah, you are right.
![image](https://user-images.githubusercontent.com/22986666/168438925-bbd608c7-12bb-4799-936e-c5fef0fb8d17.png)

Using GDK_SCALE in my case won't work. But i think allowing an option in the settings that corresponds to the css styling of the img (of the logo) elements may work. Maybe something like this could be implemented in a future release?

**Comment by friday** [comment]
It should be fixed now in 3f0420a84dde64545f4ca0dc90e3ed7b93284a67 so it looks consistent regardless of the scaling. No options added. Sorry it took so long. I didn't have a machine I could text this on until now.

**Comment by friday** [comment]
I'll close the issue. If it's still not fixed for you after updating and restarting Ulauncher v6, let me know and I'll reopen it.
