### ISSUE TITLE
Command tests well from Ubuntu terminal, but does not execute via Ulauncher

### ISSUE THREAD

**Issue by tylerssn** [Ulauncher/Ulauncher#103]
Executing `xdotool search --sync --onlyvisible --class "%s" windowactivate key alt+Tab` allows me to jump to an open window by name from terminal. I've tried adding the following to Ulauncher to no avail.

```
#! /usr/bin/bash

/usr/bin/xdotool search --sync --onlyvisible --class "%s" windowactivate key alt+Tab
```

P.S. this seems like something that might be native to Ulauncher, so if I'm missing something let me know!

**Comment by gornostal** [comment]
when adding a command to shortcuts, query string is available from arg vars -- $1 in your case, not %s

**Comment by gornostal** [comment]
Please reopen if that doesn't help
