### ISSUE TITLE
Ability to edit frequent app list

### ISSUE THREAD

**Issue by juanbbxdevs** [Ulauncher/Ulauncher#1031]
### Description

First of all ... Thank you guys for building such an amazing app! Is a daily driver for me. I love it!

I know that you can preset the amount of frequent used apps to display when Ulauncher is opened. But, something that is has been on my head since I started using it, is having the possibility of adding some mechanism to edit the most frequent apps being shown or editing the parameters that are being used to set them in the list.

The process:
 - You open **Preferences**
 - Below or next to _"Number of frequent apps to show"_ item, we include a list of the most frequent apps.
 - You have the ability of **_add / remove / rearrange_** the list

Thanks!

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing enhancement requests](https://github.com/Ulauncher/Ulauncher/labels/enhancement) before suggesting this.

**Comment by friday** [comment]
Thank you for the kind words :+1:

The frequently used apps are stored in a json file named `app_starts.json` as of Ulauncher v6 (unreleased). I think this is friendly enough for users who want to edit the file. Making a user interface for it is not something I think is warranted.

I have personally been more into not tracking app usage and let users "pin" apps manually with some button and/or keyboard combination.

**Comment by juanbbxdevs** [comment]
**_That's great news!_** Editing the file is something I can work with! I will be waiting patiently for the new version! Thanks!

**Comment by friday** [comment]
I think I will close this then. Follow #869 to be notified of a releasses. We still have some thing to tie together though, and limited time for it. #849 has more details on the actual implementation/change and the actual file location will be in ~/.local/state/ulauncher/app_starts.json and the format like this:

```json
{
    "firefox.desktop": 121,
    "org.gnome.gedit.desktop": 172,
    "chromium.desktop": 191,
    "gnome-keyboard-panel.desktop": 22,
    "com.gexperts.Tilix.desktop": 245,
    "gnome-display-panel.desktop": 139
}
```
