### ISSUE TITLE
🖌 Adopt Ubuntu accent color for Ubuntu theme (Ubuntu 22.04)

### ISSUE THREAD

**Issue by jd-solanki** [Ulauncher/Ulauncher#1037]
### Description

Currently, the Default ubuntu theme uses orange color to show the selected color (primary color). Now, we can adopt the accent color of ubuntu (from 22.04) as the ubuntu theme's primary color.

I wanted to contribute but I didn't understand the [CSS](https://github.com/Ulauncher/Ulauncher/blob/v6/data/themes/ubuntu/theme.css). I am a frontend dev and I don't write `@define-color` in my CSS 🤔 

Moreover, I tried searching how to get the current accent color of the ubuntu system but had no luck.

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing enhancement requests](https://github.com/Ulauncher/Ulauncher/labels/enhancement) before suggesting this.

**Comment by friday** [comment]
The CSS syntax is standard GTK CSS and themes documentation is here: http://docs.ulauncher.io/en/latest/themes/themes.html. Easiest way is to check out the [community contributed theme](https://gist.github.com/gornostal/02a232e6e560da7946c053555ced6cce) and fork one. There's already two Yaru themes. Maybe the 22.04 flavor is different but that's not something for Ulauncher to handle.
