### ISSUE TITLE
FeedReader from Flatpak package not found

### ISSUE THREAD

**Issue by orschiro** [Ulauncher/Ulauncher#104]
Dear all, 

Does anyone have an idea how to integrate apps installed from Flatpak packages?

I installed [FeedReader](https://jangernert.github.io/FeedReader/) as follows:

    flatpak install --from http://feedreader.xarbit.net/feedreader-repo/feedreader.flatpakref

It shows in the Unity launcher and dash but not in Ulauncher. 

![image](https://cloud.githubusercontent.com/assets/170947/23786450/71fcdf60-056d-11e7-8f91-0c06eded9390.png)

![image](https://cloud.githubusercontent.com/assets/170947/23786454/78646ab2-056d-11e7-9100-28073a6995f8.png)

![image](https://cloud.githubusercontent.com/assets/170947/23786463/81c7f9de-056d-11e7-9d43-3af8e30787de.png)

**Comment by gornostal** [comment]
I guess flatpak saves its .desktop packages in an unknown to Ulauncher location.
I'll look into this.

**Comment by orschiro** [comment]
Thank you so much!

Let me know if I can help somehow. :-)

Yours,

Robert

**Comment by gornostal** [comment]
Fixed in v2.1.1 (Dev)

**Comment by orschiro** [comment]
I just tried it.

It's working! :-)

Thank you for this quick release.

**Comment by gornostal** [comment]
Cool!
