### ISSUE TITLE
Alt + Enter for folders throwing exception in fedora 36, gnome 42.1

### ISSUE THREAD

**Issue by theweekendgeek** [Ulauncher/Ulauncher#1054]
### Environment

fedora 36, gnome 42.1

### Bug description

When I try to access the options for a folder I get no results, instead the list is empty and in the logs there is an exception.

I just added the log for the exception, if you need anything else just let me know :) 

### Log output

```shell
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 369, in show_results
    results = self.create_item_widgets(result_items, self._get_user_query())
  File "/usr/lib/python3.10/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 407, in create_item_widgets
    item_frame.initialize(builder, result_item, index, query)
  File "/usr/lib/python3.10/site-packages/ulauncher/ui/ResultItemWidget.py", line 38, in initialize
    self.set_icon(item_object.get_icon())
  File "/usr/lib/python3.10/site-packages/ulauncher/search/file_browser/alt_menu/OpenFolderItem.py", line 27, in get_icon
    return get_themed_icon_by_name('system-file-manager', self.get_icon_size())
  File "/usr/lib/python3.10/site-packages/ulauncher/utils/image_loader.py", line 69, in get_themed_icon_by_name
    return icon_theme.load_icon(icon_name, icon_size, Gtk.IconLookupFlags.FORCE_SIZE)
gi.repository.GLib.GError: gtk-icon-theme-error-quark: Icon 'system-file-manager' not present in theme Adwaita (0)
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
The error is exactly what it says. `Icon 'system-file-manager' not present in theme Adwaita (0)`. system-file-manager is a [standard icon](https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html), so you really should have it, and icon themes that don't have it should inherit from icon themes that do.

The actual error should be fixed in v6 though giving a generic fallback icon instead.

**Comment by theweekendgeek** [comment]
I see. I think something might have changed  with the way gnome handles the default themes (since 42, some stuff moved from tweaks to regular settings).
I am also running the default theme and I can definitely see multiple files if I search for the filename (see screenshot).
Also, when I go to the tweaks app and explicitly set an icon theme (Breeze e. g.) it works as expected again.

![image](https://user-images.githubusercontent.com/13828406/172252325-1fa4b8f2-bb66-4770-813c-a85cca8c3436.png)

**Comment by friday** [comment]
Most icon themes inherit from / fallback to HighContrast.

I guess the fact that it's missing and only has a symbolic variant and is categorized as "legacy" for Adwaita is an indication that there's a more recent substitute for it, but probably not one we can safely use yet without introducing this sort of issue on older distros.
