### ISSUE TITLE
docs.ulauncher.io (readthedocs) should keep a version history

### ISSUE THREAD

**Issue by friday** [Ulauncher/Ulauncher#1059]
### Description

The only version options it maintains now is "latest" and "stable" and both are the same.
![Screenshot from 2022-06-15 10-40-44](https://user-images.githubusercontent.com/515120/173783487-3b9e379a-b6f8-4555-8023-91e1d7175770.png)

We should be able to release v6 without erasing history for those who can't/won't update or just want the old version to exist so they can compare.

https://docs.readthedocs.io/en/stable/versions.html
https://docs.readthedocs.io/en/stable/integrations.html#vcs-integrations

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing enhancement requests](https://github.com/Ulauncher/Ulauncher/labels/enhancement) before suggesting this.

**Comment by friday** [comment]
@gornostal How is the ReadTheDocs page updated? It doesn't seem to have any hooks to update when we make releases?

**Comment by gornostal** [comment]
@friday RTD receives a webhook. It was automatically created by RTD automation. The webhook is here https://github.com/Ulauncher/Ulauncher/settings/hooks

I'll share access to RTD with you by email

**Comment by friday** [comment]
@gornostal Funny enough I didn't look in the hooks settings although I described it as a "hook" :D I probably broke it by renaming the branches, but we never had any changes until now anyway. I created a RTD account with my usual email and connected to this github account. Not sure if you can fine and invite me by that info.

**Comment by gornostal** [comment]
You should get an invite now.

**Comment by friday** [comment]
Got it. Thanks :+1: I hope to get some time to figure this out soon :)

**Comment by friday** [comment]
I will close this. You can switch the version from the docs page, but only if you're on an older version (which you wouldn't find from that page). But you can see and go to the versions from https://readthedocs.org/projects/ulauncher/versions/

It doesn't have all versions (only the latest minor versions). It can potentiality show all, but if any version fails the build there's no way to rebuild without removing/replacing the tag (and I don't think we should do that).

So I think it's as good as it gets now
