### ISSUE TITLE
Search among open apps too (as an option at least)

### ISSUE THREAD

**Issue by aurimus** [Ulauncher/Ulauncher#108]
Sometime I have many apps open, for example I have calculator open already but I forgot, now I start ulauncher and type calculator, it opens a new instance. I would like it to show the current instance as an option (with a dot on the left for example).

Would be a great addition.

**Comment by aurimus** [comment]
Shift + Enter could open a new instance of the app (or an existing, if the option is set the other way)

**Comment by gornostal** [comment]
Once extension API is done, this feature can be implemented as an extension.

**Comment by gornostal** [comment]
Sorry, I've decided to not have this feature built into the app.
However you can implement an extension

**Comment by ricardobarantini** [comment]
How can I make this feature to work? Still opens a new instance for any program even if already are running.

**Comment by iago-lito** [comment]
@gornostal I think this is the expected behaviour. If you need to search for opened programs instead, you need to write an extension that queries your system for currently running applications.
