### ISSUE TITLE
Can't open ulauncher

### ISSUE THREAD

**Issue by 7549brijesh** [Ulauncher/Ulauncher#1087]
### Environment

Endeavour os(Arch distro,KDE)

### Bug description

I just updated/upgrade the system and all of a sudden after the restart ulauncher was not opening at all even I tried to run ulauncher from the terminal still it generates the python error
Even in log output it generates a same python error

![2022-07-15_12-30](https://user-images.githubusercontent.com/25589680/179170917-5854138c-9a08-47eb-aeec-68776322ffaf.png)

### Log output

```shell
Traceback (most recent call last):
  File "/usr/bin/ulauncher", line 27, in <module>
    from ulauncher.main import main
  File "/usr/lib/python3.10/site-packages/ulauncher/main.py", line 26, in <module>
    from ulauncher.ui.windows.UlauncherWindow import UlauncherWindow
  File "/usr/lib/python3.10/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 34, in <module>
    from ulauncher.utils.desktop.notification import show_notification
  File "/usr/lib/python3.10/site-packages/ulauncher/utils/desktop/notification.py", line 2, in <module>
    gi.require_version('Notify', '0.7')
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Notify not available for version 0.7
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by 7549brijesh** [comment]
[https://aur.archlinux.org/packages/ulauncher](url)
its a temporary fix take a look at latest comments

**Comment by BrianDelalex** [comment]
> [https://aur.archlinux.org/packages/ulauncher](url) its a temporary fix take a look at latest comments

Hi, I'm having the same issue. I didn't understand where I can find the temporary fix.

**Comment by radupantiru** [comment]
This is what I've done:
Edited:
`/usr/lib/python3.10/site-packages/ulauncher/utils/desktop/notification.py`

`gi.require_version('Notify', '0.8')`
from
`gi.require_version('Notify', '0.7')`

**Comment by BrianDelalex** [comment]
> This is what I've done: Edited: `/usr/lib/python3.10/site-packages/ulauncher/utils/desktop/notification.py`
> 
> `gi.require_version('Notify', '0.8')` from `gi.require_version('Notify', '0.7')`

That works for me as well. Thank you.

**Comment by friday** [comment]
Thanks for the report and comments. This will be fixed very soon and I'll make a new release for the v5 branch.
