### ISSUE TITLE
Ulauncher hotkey Super L not working after OS restart.

### ISSUE THREAD

**Issue by thylacinelol** [Ulauncher/Ulauncher#110]
Hi all,

There seems to be a problem with the Ulauncher hotkey being reset every time after computer restart. The hotkey I'm using is `<Super L>`, although the same happens with other hotkeys.

Ulauncher version: ulauncher 1.0.0.

OS name and version where bug can be reproduced: Ubuntu 16.04.2 LTS, linux 16.04 4.4.0-67-generic.

Steps to reproduce:

1. Open Ulauncher preferences
2. Change Ulauncher hotkey to `<Super L>`
3. Restart computer

Hotkey `<Super L>` does not open Ulauncher anymore and it has to be re-mapped (using steps 1 and 2) to work again.

[last.log](https://github.com/Ulauncher/Ulauncher/files/861391/last.log.txt)

p.s. I have remapped the Dash to be opened via `<Ctrl> + <Space>` instead of `<Super L>` using the CompizConfig manager, if it's of any help.

**Comment by gornostal** [comment]
Ulauncher v1 may allow you to set the hotkey to a single key, but it's not officially supported and may not work (as in your case).

Ulauncher v2.0.30 is the latest stable version and is recommended to use.
You can download it from the website ulauncher.io

**Comment by thylacinelol** [comment]
Thanks, works great!
