### ISSUE TITLE
Dependency on gir1.2-notify-0.7 

### ISSUE THREAD

**Issue by jflepp** [Ulauncher/Ulauncher#112]
Ulauncher depends on gir1.2-notify-0.7, a package not listed in the dependencies

**Comment by gornostal** [comment]
@jflepp what distro do you use?

**Comment by jflepp** [comment]
debian-8.7.1 with Mate Desktop

**Comment by gornostal** [comment]
Thanks. I'll look into it

**Comment by gornostal** [comment]
Fixed in [v2.2.0](https://github.com/Ulauncher/Ulauncher/releases/tag/2.2.0.r1)
