### ISSUE TITLE
Crash upon startup when service is enabled

### ISSUE THREAD

**Issue by remyabel2** [Ulauncher/Ulauncher#1124]
### Environment

Fedora 36

### Bug description

Enabling the ulauncher user systemd service appears to cause this crash upon startup. However, the service is required for ulauncher to work. The crash does not appear to affect subsequent functionality.

### Log output

```shell
Version-Release number of selected component:
ulauncher-5.14.7-1.fc36

Additional info:
reporter:       libreport-2.17.1
backtrace_rating: 4
cgroup:         0::/user.slice/user-1000.slice/user@1000.service/app.slice/ulauncher.service
cmdline:        /usr/bin/python3 -s /usr/bin/ulauncher --hide-window
crash_function: g_log_structured_standard
executable:     /usr/bin/python3.10
journald_cursor: s=00000000000000000000000000000000;i=2d95bd;b=10efed6402524cbebe1a2ebab52bed83;m=2e75016;t=5e6ecd9576ba3;x=fc197dc18eaa8b7f
kernel:         5.18.18-200.fc36.x86_64
rootdir:        /
runlevel:       N 5
type:           CCpp
uid:            1000

Truncated backtrace:
Thread no. 0 (10 frames)
 #3 g_log_structured_standard at ../glib/gmessages.c:2030
 #4 gtk_style_context_init at ../gtk/gtkstylecontext.c:348
 #5 g_type_create_instance at ../gobject/gtype.c:1929
 #6 g_object_new_internal at ../gobject/gobject.c:2011
 #7 g_object_new_with_properties at ../gobject/gobject.c:2181
 #9 _gtk_style_new_for_path at ../gtk/deprecated/gtkstyle.c:854
 #10 gtk_style_new at ../gtk/deprecated/gtkstyle.c:888
 #11 gtk_widget_get_default_style at ../gtk/deprecated/gtkstyle.c:4061
 #13 gtk_widget_init at ../gtk/gtkwidget.c:4479
 #14 g_type_create_instance at ../gobject/gtype.c:1923
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
> However, the service is required for ulauncher to work

Please follow the issue template. Run `ulauncher -v` to get the log output and post your OS details and GTK version. Also, this issue is not in our code or in code we can fix. It's GTK's code.

**Comment by friday** [comment]
> Here is the full backtrace: https://bugzilla-attachments.redhat.com/attachment.cgi?id=1907245&t=yyIkvmD5wx

These links are only viewable with a Redhat bugzilla account (maybe only yours even).

> The crash seems to consistently happen with ulauncher and I don't have issues with other GTK apps. As the crash happens within your application, I'm struggling to understand how this is a GTK bug.

Because the stack trace you posted says it's GTK that's crashing. It's also C/C++ code. Ulauncher has no C code. It's written in Python. But we use libraries (GTK) so it GTK bugs affects us.
