### ISSUE TITLE
timer to understand minutes?

### ISSUE THREAD

**Issue by orschiro** [Ulauncher/Ulauncher#113]
Dear all, 

Would the following be possible? :-)

![image](https://cloud.githubusercontent.com/assets/170947/24861951/e7e338f0-1dfa-11e7-82b3-ee93a1ae3713.png)

**Comment by gornostal** [comment]
You can type in `timer 5m "your message"` for that.
I'm going to have to close this ticket because I'm currently not investing my time to improve everything except core features. 
Timer will become a plugin (in a separate repository) with the next major release.

**Comment by orschiro** [comment]
Thank you, @gornostal!

I will wait then until Timer has a separate repository. 

However, I believe you got my point wrong. 

It was not about adding a custom message but rather make Timer understand that `timer 5 minutes` means to run the timer for `5m`.
