### ISSUE TITLE
the id of newly added shortcut is empty

### ISSUE THREAD

**Issue by sunn4room** [Ulauncher/Ulauncher#1130]
### Environment

archlinux bspwm

### Bug description

ulauncher/modes/shortcuts/ShortcutsDb.py
```
22        self.added = time()
23        self.id = str(uuid4())
24        self.update(*args, **kwargs)  # this line override the id when create a new shortcut
```
suggestion
```
22        self.update(*args, **kwargs)
23        if not self.added:
24            self.added = time()
25        if not self.id:
26            self.id = str(uuid4())
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
Thanks. Fixed!
