### ISSUE TITLE
App no longer working in Fedora 36 Workstation after update to core sys files today

### ISSUE THREAD

**Issue by thorrrr** [Ulauncher/Ulauncher#1134]
### Environment

Fedora 36 Workstation

### Bug description

The app no longer works in any fashion just dead cannot do anything with it.

### Log output

```shell
Loaded plugins: builddep, changelog, config-manager, copr, debug, debuginfo-install, download, generate_completion_cache, groups-manager, needs-restarting, playground, repoclosure, repodiff, repograph, repomanage, reposync, system-upgrade
DNF version: 4.14.0
cachedir: /var/cache/dnf
No such command: ulauncher. Please use /usr/bin/dnf --help
It could be a DNF plugin command, try: "dnf install 'dnf-command(ulauncher)'"
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by thorrrr** [comment]
Should not have closed it same issue after reboot

**Comment by thorrrr** [comment]
Should not have closed it same issue after reboot

**Comment by friday** [comment]
You have to install it to use it

**Comment by thorrrr** [comment]
I been using it 8 months daily ?????

**Comment by thorrrr** [comment]
I have never removed it unless i have a sys issue let me reinstall it to see if i get it fixed
