### ISSUE TITLE
Passing custom text when toggling Ulauncher from CLI

### ISSUE THREAD

**Issue by JojiiOfficial** [Ulauncher/Ulauncher#1135]
### Description

Would be nice if it was possible to toggle/open ulauncher with already some text written in the search bar (eg. a extensions keyword to directly search using an extension) from cli. 'ulauncher-toggle' already exists but I couldn't find a way to pass some text.

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing enhancement requests](https://github.com/Ulauncher/Ulauncher/labels/enhancement) before suggesting this.

**Comment by friday** [comment]
Already done for v6: #1041
