### ISSUE TITLE
Compatibility with certain themes broke

### ISSUE THREAD

**Issue by FinnHering** [Ulauncher/Ulauncher#1141]
### Environment

Arch Linux, Python 3.10 vEnv

### Bug description

Support with the 'official' Dracula theme ([this one](https://github.com/dracula/ulauncher)) is broken since commit 29e4683. 
There are multiple issues, actually. At first the theme doesn't work at all because GTK fails to import theme.css from the PWD.
See: 
```log
2022-10-21 20:22:41,590 ⚠️  ERROR Uncaught exception main.except_hook:74
Traceback (most recent call last):
  File "/home/finn/projects/Ulauncher/ulauncher/ui/UlauncherApp.py", line 63, in setup
    window.init_theme()
  File "/home/finn/projects/Ulauncher/ulauncher/ui/windows/UlauncherWindow.py", line 152, in init_theme
    self.init_styles(theme.get_css())
  File "/home/finn/projects/Ulauncher/ulauncher/ui/windows/UlauncherWindow.py", line 124, in init_styles
    self._css_provider.load_from_data(css.encode())
gi._error.GError: gtk-css-provider-error-quark: <data>:3:25Failed to import: Error opening file /home/finn/projects/Ulauncher/theme.css: No such file or directory (2)
```
This is because the way the paths inside an url() are being resolved changed. The Dracula theme imports `theme.css` like so: `url(theme.css)` (see: [theme-gtk-3.20.css](https://github.com/dracula/ulauncher/blob/master/theme-gtk-3.20.css#L1)) but your regex expects relative paths to always be preceded by a `./` (see: [Theme.py L53](https://github.com/Ulauncher/Ulauncher/commit/29e46839ceac8b17a068e4798d0f0ff8f1dc3058#diff-ead518646c0718787426c71b6742edcf0e93fb1136b9061fb73aa2de5e86ac75R53))

An easy fix is to just add a `./` and call it a day. But I propose properly parsing and resolving paths using the built-in `pathlib` library.
I've come up with a solution that _might_ be safer/elegant. See: https://github.com/Ulauncher/Ulauncher/compare/v6...FinnHering:Ulauncher:v6
I didn't make a PR yet, because I rarely write code in Python and would love to get some feedback beforehand :)

Anyway… now that this issue can be resolved I stumble upon another issue. The theming doesn't really work. I see that it is being applied, but apparently only partially: 
![grafik](https://user-images.githubusercontent.com/92150718/197275121-567c3e4b-3a69-44eb-a0eb-6bebd3909931.png)
styling for the input and the setting-button is not applied. Did the CSS selectors change for those?

Thank you for your time!

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
This was a very helpful bug report. Thank you :+1:  I just pushed fixes for both those issues.

The second issue was that the theme inherited from "dark", which inherited general normalization from "light", but my code only worked with one ancestor theme.

There should actually be a similar issue remaining for the regex. I'll try to get that fixed soon, but it doesn't affect this theme.

**Comment by FinnHering** [comment]
You're welcome! 
This is your decision, but I'd still recommend checking if the theme tries to import things using url() from outside its directory on the pc and block it. I think security on every level is a decent approach and I don't see a reason for why a theme should import things from outside its directory.  :)

**Comment by friday** [comment]
> This is your decision, but I'd still recommend checking if the theme tries to import things using url() from outside its directory on the pc and block it. I think security on every level is a decent approach and I don't see a reason for why a theme should import things from outside its directory. :)

Why? It just adds more code for no reason. CSS is not a programming language. Trying to include a file you don't own accomplishes nothing. It would just fails to import when the path doesn't exist or if it's not a valid CSS file. It can't leak data, hijack privileges, access or overwrite files this way or anything. There is no security concern here. If there was it would not be on Ulauncher to fix this, but GTK. The only thing that could happen is that your theme would look broken if the theme author expects it to exist, and this is not a security concern.

**Comment by FinnHering** [comment]
You're right. I guess I'm just a little paranoid.

**Comment by FinnHering** [comment]
I just tried out your revisions, and they work great. Thank you for your great commitment to this project! :)
