### ISSUE TITLE
I don't know if it's a bug, but it does happen

### ISSUE THREAD

**Issue by mgl-pub** [Ulauncher/Ulauncher#1142]
### Environment

EndeavourOS , xfce4.16

### Bug description

After starting my goland development tool through ulauncher, it may crash randomly. For example, it may also crash when starting the project, or it may also crash when the service is stopped after starting.

### Log output

```shell
none log
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
Do you use systemd? See https://github.com/Ulauncher/Ulauncher/discussions/991
