### ISSUE TITLE
When using Shortcuts, the launcher still there untill the page is fully loaded!

### ISSUE THREAD

**Issue by sals9** [Ulauncher/Ulauncher#1145]
### Description

As described in the title, Ulauncher doesn't go away (when using Shortcuts) until the target page is fully loaded. This behavior is not so good, it should disappear as soon as I click `Enter`.

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing enhancement requests](https://github.com/Ulauncher/Ulauncher/labels/enhancement) before suggesting this.

**Comment by friday** [comment]
For me it closes immediately when I press enter. If it fails to close immediately for you then the performance issue is unrelated to the web browser loading status. Ulauncher has no way to know what the web browser is doing.

**Comment by troycurtisjr** [comment]
It works as expected for me as well, but maybe there is some odd environment issue? @sals9 Can you include some more details about your environment? Specifically:

* What version of ulauncher you are running
* What distribution and version (Ubuntu, Fedora, etc) you are running
* What desktop you are using (Gnome, KDE, twm, etc)
* Whether you are running X11 or Wayland (if you aren't sure, open a terminal and type `echo $WAYLAND_DISPLAY`. If something is output, then you are running Wayland)

**Comment by sals9** [comment]
For no apparent reason to me, now it works as expected 👍

My _current_ environment by the way:

Ulauncher v5.15.0
Ubuntu 22.04.1 LTS
Gnome desktop
X11

Thanks, mates!
