### ISSUE TITLE
Missing wmctrl dependency

### ISSUE THREAD

**Issue by Tommimon** [Ulauncher/Ulauncher#1146]
### Environment

Ubuntu 22.10, GNOME 43.0, Ulauncher v5.15.0

### Bug description

I installed the package from `ppa:agornostal/ulauncher` as suggested on the official website.

`ulauncher-toggle` was failing because `wmctrl` was not installed. After I installed it manually with `sudo apt install wmctrl` it worked perfectly. The package `wmctrl` should be included in the dependency list but is missing.

I don't know how to check for v6 because there is no package available yet.

### Log output

```shell
method return time=1667649845.747674 sender=:1.106 -> destination=:1.130 serial=7 reply_serial=2
/usr/bin/ulauncher-toggle: 13: wmctrl: not found
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
`ulauncher-toggle` is not strictly required to run Ulauncher and wmctrl is not strictly required to run `ulauncher-toggle`, so it hasn't been on the dependencies list. Should be on the optional dependencies lists, but I added it in 50f07b8 just now. Next v5 release should have it.
