### ISSUE TITLE
Add an option for multiple keywords for the same shortcut

### ISSUE THREAD

**Issue by jjeffrey** [Ulauncher/Ulauncher#1155]
### Description

I would like to use a delimiter to separate out keywords that map to the same shortcut, to avoid having to copy the shortcut multiple times.

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing enhancement requests](https://github.com/Ulauncher/Ulauncher/labels/enhancement) before suggesting this.

**Comment by friday** [comment]
I fail to see any utility in that. Just add any aliases you to the name. It's searchable and selecting it activates the keyword.

**Comment by jjeffrey** [comment]
How do you add aliases to a name besides making several duplicate shortcuts?

**Comment by friday** [comment]
![Screenshot from 2022-11-20 19-00-17](https://user-images.githubusercontent.com/515120/202918085-a6e32998-8c9b-48b9-b799-400445efdd5e.png)

**Comment by jjeffrey** [comment]
Ah, I thought you were talking about something different from what I already knew. I guess my distinction is more of a UI preference. 

I would rather be able to associate multiple names or multiple shortcuts with the same query, without having to create multiple entries, but it's probably not worth the additional implementation complexity until I have a more serious use case.
