### ISSUE TITLE
Ulauncher Crashes when calculating big numbers

### ISSUE THREAD

**Issue by Lunatic-Audits** [Ulauncher/Ulauncher#1159]
### Environment

Fedora 37

### Bug description

Ulauncher crashes when calculating big numbers like 2^222222 

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [x] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
See #549
