### ISSUE TITLE
Replace Travis releases with GitHub Actions

### ISSUE THREAD

**Issue by friday** [Ulauncher/Ulauncher#1176]
### Description

We just moved to GitHub actions for testing/linting commits. Now only the deploy/release part is left on Travis. It would be better to have it on GitHub too. I believe GitHub actions allow more granular control so we can independently make a release with a .tar.gz and .deb, then push the update to the AUR and launchpad after that. This is something that our Travis release flow doesn't do. It has to finish with uploading the build files, so you have to update the AUR and make references to the tar.gz before it exists, which is bad in particular if the release fails.

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing feature requests](https://github.com/Ulauncher/Ulauncher/labels/feature) before suggesting this.

### Feature isn't possible to support as an extension.

- [X] This feature request cannot satisfactory be supported as a third party extension.

**Comment by friday** [comment]
This has been implemented now and used as of v5.15.2.

**Comment by gornostal** [comment]
No problem!

It feels good to simplify things:)
