### ISSUE TITLE
Include "comment" into application in search 

### ISSUE THREAD

**Issue by dynobo** [Ulauncher/Ulauncher#1186]
### Description

It would be a great improvement, if the search for an application would also consider the text in the `comment` field of the `.desktop` file, not only the application's `name`.

As the `comment` is already shown in ulauncher beneath the `name`, I'd guess it shouldn't be too hard to implement.
If possible, matches with the `comment` could also be ranked a bit lower than matches in the `name`.

### Example with Thunderbird

`thunderbird.desktop:`
```
[Desktop Entry]
Name=Thunderbird
Comment=Send and receive mail with Thunderbird
[...]
```

Search for `thu` :heavy_check_mark::
![image](https://user-images.githubusercontent.com/11071876/212535147-9fcc3d92-b2fb-4190-9e38-d6eec8a5ae4e.png)

Search for `mail` :x:
![image](https://user-images.githubusercontent.com/11071876/212535200-fdb506b6-24d7-48b8-a8e4-31667e99e29c.png)
(I propose, that this search should also return Thunderbird, because `mail` is matched in the `comment` field.

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing enhancement requests](https://github.com/Ulauncher/Ulauncher/labels/enhancement) before suggesting this.

**Comment by friday** [comment]
https://github.com/Ulauncher/Ulauncher#%EF%B8%8F-this-is-the-branch-for-the-unreleased-v6-release-if-you-want-the-v5-branch-version-go-here

https://github.com/Ulauncher/Ulauncher/issues/869

938
