### ISSUE TITLE
Ulauncher crashes with the last update

### ISSUE THREAD

**Issue by Thanatermesis** [Ulauncher/Ulauncher#1193]
### Environment

Debian Bullseye Linux

### Bug description

With the last updated build, the bar doesn't shows anything when typing

### Log output

> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 161, in on_input_changed
>     ModeHandler.get_instance().on_query_change(self.app.query)
>   File "/usr/lib/python3/dist-packages/ulauncher/modes/ModeHandler.py", line 39, in on_query_change
>     results = self.search(query)
>   File "/usr/lib/python3/dist-packages/ulauncher/modes/ModeHandler.py", line 64, in search
>     sorted_ = sorted(searchables, key=lambda i: i.search_score(query), reverse=True)[:limit]
>   File "/usr/lib/python3/dist-packages/ulauncher/modes/ModeHandler.py", line 64, in <lambda>
>     sorted_ = sorted(searchables, key=lambda i: i.search_score(query), reverse=True)[:limit]
>   File "/usr/lib/python3/dist-packages/ulauncher/api/result.py", line 105, in search_score
>     return max(get_score(query, field) * weight for field, weight in self.get_searchable_fields() if field)
>   File "/usr/lib/python3/dist-packages/ulauncher/modes/apps/AppResult.py", line 62, in get_searchable_fields
>     **frequency_weight = 1 - (index / count * 0.1) + 0.05**
> **ZeroDivisionError: division by zero**
>

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by Thanatermesis** [comment]
Notes: testing with older versions built:

- still bugs in version built from 8fed3f418
- works correctly in version built from cd826659b

_didn't tested with versions between these commits, since I don't have backuped builds_

**Comment by friday** [comment]
Thank you for the report :+1:

Fixed in af6bef385d5868edabe542ce7becd1e418202748
