### ISSUE TITLE
Release tarball for 5.15.1 doesn't have the version populated

### ISSUE THREAD

**Issue by troycurtisjr** [Ulauncher/Ulauncher#1194]
### Environment

GitHub

### Bug description

The build for [Fedora rawhide failed](https://koji.fedoraproject.org/koji/taskinfo?taskID=96475314) because the newer Python packaging libraries got more particular. Specifically, the version is missing in the 5.15.1 tarball which cased the build to fail.

```
❯ grep -C 5 'version=' ulauncher/setup.py
        "conftest.py"
    ])

    DistUtilsExtra.auto.setup(
        name='ulauncher',
        version='',
        license='GPL-3',
        author='Aleksandr Gornostal',
        author_email='ulauncher.app@gmail.com',
        description='Application launcher for Linux',
        url='https://ulauncher.io',
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
I'll try to get this done this weekend, but you should also have permission to replace the file attachments in the release.

**Comment by troycurtisjr** [comment]
Ah I was wondering if it might have been using new GitHub actions or something similar.

**Comment by friday** [comment]
Gornostals API key used in the script had expired, so the release for AUR and Launchpad was made, but no GitHub release. And the AUR depends on the tar file in the GitHub release, so I had to build the file on my computer and uploaded them.

I fixed the release flow so it should make the GitHub release before making the AUR and Launchpad now, but I definitely want to switch to GitHub actions.

**Comment by friday** [comment]
Should be fixed now. Let me know otherwise.

Looks like the one I built manually I forgot to pass the version as argument, which still worked for the Arch build.
