### ISSUE TITLE
Docs: Mention symlinking ulauncher

### ISSUE THREAD

**Issue by 1fexd** [Ulauncher/Ulauncher#1197]
### Description

Hi,

when creating a plugin normally, the ulauncher imports are missing, so I cloned to repo and symlinked the `ulauncher` directory to my plugin directory, which fixed the import errors. Maybe you should mention that in your development documentation?

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing enhancement requests](https://github.com/Ulauncher/Ulauncher/labels/enhancement) before suggesting this.

### Ulauncher v6

- [X] I have checked and couldn't find my suggestion in v6.

**Comment by friday** [comment]
You're doing it wrong in that case. For v5 the documentation is here: http://docs.ulauncher.io/en/latest/extensions/debugging.html

If you're using V&, the documentation isn't complete or published yet because v6 is WIP, but the goal is to eliminate the confusion for v6 instead of documenting it.

**Comment by 1fexd** [comment]
What I meant was that when developing a plugin, you need to import classes from the ulauncher package, which my IDE (PyCharm in my case) does not find. Symlinking the ulauncher folder from this project fixes this since now the classes are present.

**Comment by friday** [comment]
Ulauncher installs in your system's python path. So assuming you have installed Ulauncher and can't import those packages it's because you're overriding the system python binary with pyenv or something.

**Comment by 1fexd** [comment]
That makes sense, thanks!
