### ISSUE TITLE
Window stuck when executing shortcut with input containing newline character

### ISSUE THREAD

**Issue by Thanatermesis** [Ulauncher/Ulauncher#1199]
### Environment

Debian Bullseye Linux

### Bug description

When the newline character is included in the input, the input box gets is kept on the desktop without being able to do anything

How to reproduce:

* Create a new "test" shortcut with these contents:
```
#!/bin/bash
echo "%s" > /tmp/logs
```
* Now select from a text editor a piece of text including at least a newline (like 2 paragraph's) 
* Run the "test" shortcut and paste the contents to it
* The /tmp/logs file will be correctly filled up, but the input box won't be removed from the desktop, like stuck processing...

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
I can't reproduce this in v6. Didn't try v5.

**Comment by friday** [comment]
I pushed a commit that fixed the error I got. I didn't get the window crashing as mentioned, but I assumed they were connected. Let me know if this doesn't fix it.

I don't think I'll backport this to v5.

**Comment by Thanatermesis** [comment]
hi @friday mmh, the bug stills here (not using v5, but the last commit build), reproduced in the exact same way as described in the report 🤔 , i just did the same steps and the window is stuck in the desktop

**Comment by friday** [comment]
Can you stop the ulauncher daemon, then run `ulauncher -v` in a terminal and check for errors when you do this?

**Comment by Thanatermesis** [comment]
Ah! there's something:

I have a text prepared to paste with these contents:

> foo
> bar
> wombat
> another line...

Then running it with debug I can see this error:

```
2023-02-20 11:13:38,999 ℹ  DEBUG Running a script from /tmp/ulauncher_run_script_1676909618.9990566 RunScriptAction.run:32
/tmp/ulauncher_run_script_1676909618.9990566: line 5: bar: command not found
/tmp/ulauncher_run_script_1676909618.9990566: line 6: wombat: command not found
/tmp/ulauncher_run_script_1676909618.9990566: line 7: another: command not found
/tmp/ulauncher_run_script_1676909618.9990566: line 10: bar: command not found
/tmp/ulauncher_run_script_1676909618.9990566: line 11: wombat: command not found
/tmp/ulauncher_run_script_1676909618.9990566: line 12: unexpected EOF while looking for matching `"'
/tmp/ulauncher_run_script_1676909618.9990566: line 13: syntax error: unexpected end of file
2023-02-20 11:13:39,011 ⚠  ERROR Uncaught exception main.except_hook:78
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 187, in on_input_key_press
    self.enter_result()
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 273, in enter_result
    if self.results_nav.enter(self.app.query, index, alt=alt):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/ItemNavigation.py", line 74, in enter
    action.run()
  File "/usr/lib/python3/dist-packages/ulauncher/api/shared/action/RunScriptAction.py", line 33, in run
    output = subprocess.check_output([file_path + " " + shlex.quote(self.arg)], shell=True).decode("utf-8")
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '["/tmp/ulauncher_run_script_1676909618.9990566 'foo\nbar\nwombat\nanother line...'"]' returned non-zero exit status 2.
2023-02-20 11:13:40,012 ℹ  DEBUG Deleting a temporary file /tmp/ulauncher_run_script_1676909618.9990566 RunScriptAction.remove_temp_file:43
2023-02-20 11:13:50,199 ℹ  DEBUG render 0 results UlauncherWindow.show_results:311
2023-02-20 11:13:50,208 ℹ  DEBUG Focus in event, grabbing pointer: <enum GDK_GRAB_SUCCESS of type Gdk.GrabStatus> UlauncherWindow.on_focus_in:152
Could not determine the accessibility bus address

```

Notice that it starts by **bar** and not **foo** which is the first line, so I assume it thinks / try to make run the next line as commands? this is a bit strange 🤔

**Comment by friday** [comment]
You should probably quote the argument in your script if you want to be able to handle newline characters. Also you can use shell script argument style like $@ or $1 otherwise the %s is substituted before you the script is created.

**Comment by Thanatermesis** [comment]
From what I recall I started using "%s" instead of "$@" because the second one had an issue

In fact, my last test was working correctly, the issue was because I used a %s in another (commented line) and so it was replaced too, making the script not able to run (wrong code), this issue then can be closed and I will open a new one related to $@
