### ISSUE TITLE
Implement Extension Configuration UI in Angular

### ISSUE THREAD

**Issue by gornostal** [Ulauncher/Ulauncher#121]
![ulauncher preferences_183](https://cloud.githubusercontent.com/assets/1202543/25627723/40f718e4-2f6c-11e7-85a1-36beadfaf2d3.png)

Page Layout:
![selection_186](https://cloud.githubusercontent.com/assets/1202543/25629184/5ff8f06e-2f71-11e7-9c20-5bf88ea129f9.png)

API is not ready, but UI can be implemented nevertheless.

**Comment by harindu95** [comment]
Is there a reason for  using a web ui instead of gtk?

**Comment by gornostal** [comment]
Yes, actually.
GTK apps are really hard to customize, plus UI development in JS is much faster with all those millions of npm packages.
Also, I want to build workflow UI (something similar to Alfred maybe) and I'm pretty sure it will be much easier with JS/HTML

**Comment by gornostal** [comment]
Done in v3.1.1
https://ulauncher.io/#Download
