### ISSUE TITLE
GDK_SCALE is set for launched app as well.

### ISSUE THREAD

**Issue by slowsage** [Ulauncher/Ulauncher#1217]
### Environment

arch linux, qtile

### Bug description

I'm on ulauncher v6. Currently running `env GDK_SCALE=2 ulauncher` does indeed launch ulauncher at double scale. However, this scaling property carries on to its children that use GDK as well.

Is there any way I can set scale just for ulauncher and not the processes launched by ulauncher?

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
I don't think we can fix that directly without adding any super weird niche settings or making assumptions that fit your use case but breaks other people's use cases (like setting GDK_SCALE=2 globally).

So I guess instead we should try to support scale/resize directly in our settings.

**Comment by friday** [comment]
Closing in favor of #970
