### ISSUE TITLE
Add an option to clear the previously written text

### ISSUE THREAD

**Issue by NetBender** [Ulauncher/Ulauncher#123]
After the latest stable update (2.2.0.r1), if the user doesn't complete the query, the text is stored and shown every time ULauncher is called (while in the previous version it was automatically removed to show an empty text field).
Can this behaviour be optional?

**Comment by gornostal** [comment]
This behavior is by design and was there since version 2 (maybe even 1).

I'll add an option to clear the input. It's not going to be any time soon, though.

**Comment by CottonEaster** [comment]
I second the request.

**Comment by diggit** [comment]
Automatically hilighting previous query could be solution too. Typing will overwrite it immediately but if you wan to reuse it, just press right arrow and continue...

**Comment by TWT-GSCHW** [comment]
This also happens if you close ULauncher with ESC key. I think in this case the search string should definitely be cleared. Else the suggestion from diggit seems perfect.

**Comment by gornostal** [comment]
Done in v3.1.1
https://ulauncher.io/#Download
