### ISSUE TITLE
Black borders when the compositor is closed in v6

### ISSUE THREAD

**Issue by QbDesu** [Ulauncher/Ulauncher#1235]
### Environment

i3wm + picom

### Bug description

Heya, this isn't really a bug but mostly of the way I handle my environment but as per https://github.com/Ulauncher/Ulauncher/issues/869 I will report my issue here.

While I think the changes to automatically detect whether transparency/compositor effects are supported are really cool it commonly results in black borders because of the window shadows for me. The problem being that I'll disable my compositor when I start a game because there is a noticeable performance impact from the compositor. And usually the will keep the game running for a longer time with my compositor turned off even when doing other things on the side.

Because this only checks whether the needed compositor effects are available at startup changes that happen down the line are not detected. It would be nice to either just re-add an option to turn the window shadow of like before or have it re-check whether the launcher is shown.

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
Thank you for the detailed and informative report. So it's working if you restart Ulauncher after every time you disable/enable your compositor?

I think it might be fixable by moving these lines to the `position_window` method of this class:
https://github.com/Ulauncher/Ulauncher/blob/v6/ulauncher/ui/windows/UlauncherWindow.py#L47-L56

Would you be up for trying that?

Maybe #1151 could fix this too.

**Comment by friday** [comment]
Should be fixed now, but I don't have any environment to proper test this, so if it's not working please let me know.

**Comment by nathanaelhoun** [comment]
I just installed v6.0.0-beta2 and I have the same bug. I do not use any compositor in my environment.

I have'nt spotted anything related to this in the logs, but happy to provide more informations if needed.

![image](https://github.com/Ulauncher/Ulauncher/assets/45119518/23c1e2c1-2113-4267-abf4-354eab0327c2)


### Environment

ArchLinux + i3wm on X11, without picom.

**Comment by friday** [comment]
@nathanaelhoun: https://github.com/Ulauncher/Ulauncher/issues/262#issuecomment-1257831153

**Comment by nathanaelhoun** [comment]
@friday Sorry, I do **not** use picom or another compositor, so I don't think this solution apply to me.

**Comment by friday** [comment]
> @friday Sorry, I do **not** use picom or another compositor, so I don't think this solution apply to me.

Sorry. I saw "Picom", so I linked to that. For i3wm search their documentation or community, or create an issue here describing your issue.

**Comment by friday** [comment]
![image](https://github.com/Ulauncher/Ulauncher/assets/515120/0e5d249b-0276-4df5-8c21-7a8c3f19a74a)

@nathanaelhoun Sorry for the late update. If you are still willing to help testing this, I have just added logging to the v6 branch when you open a window. I would be interested in what this says for you. It is not released, but you can test it from the v6 branch if you have time. If you get a visual and the "is composited" part says true also, then I'm not sure how to fix this.

**Comment by friday** [comment]
This was released as https://github.com/Ulauncher/Ulauncher/releases/tag/v6.0.0-beta10. I'm not sure if it's effectively fixed or if it's just logging it better. It would be very good to know.

**Comment by nathanaelhoun** [comment]
Hey @friday, thanks for the update. Unfortunately, I don't have access to a linux workstation these days, so I won't be able to test it. I might be able to try it after this summer though.

**Comment by friday** [comment]
Thank you @nathanaelhoun. I am pretty sure we will have released v6 by then (we are trying to release it very soon), so unless someone offers to test before or I get time to set up this environment myself someone else will make me aware if this is broken when we release. It's to be expected that things break on major versions like this.

I think I will close this again, but if you anyone has this issue on v6.0.0-beta10 or later feel free to respond (I want to know what the [log output](https://github.com/Ulauncher/Ulauncher/issues/1235#issuecomment-2068221630)).
