### ISSUE TITLE
Use Ulauncher as a app switcher by disabling launch new instance when app already open

### ISSUE THREAD

**Issue by kevgilmore** [Ulauncher/Ulauncher#1236]
### Description

I'd like to be able to use ulauncher as an app switcher, by typing in the app name i.e. 'firefox' and have the window come to the front, instead of launching a new instance.

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing enhancement requests](https://github.com/Ulauncher/Ulauncher/labels/enhancement) before suggesting this.

### Ulauncher v6

- [X] I have checked and couldn't find my suggestion in v6.

**Comment by friday** [comment]
I guess you found the option to enable this. Unfortunately it's only possible in X11.

**Comment by NamelessCoder** [comment]
I hate to ask on an already closed issue, but I've searched for 1h+ without finding the answer:

Where is the option to enable app switching? I've looked everywhere in settings and didn't find it. I'm using xorg.

**Comment by friday** [comment]
> I hate to ask on an already closed issue, but I've searched for 1h+ without finding the answer:
> 
> Where is the option to enable app switching? I've looked everywhere in settings and didn't find it. I'm using xorg.

Probably because you're using Ulauncher v5, not v6 beta? https://github.com/Ulauncher/Ulauncher/issues/162#issuecomment-1080804334

**Comment by NamelessCoder** [comment]
Thanks @friday! You're right, I'm using the latest release via `apt` so I'm on 5.14.4. This is great though, I will simply wait for the next major release - I've been using uLauncher for 2 years without this feature so I can wait a bit longer.

Thanks again for clearing this up. Much appreciated!
