### ISSUE TITLE
Latest update doesn't show the correct version of the program in the about page

### ISSUE THREAD

**Issue by NetBender** [Ulauncher/Ulauncher#124]

**Comment by gornostal** [comment]
@NetBender 
What version did you install?
What version is displayed?
What OS do you use?

**Comment by NetBender** [comment]
Installed version: 2.2.0.r1
Version displayed: the previous stable version
OS: Ubuntu 17.04

Seems that a reboot fixed everything (and i don't know how that is even possible) so i don't know how to help.
