### ISSUE TITLE
Preferences header not showing up

### ISSUE THREAD

**Issue by RodrigoNovais** [Ulauncher/Ulauncher#1243]
### Environment

Ubuntu 22.04

### Bug description

When I try to open the preferences, about or any other configuration window from Ulauncher, it displays blank
The buttons are still there and operational but it makes navigating through tabs pretty hard

![image](https://github.com/Ulauncher/Ulauncher/assets/11841314/5a593410-2833-458c-9d2f-4c6d7481ef3f)
![image](https://github.com/Ulauncher/Ulauncher/assets/11841314/1ea22d3e-66c1-445c-9161-b83e51cb17f2)

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
Closing as this has either been fixed in v6 already #869 or will be when #1257 is implemented
