### ISSUE TITLE
Setting to opt-out of application search

### ISSUE THREAD

**Issue by friday** [Ulauncher/Ulauncher#1246]
### Description

https://github.com/Ulauncher/Ulauncher/issues/834#issuecomment-1634474524
> What I'm after is rather some default box like:
> - [x] Search system applications.
>
>.. that I would personally untick. 

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing feature requests](https://github.com/Ulauncher/Ulauncher/labels/feature) before suggesting this.

### Feature isn't possible to support as an extension.

- [X] This feature request cannot satisfactory be supported as a third party extension.

### Ulauncher v6

- [X] I have checked and couldn't find my suggestion in v6.

**Comment by friday** [comment]
This should do it @iago-lito. Öet me know if there are further issues as I'm not going to be using this toggle much in testing.

**Comment by iago-lito** [comment]
Well, this does seem to work great so far :) Thanks a lot <3
