### ISSUE TITLE
Exception returning on_enter=SetUserQueryAction(...) / Howto use ExtensionResultItem() with on_enter=SetUserQueryAction(...)

### ISSUE THREAD

**Issue by ewasser** [Ulauncher/Ulauncher#125]
I've created a simple application (trying to imitate the example from your [Development Tutorial](http://docs.ulauncher.io/en/latest/extensions/tutorial.html) page.

    #!/usr/bin/python2

    from ulauncher.api.client.Extension import Extension
    from ulauncher.api.client.EventListener import EventListener
    from ulauncher.api.shared.event import KeywordQueryEvent, ItemEnterEvent
    from ulauncher.api.shared.item.ExtensionResultItem import ExtensionResultItem
    from ulauncher.api.shared.action.RenderResultListAction import RenderResultListAction
    from ulauncher.api.shared.action.HideWindowAction import HideWindowAction
    from ulauncher.api.shared.action.ExtensionCustomAction import ExtensionCustomAction
    from ulauncher.api.shared.action.SetUserQueryAction import SetUserQueryAction
    from ulauncher.api.shared.action.OpenUrlAction import OpenUrlAction 

    class DemoExtension(Extension):

        def __init__(self):
            super(DemoExtension, self).__init__()
            self.subscribe(KeywordQueryEvent, KeywordQueryEventListener())

    class KeywordQueryEventListener(EventListener):

        def on_event(self, event, extension):
            items = []
            for i in range(5):
                items.append(ExtensionResultItem(icon='images/icon.png',
                                                name='Item %s' % i,
                                                description='Item description %s' % i,
                                                on_enter=HideWindowAction()))

            # Added special button too modify the query
            items.append(ExtensionResultItem(icon='images/icon.png',
                                            name='Suchmich',
                                            description='Search me',
                                            on_enter=SetUserQueryAction("gg search me"),
                                            )
                        )

            return RenderResultListAction(items)

    if __name__ == '__main__':
        DemoExtension().run()

My main purpose was (other than testing around) to modify the query of ulauncher if you select the last entry. All I've got was this exception:

    test | 2017-05-03 15:54:28,967 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event KeywordQueryEvent
    /usr/lib/python2.7/site-packages/ulauncher/util/desktop/notification.py:1: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
    from gi.repository import Notify
    /usr/lib/python2.7/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py:5: PyGIWarning: WebKit2 was imported without specifying a version first. Use gi.require_version('WebKit2', '4.0') before import to ensure that the right version gets loaded.
    from gi.repository import Gio, Gtk, WebKit2
    test | 2017-05-03 15:54:29,009 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','destroy', 'on_destroy'
    test | 2017-05-03 15:54:29,010 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_in_event', 'on_focus_in_event'
    test | 2017-05-03 15:54:29,010 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_out_event', 'on_focus_out_event'
    test | 2017-05-03 15:54:29,011 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'input','key_press_event', 'on_input_key_press_event'
    test | 2017-05-03 15:54:29,012 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_about_activate'
    test | 2017-05-03 15:54:29,012 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_preferences_dialog_destroyed'
    test | 2017-05-03 15:54:29,012 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_close_activate'
    test | 2017-05-03 15:54:29,012 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_preferences_activate'
    test | 2017-05-03 15:54:29,012 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_input_changed'
    test | 2017-05-03 15:54:29,013 | DEBUG | ulauncher.util.display: get_screens() | Found 2 monitor(s).
    test | 2017-05-03 15:54:29,014 | DEBUG | ulauncher.util.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1920, H: 1200
    test | 2017-05-03 15:54:29,014 | DEBUG | ulauncher.util.display: get_screens() |   Monitor 1 - X: 1920, Y: 0, W: 1920, H: 1200
    test | 2017-05-03 15:54:29,017 | INFO | ulauncher.api.server.ExtensionServer: _start_thread() | Starting WS server on port 5001
    2017-05-03 15:54:29,017 | INFO | ulauncher.api.server.ExtensionController: handleClose() | Extension "None" disconnected
    Traceback (most recent call last):
    File "/usr/lib/python2.7/site-packages/ulauncher/util/SimpleWebSocketServer.py", line 664, in serveforever
        client._handleData()
    File "/usr/lib/python2.7/site-packages/ulauncher/util/SimpleWebSocketServer.py", line 250, in _handleData
        raise Exception('remote socket closed')
    Exception: remote socket closed
    test | 2017-05-03 15:54:29,025 | INFO | ulauncher.util.desktop.reader: read_desktop_file() | Could not read "...INFORMATION REDACTED...": constructor returned NULL
    ...
    test | 2017-05-03 15:54:29,028 | DEBUG | ulauncher.api.client.Client: send() | Send message
    Traceback (most recent call last):
    File "/usr/lib/python2.7/site-packages/ulauncher/api/client/Client.py", line 52, in on_message
        self.extension.trigger_event(event)
    File "/usr/lib/python2.7/site-packages/ulauncher/api/client/Extension.py", line 55, in trigger_event
        self._client.send(Response(event, action))
    File "/usr/lib/python2.7/site-packages/ulauncher/api/client/Client.py", line 82, in send
        self.ws.send(pickle.dumps(response))
    File "/usr/lib64/python2.7/pickle.py", line 1380, in dumps
        Pickler(file, protocol).dump(obj)
    File "/usr/lib64/python2.7/pickle.py", line 224, in dump
        self.save(obj)
    File "/usr/lib64/python2.7/pickle.py", line 331, in save
        self.save_reduce(obj=obj, *rv)
    File "/usr/lib64/python2.7/pickle.py", line 425, in save_reduce
        save(state)
    File "/usr/lib64/python2.7/pickle.py", line 286, in save
        f(self, obj) # Call unbound method with explicit self
    File "/usr/lib64/python2.7/pickle.py", line 655, in save_dict
        self._batch_setitems(obj.iteritems())
    File "/usr/lib64/python2.7/pickle.py", line 669, in _batch_setitems
        save(v)
    File "/usr/lib64/python2.7/pickle.py", line 331, in save
        self.save_reduce(obj=obj, *rv)
    File "/usr/lib64/python2.7/pickle.py", line 425, in save_reduce
        save(state)
    File "/usr/lib64/python2.7/pickle.py", line 286, in save
        f(self, obj) # Call unbound method with explicit self
    File "/usr/lib64/python2.7/pickle.py", line 655, in save_dict
        self._batch_setitems(obj.iteritems())
    File "/usr/lib64/python2.7/pickle.py", line 669, in _batch_setitems
        save(v)
    File "/usr/lib64/python2.7/pickle.py", line 286, in save
        f(self, obj) # Call unbound method with explicit self
    File "/usr/lib64/python2.7/pickle.py", line 606, in save_list
        self._batch_appends(iter(obj))
    File "/usr/lib64/python2.7/pickle.py", line 621, in _batch_appends
        save(x)
    File "/usr/lib64/python2.7/pickle.py", line 331, in save
        self.save_reduce(obj=obj, *rv)
    File "/usr/lib64/python2.7/pickle.py", line 425, in save_reduce
        save(state)
    File "/usr/lib64/python2.7/pickle.py", line 286, in save
        f(self, obj) # Call unbound method with explicit self
    File "/usr/lib64/python2.7/pickle.py", line 655, in save_dict
        self._batch_setitems(obj.iteritems())
    File "/usr/lib64/python2.7/pickle.py", line 669, in _batch_setitems
        save(v)
    File "/usr/lib64/python2.7/pickle.py", line 331, in save
        self.save_reduce(obj=obj, *rv)
    File "/usr/lib64/python2.7/pickle.py", line 425, in save_reduce
        save(state)
    File "/usr/lib64/python2.7/pickle.py", line 286, in save
        f(self, obj) # Call unbound method with explicit self
    File "/usr/lib64/python2.7/pickle.py", line 655, in save_dict
        self._batch_setitems(obj.iteritems())
    File "/usr/lib64/python2.7/pickle.py", line 669, in _batch_setitems
        save(v)
    File "/usr/lib64/python2.7/pickle.py", line 306, in save
        rv = reduce(self.proto)
    File "/usr/lib64/python2.7/copy_reg.py", line 71, in _reduce_ex
        state = base(self)
    TypeError: GObject.__init__() takes exactly 0 arguments (1 given)
    test | 2017-05-03 15:54:29,032 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "test" started. PID 14250
    /usr/lib/python2.7/site-packages/ulauncher/util/image_loader.py:3: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
    from gi.repository import Gtk, Gio, GLib, GdkPixbuf
    2017-05-03 15:54:29,133 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 1 results
    test | 2017-05-03 15:54:29,151 | DEBUG | root: setup_logging() | test
    test | 2017-05-03 15:54:29,152 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "test" connected
    test | 2017-05-03 15:54:29,152 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "test"
    test | 2017-05-03 15:54:29,153 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent

My questions are:

* Is this the right way to use the class `SetUserQueryAction`?
* Whats the right way to modify the query?
* Any hints?

**Comment by gornostal** [comment]
Hi @ewasser,

1. Code looks right?
2. The approach you chose is the right way to modify the query.
3. No hints yet. I'll try to repo this issue later today.

**Comment by gornostal** [comment]
That was a bug with `SetUserQueryAction()`.
Now it's fixed. Please download the newest dev release [3.0.1](https://github.com/Ulauncher/Ulauncher/releases/tag/3.0.1.r0)

Thanks for reporting the issue :+1:
