### ISSUE TITLE
Unable to launch Telegram

### ISSUE THREAD

**Issue by spicy-hero** [Ulauncher/Ulauncher#1251]
### Environment

debian 12 bookwork

### Bug description

Unable to launch Telegram, 
the .desktop file is located in `~/.local/share/applications` and it is auto-generated by Telegram, the lines are 
```
[Desktop Entry]
Name=Telegram Desktop
Comment=Official desktop version of Telegram messaging app
TryExec=/opt/Telegram/Telegram
Exec=/opt/Telegram/Telegram -- %u
Icon=telegram
Terminal=false
StartupWMClass=TelegramDesktop
Type=Application
Categories=Chat;Network;InstantMessaging;Qt;
MimeType=x-scheme-handler/tg;
Keywords=tg;chat;im;messaging;messenger;sms;tdesktop;
Actions=quit;
DBusActivatable=true
SingleMainWindow=true
X-GNOME-UsesNotifications=true
X-GNOME-SingleWindow=true

[Desktop Action quit]
Exec=/opt/Telegram/Telegram -quit
Name=Quit Telegram
Icon=application-exit
``` 
It was working days ago but not working recently, the ulauncher version is 5.15.2

### Log output

```shell
2023-07-26 15:16:32,678 | INFO | ulauncher.api.shared.action.LaunchAppAction: run() | Run application Telegram Desktop (/home/yzk/.local/share/applications/org.telegram.desktop._3e485da34fc040f9218e3891ecde1e6c.desktop) Exec ['gapplication', 'launch', 'org.telegram._3e485da34fc040f9218e3891ecde1e6c']
2023-07-26 15:16:32,686 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
error sending Activate message to application: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.telegram._3e485da34fc040f9218e3891ecde1e6c was not provided by any .service files
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by spicy-hero** [comment]
After downgrading to v5.14.0, Telegram can launch properly with the same desktop file.

**Comment by friday** [comment]
It's because your desktop entry is broken/invalid. See #1250 #952

**Comment by friday** [comment]
I just found the [issue you created for the app](https://github.com/telegramdesktop/tdesktop/issues/26573) and commented there. It is indeed a Telegram app bug, so thank you for reporting it there

**Comment by friday** [comment]
I renamed and pinned this because the dev who caused this is not taking responsibility, and I don't want more reports here, but feel free to keep the conversation going if you find a solution. It's really easy to fix issues like this though. All the necessary info is in the links I posted on that issue. In particular https://wiki.gnome.org/HowDoI/DBusApplicationLaunching

**Comment by friday** [comment]
It seems this was an issue in Ulauncher after all. https://github.com/Ulauncher/Ulauncher/releases/tag/5.15.3 should fix it.
