### ISSUE TITLE
Add desktop environment hotkey support for Budgie and Cinnamon

### ISSUE THREAD

**Issue by friday** [Ulauncher/Ulauncher#1262]
### Description

#1256 changed the implementation for the global hotkey (keyboard shortcut) using desktop environment wrappers for Gnome, KDE Plasma and XFCE.

Budgie, Panteon and Cinnamon are all forks of Gnome and they have the same system with some variation. So those should not be so hard to support either.

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing feature requests](https://github.com/Ulauncher/Ulauncher/labels/feature) before suggesting this.

### Feature isn't possible to support as an extension.

- [X] This feature request cannot satisfactory be supported as a third party extension.

### Ulauncher v6

- [X] I have checked and couldn't find my suggestion in v6.

**Comment by svandragt** [comment]
I faked the starting of the launcher with `XDG_CURRENT_DESKTOP=GNOME bin/ulauncher &` and setting a hotkey correctly set a shortcut in Pantheon's shortcuts app.

**Comment by friday** [comment]
> I faked the starting of the launcher with `XDG_CURRENT_DESKTOP=GNOME bin/ulauncher &` and setting a hotkey correctly set a shortcut in Pantheon (elementary OS) shortcuts app. The output for `XDG_CURRENT_DESKTOP` is `Pantheon`

Thanks for letting me know :+1: I wanted to test or confirm this before adding it, but since you just did it saves me a lot of time fa16d93d8fef5b7b16194d1d856085184c0f24f3

**Comment by friday** [comment]
Also implemented for Budgie now. I also implemented it for Cinnamon, but Cinnamon requires a restart for the update to take effect, so I pulled it.
