### ISSUE TITLE
ulaucher not lauching

### ISSUE THREAD

**Issue by jebnascimento** [Ulauncher/Ulauncher#1270]
### Environment

ubuntu  22.04

### Bug description

ulaucher not working anymome, after update to python 3.11.5

### Log output

```shell
➜  ulauncher --version
Traceback (most recent call last):
  File "/usr/bin/ulauncher", line 27, in <module>
    from ulauncher.main import main
  File "/usr/lib/python3/dist-packages/ulauncher/main.py", line 11, in <module>
    import gi
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3/dist-packages/gi/__init__.py)
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
You broke your system by overriding the system python version with a custom one that your OS doesn't provide.

Try hard coding the python path in the binary files (ulauncher and ulauncher-toggle) to the path to the old system python3 binary.

If you need help with that this is not the place.

**Comment by friday** [comment]
Also: You can just Google this and probably find the solution `ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3/dist-packages/gi/__init__`
