### ISSUE TITLE
Add option to increase width

### ISSUE THREAD

**Issue by prashasth-nair** [Ulauncher/Ulauncher#1277]
### Description

Add an option where we can choose width for it.

### Communication guidelines

- [x] I have read and agree with Ulauncher's communication guidelines and checked the [existing enhancement requests](https://github.com/Ulauncher/Ulauncher/labels/enhancement) before suggesting this.

### Ulauncher v6

- [X] I have checked and couldn't find my suggestion in v6.

**Comment by friday** [comment]
We had this suggestion before. It's a reasonable idea. It's really a duplicate ticket but I'll keep it up.
