### ISSUE TITLE
ulauncher getting deleted after `apt dist-upgrade`

### ISSUE THREAD

**Issue by Aviksaikat** [Ulauncher/Ulauncher#1278]
### Environment

Linux kali 6.5.0-kali2-amd64 Debian 6.5.3-1kali2 (2023-10-03) x86_64

### Bug description

`gir1.2-webkit2-4.0 libwebkit2gtk-4.0-37 ulauncher` is getting deleted every time I run `apt-get dist-upgrade -y` on my system. 

### Log output

```shell
Fetched 8,890 B in 2s (4,961 B/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  gir1.2-javascriptcoregtk-4.0 gir1.2-soup-2.4 libjavascriptcoregtk-4.0-18 libllvm15:i386 libsoup-gnome2.4-1 python3-levenshtein wmctrl
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  gir1.2-webkit2-4.0 libwebkit2gtk-4.0-37 ulauncher
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
Does that Kali version use Python v3.12?

**Comment by Aviksaikat** [comment]
> Does that Kali version use Python v3.12?

Yes 3.12.5 I believe

**Comment by friday** [comment]
3.12.5 doesn't exist. 3.12 was just release days ago. But anyway, it sounds like we need to release Ulauncher v6, so hopefully this will fix things.

**Comment by Aviksaikat** [comment]
> 3.12.5 doesn't exist. 3.12 was just release days ago. But anyway, it sounds like we need to release Ulauncher v6, so hopefully this will fix things.

![image](https://github.com/Ulauncher/Ulauncher/assets/31238298/caba284e-2655-48d9-88c5-40b06cd2fbf1)
https://www.python.org/downloads/release/python-3115/

**Comment by friday** [comment]
Ask in the Debian/Kali Linux community how to see which [Ulauncher-required package](https://github.com/Ulauncher/Ulauncher/blob/v5/debian/control) they removed.

**Comment by friday** [comment]
Also see https://github.com/Ulauncher/Ulauncher/issues/556#issuecomment-1752107407

**Comment by Aviksaikat** [comment]
I follow the instructions and build a v6 on my system. is it me or it's very very slow?

**Comment by friday** [comment]
Now you can try https://github.com/Ulauncher/Ulauncher/releases/tag/v6.0.0-beta1

Also make sure you enable ubuntu's universe repos `sudo add-apt-repository universe`

**Comment by Aviksaikat** [comment]
![image](https://github.com/Ulauncher/Ulauncher/assets/31238298/e85e1d2e-b23f-4551-82e6-91146653925e)
`apt install -f` is not helping either

**Comment by friday** [comment]
Maybe you need to run `sudo add-apt-repository security` instead for Debian. Otherwise ask in some Debian or Kali forum why you can't install https://packages.debian.org/buster/gir1.2-webkit2-4.0

**Comment by friday** [comment]
Closing. https://github.com/Ulauncher/Ulauncher/releases/tag/v6.0.0-beta2 is released now too, but doesn't change anything that will help you. But you should be able to install gir1.2-webkit2-4.0 on a debian based distro. If not it's not on us.

We might actually get rid of that depedency though, but it's not something we're actively working on yet (it's a big task): #1257
