### ISSUE TITLE
<ctrl> + <a> then <backspace> does not remove all input

### ISSUE THREAD

**Issue by ddeath** [Ulauncher/Ulauncher#128]
**Steps to reproduce:**

* open Ulauncher
* type in "/var/log"
* press < ctrl > + < a >
* press < backspace >
* it removes only "log" and not all selected input

**Ulauncher version**: 3.0.1.r0
**Linux distro**: Linux Mint 18 Sarah
**Desktop environment**: Cinnamon 3.4.0

**Logs**:
https://gist.github.com/ddeath/1253a25a0a59e5fae63c5b42095fd028

**Comment by gornostal** [comment]
Nice find :+1: 
Will be fixed soon

**Comment by gornostal** [comment]
I'm deploying release 3.0.2.r0 (Dev) that includes the fix.
