### ISSUE TITLE
Unable to launch with last version

### ISSUE THREAD

**Issue by Thanatermesis** [Ulauncher/Ulauncher#1283]
### Environment

Debian 12.2 Bookworm 

### Bug description

After compiled Ulauncher, it fails to launch:

```
$ ulauncher
2023-10-14 22:12:12,547 ⚠  ERROR Uncaught exception main.except_hook:80
Traceback (most recent call last):
  File "/usr/bin/ulauncher", line 45, in <module>
    main(IS_DEV)
  File "/usr/lib/python3/dist-packages/ulauncher/main.py", line 85, in main
    v5_to_v6()
  File "/usr/lib/python3/dist-packages/ulauncher/utils/migrate.py", line 77, in v5_to_v6
    _migrate_file(str(file), str(file), partial(_migrate_user_prefs, file.stem), overwrite=True)
  File "/usr/lib/python3/dist-packages/ulauncher/utils/migrate.py", line 46, in _migrate_file
    data = transform(data)
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ulauncher/utils/migrate.py", line 63, in _migrate_user_prefs
    manifest = ExtensionManifest.load(f"{PATHS.EXTENSIONS}/{extension_id}/manifest.json")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ulauncher/utils/json_conf.py", line 37, in load
    instance.update(data)
  File "/usr/lib/python3/dist-packages/ulauncher/utils/basedataclass.py", line 80, in update
    self[k] = v
    ~~~~^^^
  File "/usr/lib/python3/dist-packages/ulauncher/modes/extensions/ExtensionManifest.py", line 89, in __setitem__
    super().__setitem__(key, value)
  File "/usr/lib/python3/dist-packages/ulauncher/utils/basedataclass.py", line 73, in __setitem__
    raise KeyError(msg)
KeyError: '"input_debounce" must be of type float, int given.'

```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
Thanks for the report :pray:  If you upgrade now, a318aab4ea941eec8c821ab841e51eaf0051cbe4 should have fixed this. I'll close the issue, but let me know if it's unfixed or if you get another issue.

**Comment by Thanatermesis** [comment]
Thank you, it seems to work now

On the other hand, trying this version it first show a popup notification saying it doesn't supports global hotkeys or something similar (if this is displayed once it is fine, where is this setting saved?), but I still seeing an ugly warning message about it in the config, how I can get rid of it? I think that basically this message is useless and annoying 🤔 let me explain:

Actually:   If the desktop supports global hotkeys, it shows the widget configurator so the user can define it, (otherwise it shows the warning)

What I suggest is that, only show this widget if the desktop supports it and nothing more (without the warning), in other words, if the desktop cannot assign a global hotkey is totally the user's job to define it, the user knows how to run "ulauncher" and will take care of assigning a hotkey to his desktop to run it, so this warning becomes useless

On the other hand, the "gapplication" way of running it can be suggested on the "ulauncher output" on terminal if is detected have not run on this way, or just as an entry in the README file as how to run it should be more than enough 🤔

**Comment by Thanatermesis** [comment]
Also, the option "Launch at login" seems like unable to be disabled 🤔🤔, I want it to be run on-demand only in order to keep up resources free
