### ISSUE TITLE
uLauncher for Ubuntu 23.10 via ppa. 

### ISSUE THREAD

**Issue by sliddjur** [Ulauncher/Ulauncher#1284]
### Description

It would be nice to have uLauncher installed via Ubuntu 23.10 ppa, as per the documentation:
https://ulauncher.io/#Download
https://launchpad.net/~agornostal/+archive/ubuntu/ulauncher

Thanks for a great project!

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing enhancement requests](https://github.com/Ulauncher/Ulauncher/labels/enhancement) before suggesting this.

### Ulauncher v6

- [X] I have checked and couldn't find my suggestion in v6.

**Comment by friday** [comment]
Done: https://launchpad.net/~agornostal/+archive/ubuntu/ulauncher/+build/26772815
