### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by Laurens256** [Ulauncher/Ulauncher#1286]
### Environment

Mint

### Bug description

![image](https://github.com/Ulauncher/Ulauncher/assets/85798751/778c4332-f512-4310-810b-118fdb4e0adb)

Link to custom color themes: https://docs.ulauncher.io/en/latest/themes/themes.html results in 404

I think the link should be https://docs.ulauncher.io/en/stable/themes/themes.html

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
Thanks! Feel free to make a PR (it's fine to use the git text editor) to get the credit for the fix. We likely won't mention small things like this in the change notes, but it will be in the git history.

**Comment by Laurens256** [comment]
thanks!
