### ISSUE TITLE
selection shortcut alt + 1 select incorrect option

### ISSUE THREAD

**Issue by ddeath** [Ulauncher/Ulauncher#129]
**Steps to reproduce:**

* open Ulauncher
* type in "/var"
* press < key-down > multiple times to select "www" (it shows shortcut < alt > + <5>)
* press < alt > + <1>
* it selects "/var/www" anyway

**Ulauncher version**: 3.0.1.r0
**Linux distro**: Linux Mint 18 Sarah
**Desktop environment**: Cinnamon 3.4.0

**Logs**:
https://gist.github.com/ddeath/663e39a440da544f28ec29b32461c913

**Comment by gornostal** [comment]
@ddeath thanks for reporting these bugs.
I'll look into them.
