### ISSUE TITLE
Double and triple click not working

### ISSUE THREAD

**Issue by Laurens256** [Ulauncher/Ulauncher#1297]
### Environment

Mint 21.2

### Bug description

When double clicking to select a word in the Ulauncher window, the text does not always get selected because Ulauncher tries to move the window. Double click works sometimes and triple click never works. When double clicking, the mouse cursor becomes the `move` version and sometimes the windows inches like a millimeter.

The cause I found for this is for some reason the double click event passes through the `input_box` in `UlauncherWindow.py` onto `event_box`.  

If this is not intended behavior, a possible fix is to add this to `on_mouse_down` function: `if event.button == 1 and not event.type == Gdk.EventType._2BUTTON_PRESS:`. There might be a better fix though, this is just what I found in a few minutes of testing

Not 100% sure what the intended behavior for this was, if this is indeed a bug I could research a bit more and create a PR.

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
I can't even replicate this, so it might be DE/Window manager-related. Regardless, if you think it's not intuitive, then it probably isn't. So research is appreciated :+1:
