### ISSUE TITLE
Duplicate shortcuts

### ISSUE THREAD

**Issue by igorsantos07** [Ulauncher/Ulauncher#1302]
### Description

There should be a button to duplicate an existing shortcut, in case we want a similar one but with some tweaks :)

E.g. a search shortcut with an extra parameter, or another language on Wikipedia.

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing feature requests](https://github.com/Ulauncher/Ulauncher/labels/feature) before suggesting this.

### Feature isn't possible to support as an extension.

- [X] This feature request cannot satisfactory be supported as a third party extension.

### Ulauncher v6

- [X] I have checked and couldn't find my suggestion in v6.

**Comment by friday** [comment]
This is not a feature we want to support. Names and keywords should be unique, so we don't want to copy those, and "Default search" and "Run without arguments" are just checkboxes, so it's not that hard to copy them.

It sounds like you are using shortcuts for something they were not intended for, and likely you would be better off with either creating static desktop entries or an extension which can handle more dynamic things like this.

Also, in v6 you can just open ~/.config/ulauncher/shortcuts.json in a text editor and edit, then restart Ulauncher (make a backup first though).
