### ISSUE TITLE
`sys.prefix` should not be used to discover non-dev data directories?

### ISSUE THREAD

**Issue by nazarewk** [Ulauncher/Ulauncher#1320]
### Environment

NixOS

### Bug description

When packaging ulauncher for Nix (#1307) I noticed it tried to read web app files from within Python installation's directory so I patched it `{sys.prefix}` -> `$out`.

Today I started digging into issue and seems like this is a proper behavior according to [Python docs](https://docs.python.org/3/library/sys.html#sys.prefix):
> A string giving the site-specific directory prefix where the platform independent Python files are installed; on Unix, the default is /usr/local. This can be set at build time with the [--prefix](https://docs.python.org/3/using/configure.html#cmdoption-prefix) argument to the configure script. See [Installation paths](https://docs.python.org/3/library/sysconfig.html#installation-paths) for derived paths.

> Note: If a [virtual environment](https://docs.python.org/3/library/venv.html#venv-def) is in effect, this value will be changed in site.py to point to the virtual environment. The value for the Python installation will still be available, via [base_prefix](https://docs.python.org/3/library/sys.html#sys.base_prefix).

This means `sys.prefix` does what you want it to do only inside the virtualenv itself (in a development environment?) while:
- `ULAUNCHER_DATA_DIR` is set up only for development (where it seems not to be needed)
- [yesterday's patch](https://github.com/Ulauncher/Ulauncher/pull/1313/files#diff-dbb0743a2ebf03b2bf85e5c641ef71141136ef9d804051a6c8835757b10d8d3bR26) does it as a fallback when `ULAUNCHER_DATA_DIR` is missing, which has no chance of working

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
> This means sys.prefix does what you want it to do only inside the virtualenv itself (in a development environment?)

No. This works perfectly (I'm running it right now and I wouldn't have pushed it if it didn't work). Tested both running from source and installed, Arch and Ubuntu.

How could this only work in a virtual environment Ulauncher doesn't run in a virtual environment? The documentation says the Unix default is /usr/local for non-virtual environments, but for Arch and Ubuntu it's just `/usr`

![image](https://github.com/Ulauncher/Ulauncher/assets/515120/85a1e56d-711e-4758-9dd9-2d56013dd2d5)

It may be wrong to use sys.prefix here for Nix and/or other OSes though. Both me or the original maintainer have been learning how to handle these things as needed and by trial and error.

**Comment by nazarewk** [comment]
Makes sense. It assumes `ulauncher` is installed into that prefix which in itself also makes sense.

The more I think about it the more it seems to be Nix-specific.[ `$NIX_PYTHONPATH`](https://github.com/NixOS/nixpkgs/blob/e4ad989506ec7d71f7302cc3067abd82730a4beb/pkgs/development/interpreters/python/sitecustomize.py#L30-L39) seems like a good suspect.

**Comment by nazarewk** [comment]
Those 2 code pieces seem to be responsible:
- [sitecustomization.py](https://github.com/NixOS/nixpkgs/blob/e4ad989506ec7d71f7302cc3067abd82730a4beb/pkgs/development/interpreters/python/sitecustomize.py)
- [`/bin/*` wrapper](https://github.com/NixOS/nixpkgs/blob/e4ad989506ec7d71f7302cc3067abd82730a4beb/pkgs/development/interpreters/python/wrapper.nix#L44-L46)
