### ISSUE TITLE
Better instructions on using preferences devserver during development

### ISSUE THREAD

**Issue by nazarewk** [Ulauncher/Ulauncher#1322]
### Description

There is an instruction to start dev server with `yarn run dev`, but when I go to http://localhost:3002 in Firefox it cannot connect to the application:
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at prefs:///get/all. (Reason: CORS request not http).

I am not sure whether it would resolve at all outside WebKit?

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing feature requests](https://github.com/Ulauncher/Ulauncher/labels/feature) before suggesting this.

### Feature isn't possible to support as an extension.

- [X] This feature request cannot satisfactory be supported as a third party extension.

### Ulauncher v6

- [X] I have checked and couldn't find my suggestion in v6.

**Comment by friday** [comment]
Sorry about the confusion!.

I pushed 032788ac to delete the old misleading information. This never worked well. It was possible only using a static fixture, and I found that to be not helpful at all, and only a burden to maintain it, so I deleted it (607338fbc91bc73dbe59a6d7e920e6d6e7dfcb4d), without deleting the rest.

It's all going away anyway: #1257

**Comment by friday** [comment]
Unfortunately that's the best we can do for this issue, so I'm going to close it.

**Comment by nazarewk** [comment]
yeah, removing the piece of instructions is the best in this case
