### ISSUE TITLE
shortcut scripts no longer execute

### ISSUE THREAD

**Issue by 88-percent** [Ulauncher/Ulauncher#1335]
### Environment

Pop!OS 22.04 LTS

Ulauncher 5.15.6

### Bug description

Within the last week or two Ulauncher stopped executing scripts I have set as shortcuts.

All scripts stored as shortcuts no longer execute. These scripts have worked until recently. Other shortcuts work as expected.

What did you do to trigger the issue? 

1. invoke Ulauncher
2. type the keyword for the shortcut
3. hit enter

What happened?
Nothing.

What did you expect to happen instead?
Run the script.

I'm not including a log output because for some reason, the Ulauncher  instance launched via the terminal executes scripts without issue. 

This may be a results of a tweak I've made to my system, but if it is I've been unable to determine the cause.

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [ ] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
> I'm not including a log output because for some reason, the Ulauncher instance launched via the terminal executes scripts without issue.

If this happens consistently it may be because you run Ulauncher with different permissions or your scripts require an interactive shell?

Please give an example of a shortcut code and the shell scripts.

**Comment by 88-percent** [comment]
I don't think I changed any of the permissions, but I may've tweaked something I thought was totally unrelated and not noticed.

The following shortcut has been working well for over a year:

keyword: `next`

```
#! /bin/bash
rhythmbox-client --next
```

**Comment by 88-percent** [comment]
checking it looks as though Ulauncher is running as user in both instances. Here are the different outputs I'm getting from ps auxw.

Launching normally (scripts not do not execute):

```user      725370  7.5  0.4 2132024 80156 ?       S<l  11:26   0:00 /usr/bin/python3 /usr/bin/ulauncher --hide-window```

Launching via terminal (scripts execute):

``` user      724503  0.7  0.5 2243232 91148 pts/0   SNl+ 11:21   0:01 /usr/bin/python3 /usr/bin/ulauncher```

Any chance this could be an issue with python permissions?

**Comment by friday** [comment]
Hi again @88-percent
I'm especially busy with my day job these days so the time I do have left for Ulauncher I prefer to spend efficiently for known actionable issues/features, and not the obscure ones where the reproduction is unclear.

I would advice you to try Ulauncher version 6 to see if it still happens there, and to get your hands dirty with the actual code. If you can write bash scripts, writing Python is not a big step up.

**Comment by friday** [comment]
For debugging, add your own log breakpoints and check the logfile ulauncher creates, and/or use journald if you are using systemd: https://www.digitalocean.com/community/tutorials/how-to-use-journalctl-to-view-and-manipulate-systemd-logs

**Comment by 88-percent** [comment]
> the time I do have left for Ulauncher I prefer to spend efficiently for known actionable issues/features, and not the obscure ones where the reproduction is unclear.

Completely understand. Even if you _did_ have the time, I'd say it could certainly be better spent elsewhere. 

I'll check out v6. Thanks so much for your contributions to this project.

**Comment by 88-percent** [comment]
Just in case anyone else is having a similar issue, v6 wasn't able to fix whatever was causing this on my system. The workaround I found was so assign .desktop files to all of my scripts and launch them that way.
