### ISSUE TITLE
v6: doesn't start on Nix/NixOS

### ISSUE THREAD

**Issue by nazarewk** [Ulauncher/Ulauncher#1340]
### Environment

NixOS

### Bug description

I just tried updating (noticed I had old version pinned) Ulauncher and got the error described below

This is mostly a note to myself to not forget to fix it when I have some time to spare.

https://github.com/nazarewk-iac/nix-configs/commit/fa799252ba69c3e840be1c26f3c9035d95e36c58

### Log output

```shell
kdn@krul ~/d/g/n/nix-configs (main) [1]> ucs ulauncher.service
● ulauncher.service - Ulauncher service
     Loaded: loaded (/home/kdn/.config/systemd/user/ulauncher.service; enabled; preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Fri 2024-02-09 14:21:25 CET; 2s ago
       Docs: https://ulauncher.io/
    Process: 512852 ExecStart=/nix/store/xj01bb7npc4xfqv08d49fx78yijvqvs3-python3.11-ulauncher-v6/bin/ulauncher --no-window (code=exited, status=1/FAILURE)
   Main PID: 512852 (code=exited, status=1/FAILURE)
        CPU: 172ms
kdn@krul ~/d/g/n/nix-configs (main) [3]> /nix/store/xj01bb7npc4xfqv08d49fx78yijvqvs3-python3.11-ulauncher-v6/bin/ulauncher
Ulauncher is not properly installed on your system.
Please install or reinstall Ulauncher, and ensure you are not overriding your system Python version
kdn@krul ~/d/g/n/nix-configs (main) [1]>
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
Thanks for helping out again :pray: 

It's failing to import the installed ulauncher module (because it's not installed or not installed in the expected path for the given python version).

The error _message_ is from #1281 (related to issues on Arch/AUR  with Python deps: #930), but I don't think this PR introduced the issue.

**Comment by friday** [comment]
I have now also merged a PR that changes the `./ul` helper wrapper for a mikefile: #1338, but I had to keep `./ul` just for nix, so it can patch a binary: https://github.com/Ulauncher/Ulauncher/pull/1338/commits/f351d22991f9c04382e3da51aa42fd31d0e32037 If you would know a way to get it working without `./ul` it would be very apprecaited.

**Comment by nazarewk** [comment]
@friday where is this coming from? https://github.com/Ulauncher/Ulauncher/blob/main/ulauncher/modes/extensions/DeferredResultRenderer.py#L7-L7

The real error after fiddling with printing traceback is:
```text
kdn@krul ~/d/g/U/Ulauncher (fix-nix-build)> ./nix/result/bin/ulauncher
Traceback (most recent call last):
  File "/nix/store/y6rz5kjfla4r303i79f1nnzhvwalrhh3-python3.11-ulauncher-v6/bin/.ulauncher-wrapped", line 31, in <module>
    from ulauncher.main import main
  File "/nix/store/y6rz5kjfla4r303i79f1nnzhvwalrhh3-python3.11-ulauncher-v6/lib/python3.11/site-packages/ulauncher/main.py", line 12, in <module>
    from ulauncher.ui.UlauncherApp import UlauncherApp
  File "/nix/store/y6rz5kjfla4r303i79f1nnzhvwalrhh3-python3.11-ulauncher-v6/lib/python3.11/site-packages/ulauncher/ui/UlauncherApp.py", line 12, in <module>
    from ulauncher.modes.extensions.ExtensionSocketServer import ExtensionSocketServer
  File "/nix/store/y6rz5kjfla4r303i79f1nnzhvwalrhh3-python3.11-ulauncher-v6/lib/python3.11/site-packages/ulauncher/modes/extensions/ExtensionSocketServer.py", line 11, in <module>
    from ulauncher.modes.extensions.ExtensionSocketController import ExtensionSocketController
  File "/nix/store/y6rz5kjfla4r303i79f1nnzhvwalrhh3-python3.11-ulauncher-v6/lib/python3.11/site-packages/ulauncher/modes/extensions/ExtensionSocketController.py", line 8, in <module>
    from ulauncher.modes.extensions.DeferredResultRenderer import DeferredResultRenderer
  File "/nix/store/y6rz5kjfla4r303i79f1nnzhvwalrhh3-python3.11-ulauncher-v6/lib/python3.11/site-packages/ulauncher/modes/extensions/DeferredResultRenderer.py", line 7, in <module>
    from typing_extensions import Literal
ModuleNotFoundError: No module named 'typing_extensions'
Ulauncher is not properly installed on your system.
Please install or reinstall Ulauncher, and ensure you are not overriding your system Python version
```

**Comment by nazarewk** [comment]
Not sure why it was not triggered inside `checkPhase` during build, but has errors when trying to run after building.

**Comment by nazarewk** [comment]
> It was probably not detected in `checkPhase` because mypy depends on typing_extensions.

explains why I was getting it during startup, the new `installCheckPhase` will catch such errors.

**Comment by friday** [comment]
> > It was probably not detected in `checkPhase` because mypy depends on typing_extensions.
> 
> explains why I was getting it during startup, the new `installCheckPhase` will catch such errors by running in an environment having only `$HOME` set (`env -i HOME=XXX xvfb-run ... -- ulauncher`).

Awesome :pray:  I was just thinking how I could catch things like this with the CI in the future.
