### ISSUE TITLE
How would you build for Centos?

### ISSUE THREAD

**Issue by Pshemas** [Ulauncher/Ulauncher#135]
Sorry for posting this here, but I can't seem to find other place - how do you build Ulauncher for Centos7 ? 
There is no rpm for this distro and I'd love to have it - mostly because it is possible to configure Ulauncher to start from a single keystroke (super key for example). Even though from what I read it is not officially supported , for me this is the only sensible option for launcher - and the reason I would prefer Ulauncher over other options (well, and with Synapse seemingly being dead and with no docs).

**Comment by Pshemas** [comment]
I'm stuck at:
ImportError: cannot import name WebKit2

**Comment by gornostal** [comment]
Hi
Sorry for the delay.

Looks like you need to install package `gir1.2-webkit2-4.0` or alternative for Centos.
Possible names: `typelib-1_0-WebKit2-4_0`, `webkitgtk3`, `webkit2gtk`

If you get it to work, could you post list of packages that you had to install please?
Thanks.

**Comment by Pshemas** [comment]
sorry for not getting back to you sooner - I resolved the problem by installing all webkit packages (typed yum install webkitgtk* ). If there's a way to check exactly which package contained required files let me know and I'll try to sort it out.
I regret I don't know howto package apps - I'd love to hae Ulauncher as RPM for Centos . Anyways I got it working and super happy with it - Ulauncher works great (with minor quirks) and it takes way less memory than other launchers.

**Comment by gornostal** [comment]
I'm reopening this issue so I have a reminder to prepare a list of packages for Centos that are required for Ulauncher.

**Comment by krizajb** [comment]
Hmm, would you be so nice and make a rpm or maybe make a detailed instructions where to get all required libs to build this for centos7?

**Comment by gornostal** [comment]
Hi guys, 
if you could look at [setup.cfg](https://github.com/Ulauncher/Ulauncher/blob/dev/setup.cfg) and provide a similar list of package names for Centos, I would really appreciate that.

Once I have that I think I should be able to automate RPM builds for Centos.

**Comment by djwf** [comment]
@gornostal: FYI, applying the following patch allowed me to build a package that installed successfully on centos7.

```
diff --git a/build-utils/build-rpm.sh b/build-utils/build-rpm.sh
index 4a40751..7180fdb 100755
--- a/build-utils/build-rpm.sh
+++ b/build-utils/build-rpm.sh
@@ -53,6 +53,11 @@ cd $tmpdir
 python setup.py bdist_rpm
 find . -name "*noarch.rpm" -print0 | xargs -0 -I file cp file /tmp/ulauncher_$1_fedora.rpm
 
+# build for CentOS 7
+sed -i "s/python2-inotify/python-inotify/" setup.cfg
+python setup.py bdist_rpm
+find . -name "*noarch.rpm" -print0 | xargs -0 -I file cp file /tmp/ulauncher_$1_centos7.rpm
+
 # build for OpenSUSE
 sed -i "s/\[bdist_rpm\]/[bdist_rpm_fedora]/g" setup.cfg
```

Hope that helps!

**Comment by kfirba** [comment]
@Pshemas @gornostal Hey.

I'm trying to figure out how can I install ULauncher on Centos and can't figure this out. Can you please share the steps you took to do it?

Thanks!

**Comment by gornostal** [comment]
@djwf It doesn't work for me. 
The following packages cannot be found: python2-pyxdg, libappindicator-gtk3, python-Levenshtein.
I'm running Centos 7 with Linux 3.10.0 on my VirtualBox.

@kfirba there are no steps yet. Sorry

**Comment by gornostal** [comment]
@djwf could you attach an RPM file please?

**Comment by djwf** [comment]
@gornostal The file is attached.  Note that I'm running kernel 4.15, although I've also been able to use the same patch on a system running 3.10.

[ulauncher_4.0.6.r1_centos7.rpm.tar.gz](https://github.com/Ulauncher/Ulauncher/files/1869919/ulauncher_4.0.6.r1_centos7.rpm.tar.gz)

**Comment by gornostal** [comment]
@djwf Thanks for the file, but it doesn't work for me

![screenshot from 2018-04-06 10 03 33](https://user-images.githubusercontent.com/1202543/38407367-d2fb2576-3981-11e8-9c9d-267d56fc92e8.png)

Did I do something wrong?

**Comment by djwf** [comment]
I checked all three of those packages (the errors from above), and they all are in the EPEL repository.  Do you have that enabled on your CentOS system?

**Comment by gornostal** [comment]
Apparently I didn't not have EPEL repo enabled.
It worked after I installed `sudo yum install epel-release`!

**Comment by gornostal** [comment]
Done. You can now get Ulauncher for CentOS 7 from https://ulauncher.io

**Comment by ababak** [comment]
No more automated builds for CentOS?

**Comment by gornostal** [comment]
@ababak I think this deserves a new Github issue, so I've created #376
