### ISSUE TITLE
Add an option to blacklist certains directories from search

### ISSUE THREAD

**Issue by adriffaud** [Ulauncher/Ulauncher#136]
Hello,

It would be nice to be able to blacklist certain directories from indexing.
In my case, on Linux Mint, I have 210 `.desktop` files in `/usr/share/applications/screensavers`. All these shortcuts appear in Ulauncher and I often launch some of them given their names looks a lot like apps I use most :sweat_smile:

**Ulauncher version**: 2.2.1.r0
**Linux distro**: Linux Mint 18.1
**Desktop environment**: Cinnamon 3.2.7

**Comment by gornostal** [comment]
That would be a good improvement indeed.

**Comment by gornostal** [comment]
Implemented in v3.1.1
https://ulauncher.io/#Download
