### ISSUE TITLE
The box  disappeared when  swtiching input method by keyboard shortcut 

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [Ulauncher/Ulauncher#1366]
### Description

I set two keyboard shortcuts:
- `Alt + Space`: to trigger the Ulauncher
- `Super + Space` to trigger the input method

Reproduce step:
1. Trigger Ulauncher by pressing `Alt+Space`
2. I want search some chinese words in box, so I press `Super + Space`
3. The box is disappeared now

But if I trigger the input method by using mouse, that's ok, I can input chinese word in box, but I prefer to use `Super + Space`. 

Thanks in advance

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing enhancement requests](https://github.com/Ulauncher/Ulauncher/labels/enhancement) before suggesting this.

### Ulauncher v6

- [X] I have checked and couldn't find my suggestion in v6.

**Comment by friday** [comment]
Can't really be helped: https://github.com/Ulauncher/Ulauncher/discussions/891
