### ISSUE TITLE
Add button to trigger directory desktop file re-scan

### ISSUE THREAD

**Issue by viggy96** [Ulauncher/Ulauncher#137]
Basically title. It's not that difficult to kill Ulauncher and start it again to do this, but it'd be nice and more user friendly if there was a button that did this, or better yet, maybe an apt trigger which automatically did this upon application install (or both).

**Comment by gornostal** [comment]
Ulauncher watches app directories and adds apps to the index automatically.
If you install new apps but they don't appear in Ulauncher it could be a bug.
Can you provide steps to reproduce please?
