### ISSUE TITLE
Opening chrome doesn't close ulauncher window

### ISSUE THREAD

**Issue by Thanatermesis** [Ulauncher/Ulauncher#1380]
### Environment

Debian 12.5 Bookworm 

### Bug description

Using the last 6.0.0-beta8 tag build, running ulauncher launches correctly desktop apps, but when launching "chrome" it doesn't close the ulauncher window after chrome has been launched. This bug didn't existed in the version 6.0.0-b5

### Log output

```shell
version 6.0.0-beta8:

2024-04-20 09:21:25,395 ℹ  DEBUG render 48 results UlauncherWindow.show_results:351
2024-04-20 09:21:27,405 ℹ  INFO Run application Google Chrome (google-chrome) Exec ['/usr/bin/google-chrome-stable'] launch_app.launch_app:50

version 6.0.0-b5:
2024-04-20 09:29:08,647 ℹ  DEBUG render 48 results UlauncherWindow.show_results:401
2024-04-20 09:29:09,579 ℹ  INFO Run application Google Chrome (google-chrome) Exec ['/usr/bin/google-chrome-stable'] launch_app.launch_app:54
2024-04-20 09:29:09,722 ℹ  DEBUG render 0 results UlauncherWindow.show_results:401

```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.
- [X] I have tried to understand the error message and help myself, before reporting it.
- [X] My issue description has clear steps for how to reproduce the issue.
- [X] This issue applies to the whole Ulauncher application, not for a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by Thanatermesis** [comment]
Update:

Working: 6.0.0-beta6
Bugged: 6.0.0-beta7

**Comment by friday** [comment]
I just tested and cannot reproduce. There was a ton of changes in beta7, so this really gives me no clue where to look.

Could you try to find which commit introduced it?

See https://github.com/Ulauncher/Ulauncher/blob/v6/CONTRIBUTING.md#running-the-app-from-the-local-repository and git bisect https://www.youtube.com/watch?v=D7JJnLFOn4A

**Comment by Thanatermesis** [comment]
Sure,

I used git bisect to find the buggy commit, after a few steps it show that the buggy commit is cad2954aec03cdb720693be9e9020165553c02d9

Last step result from terminal:

```text
~/D/m/s/b/a/ulauncher git:tags/v6.0.0-beta7~9:bisect ❯❯❯ git bisect bad
cad2954aec03cdb720693be9e9020165553c02d9 is the first bad commit
commit cad2954aec03cdb720693be9e9020165553c02d9
Author: Albin Larsson <mail@fridaythe14th.com>
Date:   Sun Apr 14 20:28:11 2024 +0200

    refactor: force strict types

 pyproject.toml                                     |  7 ++-
 ulauncher/api/client/Client.py                     | 16 ++++--
 ulauncher/api/client/EventListener.py              | 12 +++-
 ulauncher/api/extension.py                         | 16 +++---
 ulauncher/api/result.py                            | 12 ++--
 ulauncher/api/shared/action/ActionList.py          |  7 ++-
 ulauncher/api/shared/action/DoNothingAction.py     |  2 +-
 .../api/shared/action/ExtensionCustomAction.py     |  2 +-
 ulauncher/api/shared/action/HideWindowAction.py    |  2 +-
 ulauncher/api/shared/action/OpenAction.py          |  5 +-
 ulauncher/api/shared/action/RunScriptAction.py     |  5 +-
 ulauncher/api/shared/event.py                      |  6 +-
 ulauncher/api/shared/query.py                      | 13 +++--
 ulauncher/config.py                                |  2 +-
 ulauncher/main.py                                  |  7 ++-
 ulauncher/modes/ModeHandler.py                     |  2 +-
 ulauncher/modes/apps/AppMode.py                    | 15 +++--
 ulauncher/modes/apps/AppResult.py                  | 15 +++--
 ulauncher/modes/apps/launch_app.py                 | 13 +++--
 ulauncher/modes/calc/CalcMode.py                   |  8 +--
 ulauncher/modes/calc/CalcResult.py                 |  3 +-
 .../modes/extensions/DeferredResultRenderer.py     | 13 +++--
 ulauncher/modes/extensions/ExtensionController.py  |  4 +-
 ulauncher/modes/extensions/ExtensionManifest.py    |  6 +-
 ulauncher/modes/extensions/ExtensionMode.py        |  6 +-
 ulauncher/modes/extensions/ExtensionRuntime.py     |  2 +-
 .../modes/extensions/ExtensionSocketController.py  | 16 +++---
 .../modes/extensions/ExtensionSocketServer.py      | 16 +++---
 .../file_browser/CopyPathToClipboardResult.py      |  5 +-
 ulauncher/modes/file_browser/FileBrowserMode.py    |  2 +-
 ulauncher/modes/file_browser/FileBrowserResult.py  |  4 +-
 ulauncher/modes/file_browser/OpenFolderResult.py   |  5 +-
 ulauncher/modes/file_browser/get_icon_from_path.py |  2 +-
 ulauncher/modes/shortcuts/ShortcutMode.py          | 20 ++++---
 ulauncher/modes/shortcuts/ShortcutResult.py        |  4 +-
 ulauncher/modes/shortcuts/ShortcutsDb.py           |  9 ++-
 ulauncher/ui/AppIndicator.py                       | 12 ++--
 ulauncher/ui/ResultWidget.py                       |  2 +-
 ulauncher/ui/UlauncherApp.py                       | 30 +++++-----
 ulauncher/ui/preferences_server.py                 | 47 ++++++++--------
 ulauncher/ui/windows/HotkeyDialog.py               | 10 ++--
 ulauncher/ui/windows/PreferencesWindow.py          | 15 +++--
 ulauncher/ui/windows/UlauncherWindow.py            | 64 +++++++++++-----------
 ulauncher/utils/Settings.py                        | 10 +++-
 ulauncher/utils/basedataclass.py                   | 21 ++++---
 ulauncher/utils/decorator/debounce.py              |  9 +--
 ulauncher/utils/decorator/run_async.py             |  7 ++-
 ulauncher/utils/fuzzy_search.py                    |  8 +--
 ulauncher/utils/get_icon_path.py                   |  2 +-
 ulauncher/utils/json_utils.py                      |  2 +-
 ulauncher/utils/launch_detached.py                 |  8 ++-
 ulauncher/utils/logging_color_formatter.py         | 10 ++--
 ulauncher/utils/migrate.py                         | 10 ++--
 ulauncher/utils/singleton.py                       |  4 +-
 ulauncher/utils/systemd_controller.py              |  8 +--
 ulauncher/utils/timer.py                           | 21 +++++--
 ulauncher/utils/untar.py                           |  2 +-
 57 files changed, 345 insertions(+), 241 deletions(-)
```

**Comment by friday** [comment]
Thank you :pray:

Unfortunately that still makes it pretty hard to understand what change caused this (this commit is mainly just type changes that shouldn't change anything), and I made a lot of changes since that commit so it's hard to revert.

Could you do a `git checkout cad2954; git revert HEAD --no-commit; git reset .`

This will put you at a state right after the commit was made, but revert all the changes (but not commit them). From this point you can for example run `git checkout ulauncher/api` to discard all the changes to that subdirectory and then try running Ulauncher again to see if the issue will be reintroduced? Then try narrowing it down that way?

**Comment by friday** [comment]
I may have just been able to replicate it actually. I could not replicate it with Chrome or Chromium, but it happened with GitHub Desktop when I started it with Ulauncher on a dual monitor setup. So maybe I don't need you to look at this after all. I will update as I have time to look more into it.

**Comment by friday** [comment]
It turns out the logic was all wrong, but in most cases the focus out event would still cause Ulauncher to close. It was only noticable on a dual monitor setup with some specific apps that didn't try to steal focus from Ulauncher.

Released as https://github.com/Ulauncher/Ulauncher/releases/tag/v6.0.0-beta10 (the launchpad build server usually needs ~30min to have them ready).
