### ISSUE TITLE
Can't search for a program based on name of desktop entry file

### ISSUE THREAD

**Issue by sgreene570** [Ulauncher/Ulauncher#139]
**Steps to reproduce:**
A lot of desktop entry files use an abbreviated name of the program as the filename of the `.desktop` file.
For example, GNU Image Manipulation Program (most commonly called GIMP), cannot be launched from ulauncher with the query "gimp" by default.  Instead, to run gimp in ulauncher, you need to search for "GNU Image...".  Other launchers will use the desktop entry filename as a means of searching for a program, and I think that this functionality is important out of the box.

**Ulauncher version**: v2.2.1r0
**Linux distro**: Debian 9
**Desktop environment**: Openbox

**Comment by gornostal** [comment]
Could you attach desktop file for GIMP please?

**Comment by sgreene570** [comment]
Here is the GIMP desktop file
https://pastebin.com/Tc0C954F

**Comment by gornostal** [comment]
Thanks. I'll look into it

**Comment by gornostal** [comment]
Fixed in v3.1.1
https://ulauncher.io/#Download

**Comment by sgreene570** [comment]
Thank you!
