### ISSUE TITLE
Can't open directories with azerty keyboard

### ISSUE THREAD

**Issue by altla** [Ulauncher/Ulauncher#141]
**Steps to reproduce:**
Launch ULauncher and navigate by typing to any directory. When you pess Alt+[Any Number] nothing happens and it is literally impossible to open a directory.

I'm assuming this is because of the keyboard layout (I'm using Belgian azerty). 

**Ulauncher version**: 2.2.1.r0
**Linux distro**: Elementary OS

Except for this issue, the launcher has been great. Thanks a lot for the great work!

**Comment by gornostal** [comment]
@altla thanks for reporting. I'll look into it

**Comment by altla** [comment]
Actually, I just tried this with Qwerty US keyboard layout and still the same issue. Not sure what other info might be helpful but let me know if I can provide anything else.

**Comment by gornostal** [comment]
Could you close Uluncher and then run it with `ulauncher -v` and copy
output here (or better to pastebin.com or gist.github.com)?


-- 
Thanks,
Aleksandr

**Comment by gornostal** [comment]
Please do this after you try to open a dir with a keyboard


-- 
Thanks,
Aleksandr

**Comment by altla** [comment]
It actually seems to work fine after all: I hadn't realized that to open a folder you needed to press ctrl+alt+enter.
