### ISSUE TITLE
Beta 15: missing python modules

### ISSUE THREAD

**Issue by luispabon** [Ulauncher/Ulauncher#1411]
### Environment

Ubuntu 24.04 / Sway / Ulauncher v6.0.0-beta15

### Bug description

These extensions fail to launch because of missing ulauncher modules:
 * Jetbrains launcher reloaded (`ulauncher.utils.SortedCollection`)
 * Unicode extension (`ulauncher.search`)

These work correctly on v5.

![image](https://github.com/user-attachments/assets/a590808f-cc0c-45e5-99ca-a8f2be8e026f)
![image](https://github.com/user-attachments/assets/3247993f-5bf3-43b5-954b-7ef5e016a7c2)

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.
- [X] I have tried to understand the error message and help myself, before reporting it.
- [X] My issue description has clear steps for how to reproduce the issue.
- [X] This issue applies to the whole Ulauncher application, not for a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
If extensions import Ulauncher internals like that of course they will break. Are we suupsed to never remove, rename or refactor code just because some extension figured out how to import our internals?

**Comment by friday** [comment]
I made improvements to the error message now. Should be clearer for next time (once released):
![image](https://github.com/user-attachments/assets/b215692d-4279-4cd5-a584-ac1544de31cd)
