### ISSUE TITLE
Ubuntu 24.10 Released

### ISSUE THREAD

**Issue by tomasnorre** [Ulauncher/Ulauncher#1418]
### Description

Any plans for updating the ppa:agornostal/ulauncher to contain a Ubuntu 24.10 (oracular) version too ? 

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing enhancement requests](https://github.com/Ulauncher/Ulauncher/labels/enhancement) before suggesting this.

### Ulauncher v6

- [X] I have checked and couldn't find my suggestion in v6.

**Comment by friday** [comment]
Should be fixed now for v5. For v6 it will be for next release.

**Comment by tomasnorre** [comment]
Thanks. I can confirm that it works.
