### ISSUE TITLE
Uncaught exception ProjectPathnotFoundError in /usr/lib/python2.7/site-packages/ulauncher/config.py

### ISSUE THREAD

**Issue by michael-n0813** [Ulauncher/Ulauncher#142]
Build 2.2.1.r0

I build the AUR package from arch
https://aur.archlinux.org/packages/ulauncher/

and encounted an Uncaught exception
ProjectPathnotFoundError

in /usr/lib/python2.7/site-packages/ulauncher/config.py

line 47
`os.path.dirname(__file__)`  >>was returning nil

changing it to absolute file path fixed it.
`os.path.dirname(os.path.abspath(__file__)), __ulauncher_data_directory__)`

other than that some file were missing version requirements prior to loading module:
/usr/lib/python2.7/site-packages/ulauncher/ext/notification.py
`    import gi`
`    gi.require_version('Notify', '0.7')`

/usr/lib/python2.7/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py
`    import gi`
`    gi.require_version('WebKit2', '4.0')`

**Comment by gornostal** [comment]
Interesting...
I'll look into this.

**Comment by CottonEaster** [comment]
I get the following in .xsession-errors, on Mint 18.2 Cinnamon using Ulauncher 3.0.2r0.

```
/usr/lib/python2.7/dist-packages/ulauncher/util/desktop/notification.py:1: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py:5: PyGIWarning: WebKit2 was imported without specifying a version first. Use gi.require_version('WebKit2', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gio, Gtk, WebKit2
2017-07-27 01:52:07,839 | [1;31mERROR[0m | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 268, in bind_show_app_hotkey
    self.notify_hotkey_change(accel_name)
  File "/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 273, in notify_hotkey_change
    show_notification("Ulauncher", "Hotkey is set to %s" % display_name)
  File "/usr/lib/python2.7/dist-packages/ulauncher/util/desktop/notification.py", line 10, in show_notification
    Notify.Notification.new(summary, body, icon).show()
Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.freedesktop.Notifications' on object at path /org/freedesktop/Notifications (19)
```

**Comment by gornostal** [comment]
@CottonEaster this is different. I've created a new ticket for your issue: #143

**Comment by gornostal** [comment]
@michael-n0813 I tried to reproduce it on Manjaro Linux (I don't have clean Arch Linux now), but I wasn't able to.
I used this command to install:
```
git clone https://aur.archlinux.org/ulauncher.git && cd ulauncher && makepkg -is
```
Did you use something else?

As for missing require_version, that is intentional because some legacy distros don't have newer versions and I wanted Ulauncher code to be compatible with them too.

**Comment by CottonEaster** [comment]
To install I used this ppa: agornostal/ulauncher

By the way: I am using Arch. Rather, and as I said, I'm on Mint. However, I can install Ulauncher via git cloning if you think it will help.

**Comment by gornostal** [comment]
So are you having issues with installing the app on Mint or on Arch? 
I'm a little confused :)

Anyway, I tried it on both and it works.

**Comment by CottonEaster** [comment]
I am using the app on _Mint_ (but that doesn't mean I couldn't install it from Github). But: never mind; there's only so worked up about terminal warnings that I can get! Thanks for your time.

**Comment by gornostal** [comment]
@michael-n0813 please try the new version.

**Comment by michael-n0813** [comment]
All good, thank you very much for your help.
