### ISSUE TITLE
use a code formatter?

### ISSUE THREAD

**Issue by iaacornus** [Ulauncher/Ulauncher#1431]
### Description

I thnk code formatter like help the code base in terms of maintainability/sustainability.

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing enhancement requests](https://github.com/Ulauncher/Ulauncher/labels/enhancement) before suggesting this.

### Ulauncher v6

- [X] I have checked and couldn't find my suggestion in v6.

**Comment by friday** [comment]
We already do:
https://github.com/Ulauncher/Ulauncher/blob/v6/makefile#L91
https://github.com/Ulauncher/Ulauncher/blob/v6/makefile#L116
https://github.com/Ulauncher/Ulauncher/blob/v6/.github/workflows/tests.yml#L15-L23

**Comment by iaacornus** [comment]
i havent noticed that, closing this then
