### ISSUE TITLE
Icon Selection Dialog

### ISSUE THREAD

**Issue by hickscorp** [Ulauncher/Ulauncher#145]
This is not a bug and doesn't require any immediate attention.

Something really great would be a native icon selection dialog. For instance if you're using Xfce, the attached picture shows how you can assign an icon to a shortcut. This type of dialog would be great (rather than selecting a PNG / SVG file).

Keep up the good work, ULauncher is a really cool little tool!

![image](https://user-images.githubusercontent.com/822933/28931397-d5c8df26-786d-11e7-9c38-b6fbce3d5f43.png)

**Comment by gornostal** [comment]
Sorry, I've decided to not change anything about icon selecting dialog.
I want to keep amount of code to the minimum so it's easier for me to maintain Ulauncher.
