### ISSUE TITLE
Custom .desktop file not visible in Ulanucher

### ISSUE THREAD

**Issue by Pshemas** [Ulauncher/Ulauncher#146]
I've created a .desktop file that lunches freeRDP (which connects me to remote desktop). It is visible in apps menu, but it seems Ulauncher does not see it. 
Is there a way to make it available in Ulanucher (I've gotten used to launching apps through Ulauncher :D ).
I'm running Centos 7, .desktop file is located in ~/.local/share/applications, and it looks like this:

[Desktop Entry]
Version=1.0
Name=FreeRDP_Aureus
Name[pl]=FreeRDP_Aureus
GenericName=Remote Desktop Client
GenericName[pl]=Klient zdalnego pulpitu
X-GNOME-FullName=FreeRDP Remote Desktop Client
Comment=Connect to remote desktops
Comment[pl]=Łączy ze zdalnymi pulpitami
TryExec=/usr/bin/xfreerdp /v:192.168.1.5 /u:Ludek /p:maxmini4thewin /cert-ignore +nego /w:1920 /h:1080 /network:lan /gfx -bitmap-cache -offscreen-cache -glyph-cache -themes -wallpaper /gdi:hw
Exec=/usr/bin/xfreerdp /v:ipaddress /u:username /p:password /cert-ignore +nego /w:1920 /h:1080 /network:lan /gfx -bitmap-cache -offscreen-cache -glyph-cache -themes -wallpaper /gdi:hw
Icon=remote-desktop
Terminal=false
Type=Application
Categories=GTK;GNOME;X-GNOME-NetworkSettings;Network;
Actions=Profile;Tray;Quit;

**Comment by gornostal** [comment]
It should work. Perhaps the desktop file is invalid. You can copy one that is working and try modifying it.
Please also make sure that your file is in one of directories returned by this command:

```
>>> import os; from xdg.BaseDirectory import xdg_data_dirs; filter(os.path.exists, xdg_data_dirs)
```

**Comment by Pshemas** [comment]
I might have tried to post it incorrectly but this command returns error on my side:

$ import os; from xdg.BaseDirectory import xdg_data_dirs; filter(os.path.exists, xdg_data_dirs)
bash: błąd składni przy nieoczekiwanym znaczniku `os.path.exists,'

-but that may be just me doing something incorrectly. I don't have much experience with trickier bash commands ;) .
As for .desktop file - you can see its contents above. I can see correct entry in the programs launcher and I can launch it from there. I don't see this option only in Ulauncher.
In the weekend I'll try pulling latest commits from Github and rebuilding it.
Let me know what can I do to help in nailing this one out - I'm not a dev, but I'll do my best :) .

**Comment by gornostal** [comment]
Oh, I forgot to mention that command is for Python. Enter "python" in bash
first.

**Comment by Pshemas** [comment]
LOL - yeah, I should have figured that out, sorry :) . Here's the output after those commands:

['/home/przemek/.local/share', '/usr/local/share', '/usr/share']

**Comment by gornostal** [comment]
It might be a parser error. Your OS may user a different parser than Ulauncher.

Try closing Ulauncher and running it from command line like this: `ulauncher -v`
Look errors like "Could not read "....desktop": constructor returned NULL"
If your desktop file could not be parsed because of an error, you can try to simplify the file, see what causes the error by removing some lines, maybe even taking a desktop file that is indexed by Ulauncher and using it as a template.

There is no definite solution to this problem. Sorry.

**Comment by Pshemas** [comment]
you're right - that's exactly the error I'm seeing:
XfreeRDP.desktop": constructor returned NULL

As you may see in the first post the .desktop file is pretty simple . My guess is that the exec line with all those extra parameters is causing problems as that's the only "more complex" line - will check it out and report back (but quite annoyingly the .desktop file works as it should in apps menu). If that's it I'll make a .sh file and will check whether linking it helps.

**Comment by Pshemas** [comment]
ok, modified the file and also marked the .desktop as trusted - it appears in Ulauncher now :+1:  . Thank you Gornostal for pointing this one out :) .

**Comment by gornostal** [comment]
Cool!
