### ISSUE TITLE
Typo in one of the filenames

### ISSUE THREAD

**Issue by hickscorp** [Ulauncher/Ulauncher#150]
A file is being created in ULauncher's cache directory, named `file_borwser_queries.db`.
It should be renamed `file_browser_queries.db`.

**I'm not a Python developer so I have no clue about syntax**, but something like this:
https://github.com/Ulauncher/Ulauncher/pull/151

**Comment by gornostal** [comment]
@hickscorp thanks for the PR and all the other comments. 

I'll merge that soon.

**Comment by gornostal** [comment]
Fixed in v3.1.1
https://ulauncher.io/#downloads
