### ISSUE TITLE
Cannot change the "Default search" behavior of shortcuts.

### ISSUE THREAD

**Issue by hickscorp** [Ulauncher/Ulauncher#153]
When editing shortcuts, there is this checkbox allowing them to be used when nothing matches the query.
By default, the check is ticked, but unticking it is not saved and the shortcuts keep showing in the suggested results, which is most likelly an unexpected behaviour.

The checkbox I'm talking about is accessible when editing a single shortcut, here is a screenie:

![image](https://user-images.githubusercontent.com/822933/29436663-8c07202c-83a4-11e7-8961-10c55d571355.png)

**Comment by gornostal** [comment]
Thanks for reporting this issue. I'll fix that

**Comment by gornostal** [comment]
Fixed in v3.1.1
https://ulauncher.io/#downloads
