### ISSUE TITLE
App hotkey not working 

### ISSUE THREAD

**Issue by tolisp** [Ulauncher/Ulauncher#155]
Hi everyone

i can't get ulauncher to launch using the shortcut keys (ctrl + space or any other user defined). Although ulauncher launches if i find it in the software list and click the icon, the shortcut never worked. I am trying to find a shortcut key combination that is definetely unique to be sure i don't have conflicts and will post update if i find anything

 **Steps to reproduce:**
Press the specified shortcut to launch

**Ulauncher version**: 3.0.2.r0
**Linux distro**:Fedora26
**Desktop environment**: Gnome 3.24.2 on Wayland

**Logs**:

/usr/lib/python2.7/site-packages/ulauncher/util/desktop/notification.py:1: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python2.7/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py:5: PyGIWarning: WebKit2 was imported without specifying a version first. Use gi.require_version('WebKit2', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gio, Gtk, WebKit2
2017-08-18 09:26:10,351 | INFO | ulauncher: main() | Ulauncher version 3.0.2.r0
2017-08-18 09:26:10,351 | INFO | ulauncher: main() | GTK+ 3.22.17
2017-08-18 09:26:10,352 | DEBUG | ulauncher: main() | Getting the existing instance..

**Comment by gornostal** [comment]
Hi @tolisp,

I would like to find out the reason of this issue.

Could you quit the app and start it from console using this command? `ulauncher -v`
The logs you provided don't contain all the necessary info.

**Comment by gornostal** [comment]
Subscribe in #157 for Wayland issues updates.
