### ISSUE TITLE
Segfault on Ubuntu 17.10 (Wayland)

### ISSUE THREAD

**Issue by drejones** [Ulauncher/Ulauncher#156]
Installed Ulauncher with .deb but grabbing this error message on start: 

/usr/lib/python2.7/dist-packages/ulauncher/ext/notification.py:1: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py:5: PyGIWarning: WebKit2 was imported without specifying a version first. Use gi.require_version('WebKit2', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gio, Gtk, WebKit2
Segmentation fault (core dumped)

**Steps to reproduce:**
Every time I try to start Ulauncher

**Ulauncher version**: Version 2.2.1.r0
**Linux distro**: Ubuntu 17.10
**Desktop environment**:  Gnome

**Logs**:

_To get the logs please do the following:_
_* Close the app_
_* Run "ulauncher -v" from the console_
_* Copy output to https://gist.github.com/_
_* Link to the gist here_ https://gist.github.com/drejones/cac2e3a6abee6b82f10e4976711a9331

**Comment by gornostal** [comment]
Sorry for the delay. 
Ulauncher doesn't work with Wayland.
I've recently tried that myself. There are multiple issues. Wayland incompatible Keybinder library is one of them. 

I guess I should mention that somewhere

**Comment by gornostal** [comment]
Subscribe in #157 for Wayland issues updates.
