### ISSUE TITLE
Unable to switch to Light Theme, Enabling Notification Icon Crashes (V3.1.2r2)

### ISSUE THREAD

**Issue by nexlinux** [Ulauncher/Ulauncher#166]
**Steps to reproduce:**
When 
**Ulauncher V3.1.2r2**:
**Q4OS Linux Orion - (Debian Jessie)**:
**Desktop - Trinity*:

Error 1: unable to switch to Light Theme
Error 2: Clicking the "Show Icon Indicator" on-off-on  Crashes Ulauncher

------------------
Terminal --> Konsole --> $ ulauncher -v 

[last.log](https://github.com/Ulauncher/Ulauncher/files/1332155/last.log)

================================
apt-cache show python

Package: python
Source: python-defaults
Version: 2.7.9-1
Installed-Size: 680
Maintainer: Matthias Klose <doko@debian.org>
Architecture: amd64
Replaces: python-dev (<< 2.6.5-2)
Provides: python-ctypes, python-email, python-importlib, python-profiler, python
-wsgiref
Depends: python2.7 (>= 2.7.9-1~), libpython-stdlib (= 2.7.9-1)
Pre-Depends: python-minimal (= 2.7.9-1)
Suggests: python-doc (= 2.7.9-1), python-tk (>= 2.7.9-1~)
Conflicts: python-central (<< 0.5.5)
Breaks: update-manager-core (<< 0.200.5-2)
Description-en: interactive high-level object-oriented language (default version                 )
 Python, the high-level, interactive object oriented language,
 includes an extensive class library with lots of goodies for
 network programming, system administration, sounds and graphics.
 .
 This package is a dependency package, which depends on Debian's default
 Python version (currently v2.7).
Description-md5: d1ea97f755d8153fe116080f2352859b
Multi-Arch: allowed
Homepage: http://www.python.org/
Tag: devel::interpreter, devel::lang:python, implemented-in::c,
 implemented-in::python, interface::commandline, role::metapackage,
 role::program, scope::utility
Section: python
Priority: standard
Filename: pool/main/p/python-defaults/python_2.7.9-1_amd64.deb
Size: 151042
MD5sum: f3f002b49f511c6185f666c0b49e0400
SHA1: f7cfb1e2c97f153c68b4255fa9b1a8591360c3bd
SHA256: 93dc9d03df366d658832fb238a6c1e6c57e5e57dd648145c2f57a8f3e2b419ed

===================================================

ulauncher@ulauncher:/$ apt-cache show python-gi
Package: python-gi
Source: pygobject
Version: 3.14.0-1
Installed-Size: 918
Maintainer: Josselin Mouette <joss@debian.org>
Architecture: amd64
Replaces: python-gobject (<< 3.0.2-4)
Provides: python2.7-gi
Depends: python (>= 2.7), python (<< 2.8), libc6 (>= 2.14), libffi6 (>= 3.0.4), libgirepository-1.0-1 (>= 1.33.10), libglib2.0-0 (>= 2.41.1), gir1.2-glib-2.0 (>= 1.39.0)
Suggests: python-gi-cairo
Breaks: python-aptdaemon (<< 1.0), python-gobject (<< 3.0.2-4), python-nautilus (<= 1.1-1), software-center (<= 5.6.0-0ubuntu2)
Description-en: Python 2.x bindings for gobject-introspection libraries
 GObject is an abstraction layer that allows programming with an object
 paradigm that is compatible with many languages. It is a part of Glib,
 the core library used to build GTK+ and GNOME.
 .
 This package contains the Python 2.x binding generator for libraries that
 support gobject-introspection, i. e. which ship a gir1.2-<name>-<version>
 package. With these packages, the libraries can be used from Python.
Description-md5: 8d2225b2f817f42645ac3c6bd82fee0f
Homepage: https://wiki.gnome.org/PyGObject
Tag: role::shared-lib, suite::gnome
Section: python
Priority: optional
Filename: pool/main/p/pygobject/python-gi_3.14.0-1_amd64.deb
Size: 493660
MD5sum: 5f4d650c230c0e6f5f3eeb6daf5ae48f
SHA1: 2e5ae2c3a865dba31521900771965f96698149d5
SHA256: 4596c4c7b1a39e13cae997f0f47df338ea985679e9ee38d72d5c3404384040da

=============END======================

**Comment by nexlinux** [comment]
Tested (V3.1.2r2) on Debian 9 Stretch KDE Desktop - No Problems.
More than 4 Shortcuts worked on both Q4OS Linux Orion (Jessie) and Stretch KDE.

**Comment by gornostal** [comment]
@nexlinux,
Ulauncher v3.2.0 is being built now. 

I made some changes in code that saves preferences. Please let me know if the issue with switching themes still exists in v.3.2.0
I've also fixed an app crash when switching indicator on/off.

Reopen if needed.
