### ISSUE TITLE
Convert app to Python 3 as per Debian Python Policy

### ISSUE THREAD

**Issue by gornostal** [Ulauncher/Ulauncher#17]

**Comment by dotmagic** [comment]
Ulauncher already sucessfull ported to python 3?
I see this issue closed the the archlinux package still depends on python 2 :/

**Comment by gornostal** [comment]
I've started working on this, but then discovered that not all distros that I want to support have packages that Ulauncher depends on.
So choosing between running on Python 3 or supporting a wider range of distros I chose the latter.
