### ISSUE TITLE
preferences dialog error  

### ISSUE THREAD

**Issue by kensully** [Ulauncher/Ulauncher#176]
First of all congrats on your project. I am on Ubuntu 16.04 32  bit platform. I cloned this repository and ran `sudo pip install -r ./requirements.txt` then `sudo python ./setup.py install --prefix=/usr/local --root=/`; I had to add `--root=/` parameter otherwise I get `AttributeError: 'NoneType' object has no attribute 'startswith'` error.
I launched application but when I try to open `preferences` panel via gear icon I get an error message on `Ulauncher preferences` window: `Error opening file: No such file or directory`
Here is the debug output : https://gist.github.com/kensully/b810ec07cf011f39f5d3795d68eb7a57

**Comment by gornostal** [comment]
Thanks @kensully 

Have you followed guided on installing documented in README?
https://github.com/Ulauncher/Ulauncher#build-and-run

It looks like you haven't built preferences UI, which is in JS.

**Comment by kensully** [comment]
@gornostal it's my bad. Thank you for your help.
Regards.
