### ISSUE TITLE
Request: new theme based on original themes

### ISSUE THREAD

**Issue by suberb** [Ulauncher/Ulauncher#178]
I've changed Light theme a bit so it matches my desktop but it'll go away with an update. Could you please make an option for a custom theme?
![screenshot from 2017-11-04 23-29-37](https://user-images.githubusercontent.com/24309060/32410027-0ef2867e-c1b8-11e7-98a7-2a70be347800.png)

**Comment by gornostal** [comment]
Hi @suberb 

This looks neat. I really appreciate your interest in Ulauncher design.
In my plans was to hire a designer who will refresh the design and maybe add a few more themes.

All suggestions from users (including yours) will be taken into account.

**Comment by suberb** [comment]
Thank you @gornostal :heart_eyes:

**Comment by gornostal** [comment]
@suberb Check out Ulauncher v4. It brings exactly what you've requested :slightly_smiling_face: 
https://ulauncher.io
