### ISSUE TITLE
Improve search by searching in app descriptions

### ISSUE THREAD

**Issue by gornostal** [Ulauncher/Ulauncher#18]

**Comment by gornostal** [comment]
Fixed in 5.7.2

**Comment by sebastian-65** [comment]
@gornostal Was this successfuly released? Should it search within application "comment" content, right?

`$ cat /usr/share/applications/filezilla.desktop 
[Desktop Entry]
Name=FileZilla
GenericName=FTP client
GenericName[de]=FTP-Client
GenericName[fr]=Client FTP
Comment=Download and upload files via FTP, FTPS and SFTP
Comment[de]=Dateien über FTP, FTPS und SFTP übertragen
Comment[fr]=Transférer des fichiers via FTP, FTPS et SFTP
Exec=filezilla
Terminal=false
Icon=filezilla
Type=Application
Categories=Network;FileTransfer;
Version=1.0
`
When I search for `ftp` or `FTP`, I would expected Filezilla to be returned as a result, however it isn't.
