### ISSUE TITLE
ULauncher fails to start on Ubuntu Gnome 17.10

### ISSUE THREAD

**Issue by douglasrizzo** [Ulauncher/Ulauncher#180]
I had ULauncher installed on Ubuntu Gnome 17.04. After updating to Ubuntu Gnome 17.10, ULauncher did not start automatically or manually. I reinstalled it since then, but this did not fix the problem.

**Steps to reproduce:**
1. Download the ULauncher `deb` file from the website;
2. Install it on Ubuntu Gnome 17.10;
3. Launch the application.

**Ulauncher version**: v3.2.1.r1
**Linux distro**: Ubuntu Gnome 17.10
**Desktop environment**: Gnome 3.

**Logs**: By running `ulauncher` on a terminal, I got the following error:
```Traceback (most recent call last):
  File "/usr/bin/ulauncher", line 24, in <module>
    from ulauncher.main import main
  File "/usr/lib/python2.7/dist-packages/ulauncher/main.py", line 9, in <module>
    gi.require_version('Gtk', '3.0')
AttributeError: 'module' object has no attribute 'require_version'
```

**Comment by gornostal** [comment]
Thanks for reporting. I'll look into this.

Are you on Wayland, btw?

You can check that with 
```
$ echo $XDG_SESSION_TYPE
```

**Comment by douglasrizzo** [comment]
Yeah, it's `wayland`.

**Comment by gornostal** [comment]
I see. Ulauncher doesn't support Wayland currently.
Please subscribe to #157 to get a notification when this is implemented.

I'm closing this one as a duplicate
