### ISSUE TITLE
Error starting ulauncher in Ubuntu 17.10

### ISSUE THREAD

**Issue by sathishkumar-in** [Ulauncher/Ulauncher#181]
**Steps to reproduce:**
in console,
**ulauncher**

**Ulauncher version**: 3.2.1.r1
**Linux distro**: Ubuntu 17.10
**Desktop environment**: Gnome(default)

**Logs**:
[Ulauncher Error log](https://gist.github.com/sathishkumar-in/ef189e4f68136332fc2dc4233c0c7897)

**Comment by gornostal** [comment]
If you are using Wayland (default in 17.10) instead of X11, Ulauncher won't start.
I'm working on the fix. Hopefully will release it soon

**Comment by gornostal** [comment]
you can check if it's Wayland or not with this command `echo $XDG_SESSION_DESKTOP`

**Comment by sathishkumar-in** [comment]
I did that. It says ubuntu
echo $XDG_SESSION_DESKTOP
ubuntu

**Comment by gornostal** [comment]
Oops, wrong name. It should be $XDG_SESSION_TYPE
But don't bother, it's definitely Wayland and I already have a fix. Will roll out the release soon

**Comment by gornostal** [comment]
Fixed in dev release [3.3.0.r0](https://github.com/Ulauncher/Ulauncher/releases/tag/3.3.0.r0)

**Comment by gornostal** [comment]
Fixed in stable release now
