### ISSUE TITLE
Bug / feature request: enable Ulauncher to work properly as soon as started

### ISSUE THREAD

**Issue by CottonEaster** [Ulauncher/Ulauncher#185]
**Steps to reproduce:**
Launch Ulauncher for the first time in a session and immediately try to use it. Result (on my computer, anyway): only a couple of the index items are available. To find what I want, I have to wait a few seconds, close the search box, reopen it, and retype my query.

**Ulauncher version**: 3.2.1r1
**Linux distro**: Mint 18.3 x64
**Desktop environment**: Cinnamon

**Logs**:

[gist](https://gist.github.com/anonymous/a34fb9fc965192058d3e25a204bac477)

**Comment by gornostal** [comment]
That's actually in my list of improvements.
Please follow issue #154.
I'm closing this as a duplicate.

Thanks
