### ISSUE TITLE
Update rpm dependency to webkitgtk4 or bundle webkitgtk3?

### ISSUE THREAD

**Issue by ervoiox** [Ulauncher/Ulauncher#186]
In Fedora 27, webkitgtk3 has been retired due to the number of security vulnerabilities it has.

 Is it possible to update the rpm build to support webkitgtk4 or bundle webkitgtk3?

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/7APAJVWLKRJWNLIW2N4SOGL2JOOYLW5N/

**Comment by gornostal** [comment]
I think it is possible to use webkitgtk4.
I'll add that to the next release

**Comment by AffableZonkey** [comment]
Thanks! - came here to open issue - but see you are already working on it.

**Comment by gornostal** [comment]
Done in v4.0.3
