### ISSUE TITLE
Hide ulauncher from systray

### ISSUE THREAD

**Issue by EtienneBruines** [Ulauncher/Ulauncher#188]
It'd be nice if ulauncher would could be "hidden" from the systray. (Possibly even exit after selecting an app, but I guess that comes with a huge performance cost.)

Reason for this: I solely use keyboard shortcuts to prompt it, and it's just being ignored in the systray. 

This could either be done in the settings, or perhaps as a console-flag when starting (e.g. `--no-systray`)

I'd love to be able to help with this, but you'd have to point me in the right direction (e.g. which file would be useful in doing so.)

**Comment by gornostal** [comment]
Sorry, what is a systray? :)

You can enable/disable indicator icon from preferences, but I guess that's not what you a looking.

**Comment by EtienneBruines** [comment]
Wow, that was what I was looking for.Oops. On Dec 26, 2017 19:21, Aleksandr Gornostal <notifications@github.com> wrote:Sorry, what is a systray? :)
You can enable/disable indicator icon from preferences, but I guess that's not what you a looking.
