### ISSUE TITLE
Nothing listed in Ulauncher popup

### ISSUE THREAD

**Issue by ZaLiTHkA** [Ulauncher/Ulauncher#189]
**Steps to reproduce:**
Unsure, I just installed and launched it... How it's launched (at startup or manually) makes no difference to this behaviour.

The steps I followed for the logging output gist I've linked below is as follows:

1. launched with `ulauncher -v`
1. activated with <kbd>ctrl</kbd>+<kbd>space</kbd>
1. entered `file`

The problem is that I don't have *anything* in the launcher list, even after waiting a while (as per the "5 minute delay" described in #130).

Any ideas?

**Ulauncher version**: 3.2.1.r1
**Linux distro**: Linux Mint 18.2
**Desktop environment**: XFCE

**Logs**:

* [gist with verbose console output](https://gist.github.com/ZaLiTHkA/c4ff3d0c9b9519dcaafe2c9da770be2c)

**Comment by gornostal** [comment]
Found this in the logs:
```
IOError: [Errno 13] Permission denied: '/home/dre/.config/ulauncher/shortcuts.json'
```
Looks like you have incorrect permissions for `~/.config/ulauncher`.
Please fix permissions 
```
chown -R $USER:$USER ~/.config/ulauncher
chown -R $USER:$USER ~/.cache/ulauncher_cache
```

**Comment by gornostal** [comment]
Please reopen if needed

**Comment by ZaLiTHkA** [comment]
Thanks @gornostal, only just saw your replies.. I'll check the permissions when I get home this evening.

I installed this from the PPA as per the instructions on the main website, so I wouldn't have thought permissions would be an issue.. Doesn't this point to an issue in the installation process then?

**Comment by gornostal** [comment]
> Doesn't this point to an issue in the installation process then?

I doubt that's the case because `~/.config/ulauncher` is created after installation. When you run the app for the first time. 
Ulauncher could not possibly create that dir with wrong permissions unless it was ran from a different user.

**Comment by ZaLiTHkA** [comment]
Yeah, that makes sense.. I'm running the same OS on my laptop and I didn't have this problem there, but I have had other weird permission-related issues on my desktop machine over the past few months, not sure what's going on with that.

Either way, thanks for the info. (:
