### ISSUE TITLE
super + space not working

### ISSUE THREAD

**Issue by gutierri** [Ulauncher/Ulauncher#190]
**Steps to reproduce:**
Open settings window, change <kbd>CTRL + SPACE</kbd> to <kbd>SUPER (Windows key) + SPACE</kbd>

**Ulauncher version**: 3.2.1.r1
**Linux distro**: Linux Mint 18.3
**Desktop environment**: Cinnamon

**Logs**:

[Gist](https://gist.github.com/gutierri/5a1b7db3be5819846fbe935f350c4a0e)

**Comment by gornostal** [comment]
Hi
Could you click "New issue" again, copy the contents of the text area into this issue, and fill in the required items (like steps to reproduce, environment, logs, etc)?

**Comment by gutierri** [comment]
@gornostal A strange behavior is that for several attempts he even detected the shortcut. I believe that somehow it is necessary to overwrite the current CINNAMON shortcut

**Comment by gornostal** [comment]
I've just checked, currently it's not possible to use <kbd>Win</kbd> key in hotkey.
Apparently it's a reserved in most of the DEs.
