### ISSUE TITLE
Searching for apps does't return any result. Black box around the window. gtk_main_quit: assertion 'main_loops != NULL' failed

### ISSUE THREAD

**Issue by lalitmee** [Ulauncher/Ulauncher#196]
I don't know why this problem is occuring. But whenever I shutdown my laptop and then restart it. Ulauncher misbehaves and it looks something like this. And then if you will search for any application then it only shows those three shortcuts which are Google Search, Stackoverflow Search and Wikipedia Search.
![screenshot from 2018-01-18 10-41-35](https://user-images.githubusercontent.com/10762218/35081809-40df62ec-fc3c-11e7-90c9-8a10615de82d.png)

I don't know why it's color is changing.

**Steps to reproduce:**
Whenever I shutdown my system and then restart, it occurs.

**Ulauncher version**: v3.2.1.r1
**Linux distro**: Ubuntu 16.04
**Desktop environment**: Unity

**Logs**:

[gist link](https://gist.github.com/lalitmee/270b2a9151d6d33c0f38dc4762bc189b)

Thank you.

**Comment by gornostal** [comment]
Does the problem persist after restarting Ulauncher?

Could you check if there are more logs in `!/.cache/ulauncher_cache/last.log` and post them here please?

**Comment by lalitmee** [comment]
Actually now I have reinstalled ulauncher and deleted all the cache of the ulauncher. I have to do this evertime. That's why I have not deleted the deb package of ulauncher from my system. I have to reinstall this evertime when I start my system.

After restarting, it was not showing any applications other that those shortcuts, but after sometime when I pressed hot key and then searched for the application, it was showing the applications. But the black color which was surrounding it, was not gone.

**Comment by gornostal** [comment]
I think I will be able to help you, but I need a new log file.
The one you attached doesn't have any output, because you ran `ulauncher -v` when it was already running.
You either have to copy `~/.cache/ulauncher_cache/last.log` once you restart the system or close the app and then run `ulauncher -v` (although from what you said in this case it'll be working fine)

**Comment by lalitmee** [comment]
Ok, now I have updated the logs in that gist file. I again shutdown my laptop and this problem occured again. I don't know why. 

But after exiting the ulauncher and then restart it. Now its black color is gone but it is not showing any application.

**Comment by lalitmee** [comment]
```
❯   echo $XDG_SESSION_TYPE
x11
```
This is the output.

**Comment by gornostal** [comment]
Thanks.

Looks like GTK crashes.
Could you check `journalctl -ex` for gtk errors and post them here if any?

**Comment by lalitmee** [comment]
There are some errors related to mysql, but I think those errors will not effect ulauncher. What do you think? Should I post here.

**Comment by gornostal** [comment]
I think you are right about that.

This issue is not as trivial as I thought it would be.
I'll think about what we can try next

**Comment by lalitmee** [comment]
Yeah. Actually I would like to tell you that I have added ulauncher in startup applications. Does that step creates any problem?
And when I exit the app and then restart it. Its working fine. :thinking:

**Comment by gornostal** [comment]
No, it should not create any problem.
Did you add to startup applications, by checking "Launch at Login" in Ulauncher preferences?
That's the preferred and tested way.

**Comment by lalitmee** [comment]
Ohh. Let me do that then.

**Comment by gornostal** [comment]
You should undo what you did first.

**Comment by lalitmee** [comment]
Actually "Launch at Login" is also checked. But now I have removed it from startup applications.

**Comment by gornostal** [comment]
I could not think of anything else that would help me understand this issue better :(

BTW, why did you name this issue "Unexpected API error". Where do you see that error?

**Comment by lalitmee** [comment]
Actually, when first time this error occured, I went to the ulauncher preferences and there I saw that nothing is showing and a line was written **Unexpected API Error**.
So I name it that way.

**Comment by gornostal** [comment]
I think this should've been fixed in Ulauncher v4. Please reopen if not.
Thanks
