### ISSUE TITLE
Release on AppCenter

### ISSUE THREAD

**Issue by cassidyjames** [Ulauncher/Ulauncher#199]
This launcher looks pretty neat, and seems like it would fit into elementary OS well. You could release it to elementary OS users via AppCenter: https://developer.elementary.io/

**Comment by gornostal** [comment]
Yeah, I was looking into that and decided to not distribute Ulauncher there.
The main reason is that packaging in Linux is far from easy and requires lots of work, especially when you are dealing with GTK app in Python 2.

All packages in AppCenter seems to be built with Vala. Maybe in that case it's easy to just follow the guidelines and publish app there.

Sorry, I'm closing this one

**Comment by aljelly** [comment]
Just a note, AppCenter apps don't have to be coded in Vala:

> ## Other FAQ
> We frequently get asked if developers can publish apps written in languages other than Vala or with a build system other than CMake. The answers is “yes”! All of our documentation is built around the “one true development path” that elementary follows, but as long as your app is a native Gtk3 app with Debian packaging, it should be publishable. Several apps published in AppCenter are already using the Meson build system, for example.

[Source](https://medium.com/elementaryos/so-you-wanna-publish-on-appcenter-12c675b56e1c#aec2)
