### ISSUE TITLE
Vim like navigation

### ISSUE THREAD

**Issue by CaptainQuirk** [Ulauncher/Ulauncher#204]
Hi there !

Could it be possible to navigate through the list with something else than the arrow keys ? Like `Ctrl-j/Ctrl-k` or `Ctrl-n/Ctrl-p` ?

Thanks

**Comment by gornostal** [comment]
I'm not going to do this. Sorry.

I want to keep amount of code to the minimum, so I can still maintain the app on my own without getting lost in all of the features.
I'm planning to add only features that are either absolutely necessary or affect majority of users.

**Comment by CaptainQuirk** [comment]
Thanks for your response
