### ISSUE TITLE
Question about the background listening

### ISSUE THREAD

**Issue by BlackFireFox** [Ulauncher/Ulauncher#206]
Hi, how did you leave the program listening in the background for the shortcut?
I would need to know this because I'm writing a program that must always be hidden and when the shortcut is pressed a window appear.

**Comment by gornostal** [comment]
Hi
I'm using Keybinder library for that. There is a binding for python that you can get by installing package `gir1.2-keybinder-3.0` (Debian) then you'll be able to import it from `gi.repository` module.
You can read more here https://lazka.github.io/pgi-docs/#Keybinder-3.0

Keep in mind that it doesn't work all the time in Wayland (see #183), which is getting more and more popular.

As an alternative solution you can register a DBus method and then call it from other apps or via CLI using `dbus-send`. With this approach a hotkey must be registered by a user and will work all the time (see https://github.com/Ulauncher/Ulauncher/wiki/Hotkey-In-Wayland)

Hope that helps.

Closing the issue.
