### ISSUE TITLE
Black frame issue in Linux Mint 18.3

### ISSUE THREAD

**Issue by abdyek** [Ulauncher/Ulauncher#211]
I use Linux Mint 18.3
This black frame rarely be visible.
Current Ulauncher version: v3.2.1.r1

![screenshot](https://user-images.githubusercontent.com/16313808/35782507-0b28804e-0a0a-11e8-90e4-6b666fbf38a7.png)

**Comment by gornostal** [comment]
@abdyek this usually occurs when compositor is disabled (see this [comment](https://github.com/Ulauncher/Ulauncher/issues/60#issuecomment-282560906))

BTW, you are using an old version of Ulauncher. Current is 4.0.6
