### ISSUE TITLE
Super Key can't be used for launch shortcut, and other system shortcuts

### ISSUE THREAD

**Issue by pale2hall** [Ulauncher/Ulauncher#215]
Hey there!

Awesome piece of software.

One issue:  On Mint 18 with Cinnamon, If I set the launch shortcut shortcut to the Left Super/Meta/Windows Key, ULauncher pops up before I release the key.

This prevents me from using combos like WIN-E to open the File Explorer, and WIN-LEFT, WIN-RIGHT to move windows around in cinnamon's window snapping, areo-like interface.

I know I shouldn't really be using the Windows Key with no additional modifier as a shortcut, but it's second nature to me, and I'm using the same keyboard and mouse with Synergy to use Linux and Windows at the same time, so it would take some serious mental-retraining to remember to use a different shortcut on W10 and Mint.

Thanks for looking into this.  Maybe there's an ability to set the pop-up to be on key-up, instead of key-down?

**Comment by gornostal** [comment]
Hi 

> Maybe there's an ability to set the pop-up to be on key-up, instead of key-down?

Maybe there is, but this isn't something I'm planning to include into Ulauncher. Sorry.

I really want to keep number of features to the minimum, and to only include very useful ones. The reason is I'm the only maintainer for now and more code means it's harder to maintain the software.

**Comment by ConfusedAlex** [comment]
Just wanted to say that I currently have the same problem with Ulauncher
