### ISSUE TITLE
Migration to python3.

### ISSUE THREAD

**Issue by amitbha** [Ulauncher/Ulauncher#217]
The End Of Life date for Python 2 is in 2020. 
https://stackoverflow.com/questions/4836375/end-of-support-for-python-2-7

**Comment by gornostal** [comment]
Yep. After dropping support for Ubuntu 14.04 this may be doable. I think.

**Comment by CameronNemo** [comment]
Bump.

Ubuntu 14.04 is more than 5 years old. Python2's shelf life is less than one year.

Is there any way I can help get this moving?

**Comment by gornostal** [comment]
hi @CameronNemo 
The migration of Ulauncher app is almost complete. I need to fix and test RPM builds.

If you know Python it would be great if you could help with some of these tasks: https://github.com/Ulauncher/ext-api.ulauncher.io/issues
We need to add a possibility to filter extensions by API version.

**Comment by paualberto** [comment]
The distribution I use rejected the Ulauncher package because they aren't gonna add any more Python2 stuff since the EOL is so close.  
I'm very glad to know that the Py3 migration is almost complete! (how) Will you ship the py3 version when 5.0 comes out stable? :smile:

**Comment by gornostal** [comment]
> Will you ship the py3 version when 5.0 comes out stable?

Yes @paualberto 
Starting from Ulauncher 5.0 it will run only on Python 3

**Comment by gornostal** [comment]
Implemented in 5.3.0
