### ISSUE TITLE
Failed to save preference

### ISSUE THREAD

**Issue by compilelife** [Ulauncher/Ulauncher#218]
**Steps to reproduce:**
1. open preference dialog
2. switch to extension tab
3. install any extension (https://github.com/chenjsa/kingsoft-dict in my case)
4. change keyword option to 'fy' and click save
5. close and reopen preference dialog, reviewing kingsoft-dict's keyword option
6. it's still 'ks' there...

**v4.0.6r1**:
**ubuntu 16.04**:
**unity**:

**Logs**: https://gist.github.com/compilelife/d52282e144e61461a7c03fba78d3581b

It seems that I can save keyword after fresh install. But after several ulauncher restart and reinstall, this bug occurs.

Any idea?

**Comment by gornostal** [comment]
Thanks to @jetbug123 for the fix. It was released with Ulauncher v4.0.7.r5
https://github.com/Ulauncher/Ulauncher/releases/tag/4.0.7.r5

Please reopen if needed.
