### ISSUE TITLE
ULauncher does not allow Atom (text editor) to switch branches

### ISSUE THREAD

**Issue by zbron99** [Ulauncher/Ulauncher#219]
Atom Issue [#4982](https://github.com/atom/atom/issues/4982) can be caused by ULauncher.

**Steps to reproduce:**
Open ULauncher BEFORE atom after any system startup or login, and then try to switch branches on atom. Code and files will NOT update in atom. This will remain until you either log out or reboot. Vice versa, if you open atom BEFORE ULauncher, atom will update files correctly when switching branches.

**Linux distro**:
Ubuntu 16.04.3

**Comment by dainguyenhuu** [comment]
Sound like a perm thing to me. Maybe your Atom used to run on sudo but ULancher isn't?

**Comment by gornostal** [comment]
That may also be due to [inotify watch limit](#51). You can follow that link to check how to fix that.

Please let me know if this issue is still actual for you.

**Comment by gornostal** [comment]
I wasn't able to reproduce with Ulauncher 4.0.8, Atom 1.28.0 and Xubuntu 16.0.4
