### ISSUE TITLE
ULauncher doesn't get focus in Wayland

### ISSUE THREAD

**Issue by arikfr** [Ulauncher/Ulauncher#220]
I installed ULauncher on Fedora 27 and followed the instructions [here](https://github.com/Ulauncher/Ulauncher/wiki/Hotkey-In-Wayland) to setup the hotkey.

It works from everywhere, but 90% of the time the ULauncher window opens without keyboard focus.

Is this a known issue? 

The instructions mention that you need to install `wmctrl`, which I have. Maybe there is some extra step to make ULauncher use `wmctrl`?

**Comment by gornostal** [comment]
Hi

Try this workaround https://github.com/Ulauncher/Ulauncher/issues/183#issuecomment-360592973
It's a known issue. I'll add this to the instructions later

**Comment by arikfr** [comment]
Thanks! I updated the wiki page to link to this comment.

**Comment by gornostal** [comment]
Thank you :+1:
