### ISSUE TITLE
Calculator's ^ operator does weird magic

### ISSUE THREAD

**Issue by MicroDroid** [Ulauncher/Ulauncher#221]
**Steps to reproduce:**
`2^8`

I expect the result to be 256, but I get 10.

**Ulauncher version**: 4.0.6r1
**Linux distro**: Arch Linux, latest everything
**Desktop environment**: xfce4

**Comment by gornostal** [comment]
That's actually by design, but I see why that may be confusing

Calculator in Ulauncher just evaluates python expressions, and ^ is XOR in python.
For your case use `**`: x**y (x to the power y)

**Comment by MicroDroid** [comment]
Ah I see, that was confusing for a while since the launcher I used before treated ^ as a power operator
