### ISSUE TITLE
Google search opens in Chromium instead of Chrome

### ISSUE THREAD

**Issue by feimosi** [Ulauncher/Ulauncher#223]
I've got both Chrome Canary and Chromium installed. The former is set as a default browser, but still Ulauncher opens search results in Chromium. Is there any way to set the path explicitly?

![image](https://user-images.githubusercontent.com/5721520/36746073-b50f8a5a-1bf1-11e8-8971-b63076271c1d.png)

**Steps to reproduce:**
Ctrl + Space
`g test`

**Ulauncher version**: 4.0.6.r1
**Linux distro**: Antergos (ArchLinux)
**Desktop environment**: Gnome

**Logs**:
https://gist.github.com/feimosi/c70907d0a4c0acf00cf27ae5f5d547b1

**Comment by gornostal** [comment]
Ulauncher uses `xdg-open` under the hood to open URL.
I don't know why it ignores user settings. I'd suggest to look into how that command works.

**Comment by feimosi** [comment]
You were right, `xdg-open` looks for the `BROWSER` env, I've set it explicitly and it works fine now.

By the way, is there a possibility to define custom searches without writing an extension? E.g. for YouTube, DuckDuckGo etc.? If not, could you give some reference to how Google search is implemented?

**Comment by gornostal** [comment]
As for custom searches, check out Shortcuts in Preferences.
And Yes, you can add those without having to write an extension

**Comment by feimosi** [comment]
Awesome, thanks!

**Comment by zany130** [comment]
im having this issue to if i try xdg-open www.google.com it opens vivaldi but when i do a google search in ulaunch it opens firefox
