### ISSUE TITLE
More settings and useful functions.. Tips for possible requests!

### ISSUE THREAD

**Issue by Warmuser** [Ulauncher/Ulauncher#224]
Hi, I'm really amazed from your app, and it works perfectly on my Arch+GNOME Distro. Anyway I would like to suggest you new options. I need this but I think there are really useful also to other users too. So, I hope you appreciate my ideas:

- A setting to keep always the uLauncher bar on the desktop (without to press CTRL+SPACE everytime). 
- Two settings to make visible the uLauncher bar always on top of the windows or always covered by Windows.
- A setting to move and place the uLauncher bar anywhere on the desktop or workspaces.
- A setting to reduce the uLauncher dimension of the bar and the menu/text.
- A setting to auto-open the uLauncher bar by typing something (like the bar in KDE plasma).

Let me know if there are possibilities and what do you think about, thanks.

**Comment by gornostal** [comment]
Hi,
Thanks :slightly_smiling_face:
That's really nice to hear.

I've read all your suggestions and I think they open up many cool use cases that go beyond simple app launcher.
However, I want to keep Ulauncher to be a simple launcher. The main reason is that I want to be able to maintain and support the app on my own, and it's possible only if I keep the scope of the app the minimum.

I'm going to have to close this issue now. Sorry

**Comment by gornostal** [comment]
Created a separate issue for that #229
