### ISSUE TITLE
Conflict port with pgAdmin4 

### ISSUE THREAD

**Issue by abdulkadirazm** [Ulauncher/Ulauncher#225]
**Steps to reproduce:**
_your steps to reproduce here_

**Ulauncher version**: v4.0.6.r1
**Linux distro**: Ubuntu 17.10
**Desktop environment**: GNOME Shell 3.26.2

**Logs**:

_To get the logs please do the following:_
_* Close the app_
_* Run "ulauncher -v" from the console_
_* Copy output to https://gist.github.com/_
_* Link to the gist here_

https://gist.github.com/abdulkadirazm/51d55db42d23e7d74dcd2a54ca464be5#file-gistfile1-txt

On my computer, some ports conflict like 5050. When I start pgAdmin4 before uLauncher, hotkey is not working. Or I start the uLauncher before pgAdmin4, I can not use the pgAdmin4. How can I determine the conflict ports and change them with others.

**Comment by gornostal** [comment]
Ulauncher binds on port 5050 by default, but if it's already taken it will bind on ports from 5001 to 5100.
Looking at your logs, Ulauncher took port 5001, which is expected since you started pgAdmin4 before the app.
However, app hotkey should work fine. I've just tried that myself.

**Comment by gornostal** [comment]
Could you try to use different hotkey?
Just so we can tell whether this is an issue with Ctrl+Space or with any hotkey.

**Comment by abdulkadirazm** [comment]
I tried to use different hotkey. "Shift + Space" does not work either. "Alt + U" either. Can you check the conflicts? Or how can I change the default ports.

**Comment by gornostal** [comment]
I double-checked the code, port has nothing to do with the hotkey.
I'll think about what else we can do here to find the root cause of the hotkey issue.

**Comment by gornostal** [comment]
You can try hard-coding a different port by editing `ExtensionServer.py`. You can find it with `locate ExtensionServer.py` for example.

It's on the line 47.

Please let me know if that works for you. I don't have any other ideas as to how to fix this issue.

**Comment by abdulkadirazm** [comment]
Yeah! This works for me. I changed the port to 5001. Application works fine and also hot key too. Thanks a lot. Have a nice working day

**Comment by gornostal** [comment]
I was hoping it won't work, actually :)
Now we don't have neither a permanent fix nor a cause of the issue.
You'll have to make that change every time Ulauncher is updated.

I've installed Ubuntu 17.10, Ulauncher 4.0.6, and pgAdmin4 and it works for me. Weird.

**Comment by gornostal** [comment]
I've decided to change the default port to 5054.
This change was added to release v4.0.7.r5
