### ISSUE TITLE
Add support for environments without a compositor

### ISSUE THREAD

**Issue by gornostal** [Ulauncher/Ulauncher#230]
check out this comment https://github.com/Ulauncher/Ulauncher/issues/212#issuecomment-378580674

Please give this issue a :+1: if it's important for you

----

If you decide to implement this enhancement, try doing that in as few code changes as possible.
I would probably try to detect an absence of compositor once Ulauncher starts and then remove the shadows from the window. Maybe there's a better way though...

**Comment by jonhoo** [comment]
Hi @gornostal — just a gentle ping on this. It'd be really nice if there was a simple way to disable the drop shadow for the window, even if it was just a manual configuration option!

**Comment by gornostal** [comment]
@jonhoo could you try `5.4.0~beta1` and confirm that it works for you, pelase?
I've added `--no-window-shadow` command line argument for those who don't have a composer.

But I've noticed that when ulauncher is started with that option, names of alt keys are not aligned to the right side in the list of results. I'm going to fix it.

**Comment by avently** [comment]
@gornostal I checked the behavior from the latest commit and the app works fine without black border on frontend UI but with black border in preferences panel (I think it's not important).

**Comment by gornostal** [comment]
@avently I've changed the implementation. Could you verify it once again, please?
It's already in the stable release 5.4.0

Thanks

**Comment by avently** [comment]
> I've changed the implementation

and black border returned. So this new commit ruined previous result. How did you test the new build? You only need to `killall compositorname` and it will show the result.

**Comment by gornostal** [comment]
I didn't test it. How do I do it in Ubuntu 18.04?

**Comment by avently** [comment]
>Ubuntu 18.04

Have no idea. It's not an easy task to make code changes without possibility to test the result.. What do you think about gnome boxes with i3wm based distribution? It will help you with testing without needing to install any package. Maybe even i3wm will be enought because it doesn't require to much dependencies.

**Comment by gornostal** [comment]
@avently do you mind creating a VBox image please? I'd really appreciate your help with this?

**Comment by avently** [comment]
https://github.com/Ulauncher/Ulauncher/blob/a7b869d4b2e381dc6e2a2c69981fd0baf54d433e/data/themes/light/theme.css#L40

If you change this line everything will be fine.
So, the code should be:
```
.no-window-shadow {
    margin: -20px;
}
```
Tested this right now.

**Comment by gornostal** [comment]
This way we break another thing -- the alt keys are not aligned correctly.

I will revert to this solution now, but I'd like to find a better one

**Comment by gornostal** [comment]
A new version 5.4.1~beta1 will be published in 20 min.

**Comment by avently** [comment]
> do you mind creating a VBox image please

What about this ISO? https://www.manjaro.org/download/community/i3/
Should work fine with Gnome Boxes and Virtual Box too

**Comment by avently** [comment]
> the alt keys are not aligned correctly

What do you mean? 
![screen_2019-10-27_20-05-04](https://user-images.githubusercontent.com/7953703/67638418-37e5e500-f8f5-11e9-8849-0138a8491220.png)

**Comment by gornostal** [comment]
> What about this ISO? https://www.manjaro.org/download/community/i3/

Thanks. I'll try with it.

> What do you mean?

![2019-10-27_19-18](https://user-images.githubusercontent.com/1202543/67638571-a4111a80-f8ee-11e9-9466-60d3f0f13ab9.png)

**Comment by varac** [comment]
This is how ulauncher `5.4.0-0ubuntu1ppa1~disco` looks on current sway (wayland):

![IMG_20191027_204431 cleaned resized](https://user-images.githubusercontent.com/488213/67640525-4c2ce080-f8fb-11e9-9bc6-68660d40f33d.jpg)

It's not that I care too much but the "ulauncher window title" together with the big transparent borders are not exactly pretty. I'd appreciate a slicker UI altough it's really just a nice to have.

**Comment by gornostal** [comment]
@varac was it different before v5.4.0?

**Comment by varac** [comment]
> @varac was it different before v5.4.0?

No, I installed `5.3.0-0ubuntu1ppa1~disco` and then upgraded to `5.4.0-0ubuntu1ppa1~disco` today and didn't notice a difference.

**Comment by gornostal** [comment]
OK. I thought I broken something in 5.4.0.

I'm not familiar with how sway. I'd appreciate some help with fixing hat border.

**Comment by avently** [comment]
> the alt keys are not aligned correctly

By adding this code alt keys looks good too. And with compositor nothing ruined. I don't see any issues with it but you know your app much better.
```
.no-window-shadow .item-shortcut {
    margin-left: 50px;
}
```

**Comment by varac** [comment]
> OK. I thought I broken something in 5.4.0.

I gave 5.4.1~beta1 a try - it's still the same.

**Comment by sebw** [comment]
Upgraded to 5.4.1~beta1 in Fedora 31 and starting with `--no-window-shadow` in i3 without compositor.

Results:

- no black border around search bar
- still black border around preferences window
- alt shortcuts not aligned as seen in screenshot above

Thanks @gornostal !

**Comment by evilhamsterman** [comment]
> This is how ulauncher `5.4.0-0ubuntu1ppa1~disco` looks on current sway (wayland):
> 
> ![IMG_20191027_204431 cleaned resized](https://user-images.githubusercontent.com/488213/67640525-4c2ce080-f8fb-11e9-9bc6-68660d40f33d.jpg)
> 
> It's not that I care too much but the "ulauncher window title" together with the big transparent borders are not exactly pretty. I'd appreciate a slicker UI altough it's really just a nice to have.

@varac that's not an issue with ulauncher, that's because of how sway works. You have to tell sway not to put borders on the ulauncher window. I have this in my sway config
```
exec GDK_BACKEND=wayland ulauncher --hide-window
for_window [app_id="ulauncher"] floating enable, border none
```

**Comment by varac** [comment]
@evilhamsterman Thx for that hint, looks much better now !

**Comment by gornostal** [comment]
I've added a workaround for Sway to the list of known issues and fixed the remaining issue with `--no-window-shadow` flag. Should work fine in v5.5.0

Please reopen if needed

**Comment by infinity-98** [comment]
Same when using budgie pixel saver applet, couldn't find the config file

**Comment by infinity-98** [comment]
> I've added a workaround for Sway to the list of known issues and fixed the remaining issue with `--no-window-shadow` flag. Should work fine in v5.5.0
> 
> Please reopen if needed

same when using budgie pixel saver applet, how to workaround this issue
