### ISSUE TITLE
Preferences window won't open on Linux Mint

### ISSUE THREAD

**Issue by gornostal** [Ulauncher/Ulauncher#231]
_(originally posted [here](https://github.com/Ulauncher/Ulauncher/issues/205#issuecomment-377526194))_

Here is a VM https://drive.google.com/open?id=1HYWNuyrfFvO5ftUSaPXUmqu5lQEzY8lG

It's a Linux Mint with ulauncher_4.0.6.r1_all.deb installed & failling

user/pass : chou/chou

launching uLauncher is working, but opening the pref window is... pretty weird

**Comment by gornostal** [comment]
@Shuunen I've created a separate issue for this bug.
I've looked into it, but I don't have any idea what causes that or how to fix the bug.

**Comment by rohitchormale** [comment]
Strangely it is working for me. Any scenario to reproduce ? I tested on Mint 18.3

**Comment by gornostal** [comment]
If anyone else is able to reproduce this, please reopen
