### ISSUE TITLE
Add support to Ubuntu 18.04 `bionic` to the official launchpad PPA

### ISSUE THREAD

**Issue by leinardi** [Ulauncher/Ulauncher#233]
Please consider supporting the newer version on Ubuntu even before the stable release, this way users can do some test for you and maybe find new bugs on these releases before the official launch.

`bionic` will be released in 18 days, it would be nice to add support for it:

![image](https://user-images.githubusercontent.com/273338/38464570-173101f4-3b10-11e8-94fc-6b4432715e2e.png)

**Comment by gornostal** [comment]
Done.
