### ISSUE TITLE
Autofocus URL bar popup on clicking "Add Extension"

### ISSUE THREAD

**Issue by uncertainquark** [Ulauncher/Ulauncher#236]
It will be natural to focus the URL bar popup when "Add Extension" action is clicked.

![screenshot from 2018-05-08 11-09-25](https://user-images.githubusercontent.com/22585732/39739768-535671d4-52b0-11e8-9b20-0839d50f70b3.png)

**Comment by goodwillcoding** [comment]
@uncertainquark ... a PR would be welcome on this :)
