### ISSUE TITLE
ValueError exception (LinuxMint)

### ISSUE THREAD

**Issue by rmassidda** [Ulauncher/Ulauncher#243]
**Steps to reproduce:**
Pressing any key raises a ValueError exception.

**Ulauncher version**: ulauncher 4.0.8.r1
**Linux distro**: Linux Mint 18.2 Sonya x86_64
**Desktop environment**: Cinnamon 3.4.6 

**Logs**:
https://gist.github.com/rmassidda/bfa5558f72013668d2c78af7b1e0ffd4
(first exception after line 188)

**Comment by rmassidda** [comment]
_shortcuts.json_ inside _~/.config/ulancher/_ was damaged, deleting it resolved the issue.

**Comment by gornostal** [comment]
Hmm.. I wonder how that could happen?
Do you have steps to reproduce that broken shortcuts.json?

**Comment by gornostal** [comment]
If anyone can provide reliable steps to reproduce, please reopen the bug.
