### ISSUE TITLE
Ulauncher has stopped displaying a Wine application

### ISSUE THREAD

**Issue by CottonEaster** [Ulauncher/Ulauncher#245]
**Steps to reproduce:**
Uncertain - for previously the Wine program at issue, namely the installable (as against portable) version of Lucas Chess - was locatable within Ulauncher.

**Ulauncher version**: 4.0.8.r1
**Linux distro**: Mint 18.3
**Desktop environment**: Cinnamon

**Logs**:

https://gist.github.com/CottonEaster/7185aaeb10d31289e1bcfb2e07a73173

NB: uninstall unlauncher (`sudo apt purge ulauncher`) and reinstalling seems to have fixed the problem.

**Comment by gornostal** [comment]
Did you get that log after reinstalling Ulauncher?
Could you post contents of the Wine program's .desktop file? You can locate it by launching with Ulauncher and then checking the logs. You will see something like `Run application Screenshot (/usr/share/applications/screenshot-tool.desktop)`

**Comment by CottonEaster** [comment]
No; the log was from before reinstallation.

The .desktop file comprises the following.

```
[Desktop Entry]
Name=Lucas Chess
Exec=env WINEPREFIX="/home/nicholas/.wine" wine C:\\\\windows\\\\command\\\\start.exe /Unix /home/nicholas/.wine/dosdevices/c:/users/Public/Start\\ Menu/Programs/Lucas\\ Chess/Lucas\\ Chess.lnk
Type=Application
StartupNotify=true
Path=/home/nicholas/.wine/dosdevices/c:/Program Files (x86)/LucasChess
Icon=E12D_Lucas.0
```

**Comment by gornostal** [comment]
Hmm, the file looks good.
Sorry, I don't know what happened, but if it occurs again, please reopen this issue and we should be able to figure out the cause while it can be reproduced.
