### ISSUE TITLE
scrolling on RenderResultListAction

### ISSUE THREAD

**Issue by brpaz** [Ulauncher/Ulauncher#246]
**RenderResultListAction** seems to be limited in terms on visible number of items (maybe its related to screen height)

I think it would be nice to implement scrolling in the list. So lets say we define a max height of the results list, and if has more results, it will allow the user to scroll. That way, not only it looks prettier but also allow more complex workflows.

What do you think?

**Comment by Dankni95** [comment]
Any updates on this?

**Comment by friday** [comment]
It's in the v6 branch now (see #968 for details). Follow https://github.com/Ulauncher/Ulauncher/issues/869 if you want to be notified of v6 release plans.
