### ISSUE TITLE
Always Show Search Tasks

### ISSUE THREAD

**Issue by ibrokemypie** [Ulauncher/Ulauncher#248]
In uluancher the search tasks (google, wikipedia etc) only show if no other results show, however sometimes I want to search something even if there are results that come up. Showing the search tasks below all other results at all times or having an option to do so would be incredibly useful.

**Comment by gornostal** [comment]
The list or search results will include shortcuts too if their names match the query.

I don't want to change that behavior, so I'm going to close this ticket. Sorry
