### ISSUE TITLE
Segmentation fault on openSUSE w/ GNOME

### ISSUE THREAD

**Issue by retrixe** [Ulauncher/Ulauncher#250]
**Steps to reproduce:**
1. On openSUSE Tumbleweed with GNOME and Wayland, run `ulauncher` in a terminal.
2. Prompt will tell you to run `GDK_BACKEND=x11 ulauncher` instead.
3. On running Ulauncher with GDK_BACKEND as x11, segmentation fault occurs.

**Ulauncher version**: 4.0.8.r1
**Linux distro**: openSUSE Tumbleweed 20180605
**Desktop environment**: GNOME, occurs on Wayland and X for some reason

**Logs**: https://pastebin.com/Ep7jar2Y

Was unable to find any solution throughout the issue tracker..

**Comment by gornostal** [comment]
Thanks for reporting the bug. I'll look into this

**Comment by gornostal** [comment]
I can confirm, the issue exists. I did a clean install of openSUSE Tumbleweed and I see the segfault when I run Ulauncher.

I was able to identify the line in Ulauncher code that triggers it, it's `Gtk.Builder.add_from_file(self, filename)`. However, I don't know where to go from there :slightly_frowning_face: 

Weirdly enough, Ubuntu 18.04 also has GTK+ 3.22.30, but the bug cannot be reproduced there.

Are you saying it can also be reproduced if you switch to X11 session in openSUSE?

**Comment by retrixe** [comment]
Yeah, under the GNOME on X.org session as well.

**Comment by friday** [comment]
Closing this, since it's and old issue that doesn't seem to happen any more, and we don't package for openSUSE currently (hopefully we'll get back to do that in the future).

If this is still happening to people, especially on supported distros we package for, please create a new issue.
