### ISSUE TITLE
Shared installation of extention with settings for all users

### ISSUE THREAD

**Issue by moocan** [Ulauncher/Ulauncher#253]
I would like to know if it's possible to install extension globally and configure settings for every users ?

I tried to copy extensions from ~/.cache/ulauncher_cache/extensions/ to /usr/share/ulauncher/extensions/ but don't seems to work.

I don't know where to place preferences and I don't if it's possible.

Kind Regards

**Comment by gornostal** [comment]
Hi,
Currently the only way to do that is by copying `~/.config/ulauncher/extensions.json` to `/home/<username>/.config/ulauncher/` for every user. 

BTW, everything in `~/.cache/ulauncher_cache` is autogenerated, so you don't have to copy that.

Hope that helps. I'm closing this issue now.
