### ISSUE TITLE
Ulauncher no longer starts after recent Arch Update - PyGIWarnings

### ISSUE THREAD

**Issue by faasie** [Ulauncher/Ulauncher#255]
**Steps to reproduce:**
Ulauncher just doesn't start.

**Ulauncher version**: 4.1.0.r1
**Linux distro**: Arch Linux
**Desktop environment**: Gnome 3.28.2

**Logs**:
[Logs-Gist](https://gist.github.com/faasie/77f8bef3691cd64bcd11f87178676b15
)

**Comment by gornostal** [comment]
Looks like Ulauncher's data directory have been removed.
Could you try to re-install Ulauncher?

**Comment by faasie** [comment]
Completely uninstalled and reinstalled. Still getting the same error.

**Comment by faasie** [comment]
Just reinstalled again and it's working now. *shrug*

I'm happy! 

Closing issue.
