### ISSUE TITLE
Problem stopping the wrong version of 'Preferred applications' being run by the launcher

### ISSUE THREAD

**Issue by CottonEaster** [Ulauncher/Ulauncher#256]
**Steps to reproduce:**

Install xfce4 in a non-xfce DE, such as Cinnamon.
Add `/usr/share/xfce4` to ulauncher's black list - to no avail.
Use Uauncher to search for a run Mint Cinnamon's 'Preferred applications' program / window (`cinnamon-settings default`) - which looks like this:

![image](https://user-images.githubusercontent.com/9998846/42550891-5927a0ee-84cc-11e8-9383-0a1e050b655d.png)

Have this appear instead:

![image](https://user-images.githubusercontent.com/9998846/42550910-6ed79962-84cc-11e8-8889-2ba10ef8eeb6.png)

which, I believe, is the xfce4 version of Preferred Applications - [a program](http://docs.xfce.org/xfce/exo/preferred-applications) that gets pulled in, non-optionally, by `xfce4-terminal` (which I have and want as my terminal).

**Ulauncher version**: 4.1.0.r1
**Linux distro**: Mint 19
**Desktop environment**: Cinnamon

**Logs**:

[gist](https://gist.github.com/CottonEaster/150469e849655e2fe1d2e3d6b416828a).

**Comment by gornostal** [comment]
That doesn't seem like something that has to be resolved in Ulauncher.
You can try to figure out why it runs one instead of another by examining desktop files for "Preferred Applications" program.
