### ISSUE TITLE
Looks like Ulauncher seaches the trash for apps

### ISSUE THREAD

**Issue by CottonEaster** [Ulauncher/Ulauncher#258]
**Steps to reproduce:**
Put a launcher file (a .desktop file) on the desktop (or elsewhere?) and then move it to the trash.
Check the ulauncher log.
Possibly also: create a new launcher for the same app, and see whether one has trouble launching that app from Ulauncher.

**Ulauncher version**: 4.1.0.r1

**Linux distro**: Mint 19
**Desktop environment**: Cinnamon

**Logs**:

I seem to have lost the relevant bit of the logs, but Ulauncher seemed to be saying (in the log, as was) that it had found a new app in `~/.local/share/Trash`. I have now added that folder to Ulauncher's exclusions.

**Comment by gornostal** [comment]
Thanks for reporting this issue @CottonEaster

**Comment by goodwillcoding** [comment]
@gornostal as note, I think #286 addresses this issue. Only outlier is some is sticking their trash folder into XDG_DATA_DIRS in which case you know ... it's on them. I recommend closing.

**Comment by gornostal** [comment]
@goodwillcoding you're right. It's fixed with your changes in v4.3.0.
Thanks.

Closing this issue
