### ISSUE TITLE
Crash on startup - (Notify|WebKit2) was imported without specifying a version first.

### ISSUE THREAD

**Issue by mkody** [Ulauncher/Ulauncher#259]
Looks like #200 is happening again.  
I upgraded my Arch system yesterday and with it ulauncher (4.0.8.r1-1 -> 4.1.0.r1-1).

**Steps to reproduce:**
Start ulauncher.

**Ulauncher version**: 4.1.0.r1
**Linux distro**: Arch Linux 4.17.5-1-ARCH
**Desktop environment**: i3

**Logs**: https://gist.github.com/mkody/b4fd7f636b2c6bef62c824a964468f7e

**Comment by gornostal** [comment]
That's not because of Notify|Webkit2.
Seems like part of Ulauncher has been removed from your file system. Could you try re-installing the app?

Please reopen if necessery.

**Comment by mkody** [comment]
I already tried to remove and reinstall ulauncher two times but with no luck.

**Comment by gornostal** [comment]
Apologies for the delay.

Could you open `/usr/lib/python2.7/site-packages/ulauncher/config.py` in editor (requires sudo) and add this
```
    print('abs_data_path', abs_data_path)
```
after line 55?

Save the file and then start again. In the logs you should see what path it cannot find.

**Comment by mkody** [comment]
Huh. So after adding that line in config.py, it now starts (while it didn't as I tried just before).

`% ulauncher`: https://gist.github.com/mkody/4e105ee654ff669ce46e1745f1ce14e5
`% ulauncher -v`: https://gist.github.com/mkody/79ad59c9196777e79dcb7e400020043a

**Comment by gornostal** [comment]
Interesting.
Have you tried removing the line?

That couldn't possibly be a fix :slightly_smiling_face:

**Comment by mkody** [comment]
Yes, I removed the line and it works. So editing the file once did fix the issue.

**Comment by gornostal** [comment]
I'm glad it worked. Unfortunately, I can't explain why.
