### ISSUE TITLE
Create a script that automates releases

### ISSUE THREAD

**Issue by gornostal** [Ulauncher/Ulauncher#26]
Here is what I need to do in order to make a new release:
1. Change version in `setup.py`
2. Run `debchange` and create a new entry
3. Specify `trusty` as a target distibution
4. Run `./create_deb`
5. Go to `/tmp/ulauncher_deb`
6. Do `dput ppa:agornostal/ulauncher ulauncher_x.y.z_source.changes`
7. Open Launchpad website and copy compiled binaries to other distributions like `vivid` or `wily`
8. Merge dev to master
9. Create and push tag
10. Update version on the website

I found [make-ppa](https://github.com/dainnilsson/scripts/blob/master/make-ppa) script. Have to look if it's going to be useful for automation.

Any suggestions are welcome.

**Comment by Abhinav1217** [comment]
You can simply create a shell script to do all that. Have a version info on a separate file so tfhat you can automate process like `./setup.py --new-release` which will tell setup.py to get version number from that file.

Best option is to use github's tag feature. or git head hash. I am one of the maintainer of fedy, I once had a personal script for building and updating it. What I did is I pushed new version on github, Then that script used to pull the repo on tmp folder, compressed it as .tar.gz, then pushed it to the server and ran the publishing script on the server. It was a simple shell script which ran all the bash and git commands which I had to run manually.

**Comment by gornostal** [comment]
Thanks for the great suggestions @Abhinav1217.
I'm going to implement something like that, but I'm not planning to use deb packaging anymore, so this ticket is no issue relevant.
