### ISSUE TITLE
[request] Add option to disable/enable animations and set animation duration

### ISSUE THREAD

**Issue by Arohdin** [Ulauncher/Ulauncher#263]

**Comment by Arohdin** [comment]
That seems to be the case. If I disable the animations on my DE I don't see the animations anymore.
The reason I thought it was ULauncher is because I just moved from Albert Launcher; on which I didn't have any animations.

Maybe it has to do with how he program handles closing and opening of the search box.

**Comment by gornostal** [comment]
Maybe Alfred handles open/close events differently.

I'm going to close this issue because I want to keep Ulauncher configuration as simple as possible. Sorry
