### ISSUE TITLE
Bug when trying to open the configuration window on Fedora 28 / XFCE

### ISSUE THREAD

**Issue by polemon** [Ulauncher/Ulauncher#264]
I'm getting an error when trying to open the config window (cogwheel in the Launcher).
When I click that cogwheel, a window with "Loading..." appears, and that's where it all kinda stops
If I click anywhere, the window becomes translucent, and is not close-able.
I have to use the XFCE taskbar to kill the program.

Logs are supplied as requested.

**Steps to reproduce:**
 1.  install Fedora rpm ulauncher_4.1.0.r0_fedora.rpm
 2. run ulauncher: `ulauncher --hide-window &`
 3. open ulauncher with <kbd>Ctrl</kbd> + <kbd>Space</kbd>
 4. click on the little cogwheel to open up the configuration window

**Ulauncher version**:  v4.1.0.r0 (also happens with  v4.1.0.r1)
**Linux distro**: Linux Fedora 28
**Desktop environment**: XFCE

**Logs**: https://gist.github.com/polemon/2f199d12f80096cbd29ae065acc54e7e

The error I'm getting is:
```
(WebKitWebProcess:26118): Gdk-ERROR **: 19:53:44.287: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 197 error_code 2 request_code 153 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```
I also tried opening the config window from the icon in the notification area, same result: I'm just getting a a non-working window.

**Comment by gornostal** [comment]
Apologies for the delay, but I still haven't had time to install Fedora 28 and look into that issue.
In the meantime, you can try to google that error. Maybe it's a known issue with the latest Fedora and GTK

**Comment by gornostal** [comment]
Hi @polemon 
I've tried to reproduce it on Fedora 28 with the latest updates and Xfce, but I wasn't able to.
It would be very helpful if you could provide a Vbox image where I can reproduce the issue.

Also, do you think there's something that you installed that may have caused that issue? 
Like unstable version of Gtk or Linux kernel or something.

**Comment by gornostal** [comment]
Please reopen if needed

**Comment by polemon** [comment]
Sorry for not responding sooner, but I literally forgot about it, once I upgraded to Fedora 29, when the problem stopped appearing.
