### ISSUE TITLE
Set launch shortuct to Alt + Space

### ISSUE THREAD

**Issue by spajdo** [Ulauncher/Ulauncher#265]
Hi. I want say thank you for this software. 
Nice work.
I want ask why is not possible set shortcut Alt + Space to launch Ulauncher.

**Comment by gornostal** [comment]
Hi @spajdo 
Thanks :)

> I want ask why is not possible set shortcut Alt + Space to launch Ulauncher.

It is possible, but only manually (see #100)
I wasn't able to find a good solution to read the hotkey that starts with Alt in the popup window that appears when you click on the hotkey input.

**Comment by spajdo** [comment]
Thanks for replay... it works.
