### ISSUE TITLE
Can't set shortcut to alt+space on Ubuntu Budgie

### ISSUE THREAD

**Issue by TobiasDev** [Ulauncher/Ulauncher#267]
**Steps to reproduce:**
Install the app on Ubuntu Budgie
Try changing shortcut to alt+space
See it not working

**Ulauncher version**: 4.1.0.r1
**Linux distro**: Ubuntu 
**Desktop environment**: Budgie

---
I used to have Albert installed before this and I had no issue setting alt+space as shortcut in that app, however, when I try and replace it in this app it just doesn't allow me. Is there a special reason for that?
PS. I have re-started my PC after un-installing Albert, so it should be that Albert is still taking that shortcut

**Comment by gornostal** [comment]
It's a known issue. Please see #100 for a workaround
