### ISSUE TITLE
Can't install, hash sum mismatch package python-levenshtein

### ISSUE THREAD

**Issue by rockmanvnx6** [Ulauncher/Ulauncher#269]
**Steps to reproduce:**
_your steps to reproduce here_

**Ulauncher version**:  ulauncher_4.1.0.r1_all.deb
**Linux distro**: ubuntu 16.04 lts
**Desktop environment**: unity

**Logs**:
~$ sudo apt-get -f install ulauncher
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  gir1.2-keybinder-3.0 libkeybinder-3.0-0 python-backports.ssl-match-hostname
  python-levenshtein python-pkg-resources python-pyinotify python-pysqlite2
  python-six python-websocket python-xdg
Suggested packages:
  python-setuptools python-pyinotify-doc python-pysqlite2-doc
  python-pysqlite2-dbg
The following NEW packages will be installed:
  gir1.2-keybinder-3.0 libkeybinder-3.0-0 python-backports.ssl-match-hostname
  python-levenshtein python-pkg-resources python-pyinotify python-pysqlite2
  python-six python-websocket python-xdg ulauncher
0 to upgrade, 11 to newly install, 0 to remove and 45 not to upgrade.
Need to get 35.7 kB/1,496 kB of archives.
After this operation, 5,402 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://au.archive.ubuntu.com/ubuntu xenial/universe amd64 python-levenshtein amd64 0.12.0-2build1 [35.7 kB]
Err:1 http://au.archive.ubuntu.com/ubuntu xenial/universe amd64 python-levenshtein amd64 0.12.0-2build1
  Hash Sum mismatch
Fetched 35.7 kB in 0s (184 kB/s)              
E: Failed to fetch http://au.archive.ubuntu.com/ubuntu/pool/universe/p/python-levenshtein/python-levenshtein_0.12.0-2build1_amd64.deb Hash Sum mismatch

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

_To get the logs please do the following:_
_* Close the app_
_* Run "ulauncher -v" from the console_
_* Copy output to https://gist.github.com/_
_* Link to the gist here_
https://gist.github.com/rockmanvnx6/2c4157005711fb1bb1ba116950a9bf58

**Comment by gornostal** [comment]
This issue is not really related to Ulauncher. Looks like there's something wrong with packages in your system.

After a bit of googling (query `apt-get "hash sum mismatch") I found this answer https://askubuntu.com/a/41618

You may also check out this forum entry https://ubuntuforums.org/showthread.php?t=2268528

Hope that helps.
Closing this issue
