### ISSUE TITLE
Ulauncher breaks Deepin File Manager File Sync

### ISSUE THREAD

**Issue by eMSiBi** [Ulauncher/Ulauncher#277]
**Steps to reproduce:**
Install ulauncher from Deepin repo (version: 3.2.1.r1-0ubuntu1ppa1~zesty)
or
Install ulauncher from original Maintainer (version: 4.1.0.r1)
After installation, and start to using app, on deepin file manager, when create a file/folder, or rename a file/folder or delete file/folder, or modify/create/delete anything file manager is not sync, so should be refreshed. Specially happens on different partition data which currently used operating system is not installed on that partition.

---------------------------------------------------------------------------------------------------------------------------------------

**Ulauncher version**: 3.2.1.r1-0ubuntu1ppa1~zesty & 4.1.0.r1
**Linux distro**: Deepin 15.7 (Latest)
**Desktop environment**: DDE

---------------------------------------------------------------------------------------------------------------------------------------
**Logs**:

v3.2.1.r1-0ubuntu1ppa1-zesty logs: https://gist.github.com/eMSiBi/8e78fd539bb5f378ba4c862ae251b223

v4.1.0.r1 Logs: https://gist.github.com/eMSiBi/b12f8f3e1c972aa0334923b2a1b4e5dd

**Comment by gornostal** [comment]
Thanks for reporting this issue. I'll look into it

**Comment by gornostal** [comment]
@eMSiBi if you have deepin-15.7-amd64.iso. Could you upload it somewhere please?

Download speed from the official website is 20 KB/s :(

**Comment by eMSiBi** [comment]
@gornostal , forgot to say that, at thesame time bot of these can't add extensions

I tried many of them but tried this one at log: https://ext.ulauncher.io/-/github-yegorf1-ulauncher-translator

https://gist.github.com/eMSiBi/5ce608205e120a2f4cee13e3cb435d0c

I don't have any firewall, clean install of Deepin and i can access/download to the extension link on browser. Thanks a lot for help :)

**Comment by gornostal** [comment]
Thanks for the Deepin image.

I'll take a look at the issue with the extension too

**Comment by gornostal** [comment]
@eMSiBi I noticed that there was a missing dependency when installing Ulauncher on Deepin.
I fixed that in 4.2.1 (dev release). Could you try this build? https://github.com/Ulauncher/Ulauncher/releases/download/4.2.1.r0/ulauncher_4.2.1.r0_all.deb

**Comment by eMSiBi** [comment]
> @eMSiBi I noticed that there was a missing dependency when installing Ulauncher on Deepin.
> I fixed that in 4.2.1 (dev release). Could you try this build? https://github.com/Ulauncher/Ulauncher/releases/download/4.2.1.r0/ulauncher_4.2.1.r0_all.deb

Seems working well. I'll try it for a while. So Thank you so much for your help.
I hope you could fix python3 problem (extensions) as soon as possible. 
As a temp workaround, why don't you force the Ulauncher to use python2?

**Comment by gornostal** [comment]
> I hope you could fix python3 problem (extensions) as soon as possible.

Which python3 problem are you referring to?
Sorry, maybe I missed something.

BTW, good suggestion about forcing python2 :+1: 
I'm going to add that

**Comment by gornostal** [comment]
Fixed in 4.3.0
