### ISSUE TITLE
Ulauncher is having black color border in Lubuntu 18.04

### ISSUE THREAD

**Issue by lalitmee** [Ulauncher/Ulauncher#278]
**Steps to reproduce:**
_your steps to reproduce here_
Install Ulauncher in Lubuntu 18.04 and you will see something like this.

![selection_005](https://user-images.githubusercontent.com/10762218/44922677-a536ce00-ad63-11e8-8172-a069531bdcfe.png)

**Ulauncher version**: v4.1.0.r1
**Linux distro**: Lubuntu 18.04
**Desktop environment**: LXDE

**Logs**: https://gist.github.com/lalitmee/1dc3f8e824e374f9755baa77ee206a3c

**Comment by gornostal** [comment]
Ulauncher requires compositor to correctly render UI.
Could you check if it's enabled in your system?

Since you've mentioned you're using LXDE, which is a super-lightweight DE, I guess it's not enabled by default there.

**Comment by lalitcc** [comment]
Ohh, great. I will check it and inform you.

**Comment by lalitcc** [comment]
@gornostal, thank you so much. Problem solved. :grinning: :innocent: 
You were right Compositor was not enabled by default. I enabled it and now its working fine.

**Comment by gornostal** [comment]
Cool :+1:
