### ISSUE TITLE
Additional HTML "span" tags added after typing

### ISSUE THREAD

**Issue by cncastillo** [Ulauncher/Ulauncher#282]
**Steps to reproduce:**

I was starting to create an extension for Ulauncher and for some reason after typing some letters the items get updated with additional "span" tags breaking the whole styling.

![screenshot from 2018-09-07 00-12-59](https://user-images.githubusercontent.com/5957134/45196771-475b2800-b234-11e8-88c6-31d6c12a571c.png)
![screenshot from 2018-09-07 00-14-37](https://user-images.githubusercontent.com/5957134/45196770-475b2800-b234-11e8-86a0-5bd3a66263bb.png)

**Ulauncher version**: v4.1.0.r1
**Linux distro**: Elementary OS 0.4.1 Loki (Built on Ubuntu 16.04)
**Desktop environment**: Pantheon

**Logs**: [Log file](https://gist.github.com/cncastillo/c666d6936b6dc570d6552d8ae0847a43)

**Comment by gornostal** [comment]
Oh you are using markup language to style bus numbers. That's nice
I wasn't expecting someone would do something like that so I didn't check that scenario.

Seems like the span you're talking about is a highlighting span. You can try to pass `highlightable=False`  when creating an instance of `ExtensionResultItem`

Please let me know if that works or not

**Comment by cncastillo** [comment]
Yes! that worked thanks  :smile:. 

*Off-topic*: There is any way to add a side panel with an interactive map or a plain image like the following?: 

![screenshot from 2018-09-07 14 19 43](https://user-images.githubusercontent.com/5957134/45236946-c04d9480-b2b3-11e8-8710-8b133720dbb3.png)

That is from Cerebro-App that uses Electron.

**Comment by gornostal** [comment]
Thanks for the suggestion. It's in my plans to implement a new template for a result item, so Extensions can implement things like that

**Comment by jbriales** [comment]
Having the ability to have extra capabilities in the result item (like this) would be absolutely awesome.
Is there any expected time to introduce this feature? Or how could I keep track of any changes in that direction to introduce them as soon as possible? :)

**Comment by gornostal** [comment]
> Is there any expected time to introduce this feature?

@jbriales there's no ETA yet. I can only tell that once Python 3 migration is complete (work is in progress) I'm planning to implement that feature.

Please subscribe to email notifications about new releases on https://ulauncher.io
Or you can follow [UlauncherApp](https://twitter.com/UlauncherApp) on Twitter

**Comment by jbriales** [comment]
@gornostal quick check here: any updates on the roadmap towards having visualization (i.e. is Python 3 migration finished/ near to finish?)
I'm having renovated needs to previsualize some stuff for an important use case.
Depending on the ETA I might wait for this feature here or migrate this use case out of Ulauncher.
Thanks!

**Comment by gornostal** [comment]
Hi @jbriales 
Sorry for the delayed reply. The migration to Python 3 will take more time. It's not near to finish.
