### ISSUE TITLE
API suggestion: add event.get_keyword_id()

### ISSUE THREAD

**Issue by friday** [Ulauncher/Ulauncher#284]
`event.get_keyword()` is very useful, since extensions may use multiple keywords, and in this case there's a need to distinguish between them in `KeywordQueryEventListener`.

However, it gets the user defined keyword, not the keyword id. Since users can change these it has to be converted back to the keyword id.

This is not hard by any means, but it feels like a hack having to do it.
https://github.com/brpaz/ulauncher-hash/pull/4/commits/be88b73b7cc14416893c3a417ecf67900b3d3577

**Comment by goodwillcoding** [comment]
@friday send a PR?

**Comment by gornostal** [comment]
Hey @friday 
Feel free to rebase your PR over `dev`. I think we can now merge it.

**Comment by friday** [comment]
I will try to do that soon. Don't have the time right now I'm afraid.

**Comment by brpaz** [comment]
Any chance for this to be added?

**Comment by friday** [comment]
This is fixed in the Ulauncher v6 branch and PR #870. It won't be released for a while, but we made a tracking issue if you want to be notified #869
