### ISSUE TITLE
Extension idle ram usage

### ISSUE THREAD

**Issue by friday** [Ulauncher/Ulauncher#285]
I may be measuring this wrong, but it seems that every extension uses at least 16mb of ram while idle (maybe this is the Python runtime and the websocket client). This builds up.

**Ulauncher version**: 4.1.1.r1
**Linux distro**: Arch
**Desktop environment**: Gnome

![screenshot from 2018-09-07 18-16-32](https://user-images.githubusercontent.com/515120/45230767-3ceb6d80-b2ca-11e8-9c0b-20af6f48e53e.png)

**Comment by goodwillcoding** [comment]
@friday right, it's the python interpreter run per plugin ... using ram if has to. completely normal usage. it's is not leaking memory as far as I can tell. how is this an issue?

**Comment by friday** [comment]
> No memory leaks as far as I can tell.

I never said it was. I said "This builds up". This is referring to extensions using 16mb ram each, so if you have a lot of extensions this builds up. Over 200mb with 10 extensions, and close to 400mb with 20, 700mb with 40 etc (doubt anyone has this many but my point is this doesn't scale well). 

> It's the python interpreter run per plugin ... using ram if has to. completely normal usage.

> how is this an issue? 

> still not an issue, just standard python process running.

I don't understand what point you are trying to make. Allocating ram comes with a cost. There are multiple possible solutions to allocate less ram. How is "this is normal" or "this is not an issue" relevant or constructive arguments? How much does it need to allocate before it becomes an issue?

* Aprox 11/16mb (see footnote 1) allocated per extension seem to be due to the Python Gnome API's (GLib, Gtk and Gdk). Architecturally, they don't need to be loaded into each extension. Any point where extensions need to call them this should optimally be done by sending a message to the server. Duplicating the API is inefficient. It's also fair to assume it's a blocker for #283 if that issue is under consideration.
* I have yet to see any extension that actually runs background jobs, so I don't understand why extensions are kept running after the Ulauncher UI is closed. Extensions may depend on other API's and services doing the heavy lifting, but rarely does much more than wrap their APIs. It could be just a missed opportunity rather than intentional design, or it's a performance benefit. At least on my system running a small Python script with a basic websocket implementation (see footnote 2) takes less than 50ms. So I don't really see the need. Maybe I'm missing something?

This issue may not be a low-hanging fruit, but well worth considering for long term API-breaking improvements imo. If you disagree, you have to argue better.

Footnotes:
1. Python2 doesn't support memory inspection unless you patch it. My tests were performed by running the an extension and cutting out dependencies.
2. The test was made with the same ws-client as Ulauncher uses measuring the time it took to start up and connect to the Ulauncher Extension server.

**Comment by goodwillcoding** [comment]
>>> Allocating ram comes with a cost. 

RAM is there to be used, and interpreted languages like Python use a bit of it.
For example this is a screenhost of just the python2 shell running with **NOTHING** imported in it except for stdlib and consuming near 3MB of RAM already.

![image](https://user-images.githubusercontent.com/582074/45910764-ccac1400-bdc0-11e8-8231-973e3686c65d.png)

As you can imagine as more libraries are imported and used it will pump up the usage more. For example, importing GTK using  (as an example, and no I am not saying plugins have to) bring up the ram usage to 9Mb.

>>> import gi
>>> gi.require_version('Gtk', '3.0')
>>> from gi.repository import Gtk

![image](https://user-images.githubusercontent.com/582074/45910756-c027bb80-bdc0-11e8-96bc-04dc3a9297bc.png)

So if the case is to be made that work should be put in thinning down RAM usage of Ulauncher plugins the only way is to profile it's usage and identify which libraries and components consume RAM and where they can be swapped for libraries or code maintainers have to write that consume less RAM.

There is number of tools that do that like guppy (https://pypi.org/project/guppy/) and whether or not they patch python2 is irrelevant if one does need to profile

>>> This issue may not be a low-hanging fruit, but well worth considering for long term API-breaking improvements imo. If you disagree, you have to argue better.

You might end up being right, but I'd say without more data about what consumes RAM, where and why there is no a reason to spend time on this, 16Mb is not unresonable IMHO (though @gornostal may disagree). That said, you want to write an example of a plugin architecture that connects to Ulauncher, does what it needs with less RAM it would help both your argument and potentially the project :)

**Comment by gornostal** [comment]
> I don't understand why extensions are kept running after the Ulauncher UI is closed

@friday Extensions must be running because when the user starts typing a query I want to have the fastest response time. 

UX is what I think the users will value the most. Other things I'm going to optimize when I resolve all the UX issues

**Comment by friday** [comment]
> UX is what I think the users will value the most. Other things I'm going to optimize when I resolve all the UX issues

Fair enough.

**Comment by friday** [comment]
Replaced by https://github.com/Ulauncher/Ulauncher/issues/1063
