### ISSUE TITLE
KeyError: '\x00' on launch

### ISSUE THREAD

**Issue by ibot3** [Ulauncher/Ulauncher#290]
I installed Ulauncher from AUR and it worked fine. But some weeks ago, it stopped working. I tried updating and reinstalling, but the problem persists.

**Steps to reproduce:**
Start ulauncher

**Ulauncher version**:
**Linux distro**: Arch
**Desktop environment**: i3wm

**Logs**:
https://gist.github.com/ibot3/e960dab5c53c6fc40c57475b2abe0bfc

**Comment by gornostal** [comment]
@ibot3 did the @goodwillcoding's suggestion work for you?

**Comment by gornostal** [comment]
Apparently Ulauncher was run with Python3, which caused that issue.
I agree, removing `~/.cache/ulauncher_cache` should fix the issue

**Comment by gornostal** [comment]
I've added a patch that forces Python 2 to avoid issues like this in future

**Comment by ibot3** [comment]
Deleting the cache folder solved the problem. Thank you.

**Comment by gornostal** [comment]
Cool. Closing this one
