### ISSUE TITLE
Unable to set the hotkey "Meta_L + space" on Linux using PC keyboard

### ISSUE THREAD

**Issue by WispZhan** [Ulauncher/Ulauncher#291]
**Steps to reproduce:**
I running Ulauncher is Normal.

I am trying  use a PC Keyboard on Linux.And modify it to Mac keyboard layout. Mapped win to meta, and switch win-key and alt-key.

But I can't set hotkey to 'Meta_L + space'.
I can set hotkey to 'Meta_L' or ‘space’ separately.
Is this a bug? How can I solve it?

**Ulauncher version**:  4.1.1.r1
**Linux distro**: Linux Mint 19
**Desktop environment**: Cinnamon 3.8

**Logs**:
No Logs.

**Comment by WispZhan** [comment]
Ooops. I didn’t see #100. I’m sorry.

**Comment by gornostal** [comment]
Library that Ulauncher uses for key binding doesn't read Meta+Space.
The workaround in #100 should work I think.

Closing this issue.
