### ISSUE TITLE
Default terminal for htop

### ISSUE THREAD

**Issue by yegorf1** [Ulauncher/Ulauncher#295]
Can't change default terminal for htop

**Steps to reproduce:**
Just open htop from ulauncher and it will be openned from `gnome-terminal`, but my default terminal is Tilix

**Ulauncher version**: v4.1.1.r1
**Linux distro**: Elementary loki 0.4
**Desktop environment**: Pantheon

**Comment by goodwillcoding** [comment]
@yegorf1 how does elementary choose it's default terminal. I only ask because only DE I know Terminal can be looked up is XFCE (using an exo util)

**Comment by yegorf1** [comment]
@goodwillcoding, I changed my default terminal with these commands: 

```Bash 
gsettings set org.gnome.desktop.default-applications.terminal exec tilix 
gsettings set org.gnome.desktop.default-applications.terminal exec-arg '' 
``` 

But ulauncher uses `gnome-terminal` while elemenatery default terminal is `pantheon-terminal`

**Comment by goodwillcoding** [comment]
@yegorf1 yeah I agree with @friday assessment, `org.gnome.desktop.default-applications.terminal` is deprecated for GNOME (or GNOME based DEs). Other DE's have their own magical ways to specify default terminal with various OS workaround in place. The fix @friday suggested is probably the most sane one with some alternative of auto detection ... maybe @yegorf1 or @friday ya wanna take a swing at getting that done?

**Comment by yegorf1** [comment]
@friday's fix looks best in this situation I think. Closing issue for now
