### ISSUE TITLE
Build setup assumes python is Python 2 (not Arch-friendly)

### ISSUE THREAD

**Issue by friday** [Ulauncher/Ulauncher#302]
In Arch and Arch-based distros (possibly others as well) the `python` binary is Python v3. The [AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ulauncher#n22) fixes this, however not for local development.

To fix dev [building](https://github.com/Ulauncher/Ulauncher#build-and-run) for Arch you need to change:
* `/usr/bin/python` to `/usr/bin/python2` in
  * bin/ulauncher
  * setup.py
* `python setup.py` to `python2 setup.py` in
  * dev-run.sh [line 4](https://github.com/Ulauncher/Ulauncher/blob/dev/dev-run.sh#L4)

This is undocumented and takes a little time and frustration to find. I imagine it could stop others from contributing. I think optimally this should be detected from the current system using executable wrappers (bash scripts) instead of executable python scripts. Something like [this](https://stackoverflow.com/a/19489336/633921) is possible too, but a bit ugly imo. #279 should solve this as well.

This issue is in part created for others or myself to find for the (next) time they run into the issue.

**Comment by gornostal** [comment]
I didn't notice that dev env for Arch users is broken. Thanks for notifying about that.
IMO better to migrate to Python 3 (#279) than adding workarounds.

**Comment by gornostal** [comment]
Now it's Python 3 for both stable and dev builds
