### ISSUE TITLE
Subclassing ExtensionResultItem

### ISSUE THREAD

**Issue by jbriales** [Ulauncher/Ulauncher#304]
The ExtensionResultItem states:
> Should be used in extensions.
> Cannot be subclassed there because :func:`pickle.loads` won't work in Ulauncher app

I guess that means we cannot specialize ExtensionResultItem via class inheritance.
Is there any suggested workflow to generate our own specialized cases of ExtensionResultItem?
Is there any expectation that inheritance could be used in the future?

**Comment by friday** [comment]
Do you have a case for why this would be important? I don't see this as something that would benefit a lot of extension devs.

If you want one or more features added to ExtensionResultItem, you could suggest them in new issues, and additionally submit a PR (although wait until #279 is merged).

**Comment by jbriales** [comment]
In my extension I was producing several fixed types of ExtensionResultItem, and I thought subclassing would be a nice way to do DRY code. However I guess there may be constraints why ExtensionResultItem cannot be inherited, so rather than asking for this feature, I was wondering what's the recommended alternative way to define some Item prototype and reuse it.
In the end I defined a set of wrapper functions that create an item given certain input options. That should work fine for me :)

Anyway I will keep in mind the possibility to discuss the addition of specific features to ExtensionResultItem here. Thanks! :+1:

**Comment by gornostal** [comment]
Hi @jbriales 

Have you considered using composition instead of inheritance? I.e. crating a new class that handles instances of ExtensionResultItem under the hood.
Then you can change interfaces of your classes and inherit them however you want.

I'm going to close this issue now. 
Feel free to comment here if you any questions about using `ExtensionResultItem`
