### ISSUE TITLE
Does ulauncher command admit arguments?

### ISSUE THREAD

**Issue by jbriales** [Ulauncher/Ulauncher#307]
I tried `ulauncher --help` in the terminal to see if there were any optional input parameters, but got nothing.
Actually, I was looking for the possibility to pass a certain keyword (for an extension) from the terminal. This would make it possible to associate a system shortcut to a specific ulauncher call (that would go straight to a particular extension).

**Comment by friday** [comment]
There are some flags for [debugging](http://docs.ulauncher.io/en/latest/extensions/debugging.html), and `--hide-window` for starting in the background. Nothing for managing or triggering extensions or changing preferences though. I miss that too.

**Comment by jbriales** [comment]
#312

**Comment by gornostal** [comment]
Closing this one.
