### ISSUE TITLE
App scanner doesn't follow symlinks

### ISSUE THREAD

**Issue by ababak** [Ulauncher/Ulauncher#310]
**Steps to reproduce:**
Place a shortcut to a folder that contains some desktop configuration files into ~/.local/share/applications/
These applications will immediately become available to default application finder but not to Ulauncher

**Ulauncher version**: v4.3.1r4
**Linux distro**: CentOS
**Desktop environment**: xfce

**Logs**:

**Comment by gornostal** [comment]
Thanks for the bug report. I'll look into it...

**Comment by gornostal** [comment]
I wasn't able to reproduce. 

@ababak could you provide the desktop file please?

**Comment by ababak** [comment]
This happens with any desktop file I put into this shortcut folder.
![image](https://user-images.githubusercontent.com/11334363/47496694-4c198100-d860-11e8-9645-063bae773638.png)

**Comment by ababak** [comment]
@gornostal Have you been able to reproduce this?

**Comment by gornostal** [comment]
I've tried this:

1. Create new file `~/.local/share/applications/test.desktop` with content as below
1. Trigger Ulauncher: <kbd>Ctrl</kbd><kbd>Space</kbd>
1. Enter `test` and I was able to see a new item

Preconditions:

* Ulauncher 4.3.1
* CentOS 7-1611 (64bit)

Content:
```
[Desktop Entry]
Name=Test
Exec=echo OK
Icon=org.gnome.Totem
Terminal=true
Type=Application
```

Could you provide logs and the desktop file that you are adding?
I understand that any file doesn't get scanned, but I need to see its content to make sure it's OK.

**Comment by ababak** [comment]
Please try this:

1. Create a new folder: `~/shortcuts`
1. Create a new file `~/shortcuts/test.desktop`
1. Create a symlink in `~/.local/share/applications/` that will point to `~/shortcuts`
1. Try <kbd>Alt</kbd>-<kbd>F3</kbd> to launch a default Aplication Finder and make sure you see the `test` entry
1. Trigger Ulauncher: <kbd>Ctrl</kbd><kbd>Space</kbd> and you'll see no `test` entry

Hope this helps.

**Comment by gornostal** [comment]
I need logs and the file contents.

Thanks

**Comment by ababak** [comment]
I've created a file named `~/shortcuts/test.desktop` with the contents posted in your earlier message.
Unfortunately, I can't find where's the log.
Am I right that you've tried the steps that I described above and it worked fine for you?

**Comment by ababak** [comment]
Here is the command for step 3:
`ln -s ~/shortcuts ~/.local/share/applications/shortcuts`

**Comment by ababak** [comment]
Have you been able to reproduce this?

**Comment by gornostal** [comment]
Hi @ababak 
Yes, I was. Ulauncher doesn't seems to handle symlinks properly.
I'll fix it for the next release, but cannot give any ETA now.

**Comment by ababak** [comment]
Good to know. Thanks for the update.

**Comment by friday** [comment]
This will be fixed in the Ulauncher v6 branch, as this branch has completely rewritten this part or the app (see PR linked above). It won't be released for a while, but we made a tracking issue if you want to be notified #869
