### ISSUE TITLE
Improve internal API for Preferences UI

### ISSUE THREAD

**Issue by gornostal** [Ulauncher/Ulauncher#315]
There's a lof of plumbing when changing or adding to preferences. Each setting has it's own server route as well as getter/setter in Preferences.vue. Couldn't that be changed to one general server route taking an argument for the setting's name? If type sanity is to be upheld, then one getter/setter per type could be used instead (ex `preferences.get_bool("show_recent_apps")` and `preferences.get_string("theme_name")`).

cc @friday

**Comment by friday** [comment]
As of #866 getting merged into the v6 branch it's now going to be much easier to add a new setting. Only a few places to add them to now.

Example: https://github.com/Ulauncher/Ulauncher/pull/868/commits/514408e6dd6aee658ed334141ae3532882de3f59
