### ISSUE TITLE
My extension got removed without me being notified...

### ISSUE THREAD

**Issue by leinardi** [Ulauncher/Ulauncher#318]
Hi, I just find out that one of my extensions got removed without me being notified so currently I don't even know the reason.

The extension removed is this one: https://github.com/leinardi/ulauncher-systemctl

If I had to make a guess is because is very similar to my other extension: https://github.com/leinardi/ulauncher-exit-gnome

The main difference is that one is gnome specific and it uses `gnome-session-quit` and provides logout feature but not suspend feature, the other uses `systemctl` and provides suspend feature but not logout from Gnome feature.

I don't want to merge these two in a single one because than you'll dependent on both Gnome and Systemd.

Do you think I can upload again the systemctl extension?

**Comment by gornostal** [comment]
That's weird because I don't even have functionality to delete extensions.

My only assumption is a bug in the code of ext.ulauncher.io. 

> Do you think I can upload again the systemctl extension?

Yes, absolutely.

**Comment by gornostal** [comment]
I forgot, there's functionality to delete them, but it's only available to a user who added that extension, which is you

**Comment by leinardi** [comment]
Hey thanks for the quick reply. I have re-added it: https://ext.ulauncher.io/-/github-leinardi-ulauncher-systemctl

**Comment by gornostal** [comment]
I've checked the logs. There were no DELETE requests since 2nd of October. I don't have earlier logs.
When did you upload the extension and when did you notice it was deleted?

**Comment by leinardi** [comment]
The extension was added long time ago, around the end of February:
![image](https://user-images.githubusercontent.com/273338/47449989-52f2b600-d7c4-11e8-9449-b2d37884a029.png)
