### ISSUE TITLE
dbus.exceptions.DBusException

### ISSUE THREAD

**Issue by LinArcX** [Ulauncher/Ulauncher#319]
**Steps to reproduce:**
start the app, go to settings, set on __SHOW FREQUENT APP__ and __SHOW INDICATOR ICON__. after one search i can't get back to application and this error rise.

**Ulauncher version**: 4.3.1.r4
**Linux distro**: Arch
**Desktop environment**: i3, gnome

**Logs**:

https://gist.github.com/LinArcX/9cbd2b7a0d8a3aa621d4a04dc905a590

_To get the logs please do the following:_
_* Close the app_
_* Run "ulauncher -v" from the console_
_* Copy output to https://gist.github.com/_
_* Link to the gist here_

**Comment by LinArcX** [comment]
The log:
https://github.com/LinArcX/Ganje/blob/master/Log/ulauncher.log
And yes, if i off those flags, ulauncher works properly.

**Comment by gornostal** [comment]
Thanks for the logs. I'm not sure what could cause that issue.
`SHOW_FREQUENT_APPS` should not be a problem. I'm pretty sure if you turn it on and off it's not going to case any issues.

`SHOW_INDICATOR_ICON` is on by default. Could you try reseting your settings by deleting or renaming `~/.config/ulauncher/settings.json`  and then restarting Ulauncher? I wonder whether that will help or not.

**Comment by gornostal** [comment]
Hi @LinArcX 

There were no updates in this issue for a while and no one else has complained about this.
Please reopen if this issue is still actual for you.

Thanks
