### ISSUE TITLE
Issue with fonts on HiDPI display

### ISSUE THREAD

**Issue by billop** [Ulauncher/Ulauncher#322]
I'm running Arch Linux with KDE, and for some reason the dev version won't build so I was using v4.3.1.r4. On my 4K screen Ulauncher is tiny and the text spacing is off:

![screenshot_20181205_145444](https://user-images.githubusercontent.com/12755239/49549851-d234d880-f89e-11e8-8f06-eab54d1af4dd.png)

![screenshot_20181205_145524](https://user-images.githubusercontent.com/12755239/49549861-d9f47d00-f89e-11e8-868d-50f893fc074c.png)

**Comment by zetorian** [comment]
have you properly set environment variables?
https://wiki.archlinux.org/index.php/HiDPI#GUI_toolkits

**Comment by UnicodeAlt255** [comment]
Yes, I have been using Arch Linux with a 4k screen for several years now and I have it set up for every GUI toolkit except for JavaFX (never figured it out). But a lot of applications account for it themselves, Rofi for example simply has a a dpi variable to adjust for different resolution screens.

**Comment by gornostal** [comment]
@UnicodeAlt255 I'm assuming you've tried GDK_SCALE or GDK_DPI_SCALE, because Ulauncher uses GTK.
I'll come back to this issue once I find a 4k screen.

**Comment by friday** [comment]
Pretty sure now this is caused by `text-scaling-factor` which is separate from the mentioned variables.

Repro instructions: Run this in a terminal and type something (ex "ulauncher") while it's temporarily using `text-scaling-factor` `2` (it reverts back after 10s).

No special screen (or KDE) should be needed.

```sh
scalingfactor=$(gsettings get org.gnome.desktop.interface text-scaling-factor)
ulauncher-toggle
gsettings set org.gnome.desktop.interface text-scaling-factor 2
sleep 10
gsettings set org.gnome.desktop.interface text-scaling-factor $scalingfactor
```

**Comment by gornostal** [comment]
I've recently got laptop with HiDPI screen, Ulauncher doesn't look as bad as on the screenshot thought.
Actually it looks OK, but images are in low resolution. We need to fix that

**Comment by Karrq** [comment]
I'm also using a HiDPI screen with KDE on Arch and I get the [same](https://i.imgur.com/5o6MBwE.png) issue as OP

**Comment by gornostal** [comment]
@Karrq have you tried the solution suggested above by @friday?

**Comment by friday** [comment]
@gornostal It isn't a solution. It's code to reproduce the issue and then revert to your previous settings. 

`gsettings set org.gnome.desktop.interface text-scaling-factor 1` should "solve" it, but then the font will be very small on big displays.

**Comment by gornostal** [comment]
ah, I see.

So then ulauncher has to take into account `text-scaling-factor` by adjusting the font size, right?

**Comment by friday** [comment]
I would say the best case scenario is Ulauncher adjusting the "line height" and possibly other aspects of the size according to the `text-scaling-factor`, to respect user preferences. I'm not too acquainted with GtkBuilder/Glade myself so I don't know how it works.

Making the text smaller so Ulauncher looks consistent not broken (but doesn't respect `text-scaling-factor`) should be an improvement too.

**Comment by gornostal** [comment]
OK. Thanks for the suggestion

**Comment by vyachkonovalov** [comment]
A little hack, but makes look better
```diff
diff --git a/usr/share/ulauncher/ui/result_item.ui b/result_item.ui
index 2fab860..3df4fed 100644
--- a/usr/share/ulauncher/ui/result_item.ui
+++ b/result_item.ui
@@ -58,7 +58,7 @@
                     </style>
                   </object>
                   <packing>
-                    <property name="y">5</property>
+                    <property name="y">0</property>
                   </packing>
                 </child>
                 <child>
@@ -75,7 +75,7 @@
                     </style>
                   </object>
                   <packing>
-                    <property name="y">28</property>
+                    <property name="y">34</property>
                   </packing>
                 </child>
               </object>
```
Apply with
```shell
sudo patch /usr/share/ulauncher/ui/result_item.ui result_item.ui.patch
```
My `GDK_DPI_SCALE=1.66`, so you may need different `"y"` property values.
<details> 
  <summary>Before and after</summary>
  <img src="https://i.imgur.com/FUN1vNk.png" alt="before"></img>
  <img src="https://i.imgur.com/rBxpzMq.png" alt="after"></img>
</details>

**Comment by friday** [comment]
Nice! Should be possible to set those to a value relative to the scaling factor before displaying it imo.
