### ISSUE TITLE
Feature request: Run executables in path via ulauncher

### ISSUE THREAD

**Issue by jbriales** [Ulauncher/Ulauncher#323]
Is it feasible that executables in the path (e.g. /usr/bin) could be found and run via ulauncher?
I used rofi before ulauncher, and it provides this functionality, which I really miss in ulauncher. Actually this is the only reason why I keep rofi and ulauncher installed, but ulauncher now keeps the most convenient shortcut ;)

**Comment by friday** [comment]
Rofi is more CLI and i3wm oriented, while Ulauncher is desktop oriented. Adding all binaries in PATH to Ulauncher would be noisy I think. `compgen -c | wc -l` should show you how many you have. For me it's over 5000. They also don't have icons or descriptive names, so the formatting would not look good. 

This could be supported by an extension (briefly looked into that myself) or a prefix such as `>` (like Albert and Alfred).

**Comment by jbriales** [comment]
Thanks for the explanation! I think you're right. It makes all sense to keep then separate rather than clutter both of them together.

**Comment by jbriales** [comment]
Closing, waiting for a possible extension to cover this use case.
