### ISSUE TITLE
About Ulauncher .desktop search (fuzzy search improvements)

### ISSUE THREAD

**Issue by jbriales** [Ulauncher/Ulauncher#324]
I have created my own .desktop files (in /home/jesusbriales/.local/share/applications/) for some of my command-line applications.
One example is `web-whatsapp`.
When I open Ulauncher and intend to launch this app, writing 'web-w' will already prompt `web-whatsapp` among options to run.
However, the output for other search inputs are a little unexpected to me:
- 'what' -> prompts `Atom`
- 'whats' -> prompts `Photos`, `Tweaks` and `web-thesaurus`
- 'whatsa' -> prompts `web-thesaurus`, `Photos` and `Tweaks`
- 'whatsap' -> prompts `web-thesaurus`, `web-whatsapp` and `web-maps`
- 'whatsapp' -> finally prompts `web-whatsapp` and others after it
So, I know Ulauncher uses some kind of fuzzy search, although I'm not familiar with its details yet.
I was wondering though if the behavior above is right/expectable, as just writing 'what' should be (I think) much closer to `web-whatsapp` than to any other of the options listed by Ulauncher.

**Comment by friday** [comment]
The current behavior is not optimal, but finding what is optimal isn't easy.

There's both matching and scoring/sorting involved. Matching uses the binary name too, so you can type "nautilus" or "eog" to get the file manager and image viewer for Gnome although they've both given different names in the desktop entries. There's also some feature to sort and highlight the most apps you open the most,

If you get these strange matches only for desktop entries you just created, you could try to narrow it down by tweaking them. You may also want to try to close ulauncher and open `ulauncher -v` from a terminal so you see when it detects changes and updates or if it fails to do so.

I'm not sure the behavior is safe if you copy a desktop entry for one app, rename it and change the file after it has been indexed (it seems like the kind of thing that could cause something like this). If restarting Ulauncher doesn't do it, I would try closing Ulauncher and deleting the db files in `~/.cache/ulauncher_cache/` just to be sure. Note that this is based entirely on hunches. I don't know the indexing and db code well.

Btw, you know you can create shortcuts for searching websites, right? It looks a bit like you're doing something similar with `web-thesaurus` and `web-maps`. Shortcuts would avoid one page load and take you directly to the search results.

**Comment by jbriales** [comment]
Hi @friday, thanks for the hints! I'll have a look at it and come back if I get any useful insight.
Also, what do you mean by creating shortcuts for searching websites? That might interest me.

**Comment by friday** [comment]
I don't think this is documented online, but it's in the Ulauncher settings under its own tab. Pretty easy to use.

**Comment by gornostal** [comment]
@jbriales This is related to issue #232.
I'll take the case you described in the description into account when work on fuzzy search improvements.

Thanks

**Comment by friday** [comment]
I consider this to be fixed in the Ulauncher v6 branch (with this PR: #827). It won't be released for a while, but we made a tracking issue if you want to be notified #869
