### ISSUE TITLE
Add "sleep 0.03" to ulauncher-toggle so it waits a bit before it tries to focus on Ulauncher

### ISSUE THREAD

**Issue by gornostal** [Ulauncher/Ulauncher#327]
Add "sleep 0.01" to ulauncher-toggle so it waits a bit before it tries to focus on Ulauncher

**Comment by gornostal** [comment]
Implemented in v4.4.0

**Comment by josiahwitheford** [comment]
Hey there, I am still seeing this issue. Ulauncher will get the focus the first time it is run, but every subsequent attempt it will not get the focus. Modifying the sleep value resets the cycle and the next time ulauncher is toggled it will gain focus.

If I run `ulauncher-toggle` from the command line then it gains the focus every time.

Fedora 33
Kernel: 5.11.11-200.fc33.x86_64
Gnome Version: 3.38.5
Windowing System: Wayland

**Comment by DrewBrunning** [comment]
I've run into this on Ubuntu 22.04; however it's not a ULauncher issue, it was that `wmctrl` wasn't installed. Noting here in case anyone else ends up here trying to find the solution: if you're running into the issue of ULauncher not getting focus with a fresh Ubuntu install check that `wmctrl` is installed and that no other issues are noted if you run `ulauncher-toggle` from the terminal.

**Comment by wflore19** [comment]
I got it working with Ubuntu 24.04

Check if wmctrl is installed
```shell
wmctrl --version
```

If not installed, install it
```shell
sudo apt install wmctrl
```

Set the ULauncher Hotkey setting to something you won't use for any application (I used ctrl+h)
![Image](https://github.com/user-attachments/assets/d3bf649a-f5d6-46c9-8f75-a0aee2e4f813)

Setup Custom Shortcuts in systems settings to open ULauncher:
![Image](https://github.com/user-attachments/assets/c4c99208-c75f-4c6a-9dfc-2d41b2923465)

You can also open it from the terminal with:
```shell
ulauncher-toggle
```

**Comment by andreas-bulling** [comment]
Doesn't work for me unfortunately. ULauncher still doesn't get the focus, I always have to click on the text input field first. Very annoying

**Comment by friday** [comment]
> Doesn't work for me unfortunately. ULauncher still doesn't get the focus, I always have to click on the text input field first. Very annoying

This ticket is from 2018. Several things has changed since then, in particular if you run the v6 beta. Which version of Ulauncher are you using? Which distro and desktop environment?

**Comment by andreas-bulling** [comment]
I am running v5.15.15 on Ubuntu 25.10 with Gnome 49

**Comment by friday** [comment]
> I am running v5.15.15 on Ubuntu 25.10 with Gnome 49

Try v6 (see https://ulauncher.io/#Download) or this extension if you want to keep using v5 https://extensions.gnome.org/extension/5410/grand-theft-focus/

See #1128 for more info

**Comment by andreas-bulling** [comment]
Thanks a lot! I'll give that a try

**Comment by andreas-bulling** [comment]
Worked - thanks a lot! @friday
