### ISSUE TITLE
b *URL* fails to open entire URL

### ISSUE THREAD

**Issue by papermache** [Ulauncher/Ulauncher#329]
**Steps to reproduce:**
open ulauncher
type b *URL*
hit enter
browser opens and only partially completes URL.

**Ulauncher version**: v4.1.0r1
**Linux distro**: Linux Mint 19 Cinnamon 4.15.0-43-generic
**Desktop environment**: Cinnamon

**Logs**:

_To get the logs please do the following:_
_* Close the app_
_* Run "ulauncher -v" from the console_
_* Copy output to https://gist.github.com/_
_* Link to the gist here_
![ulauncher](https://user-images.githubusercontent.com/2126012/50540702-af77a600-0b64-11e9-9aeb-33b873af6cfd.png)

**Comment by friday** [comment]
v4.1.0r1 is 6 months old by now. You should get the latest version before reporting bugs in case your problem has been fixed. You also haven't attached any log (it's in the instructions), and you didn't mention this is a problem with a specific extension (seemingly [Open in Browser](https://ext.ulauncher.io/-/github-manulaiko-ulauncher-openinbrowser)). Ulauncher doesn't have any "b" shortcut (and the extension doesn't use this by default either).

So, please upgrade Ulauncher, Python2 and the extension to the latest versions. If the issue remains, report this for the extension ([here](https://github.com/manulaiko/ulauncher-openInBrowser/issues/new) if it's "Open in Browser") instead.

The author probably wants to know the output of `python --version` and if this works for you:

```
python -c "import webbrowser; webbrowser.open_new_tab('https://www.facebook.com')"
```

**Comment by papermache** [comment]
Problem solved!
