### ISSUE TITLE
Suggestions: Move or remove the extension preferences UI buttons

### ISSUE THREAD

**Issue by friday** [Ulauncher/Ulauncher#330]
The buttons "Save", "Remove" and "Check Updates" are not visible for some extensions with many preferences or keywords, until you scroll down (all 3 of the extensions I've published).

I'd argue that the "Save" button is not needed. The main settings doesn't have any such button, so it's inconsistent. I also think that "save" buttons in preferences is generally an abandoned praxis (at least for MacOS, GTK and Pantheon user) and considered dated and cumbersome. The extension event for preferences changing is triggered once per setting changed, so it would work on focus out without changing the API. In addition pressing "enter" inside of an input field doesn't save any changes it seems.

"Remove" and "Update" could be replaced with icons (like 🗑 and ↺) and moved either to the top right corner next to the date and hash (which makes me think you planned to put the update button there all along). They could also be moved next to each extension in the list to the left and shown once you hover (like the shortcuts UI), or both.

Both of these have interactive steps of course, but the same mechanism could still work if moved to the header (though perhaps the header would need more space).

**Comment by gornostal** [comment]
Good suggestions. Thanks @friday

**Comment by gornostal** [comment]
I've modified the UI. Now it's one button and a drop-down menu.

I've decided to keep Save, otherwise it's not clear when Ulauncher should trigger `PreferencesUpdateEvent`

There are still a few UX issues with editing extension preferences (IMO, it's not super clear that Update and Delete buttons are hidden under that arrow ▽), but that's for another time.

**Comment by gornostal** [comment]
Implemented in 5.3.0
