### ISSUE TITLE
Ulauncher window closes unexpectedly during query

### ISSUE THREAD

**Issue by jbriales** [Ulauncher/Ulauncher#337]
**Steps to reproduce:**
IF upon triggering Ulauncher the mouse pointer is over the Ulauncher floating window
AND after entering some query the window size changes (because of a smaller number of items)
AND the mouse pointer falls out of the Ulauncher floating window area,
THEN the Ulauncher window will close "unexpectedly".

Does this make sense? If some of the missing information below is important I can reproduce it later (I'm writing this on a rush).

**Ulauncher version**: TODO
**Linux distro**: Fedora28
**Desktop environment**: i3-gnome

---

**For contributors**

Introduce a new CLI option `--keep-on-focus-out`, which disables keeps the ulauncher window visible even if it receives focus out event.

**Comment by gornostal** [comment]
Hi @jbriales 

There's `focus_follows_mouse` setting in i3, which by default is set to `yes`.
You may want to set it to `no` to fix the issue.
More info here https://i3wm.org/docs/userguide.html#_focus_follows_mouse

Hope that helps. Please reopen the issue if needed.

**Comment by troycurtisjr** [comment]
Are you saying that you'd prefer to keep focus follows mouse as incompatible with ulauncher? 

This setting is one of the biggest things I miss when I have to work on Mac and Windows. Would you consider an option to not close when ulauncher loses focus? I think there are several explicit actions which can cause ulauncher to hide already: hitting Enter to select an option, Esc to cancel, etc.  

Such an option would allow ulauncher to work with focus follows mouse (and sloppy focus as mentioned in issue #58 ), and would also allow for the use case described in #459 .  Additionally I suspect it would address #242.

Finally, this is not an unusual setting, and as mentioned in this Issue, it is the default for i3 with is definitely a power user WM (which I would argue is a similar demographic as ulauncher itself).

**Comment by troycurtisjr** [comment]
Additionally it might address #364 as well.

**Comment by ToxaZ** [comment]
@troycurtisjr sure. Especially considering that my wrapper no longer working for new version. I haven't done much research on that, but now the code I wrote is useless.

**Comment by gornostal** [comment]
@troycurtisjr @ToxaZ I've reopened this one.

Added details to the description about a new CLI option that prevents window from hiding.

**Comment by gornostal** [comment]
Just released v5.9.0 that has a new setting:
![image](https://user-images.githubusercontent.com/1202543/99916045-4547eb80-2d10-11eb-8509-5cf4eed798c5.png)

Thanks @troycurtisjr for the PR!
