### ISSUE TITLE
Suggestion: Replace Disqus with deeper GitHub integration

### ISSUE THREAD

**Issue by friday** [Ulauncher/Ulauncher#348]
The Disqus comments are [frustrating me](https://ext.ulauncher.io/-/github-friday-ulauncher-clipboard#comment-4341058340). Most of them seem to be variants of "It doesn't work" or similar vague and not very helpful complaints. Some of them are commenting on other extensions (some extensions share the same Disqus page as others so comments for one extension will show up for others - maybe this is only for older extensions though) or possibly Ulauncher issues (like #192). Others haven't installed dependencies that were specified in the GitHub readme of the extension. Most of them don't seem to follow up on comments if you reply. Additionally extension authors have to subscribe to each of their extensions boards to get notified about comments, which I don't think many are aware of and/or do.

GitHub has similar features such as issues and stars that are better for productive and constructive communication than the emoji votes and comments Disqus has imo (and you can also reuse the title and description). It lets extension authors manage the info properly in one place, and unlike Disqus comments outdated or invalid issues can be closed.

Some problem I see:
1. It makes it harder to handle competitors like GitLab and Bitbucket (if this should be of interest in the future)
2. It needs more work on the extension server to keep the data in sync or cache API requests.
3. Since this means the GitHub repo owners are in control, this also means they can disable the issue page or mismanage / censor unwanted information of course, but I don't think this will be a real problem.

**Comment by gornostal** [comment]
Looking at things like Google Play, Chrome Web Store, and other market places I see that a common approach is to have some sort of rating system and a way to report an issue.
I think that approach makes sense for Ulauncher extensions too.

The following steps should be taken to migrate:
1. Make Disqus comments read-only for some period of time
1. Add "Report Issue" button to an extension page on the website and in the Ul. Preferences. It will take a user to Github issues of that ext.
1. Use Github stars as extension rating. That should also solve a problem of sorting extensions (currently they are sorted from new to old)
1. Finally turn off Disqus completely

Items 1 and 2 are relatively easy. I'll try to do that soon.
Item 3 requires some amount of codding (frontend and backend). I'm going to define the details and try to find contributors who could do that

**Comment by friday** [comment]
Nice work so far! :+1:

**Comment by gornostal** [comment]
Thanks :)
I ran into some issues with Arch build. I hope I can figure out how to fix it on weekends

**Comment by friday** [comment]
I'm in no hurry. I was mostly referring to the new extension pages, though I see you've done a few releases too.

**Comment by gornostal** [comment]
I think we can consider this one as done.

I've created a separate issue to use Github stars as a rating https://github.com/Ulauncher/ext-api.ulauncher.io/issues/6

**Comment by friday** [comment]
Great! I may not be able to take the time to help out for a while, but nice to see things moving :+1:
