### ISSUE TITLE
Search contents of text files, doc and pdf files. 

### ISSUE THREAD

**Issue by wyattbiker** [Ulauncher/Ulauncher#350]
Hello, I just found this and wanted to know if I can use it to search for contents of textfile or PDF or even doc files on my local drive. Similar to Spotlight on Mac OS X.

**Comment by gornostal** [comment]
Hi @wyattbiker 

That type of functionality is not supported and not planned.

Ulauncher extension that indexes and allows searching inside of  files could be a solution for that type of problem. I want to keep the core functionality of Ulauncher to the minimum.
