### ISSUE TITLE
Open file using file browser in background

### ISSUE THREAD

**Issue by 1earch** [Ulauncher/Ulauncher#355]
### Steps to reproduce
1. Search for a file to open using the `~` shortcut
2. Press `<Enter>` to open the file

### Current behavior
The file is opened, but Ulauncher is not hidden until file is closed.

### Expected behavior
The file should be opened in background and Ulauncher should be hidden.

### Environment
**Ulauncher version**: 4.3.2.r8
**Linux distro**: Arch Linux
**Desktop environment**: i3wm

**Comment by gornostal** [comment]
Implemented in 5.3.0
