### ISSUE TITLE
Links in the extension preferences view should open in a browser

### ISSUE THREAD

**Issue by friday** [Ulauncher/Ulauncher#357]
Currently links in the preferences such as [this](https://github.com/brpaz/ulauncher-currency/blob/master/manifest.json#L22) seem to open in the preferences window rather than externally. I think the same solution which is already used for the [Help tab](https://github.com/Ulauncher/Ulauncher/blob/690bc8e3d3edf26a1510409978565549cc7d8b7c/data/preferences/src/components/pages/Help.vue#L6) could be used to fix this.

![ulauncher-ext-prefs-links](https://user-images.githubusercontent.com/515120/54565459-a2818a80-49ce-11e9-9821-0aaccb052443.gif)

**Technical details**
Here's an example of how to open link in a browser: https://github.com/Ulauncher/Ulauncher/blob/dev/data/preferences/src/components/pages/Help.vue#L51-L53

**Comment by gornostal** [comment]
Fixed in 5.4.0. Closing.
