### ISSUE TITLE
Ulauncher Auto Start is Not working throwing Exceptions

### ISSUE THREAD

**Issue by mukeshkrishnan666** [Ulauncher/Ulauncher#359]
`Caught an error while switching "autostart": Unexpected exception: [Errno 17] File exists: '/home/user/.config/autostart'`

Please Let me know what's the how to solve this

**Comment by friday** [comment]
`~/.config/autostart` should be a folder. It seems you have a file there instead. Deleting it probably solves it.

**Comment by gornostal** [comment]
hi @mukeshkrishnan666 
Have you been able to resolve the issue?

Please reopen the bug if it still exists.

Thanks
