### ISSUE TITLE
disable ulauncher if app is focused

### ISSUE THREAD

**Issue by Hero9909** [Ulauncher/Ulauncher#371]
Im developing with the tools of jetbrains, so autocomplete is triggered the same way as i open ulauncher, is there a way to choose action for centrain apps if ulauncher should override the behaviour or not? if none feature like this is avilable please take this as an feature request.

i would appreciate to have the option to white / blacklist an application for override. Maybe this feature would be out of scope, so i would modify either the shortcuts in the tools or the ulauncher shortcut

**Comment by gornostal** [comment]
Hi @Hero9909 

>  is there a way to choose action for centrain apps if ulauncher should override the behaviour or not? 
There's no such possibility in Ulauncher, and I have no plans on adding anything like that.

You can of course choose a different hotkey for Ulauncher, or build a custom trigger script that will call `ulauncher-toggle` only when active window is not Jetbrains IDE. Then you can bind a hotkey to that script via Keyboard settings in your desktop env.

Sorry, I'm going to have to close this issue.
