### ISSUE TITLE
Launchpad error while building deb package for Xenial

### ISSUE THREAD

**Issue by gornostal** [Ulauncher/Ulauncher#373]
Log https://launchpadlibrarian.net/424400587/buildlog_ubuntu-xenial-amd64.ulauncher_5.2.0.r0-0ubuntu1ppa1~xenial_BUILDING.txt.gz

Error
```
The following packages have unmet dependencies:
 sbuild-build-depends-ulauncher-dummy : Depends: debhelper (>= 11~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Looks like the latest `debhelper` version available in Xenial (16.04) is 9. 
It's probably better to use 9 for all builds.

**Comment by fougner** [comment]
Seems like this one should be closed, no? Last failed build in https://launchpad.net/~agornostal/+archive/ubuntu/ulauncher-dev/+builds?build_text=&build_state=depwait was many months ago

**Comment by gornostal** [comment]
Yes, I forgot to close this one.

Thanks @fougner!
