### ISSUE TITLE
Is it possiable to register the commands under global namespace, and not under a prefix?

### ISSUE THREAD

**Issue by rabin-io** [Ulauncher/Ulauncher#375]
I prefer just to type `reboot` and not `sys reboot`

I tried to remove the prefix or use (white)space, but that didn't work.

**Comment by gornostal** [comment]
@rabin-io it's not possible to register global commands programmatically, however you can define all of them in a manifest file as keywords, then handle events appropriately in your extension.

See how it's done in this extension https://github.com/friday/ulauncher-gnome-settings
