### ISSUE TITLE
Programs requiring pkexec don't launch

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [Ulauncher/Ulauncher#382]
I thought this was reported already - at least for Mint's program `mintsources' - but I cannot find that report.

### Steps to reproduce
1. Be on Mint (or some other OS?)
2. Try to run a program that launches via `pkexec`, such as bleachbit or minsources. (Bleachbit is not installed by default in Mint. Also, Bleachbit creates system menu items to run the program as root and as a normal user, respectively. Accordingly, Ulauncher shows two entries for Bleachbit; and only the entry for running as root fails to work.)

### Current behavior

Nothing happens, i.e. nothing is launcher.

### Expected behavior

An authentication window should appear and then, if the user authenticates successfully, the program in question should run.

### Environment
**Ulauncher version**: 4.4.0.r1
**Linux distro**: Mint 19.1
**Desktop environment**: Cinnamon

### Logs

<script src="https://gist.github.com/LinuxOnTheDesktop/b65348955b84303b87976373731997cc.js"></script>

**Comment by friday** [comment]
That's not a log file. Also, what does the `Exec` line say in the desktop entry for Bleachbit? It's probably named `bleachbit.desktop` and located in `/usr/share/applications/`

**Comment by LinuxOnTheDesktop** [comment]
Log file: I was trying to provide the terminal output that your issue template requests. I have done so again [here](https://gist.github.com/LinuxOnTheDesktop/ebe9ac4d521e75f6d69e1a14eeb8a5b3) and (in case there is any problem with that link, which is to a 'gist'), [here](https://pastebin.com/bTjL90xh).

> what does the Exec line say in the desktop entry for Bleachbit?

Relevant parts of `bleachbit.desktop`:

```
TryExec=bleachbit
Exec=bleachbit
Icon=bleachbit
Categories=GTK;System;
Keywords=clean;performances;free;privacy;
StartupNotify=true
```

Relevant parts of the more relevant file, viz., `bleachbit-root.desktop`:

```
TryExec=pkexec
Exec=pkexec bleachbit
Icon=bleachbit
Categories=GTK;System;
Keywords=clean;performances;free;privacy;
StartupNotify=true
```

**Comment by friday** [comment]
That log file gave it away. Seems to be this issue: https://askubuntu.com/questions/608419/trying-to-execute-a-process-with-pkexec-asynchronously-and-get-refusing-to-rend

I'm not the author and maintainer so not sure how easy it is to fix. There's an async decorator that could be causing this, or it's just a matter of switching the method or arguments.

**Comment by gornostal** [comment]
Looking at an answer here https://askubuntu.com/a/721075, I think this issue can be fixed like this:
# before launching an app check if `Exec` starts with `pkexec`
# If it does, create a [tempfile](https://docs.python.org/3/library/tempfile.html) and make it executable
# Set the content of the file to what's suggested in the askubuntu answer 
# Launch the file
# Remove the file

I'll mark this bug as contributor-friendly.

**Comment by gornostal** [comment]
@LinuxOnTheDesktop as a workaround you can create create an Ulauncher Shortcut to launch the script

**Comment by LinuxOnTheDesktop** [comment]
@gornostal 

> as a workaround you can create create an Ulauncher Shortcut to launch the script

Thanks, but there could be a duplication problem - for the programs that Ulauncher fails to launch properly - the pkexec ones - still show up in Ulauncher. So if I want to run, say, Timeshift (which as of Mint 19.3 runs via pkexec), then, if I make a Ulauncher shortcut for it that is called 'Timeshift', then if I type 'Timeshift' in Ulauncher then I will see two entries. If instead I give the shortcut a considerably different name to the original problem, then I will need to remember the new name.

All in all, it seems the workaround is not great. Also, it seems that you yourself outlined a proper fix, above . .

**Comment by gornostal** [comment]
@LinuxOnTheDesktop I didn't get to implementing the fix yet, but I have a better workaround if it's still actual for you:

You can copy .desktop file of Timeshift (it's probably in `/usr/share/applications`) to `~/.local/share/applications` and then edit `Exec` property

**Comment by LinuxOnTheDesktop** [comment]
Thanks, but I have tried that just now and I found that it did not work - no pkexec box appeared. Perhaps I make some mistake. By the way, the file at issue is `timeshift-gtk`, not `timeshift`. The other - older - workaround still works.

**Comment by LinuxOnTheDesktop** [comment]
I managed to get the workaround working, but [this commit](https://github.com/linuxmint/mintmenu/pull/248), from the Mint team (and to Mint), might help others to fix the problem.

**Comment by WhosyVox** [comment]
I took a stab and the closest I could get (with an extra feature of Python 3.8) is the following.
It's a cludge but I can't figure what 'app.launch()' is doing.
This so far seems to work but doesn't suppress all messages to the parent process terminal.
I'll leave it here though, in hope some inspiration or fresh ideas from a more competent Python dev will be able to finally close this issue.

ulauncher/api/shared/action/LaunchAppAction.py
`
            try:
                if (command.startswith("pkexec")):
                    subprocess.Popen(
                        args=shlex.split('sh -c "'+command+'"'),
                        stdout=subprocess.PIPE,
                        stderr=subprocess.PIPE,
                        start_new_session=True
                    )
                else:
                    app.launch()
            except Exception as e:
                logger.error('%s: %s', type(e).__name__, e)
`

**Comment by friday** [comment]
@WhosyVox: Something similar to your suggestion has been added in #778. It's now in the latest release (5.12.0), and I think it will fix this issue too?

**Comment by WhosyVox** [comment]
@friday
I've pulled down the latest change and while I haven't read the code (and it's undoubtedly better than my half-arsed attempt) it does indeed seem to do the job.
I'm sure the folks over at MintCast will be happy to hear about this too, after I'd been singing praises about ULauncher in one of their livestreams.

**Comment by friday** [comment]
Thanks for verifying! I'll close this issue and the PR then :)
