### ISSUE TITLE
Text boxes in the preferences jump to EOL when typing

### ISSUE THREAD

**Issue by tildica** [Ulauncher/Ulauncher#383]
### Steps to reproduce
1. Open the preferences
2. Go to any text box with editable text in it
3. Start typing anywhere before the last character

### Current behavior
Typing a character immediately jumps to the end of text box / end of line.

### Expected behavior
The user should be able to continuously type at the position of the cursor. 

### Environment
**Ulauncher version**: 5.2.0.r0
**Linux distro**: Mint Xfce (latest), Ubuntu Budgie 19.04
**Desktop environment**: Xfce, Budgie

### Details
Text boxes in the settings menu jump to end of line immediately after inserting a character anywhere in the text box. I'm typing "example" and "12345" as test strings (see the .gif). Immediately after typing the first character the text box pushes me to the end of line. So, when I try to type "example" in front of "EM" I get "eEMxample" instead of "exampleEM". This makes editing text (mainly scripts) inconvenient if you need to add a word before what you've already written.
![text issue](https://user-images.githubusercontent.com/46450583/58374470-2c4d5700-7f2e-11e9-981d-fe652880a89e.gif)

**Comment by gornostal** [comment]
Thanks for reporting this bug @tildica

**Comment by Sebastian69** [comment]
I'm also affected by this bug.

**Comment by gornostal** [comment]
Fixed in 5.4.0. Closing.
