### ISSUE TITLE
Install older version?

### ISSUE THREAD

**Issue by kevquirk** [Ulauncher/Ulauncher#384]
## Question
I just installed the latest version of Ulauncher on one of my systems (5.3.0 beta1), but I can't install any of the extensions I use due to them not being updated yet. Is it possible to install a previous working version of Ulauncher instead?

Thanks

**Comment by gornostal** [comment]
Yes, you can install the stable version.
Go to ulauncher.io and select Stable, and then download v4.4.0.r1.

Yesterday there was an issue with downloads and for a short period of time you would see beta version in both stable and dev channels. If you see that now, try refreshing the page with Ctrl+F5 to clear the cache.

If you have any issues with that, please reopen the ticket.

**Comment by kevquirk** [comment]
Thanks. I didn’t actually download the deb, I used the Ubuntu repo. I assume the dev branch isn’t supposed to be in the main repo?

I’ll remove and download the deb, thanks.

**Comment by gornostal** [comment]
I've double checked, the main repo doesn't have dev builds: https://launchpad.net/~agornostal/+archive/ubuntu/ulauncher/+packages

**Comment by kevquirk** [comment]
Not sure what happened then, but I added the PPA, did and update, then apt install Ulauncher and ended up with the beta version.

**Comment by gornostal** [comment]
I see.
Actually I accidentally published beta version to the stable repo yesterday, but I was sure I had deleted the new versions before the build was completed. 

Most likely that was the cause

**Comment by kevquirk** [comment]
Cool. Thanks for clarifying. 👍

**Comment by kevquirk** [comment]
Looks like the repo is still pulling down the beta version:

```
The following NEW packages will be installed
  ulauncher
0 to upgrade, 1 to newly install, 0 to remove and 3 not to upgrade.
Need to get 0 B/1,221 kB of archives.
After this operation, 5,077 kB of additional disk space will be used.
Selecting previously unselected package ulauncher.
(Reading database ... 326034 files and directories currently installed.)
Preparing to unpack .../ulauncher_5.3.0~beta1-0ubuntu1ppa1~bionic_all.deb ...
Unpacking ulauncher (5.3.0~beta1-0ubuntu1ppa1~bionic) ...
Setting up ulauncher (5.3.0~beta1-0ubuntu1ppa1~bionic) ...
```
I'll install manually, but thought you should know.

Thanks

**Comment by gornostal** [comment]
I could not find a way to delete the beta release from the stable repository.
I'm going to try to release a stable version v5, which is going to be the beta1 release + some minor fixes.

Sorry for making you beta testers involuntarily.
