### ISSUE TITLE
Arch Linux: Upgrade ulauncher-git to v5

### ISSUE THREAD

**Issue by friday** [Ulauncher/Ulauncher#385]
For Arch, to upgrade I previously did a development build. This is sort of cumbersome. It hijacked my current installation and I had to delete files/settings in my home dir to restore it (possibly related: Docker didn't work so I was running the Docker commands without Docker).

The Download link for Arch v5.3.0~beta1 https://ulauncher.io/#Download isn't up to date (still has the Python v2 dependencies, `sed` command to replace `python` with `python2` and the old build commands).

Maybe this is the reason you haven't marked #302 as fixed though?

**Comment by materemias** [comment]
the AUR package needs to be updated, [this](https://pastebin.com/vh5LaBKB) is how i got 5.3.0 b1 build with python3

an update is due since python2-levenshtein is gone from arch

**Comment by friday** [comment]
I didn't know that actually. This issue is for the development aur, so I think it's a separate issue. You can probably `sudo pip2 install python-Levenshtein`, though it's more of a workaround imo. Don't like to sudo pip.

**Comment by gornostal** [comment]
Both ulauncher and  ulauncher-git repositories in aur has been updated
