### ISSUE TITLE
Undocumented requirement for SystemExitEvent handler

### ISSUE THREAD

**Issue by psukys** [Ulauncher/Ulauncher#387]
### Is your feature request related to a problem? Please describe
An extension without `SystemExitEvent` subscribed event listener cannot run.

### Describe the solution you'd like

Multiple options:
 - Remove this requirement
 - Document this

### Additional context

When attempting to run the application:
```
2019-05-29 08:09:57,907 | DEBUG | ulauncher.api.client.Extension: trigger_event() | No listeners for event SystemExitEvent
```

**Comment by friday** [comment]
It's not a requirement or an error. Just a debug message. If your extension fails to load it's not because of this.

**Comment by gornostal** [comment]
Closing.

BTW, it's documented here http://docs.ulauncher.io/en/latest/extensions/events.html#systemexitevent
