### ISSUE TITLE
Installing extensions from non-Github repos

### ISSUE THREAD

**Issue by cryobry** [Ulauncher/Ulauncher#388]
### Is your feature request related to a problem?

When I try to install an extension from a self-hosted gogs repo, Ulauncher complains that it is not from github ("The URL must look like this: https://github.com/userName/projectName")

### Describe the solution you'd like

I host my own code in a gogs repo and would like to install a Ulauncher extension I wrote directly from that repo without having to move it to github. IMO the lock-in is not good.

**Comment by friday** [comment]
Unofficial answer:
You can put them in ~/.cache/ulauncher_cache/extensions/
Ex: `git clone git@domain.com:user/your_extension_name.git ~/.cache/ulauncher_cache/extensions/your_extension_name`

You can also create a github mirror. Basically add a new remote for github and push to both (though I suspect you don't want to).

**Comment by cryobry** [comment]
Got it, thanks.
