### ISSUE TITLE
Argument to shell commands get %s instead of the real argument

### ISSUE THREAD

**Issue by ckruse** [Ulauncher/Ulauncher#389]
### Steps to reproduce
1. create a script just echoing the CLI arguments
2. create a shortcut executing that script with `%s`, e.g. `~/test.rb %s`
3. execute that shortcut with an arguments.

### Current behavior

Currently the script gets executed with `'%s'` as the argument. Given this script:

~~~ruby
#!/usr/bin/env ruby

puts ARGV.inspect
~~~

And this shortcut:

![Bildschirmfoto vom 2019-06-01 08-03-28](https://user-images.githubusercontent.com/175095/58744486-c8ea8a00-8443-11e9-9e9b-8664c7e97db4.png)

It outputs `["%s"]`

### Expected behavior

It should print the correct argument.

### Environment
**Ulauncher version**: ulauncher 5.3.0~beta1
**Linux distro**: Ubuntu 18.04
**Desktop environment**: GNOME

### Logs
<https://gist.github.com/ckruse/19a9dc0c11c48240481756d9c26265d7>

**Comment by IgorMael** [comment]
Hum... Thanks god it was not my commit haha
This is also happening on V4.3.2.r8.

It's unintended behaviour? I think I can fix it.
but maybe we will need some form of escape, i don't know

**Comment by cryobry** [comment]
I just ran into this too when trying to execute a shell script.

**Comment by gornostal** [comment]
`%s` can only be used in URLs as a placeholder.
Scripts should use arguments to get the query params. I'll update the example to make this clearer

**Comment by malanvaneck** [comment]
Hi there @gornostal 
I'm actually lost with your statement:
`Scripts should use arguments to get the query params. `

What does that mean?
Does Ulauncher cater for script startup with arguments or not?
If True, could you please give some more examples on how to do so?

Thank you in advance. :-)

**Comment by balazsorban44** [comment]
Was wondering the same as @malanvaneck 

I have the following shortcut script:
```sh
#!/bin/bash
cd projects && cd url-shortener && npm run shorten $1 $2
```
(following this Kent C. Dodds video for creating your own URL shortener: https://www.youtube.com/watch?v=HL6paXyx6hM )

Naming the shortcut "shorten", I would assume that running `shorten https://example.com example` would replace the $1 and $2 with the arguments.

**Comment by friday** [comment]
This is now supported in the Ulauncher v6 branch. V6 won't be released for a while, but we made a tracking issue if you want to be notified #869

**Comment by malanvaneck** [comment]
Yeah! This will be super Awesome! I'm so excited!

**Comment by malanvaneck** [comment]
Thanks @friday

**Comment by lyqide** [comment]
@balazsorban44 as a quick workaround I just found a solution to this (I'm a bit late though...)
I do most of my stuff in private tabs so I wanted to get that working somehow. Long story short - you can use all the arguments like this:
```
#!/bin/bash
args="$@"
firefox --private-window "https://duckduckgo.com/?q=$args"
```
If you create a variable first it should work - at least it did in this case

hope this helps
