### ISSUE TITLE
Enhancement: Using tab to toggle search results

### ISSUE THREAD

**Issue by eyun89** [Ulauncher/Ulauncher#391]
Hi there, 

I was wondering if it was possible to use `tab` and `shift+tab` to toggle through the search results.

Thanks for all your efforts in making this application.  It is a great experience having this as a part of my workflow.

**Comment by gornostal** [comment]
Sorry, it's not possible. Only arrow up/down will work. Or you can use `Alt + <1,2,3..>` to choose a result item.

**Comment by gornostal** [comment]
I'll keep this open. If it receives many thumbs up, I'll consider implementing it.

**Comment by matheusfillipe** [comment]
Once in a while I accidentally hit tab on ulauncher. I would definitely like this to work as well.

**Comment by matheusfillipe** [comment]
Oh, why the reopen? Did I screw something up? :P

**Comment by gornostal** [comment]
No, no.
I'm not closing issues until release is published.

[Travis](https://travis-ci.org/github/Ulauncher/Ulauncher/builds) doesn't want to start building releases for some reason :thinking:

**Comment by gornostal** [comment]
Now release is ready.
The enhancement is available in v5.8.1

Thanks again @matheusfillipe for the PR!
