### ISSUE TITLE
Extensions not started with Ulauncher

### ISSUE THREAD

**Issue by jbriales** [Ulauncher/Ulauncher#392]
### Steps to reproduce
1. Start ulauncher from terminal, i.e. `ulauncher -v` or `ulauncher --dev -v`

### Current behavior
No extensions work, as they all seem to fail to load with ServerIsNotRunningError in the output log

### Expected behavior
Well, ExtensionServer works and extensions work

### Environment
**Ulauncher version**: ulauncher 4.3.1.r4
**Linux distro**: Fedora29
**Desktop environment**: Xfce + i3

### Logs
https://gist.github.com/jbriales/1931970966f359e29fbbd25d746b8b68

**Comment by friday** [comment]
Same issue as #396. Try moving or deleting the .db-files in `~/.cache/ulauncher_cache/`. My guess is one of them (likely `app_stat_db.db` is corrupted).

If that fixes it whatever caused this could happen again I guess. Maybe you upgraded and then downgraded Ulauncher. I think the DB-library is different.

**Comment by jbriales** [comment]
Thanks! I'll try that next time the issue happens. I'll close the issue meanwhile.
