### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by SolarAquarion** [Ulauncher/Ulauncher#394]
File "setup.py", line 12
    print('To build ulauncher you need "python3-distutils-extra"', file=sys.stderr)
                                                                       ^
SyntaxError: invalid syntax

**Comment by friday** [comment]
That's because you're running Ulauncher 5 (which is for Python 3) in Python 2.

**Comment by SolarAquarion** [comment]
Silly me, I forgot to update the build of ulauncher-git

**Comment by SolarAquarion** [comment]
Silly me I forgot to update the pkgbuild of ulauncher-git

**Comment by friday** [comment]
You shouldn't have to imo. I didn't know you were using it. There's a separate issue for that though (#385)
