### ISSUE TITLE
Ulauncher does not start

### ISSUE THREAD

**Issue by VladChekunov** [Ulauncher/Ulauncher#396]
### Steps to reproduce
1. Install package
2. Trying to run from start menu.
3. Trying to run from console

### Current behavior
Ulauncher does not start.

### Expected behavior
Ulauncher will start.

### Environment
**Ulauncher version**: 5.3.0 and 4.4.0.r1
**Linux distro**: Ubuntu 18.04
**Desktop environment**: LXDE

### Logs
https://gist.github.com/VladChekunov/088f464aa0c01648f51b2e26c79ab166

**Comment by friday** [comment]
Try moving or deleting the .db-files in `~/.cache/ulauncher_cache/`. My guess is one of them (likely `app_stat_db.db` is corrupted).

**Comment by VladChekunov** [comment]
Thanks. It's work.
