### ISSUE TITLE
All extensions have stopped after update

### ISSUE THREAD

**Issue by papermache** [Ulauncher/Ulauncher#398]
### Steps to reproduce
1. Run Linux update from Update Manager
2. Open ULauncher
3. Initiate System Management extension with 's' 

### Current behavior
System Management extension returns "Loading. . ."

### Expected behavior
Return option to shut down, sleep, log out, or hibernate.

### Environment
**Ulauncher version**: ULauncher 4.4.0.r1
**Linux distro**: Linux 4.15.0-48-generic
**Desktop environment**: Cinnamon

**Comment by friday** [comment]
Reinstall (remove and add) the extension. If it still happens post an issue to the extension github page with the log output and your distro (Linux 4.15.0-48-generic is your kernel version)

**Comment by papermache** [comment]
Reported.

**Comment by Bananaman** [comment]
> Reinstall (remove and add) the extension and restart ulauncher.

Writing to say thanks from 2022. This was necessary after some recent Ulauncher update which put all extensions in a "Stopped" state. Removing them and adding them again has fixed Ulauncher. I guess there was some change to how metadata about installed extensions is handled in Ulauncher.

**Comment by friday** [comment]
> Writing to say thanks from 2022. This was necessary after some recent Ulauncher update which put all extensions in a "Stopped" state. Removing them and adding them again has fixed Ulauncher. I guess there was some change to how metadata about installed extensions is handled in Ulauncher.

Never ran into this, but it was probably caused by 2022 me, so glad 2019 me could step in and help :+1:

**Comment by Bananaman** [comment]
@friday Hahah. Maybe it was because I was doing a large jump between Ulauncher versions due to not updating my system in a month, so I missed some intermediate updates that may have given a smoother upgrade path. Either way, 2019 you totally solved it! :D Also glad that removing and re-adding extensions still remembered my custom settings in them. Thanks for Ulauncher. I love you. :heart:

**Comment by sanbids** [comment]
same every time i open my laptop or restart my laptop all extensions will be stopped .. what a pain
