### ISSUE TITLE
Shortcuts with both tilda and quotes don't work

### ISSUE THREAD

**Issue by Sebastian69** [Ulauncher/Ulauncher#400]
### Steps to reproduce
Make a shortcut: xdg-open "~/folder name with spaces"

### Current behavior
OS GUI returs an error "Unable to detect the URI-scheme of "~/folder name with spaces".

### Expected behavior
Opens a folder. It does work with this variations:
- xdg-open "/home/user/folder name with spaces"
- xdg-open ~/folderwithoutspaces

### Environment
**Ulauncher version**: 5.3.0.~beta1
**Linux distro**: Ubuntu 16.04.3 LTS
**Desktop environment**: Xfce

**Comment by friday** [comment]
Not a Ulauncher issue. Same command also doesn't work in terminal

These work:
`xdg-open ~/My\ Folder`
`xdg-open ~/"My Folder"`
`xdg-open /home/me/My Folder`
