### ISSUE TITLE
UnhandledError in com.github.brpaz.ulauncher-docker extension

### ISSUE THREAD

**Issue by asm0dey** [Ulauncher/Ulauncher#403]
Message: 'com.github.brpaz.ulauncher-docker'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 192, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3.7/site-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3.7/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 411, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3.7/site-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.brpaz.ulauncher-docker'

```

**Comment by gornostal** [comment]
Thanks for reporting @asm0dey 
I'll check how to properly handle that error in Ulauncher, but there's definitely a bug in the extension, which I recommend reporting to the author's Github

**Comment by friday** [comment]
It's probably just the missing dependency/binary issue https://github.com/Ulauncher/Ulauncher/issues/273#issuecomment-453826067 He might not have docker or some other dependency.

Since it happens so frequently I think it needs to be handled in Ulauncher. If you install an extension without the dependency the dependency settings view will be broken (at least until you reopen).

**Comment by friday** [comment]
Closing this. This should be handled better now so you see an error message with missing python dependencies. If it's a binary dependency you should still see an error message about it. See #767

**Comment by asm0dey** [comment]
Thanks! (I don't remember currently what ulauncher is, but still: thank you for fixing!)
