### ISSUE TITLE
hotkey not working in ubuntu 19.04

### ISSUE THREAD

**Issue by gauravsood1991** [Ulauncher/Ulauncher#406]
**Steps to reproduce:**
CTRL+ single Spacebar
**Ulauncher version**: latest version form the website
**Linux distro**: ubuntu 
**Desktop environment**: 19.04

HotKey not activating the search bar on single CTRL+Spacebar

**Comment by friday** [comment]
Wayland or X11?
This might help: https://github.com/Ulauncher/Ulauncher/wiki/Hotkey-In-Wayland

**Comment by gornostal** [comment]
@gauravsood1991 please reopen if it's still actual for you
