### ISSUE TITLE
Add URL shortcuts to profile

### ISSUE THREAD

**Issue by papermache** [Ulauncher/Ulauncher#407]
### Describe the solution you'd like

I would like to open a URL using a keyword like u instead of just g to search google. I would also like to string the keyword with the Chrome Profiles extension so I can open a URL or search google with a certain profile.

### Additional context
Ideal query: "b u www.theverge.com" opens www.theverge.com using my personal gmail address.

**Comment by friday** [comment]
?

**Comment by papermache** [comment]
Fixed the comment.

**Comment by gornostal** [comment]
@papermache You can do it yourself like this:
![image](https://user-images.githubusercontent.com/1202543/64484284-93122a00-d218-11e9-97da-2fbac1743dbe.png)

I'm not sure how to open urls using a certain profile in Chrome though.

**Comment by papermache** [comment]
Can I add the profile shortcut into the query or script field as an
argument? So if I type "U B www.google.com"  I can select the profile to
open www.google.com if B is the profile shortcut?
