### ISSUE TITLE
Hotkey is showing all hidden windows

### ISSUE THREAD

**Issue by HannanAkbar** [Ulauncher/Ulauncher#409]
![deepin-screen-recorder_Navigator_20190803233810](https://user-images.githubusercontent.com/5216873/62415717-d856a100-b647-11e9-9b2e-4822a4ff095e.gif)

### Steps to reproduce
1. Show desktop / Hide all windows (Super + D)
2. Press Ulauncher hotkey
3. All hidden windows will get restored

### Environment
**Ulauncher version**: 5.3.0~beta1
**Linux distro**: Debian/Deepin
**Desktop environment**: Deepin (Qt)

**Comment by friday** [comment]
That's probably not related to Ulauncher. I'm guessing your distro/DE does that automatically either when any app gains focus, or specifically when the Ulauncher key combo is triggered.

**Comment by gornostal** [comment]
@HannanAkbar have you tried changing the default Ulauncher hotkey? Maybe that's default Deepin's behavior on Ctrl+Space?

**Comment by CrowdSalat** [comment]
I can confirm this behaviour on the same enviroment. Changing the hotkey does not solve it.

But i am also guessing that this is a deepin specific behaviour. If you use ALT + TAB to switch the window after you pressed SUPER + D, deepin will also bring up all old windows and the choosen one on top.

**Comment by friday** [comment]
You have to change the Deepin hotkeys or the Ulauncher hotkey. You're currently triggering two different behaviors with the same key.
