### ISSUE TITLE
Default plugin if no result with cache

### ISSUE THREAD

**Issue by pierrehenrymuller** [Ulauncher/Ulauncher#411]
I have been a Gnome-Do user for more than 10 years and I am looking for a successor since Gnome-Do is no longer supported and no longer available under Debian 10.

Ulauncher is the one that caught my attention after testing quite a few different launchers.

Nevertheless I do not find the strength of Gnome-Do on one point the local file search.

Imagine files scattered in a multitude of directories:
- personal.kdbx
- personal.odt

With Gnome-Do there is no need to launch a shortcut before the search, the latter searches among applications, files and any other plugin with results registration: search / user choice.
This combination is very productive since it is enough to type "perso" so that it associates the opening of the file personnal.kdbx, if I type "personn" it associated this search with my choice of personnal.odt.

I tested the two file search plugins "search files" and "File Search" but these two plugins in stable version 4.4.0.r1 require you to enter the shortcuts s or fd before searching but above all the search is restarted with each request and the result is not saved. This translates into a fairly high latency when there are several tens of thousands of indexed files.

My proposal for improvement would be :

- be able to define a default plugin to launch if no results are found instead of launching a shortcut. Let's say I select the "File Search" plugin that starts with the "fd" shortcut. By selecting it as the default plugin, if I type "custom" and no application matches then the search starts with this plugin and automatically adds its shortcuts in prefix.
Maybe it's possible to launch a plugin with shortcuts but I didn't success.

- in order to make searches more fluid, the search results should be cached by keeping the user choice made for an identical previous query

I look forward to discussing it.

**Comment by friday** [comment]
I think gornostal will answer this saying he wants to keep the scope of ulauncher small enough so it's easier to maintain, and to keep using extensions for file search.

File search is not trivial. You need a daemon to monitor changes and update a db, and if you want really powerful file search you want to index file content and use full text search to query it. And then maybe you'd also want to parse pdf files, word documents etc. You can use third party software to do some of that, but depending on your de/distro it may not be possible. That's probably why there are several search extensions.

You may want to test this one btw: https://github.com/dalanicolai/gnome-tracker-extension It integrates with a couple of third party ones that have their own file databases rather that matching your files every time.

**Comment by pierrehenrymuller** [comment]
Ok I understand the goal to keep UL in KISS mode. This is a good practice to maintain the project over time.

But having a choice in what is proposed by default if there is no result should not be a big problem.

Just designate a default plugin that would replace web search launches.

The possibility to designate for example https://github.com/dalanicolai/gnome-tracker-extension which has the shortcuts lc and when we look for something that does not match an application it starts the search with this plugin by automatically adding (hidden or not) the shortcuts lc as a prefix.

The purpose is to simplify searches when UL is used mainly to search for files.

**Comment by friday** [comment]
We already went down that road #306

**Comment by gornostal** [comment]
@pierrehenrymuller as @friday correctly pointed out the idea of keeping Ulauncher simple is important for me. And it's not only about maintenance, but also about simplicity in how it works.

Regarding the file search, I'm not familiar with the two extensions you've mentioned, but I would suggest looking for an extension that uses `locate` (`man locate`) under the hood. It's works quickly because it uses an index created by `updatedb` (usually it's installed by default on Ubuntu-based systems).
