### ISSUE TITLE
Unexpected API error. KeyError: com.github.brpaz.ulauncher-github

### ISSUE THREAD

**Issue by anibalardid** [Ulauncher/Ulauncher#414]
Hi ! I installed in ubuntu 18.04 ulauncher 4.4.0 r1
I installed some extensions ok, but when I tried to save options of some extensions it show error:
Unexpected API error. KeyError: com.github.brpaz.ulauncher-github

### Steps to reproduce
1. Open ulauncher settings
2. Go to extensions TAB
3. click on GitHub extension 
4. Modify or not some option
5. Click on SAVE

### Current behavior
Unexpected API error. KeyError: com.github.brpaz.ulauncher-github

### Expected behavior
Save options

### Environment
**Ulauncher version**: 4.4.0 r1
**Linux distro**: ubuntu
**Desktop environment**: gnome

### Logs
https://gist.github.com/anibalardid/7b8f25df492b00aff42cb5f60059d725

**Comment by anibalardid** [comment]
It happens also with:
Unexpected API error. KeyError: com.github.brpaz.ulauncher-cheats

Unexpected API error. KeyError: com.github.brpaz.ulauncher-text-expander

Unexpected API error. KeyError: com.github.robertokl.ulauncher-unit-converter

**Comment by friday** [comment]
#273

**Comment by gornostal** [comment]
I've tried ulauncher-cheats and ulauncher-github extensions. Both have dependencies on external packages that users have to install manually.
Ulauncher v4 doesn't have a very good error handling for such cases. It has been improved in Ulauncher v5
