### ISSUE TITLE
Extensions configuration: add a link to the github page (extension Readme)

### ISSUE THREAD

**Issue by arigit** [Ulauncher/Ulauncher#416]
After installing an extension, uLauncher provides it with a simple way to configure its parameter.
For example, file search looks like this:

![image](https://user-images.githubusercontent.com/652673/63212789-7120fe00-c0d7-11e9-9e80-fa38a1f1cd34.png)

The little improvement I suggest is to include there a link to the "github repo" of the extension, specifically: make the extension name "clickable" (or add and ad-hoc clickable 'link' icon right beside the extension name).
When clicking the said link, the browser would open the the extensions "Readme.md" in github which serves the purpose of a 'user manual' of sorts.

Right now, when a question comes on any of the extensions, I have to make a google search to try and find the repo (or go back to ulauncher's site, browse the extension listing, find the extension, copy the github address and manually paste it in the browser to reach the site.

### Additional context

An additional/aligned suggestion would be to add the same link in the "extension page" within the extension browser site, for people to be able to browse the full documentation before installing it.
Graphically:

![image](https://user-images.githubusercontent.com/652673/63212919-f1942e80-c0d8-11e9-978c-a06db28b6448.png)

**Comment by gornostal** [comment]
@arigit In Ulauncher v5 I've improved Extensions page.
If you click on a drop-down menu there where you can navigate to github page from there:
![image](https://user-images.githubusercontent.com/1202543/65234826-000da580-dade-11e9-907d-2d85048ca815.png)

This doesn't solve the problem of having a convenient access to instructions that an extension author may want to show to users. I need to think about how we could solve that problem.

Thanks for the suggestions

**Comment by friday** [comment]
Closing this as it's been mostly fixed, and #805 has an actionable solution for how to include installation instructions.
