### ISSUE TITLE
Don't run in background

### ISSUE THREAD

**Issue by piegamesde** [Ulauncher/Ulauncher#420]
I think that a launcher should not run in background listening for the activation shortcut – this should be the job of the window manager or desktop environment. Thus, I'd like to have Ulauncher exit after it has run a command.

**Comment by gornostal** [comment]
Sorry, it's going to be running the way it is. 
When I type in a query I want to have the fastest response time possible.

Maybe if I implemented Ulauncher in C I would consider this approach, but with Python it's going to be noticeably slower.

**Comment by piegamesde** [comment]
If this is not possible, I'd like to have the option so that Ulauncher doesn't listen for any activation shortcuts. Binding shortcuts globally is not something an application should do, but the window manager. (This is especially relevant under Wayland, where permissions are handled way more strictly).

**Comment by daveriedstra** [comment]
> If this is not possible, I'd like to have the option so that Ulauncher doesn't listen for any activation shortcuts. Binding shortcuts globally is not something an application should do, but the window manager. (This is especially relevant under Wayland, where permissions are handled way more strictly).

This would clean up the "[set the hotkey to something you'll never use](https://github.com/Ulauncher/Ulauncher/wiki/Hotkey-In-Wayland)" stopgap.

**Comment by piegamesde** [comment]
@gornostal Please reopen this issue (or should I create a new one)

**Comment by gornostal** [comment]
@piegamesde there's a feature request for disabling hotkey: #360

You can subscribe to that issue in order to get notifications about any updates
