### ISSUE TITLE
Ulauncher doesn't search local programs

### ISSUE THREAD

**Issue by DJuan33** [Ulauncher/Ulauncher#421]
### Steps to reproduce
1. Open Ulauncher with Super-L key
2. Search a program
3.

### Current behavior

Ulauncher doesn't search in ~/.locale/applications folder 

### Expected behavior

List all .desktop files anywhere

### Environment
5.3.0
Manjaro Linux x86_64
KDE

**Comment by subdavis** [comment]
This doesnt make sense.  Desktop files belong in one of three places

* ~/.local/share/applications
* /usr/local/share/applications
* /usr/local/applications

If you could just put them anywhere, there would be no way to decide override behavior and scanning would take forever.

You can fix your issue by symlinking your stray files into any of those above.

**Comment by slaykachu** [comment]
I wonder why it doesn't search in $PATH as a backup, like say dmenu.

**Comment by subdavis** [comment]
@slaykachu that's a different issue, and it's being discussed @ https://github.com/Ulauncher/Ulauncher/issues/454

**Comment by spicy-hero** [comment]
Ulauncher was working perfectly until today. I have `org.telegram.desktop._3e485da34fc040f9218e3891ecde1e6c.desktop` in `.local/share/applications` 
content are follow
```
[Desktop Entry]
Name=Telegram Desktop
Comment=Official desktop version of Telegram messaging app
TryExec=/opt/Telegram/Telegram
Exec=/opt/Telegram/Telegram -- %u
Icon=telegram
Terminal=false
StartupWMClass=TelegramDesktop
Type=Application
Categories=Chat;Network;InstantMessaging;Qt;
MimeType=x-scheme-handler/tg;
Keywords=tg;chat;im;messaging;messenger;sms;tdesktop;
Actions=quit;
DBusActivatable=true
SingleMainWindow=true
X-GNOME-UsesNotifications=true
X-GNOME-SingleWindow=true

[Desktop Action quit]
Exec=/opt/Telegram/Telegram -quit
Name=Quit Telegram
Icon=application-exit
```

ulauncher is unable to launch telegram, but if this file is moved to `/usr/share/applications`, it launches fine.
