### ISSUE TITLE
Nothing shows up in Ulancher

### ISSUE THREAD

**Issue by Brandters** [Ulauncher/Ulauncher#422]
**Steps to reproduce:**
Unable to search for anything. The app starts as it should but nothing shows up.
I've cleared the cache but it doesn't help, also reinstalled both python and Ulauncher but to no avail.

**Ulauncher version**: 4.0.7.r5
**Linux distro**: Ubuntu 19.04
**Desktop environment**: Gnome

**Logs**:

_To get the logs please do the following:_
_* Close the app_
_* Run "ulauncher -v" from the console_
_* Copy output to https://gist.github.com/_
_* Link to the gist here_https://gist.github.com/Brandters/ac904ceae042a5887cbc06e64884212c

**Comment by gornostal** [comment]
It looks like the shortcuts config file is not a valid JSON file.
It's located at `~/.config/ulauncher/shortcuts.json`. 
You can try to fix the issue manually or delete it (ulauncher will replace it with a default config on the next run)

Hope that helps
