### ISSUE TITLE
Unexpected error occured while installing extension

### ISSUE THREAD

**Issue by lalitmee** [Ulauncher/Ulauncher#423]
### Steps to reproduce
1. Open Add extension
2. Get the URL of extension from extensions page Ulanucher
3. Paste URL and enter

### Current behavior
Not installing the Extension

### Expected behavior
Should install the Extension properly

### Environment
**Ulauncher version**: Ulauncher v5.3.0~beta1
**Linux distro**: Linux Mint 19.2
**Desktop environment**: GNOME

### Logs

[Link to Gist](https://gist.github.com/lalitmee/289bb426480e959cc4e990aa5ca30210)

**Comment by gornostal** [comment]
> CERTIFICATE_VERIFY_FAILED

That's 100% a user error. Github certificates are valid
Possible causes:

1) Invalid time set on your machine
2) You are at work and your network has overrides all SSL certificates with custom (untrusted) ones

**Comment by gornostal** [comment]
You can try to set proxy server to bypass the network restriction
See how here https://wiki.archlinux.org/index.php/Proxy_server#Environment_variables

**Comment by gornostal** [comment]
ah, I forgot one more
The most probable cause is outdated certificate installed in you system. Try `sudo update-ca-certificates`
