### ISSUE TITLE
Won't start under wayland

### ISSUE THREAD

**Issue by luispabon** [Ulauncher/Ulauncher#426]
So I'm trying out ulauncher as it would be mint to be used under Sway as an app launcher instead of Rofi which is X11 only.

### Steps to reproduce
1. Install latest from ppa
2. Try to run on a pure wayland session (no `GDK_BACKEND=x11`)

### Current behavior
```
~ ulauncher

/usr/lib/python3/dist-packages/ulauncher/main.py:8: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk

                    [!]
        Looks like you are in Wayland session
        Please run Ulauncher with env var
        GDK_BACKEND set to 'x11' like this:

        GDK_BACKEND=x11 ulauncher
```

### Expected behavior
Starts and works.

### Environment
**Ulauncher version**: 5.3.0.beta1
**Linux distro**: Ubuntu 19.04
**Desktop environment**: Sway 1.2

### Logs
No logs (see above).

**Comment by friday** [comment]
https://github.com/Ulauncher/Ulauncher/wiki/Hotkey-In-Wayland

**Comment by luispabon** [comment]
So that's why wayland start is disabled. It is of no consequence in sway however since one registers hotkeys into commands, for what `ulauncher-toggle` handily exists.

Removing entirely the section in main.py that exits the app at that point so far causes no weird side effects in sway and app works perfectly natively in wayland as far as I can tell. Running the app like that for now - perhaps I could send in a PR that makes that code block bypassable via a startup option?

**Comment by friday** [comment]
It's quite late here so I'm not sure I'm following, but I think what you're asking about is what's been discussed in #363 

You may want to read that first, and I'd suggest also asking @gornostal about his opinion about adding that flag before putting much work on a PR. He's the creator and maintainer, so it's his call.

**Comment by luispabon** [comment]
Ahh I see, yes this is it.

**Comment by gornostal** [comment]
I'm closing this issue. I'm going to remove code that forces users to run ulauncher inX11 compatibility mode under Wayland. See my comment in https://github.com/Ulauncher/Ulauncher/issues/363#issuecomment-532312952

**Comment by luispabon** [comment]
Copy that, thank you @gornostal

**Comment by varac** [comment]
> I'm going to remove code that forces users to run ulauncher inX11 compatibility mode under Wayland. 

@gornostal Is there any issue that tracks this removal ? I'd like to use ulauncher natively with sway/wayland and don't know how/if this is even possible.

**Comment by gornostal** [comment]
@varac please subscribe to updates in #363. I'll prioritize it
