### ISSUE TITLE
Manifest updates have no effect on extension updates

### ISSUE THREAD

**Issue by luispabon** [Ulauncher/Ulauncher#427]
### Steps to reproduce
1. Make an example extension, make sure there is at least 1 preference (eg `keyword` type)
2. Install it in ulauncher
3. Edit manifest.json and add another preference (eg `input` type)
4. Update extension in ulauncher

### Current behavior
The new preference is not shown on the extension config, nor is it available to fetch at the `extension.preferences` dict during events.

Only deleting and re-adding the extension fixes it.

### Expected behavior
The opposite of that.

### Environment
**Ulauncher version**: 5.3.0 beta1-0ubuntu1ppa1~disco
**Linux distro**: Ubuntu 19.04
**Desktop environment**: Sway

### Logs
No errors on the log.

**Comment by gornostal** [comment]
Fixed in v5.5.0

Closing
