### ISSUE TITLE
Can't input multiline shortcut scripts

### ISSUE THREAD

**Issue by magthe** [Ulauncher/Ulauncher#428]
### Steps to reproduce
1. Enter config tab for adding shortcuts
2. Press the "Add shortcut" link
3. Try to type multiple lines into the "Query or Script" text box

### Current behavior

All text ends up being on a single line, there is no effect at all when pressing enter/return key.

### Expected behavior

That pressing enter/return would insert a newline, thereby making it possible to input scripts.

### Environment
**Ulauncher version**: 5.3.0 beta 1
**Linux distro**: Arch Linux
**Desktop environment**: Gnome

### Logs

I doubt the logs are that important for this issue, but they can be found at https://termbin.com/5yjq

**Comment by gornostal** [comment]
I've tried in Manjaro linux, but could not reproduce this issue.
I also have the same version of GTK+ 3.24.10.

Not sure how I can help with this...

**Comment by magthe** [comment]
What do you press in order to insert a newline? I've tried with `enter`, `shift+enter`, `ctrl+enter`, nothing produces a newline.

I've also attempted writing the script in an external editor, copying the lines and then pasting. That also results in a single long line.

**Comment by magthe** [comment]
Would you guide me to adding a shortcut manually, I'm guessing I'll put it in `~/.config/ulauncher/shortcuts.json`, but I don't really know the format. What would a shortcut for the example script look like?

```sh
#!/usr/bin/env node
// query is passed as a first argument
console.log("Query is:", process.argv[1]);
```

**Comment by gornostal** [comment]
@magthe could you attach a screenshot please?

**Comment by gornostal** [comment]
@magthe also try to update to the latest version. I doubt that it will help, but worth trying anyway.

I remember someone reported a bug like this, but it has been fixed long time ago

**Comment by magthe** [comment]
Indeed, an upgrade to 5.3.0 (no beta) solved it.
