### ISSUE TITLE
Bug - Draw over Gnome Shell apps

### ISSUE THREAD

**Issue by phillip-white-jarden** [Ulauncher/Ulauncher#430]
## Question
When trying to toggle Ulauncher with ctrl + space, it doesn't pop up on gnome shell apps. Running Ubuntu 18.04. It pops up under most apps. With gnome apps like terminal and settings, it doesn't pop up.

Any fix for this?

**Comment by gornostal** [comment]
That sounds like a bug. 
@phillip-white-jarden could you please update the description filling in a bug template?

**Comment by phillip-white-jarden** [comment]
Bug report [here](https://github.com/Ulauncher/Ulauncher/issues/434)
