### ISSUE TITLE
Ulauncher can't draw over the top, or pop up on top of Gnome Shell apps

### ISSUE THREAD

**Issue by phillip-white-jarden** [Ulauncher/Ulauncher#434]
### Steps to reproduce
1. Run Ulauncher with GDK_BACKEND=x11 ulauncher (for wayland). Or run Ulauncher from the desktop shortcut. (both don't draw over gnome shell apps)
2. Press shortcut keys to launch

### Current behavior
Ulauncher does not draw over gnome shell apps such as terminal or files. Ulauncher toggle draws over the top, however the keyboard input is not in focus, one has to click inside Ulauncher to type when using toggle.

### Expected behavior
Ulauncher draws over the top, or pops up on top of gnome shell apps.

### Environment
**Ulauncher version**: 5.3.0
**Linux distro**: Ubuntu 18.04
**Desktop environment**: Gnome / Ubuntu

### Logs
[here](https://gist.github.com/phillip-white-jarden/2f73f053060670a3300dac29c82ce70e)

**Comment by gornostal** [comment]
@phillip-white-jarden did you install `wmctrl` as it's described here? https://github.com/Ulauncher/Ulauncher/wiki/Hotkey-In-Wayland

**Comment by phillip-white-jarden** [comment]
Ok. My bad. Didn't read that. It works with wmctrl and toggle, or x session. Thanks!
