### ISSUE TITLE
When laptop is connected to 2nd monitor, ulauncher appears, only, on 2nd monitor

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [Ulauncher/Ulauncher#435]
**Steps to reproduce:**
Boot computer (laptop) with second monitor attached.
Invoke ulauncher with keyboard shortcut.
Have mouse pointer on 2nd monitor.
ulauncher appears, only, on the second monitor.

What should happen: ideally, there should be a ulauncher option that detemines whether ulauncher will appear (1) on all monitors or (2) on the default monitor only or (3) on the currently selected monitor. Second-best would be for scenario 1 - or indeed scenario 2 - to occur, without a choice. At present 3 occurs. I find 3 counter-intuitive. For consider: the keyboard, with which one typically invokes ulauncher, may be far from the second monitor.

**Ulauncher version**: 5.3.0; extension API 2.0.0
**Linux distro**: Mint 19.2
**Desktop environment**: Cinnamon

**Comment by gornostal** [comment]
Rendering on all monitors is not an option for me. I've created a feature request #437 which, when implemented, will allow to select between options 2 and 3 that you've described.
