### ISSUE TITLE
Add a new setting to select where Ulauncher should appear: default monitor or the one with a mouse pointer

### ISSUE THREAD

**Issue by gornostal** [Ulauncher/Ulauncher#437]
Add a new setting in preferences called "Render On" and a dropdown list of two options "Monitor with a mouse pointer", "Default monitor".

Use "Monitor with a mouse pointer" as a default setting.

**Comment by nikazooz** [comment]
Hi @gornostal :slightly_smiling_face: 
I'd like to tackle development of this feature if that's OK?
I don't have much experience with python or desktop applications, but I think I'll be able to find my way around it. :smile:

**Comment by gornostal** [comment]
@nikazooz thanks a lot for this improvement! :+1: 
The code changes look good. I've merged them in. I'm going to close the issue with the next release

**Comment by gornostal** [comment]
The feature is now available in Ulauncher v5.6.0
