### ISSUE TITLE
Ubuntu PPA is missing the Eoan package

### ISSUE THREAD

**Issue by leinardi** [Ulauncher/Ulauncher#438]
The Beta of Ubuntu 19.10 is out and it would be nice to have it supported in the official Ulauncher PPA so that can easily installed and updated.

**Comment by leinardi** [comment]
Ubuntu 19.10 was released the 17th but still no PPA for Ulauncher :cry:.

**Comment by gornostal** [comment]
Added support with 5.4.0 release. Closing.
