### ISSUE TITLE
Need to press activating key twice on Gnome 3.34

### ISSUE THREAD

**Issue by abbyck** [Ulauncher/Ulauncher#440]
### Steps to reproduce
1. Install Gnome 3.34 with Dash to Dock extension on Wayland.
2. Set Ulauncher activation keys to ctrl + space combination
3. use the set combination to invoke Ulauncher

### Current behavior
* After pressing invoke combination, the launcher appears for an instant with the Dash to Dock extension. After that both disappears. Then you have to use the combination again to make the launcher stay visible.

### Expected behavior
* After pressing invoke combination, the launcher should appear and it should stay visible.

### Environment
**Ulauncher version**: 2
**Linux distro**: Arch Linux
**Desktop environment**: Gnome 3.34

### Logs
https://gist.github.com/abbyck/0b8c8d656e76690682a50f3c0f6d85f8

**Comment by gornostal** [comment]
> Set Ulauncher activation keys to ctrl + space combination

@abbyck are you using these steps to set the hotkey in Wayland? https://github.com/Ulauncher/Ulauncher/wiki/Hotkey-In-Wayland

BTW, you mentioned you are running ulauncher version 2. It's way too old.
