### ISSUE TITLE
Search in English when user types in some other language/layout

### ISSUE THREAD

**Issue by neluzhin** [Ulauncher/Ulauncher#442]
Every user who uses more than one language faces one problem: we oftenly forget to switch to English from our language. For example I live in Russia and I use 2 languages every day: Russian for texting with people in messengers and English for everything else (my Linux is in English too).

So when I'm triggering Ulauncher from any messenger I'm starting typing in Russian and it's very annoying because Ulauncher can't find anything.

That's what will happen if I type "Tel":

![image](https://user-images.githubusercontent.com/12474739/65978961-3c95b580-e47d-11e9-81e1-728b8e34e167.png)

That's what will happen if I type "Еуд" (same buttons on my keyboard, but I forgot to switch layout):

![image](https://user-images.githubusercontent.com/12474739/65979166-7ff02400-e47d-11e9-8fde-23fba148ba57.png)

That's how keyboard with Russian layout looks like:

![image](https://user-images.githubusercontent.com/12474739/65979352-ce9dbe00-e47d-11e9-9a42-cbd5d2a41a73.png)

I suggest start searching in English when user types non-latin letters. This is very popular feature implemented in tons of software, for example Google Search, Telegram and JetBrains IDEs know how to search if user forgot to switch layout. 

Example from JetBrains IDE:

![image](https://user-images.githubusercontent.com/12474739/65979990-f5102900-e47e-11e9-85a9-4b948b362e1e.png)

**Comment by gornostal** [comment]
Sorry I'm going to have to close it.

If we implement this feature it will bring too much unnecessary complexity to the code base. I prefer keeping ulauncher simple.
