### ISSUE TITLE
is there system wide configuration file ?

### ISSUE THREAD

**Issue by changchichung** [Ulauncher/Ulauncher#446]
### Describe the solution you'd like
I want to install this nice tool for all clients with some extesions , but so far , looks like there's no system wide configuration file. 
is it possible to add configuration file in /etc , and when user  launchers ulauncher at the first time , read the settings (shortcuts,hostkeys,install extensions if not exists ) and customize ulauncher ?

**Comment by gornostal** [comment]
There's no such possibility @changchichung.

You can move `~/.config/ulauncher/*.json` files to `/etc` and then symlink them to `~/.config/ulauncher` for each user, but then users won't be able to change preferences because files will be read only
