### ISSUE TITLE
Question about the dependence

### ISSUE THREAD

**Issue by gapplef** [Ulauncher/Ulauncher#449]
## Question
![ulauncher](https://user-images.githubusercontent.com/5604665/66533402-59994b00-eb45-11e9-98e2-d94c06703ebd.png)
Why build tools (autoconf, automake, autotools-dev) still need for the binary package.

**Comment by gornostal** [comment]
Ulauncher doesn't depend on autoconf, automake, etc.
The list of dependencies you can see by running `dpkg -I ./packagename.deb`

It's the dependencies of dependencies that bring those packages in.

**Comment by gapplef** [comment]
Turn out these are the depends of `python3-distutils-extra`, which is tool for building python module.
Is it necessary for Ulauncher at runtime?

**Comment by gornostal** [comment]
No Ulauncher doesn't depend on that package. Unless you want to build ulauncher from source

**Comment by gapplef** [comment]
This is what I got:
![Screenshot](https://user-images.githubusercontent.com/5604665/71807552-81e20880-30a6-11ea-966b-0e8c43aace51.png)
you can see the `python3-distutils-extra` in depends of Ulauncher

**Comment by gornostal** [comment]
Hmm indeed.
I'm going to check why...

**Comment by gornostal** [comment]
At first I didn't notice that it's used in Ulauncher.
I've created a separate ticket to remove this dependency: #500 
We only need two small utility functions from it, so I hope it's going to be quite easy

Closing this issue.

**Comment by gornostal** [comment]
@gapplef it's good you pointed this out :+1: 
Ulauncher will bring much less stuff if we remove this dependency

**Comment by gapplef** [comment]
@gornostal  Thanks for your work!
