### ISSUE TITLE
Handle shutdown / lock / suspend

### ISSUE THREAD

**Issue by arthurlogilab** [Ulauncher/Ulauncher#450]
### Steps to reproduce
1. launch ulauncher
2. activate it
3. type shutdown, press enter

### Current behavior

Nothing happens

### Expected behavior

The computer to shutdown. 

For Lock and Suspend the actions/icons aren't even found (no gnome session? only mate-settings-deamon running) 

### Environment
**Ulauncher version**: v5.3.0
**Linux distro**: Ubuntu
**Desktop environment**: awesomewm https://awesomewm.org/

**Comment by friday** [comment]
https://ext.ulauncher.io/-/github-leinardi-ulauncher-systemctl

**Comment by gornostal** [comment]
@arthurlogilab there are plenty extensions for that.

Thanks for the link @friday

**Comment by arthurlogilab** [comment]
Thanks @friday and @gornostal. Installing that extension. 

The work around I found was to add shortcuts : 

![Screenshot from 2019-11-19 11-03-45](https://user-images.githubusercontent.com/445200/69137085-55553b80-0abc-11ea-9632-e57ba6da7dab.png)
