### ISSUE TITLE
Hide window on launch

### ISSUE THREAD

**Issue by jonhoo** [Ulauncher/Ulauncher#451]
Currently, the ulauncher window is immediately shown when ulauncher is first run. This is awkward when you start ulauncher at boot, since you don't generally want the launcher window to immediately pop up unnecessarily. It'd be good if there was a `--no-splash` option to suppress the window from showing on launch.

**Comment by gornostal** [comment]
Hi @jonhoo 
There's `--hide-window`.

**Comment by jonhoo** [comment]
Ah, excellent! Is that documented anywhere?

**Comment by gornostal** [comment]
Only in `ulauncher --help`

Usually users don't need to know that this option exists, because if you use "Launch at login" checkbox in Ulauncher Preferences, it'll add `--hide-window` to the startup command automatically

**Comment by gortegasolis** [comment]
Hi. ulauncher --help works if ulauncher has not been started.
