### ISSUE TITLE
Shortcut + Args history

### ISSUE THREAD

**Issue by ralawa** [Ulauncher/Ulauncher#452]
### Is your feature request related to a problem? Please describe

I use Ulauncher to launch a bash script which mounts some sshfs volumes. I use a shortcut (mount) which launch the script mount.sh with the volume name as argument. 
It works fine but when I'm starting to type the shortcut name, Ulauncher suggests only the shortcut without any args, so everytime I have to type the complete shortcut with the argument. 

### Describe the solution you'd like

I would have liked Ulauncher to suggest the history of my commands with the arguments and classified by popularity. It would then be easier to select the right command with the arrows.

**Comment by gornostal** [comment]
Sorry I will close this feature request because I prefer to keep ulauncher and its code base as simple as possible. This feature requires lot of changes if done properly.
