### ISSUE TITLE
Some actions don't execute when returned from ItemEnterEvent handler unless keep_app_open is True

### ISSUE THREAD

**Issue by pbkhrv** [Ulauncher/Ulauncher#453]
First, thank you for making Ulauncher. I've been having a lot of fun writing extensions recently. Bumped into the following undocumented behaviour (or bug?). Not sure about the right way to address it, but it feels like a bug.

### Steps to reproduce
1. Create an extension that returns `ResultItem` with `on_enter=ExtensionCustomAction(some_data)`

https://github.com/pbkhrv/ulauncher-demo-ext/blob/master/main.py#L37-L44

2. In `ItemEnterEventListener.on_event` return `OpenAction` or `OpenUrlAction` (didn't test with others)

https://github.com/pbkhrv/ulauncher-demo-ext/blob/master/main.py#L49-L53

3. Run the extension, trigger the custom action, watch `OpenAction` or `OpenUrlAction` not get executed

Demo extension that demonstrates this behavior is here: https://github.com/pbkhrv/ulauncher-demo-ext

### Current behavior
`OpenAction` or `OpenUrlAction` returned from event handler doesn't get executed UNLESS `keep_app_open` is set to `True` in `ExtensionCustomAction` constructor

### Expected behaviour
Actions that don't require Ulauncher window to stay open (like OpenAction etc) arguably shouldn't require `keep_app_open=True`, or at least this behaviour should be documented.

Upon further debugging, it appears that a call to `DeferredResultRenderer.on_query_change()` sets active_controller to None, which ends up preventing the action.run() from being called due to `if` statement here https://github.com/Ulauncher/Ulauncher/blob/master/ulauncher/api/server/DeferredResultRenderer.py#L57

### Environment
**Ulauncher version**: 5.3.0
**Linux distro**: Ubuntu 18.04
**Desktop environment**: Gnome (whatever the default is in Ubuntu)

**Comment by gornostal** [comment]
@pbkhrv did you delete your fork of ulauncher-demo-ext?

I've just tried to follow your steps to reproduce, but didn't see any issues.

Please reopen if it's still actual for you.
