### ISSUE TITLE
Is it possible to run bash scripts (that are in PATH) without creating .Desktop or creating Ulauncher-specific shortcuts?

### ISSUE THREAD

**Issue by chetcuti** [Ulauncher/Ulauncher#454]
Is it possible to run bash scripts that are in your PATH via Ulauncher without having to create a .Desktop file or create a Ulauncher-specific shortcut? Based on [this issue](https://github.com/Ulauncher/Ulauncher/issues/289) it sounds like it is, but I can't get it working.

The reason I don't want to have to have to create a .Desktop file or a Ulauncher-specific shortcut is because I have 600+ bash scripts, so both of these options are quite the undertaking, and I would really prefer to not have to perform these extra steps for future bash scripts as well.

Other launchers have this functionality but I _really_ prefer Ulauncher, so I'm hoping this is possible and I'm just overlooking something.

Ulauncher version: 5.3.0
Linux distro: Mint 19.2
Desktop environment: Xfce

**Comment by gornostal** [comment]
No, Ulauncher can't be used like that.

However, I found an extension that seem to solve the problem you've described: https://ext.ulauncher.io/-/github-james-dumas-ulauncher-run

I haven't tried it thought

**Comment by gornostal** [comment]
As another alternative, you can create a simple Ulauncher Shortcut that will run the command:
![image](https://user-images.githubusercontent.com/1202543/71782859-8398c700-2fe7-11ea-9f1f-777c1b3a3fd0.png)

**Comment by chetcuti** [comment]
I appreciate the response, but unfortunately neither of those solutions really do the job. With the first solution I'll need to remember every single command (I'm looking to have the launcher index and remember them), and the second solution would be very time-consuming and the UI gets pretty slow when you start to add that many shortcuts, which is why I ruled it out in my initial post.

As much as I love Ulauncher and would have preferred to use it over alternatives, unfortunately I've had to make the switch to rofi so that I can automatically index my bash scripts.

**Comment by gornostal** [comment]
> and the second solution would be very time-consuming and the UI gets pretty slow when you start to add that many shortcuts

What do you mean? It's just one shortcut called "run" with keyword `r`. Then you open ulauncher and enter `r your-command`. That's it

**Comment by chetcuti** [comment]
> What do you mean? It's just one shortcut called "run" with keyword r. Then you open ulauncher and enter r your-command. That's it

I was referring to creating official Ulauncher Shortcuts, where I would need to create an entry for each script. Not only would that mean creating 600+ shortcuts, but with the way the Ulauncher UI is laid out I would need to scroll down through 600+ shortcuts in order to add a new one.

With your suggestion of creating a run shortcut that uses "r" to run scripts, you then still need to remember the exact names of every one of your bash scripts, whereas with launchers that actually index the scripts, they'll appear on a list when you start typing them, so you don't have to remember the exact names of every single bash script.

**Comment by gornostal** [comment]
@chetcuti I see what you mean.
I have no plans on adding support for executables from `$PATH`.

You may want to check out the extension I've linked above. Maybe it has autocompletion for scripts. I would solve a problem with remembering their names.

**Comment by rileyrg** [comment]
Was just here looking for the same. May I ask why you dont allow running utlities from $PATH? it seems quite convenient.

**Comment by gornostal** [comment]
@rileyrg the main objective was too launch desktop apps. Also, there are many other apps that focus on rubbing command line utilities. I personally user Guake for that.
