### ISSUE TITLE
An option not to hide ulauncher window when unfocused

### ISSUE THREAD

**Issue by Sebastian69** [Ulauncher/Ulauncher#459]
### Is your feature request related to a problem? Please describe
E.g. when using integrated calculator it's annoying when ulauncher window disappears immediately after switching to another window from where you are reading numbers to calculate. 

Same thing when other window steals focus, for some reason.

### Describe the solution you'd like
Having a checkbox in options to disable default window hiding when ulauncher window is unfocused.

**Comment by gornostal** [comment]
Sorry I will close this feature request because I want to keep ulauncher and its code base as simple as possible. 
If you want ulauncher to stay active when it looses focus you probably need another program to solve that particular problem (like a calculator).
