### ISSUE TITLE
Feature request: Ulauncher history - configurable number of items

### ISSUE THREAD

**Issue by uffejakobsen** [Ulauncher/Ulauncher#460]
It would be nice if Ulauncher had a configurable number of history items that is displayed 

Currently only the last 3 items are displayed (reachable with ALT+number)
A configurable lenght would be really nice to have
Ofcourse only the first 9 ot 10 items would be reachable through ALT+number - but that would be acceptable I think :-)

---

**Technical details**
1. Change "Show Frequent Apps" setting from checkbox to an input. Use `0` as default value
1. For backward compatibility, if `show-recent-apps` setting is set to `True`, use `3` as a value
1. Update `UlauncherWindow.py` so it uses the number (look around line 332)

**Comment by gornostal** [comment]
I think we can do that.
I hope a kind contributor will come across this ticket and submit a PR :)

**Comment by IgorMael** [comment]
I can do that, just give a day or two.

**Comment by G-i-o** [comment]
> I can do that, just give me a day or two.

I second this request. Has it been done by any chance? I don't seem to see it in the current release, v5.7.5

Thank You!

**Comment by mewejo** [comment]
Could this be implemented like Alfred, where you can just push the up arrow (like shell too) to go through the history? I'm willing to have a go, having never written Python, if I can find where to start!

**Comment by G-i-o** [comment]
Big kudos to the devs for implementing this. 🎩 🎩 🎩 🙏🙏🙏

**Comment by gornostal** [comment]
Implemented in 5.8.0

Big thanks to @DraggonFantasy for the PR!
