### ISSUE TITLE
Feature request: quit pseudo command

### ISSUE THREAD

**Issue by uffejakobsen** [Ulauncher/Ulauncher#461]
It would be nice with a quit pseudo command..
So that you could quit Ulauncher from the command line within Ulauncher itself. 
Most equivalent launchers have such facility (Kupfer, GnomeDo etc)

**Comment by gornostal** [comment]
Sorry, I'm going to close this one as there are multiple ways to close Ulauncher.
I prefer keeping the code base simple when possible
