### ISSUE TITLE
Fedora 30 & 31 Releases?

### ISSUE THREAD

**Issue by holmanb** [Ulauncher/Ulauncher#462]
### This ticket is a just to notify you that the fedora releases are outdated.

It looks like you are [currently producing releases](https://github.com/Ulauncher/Ulauncher/releases/) for Fedora 28 & 29.  Fedora 28 is no longer supported, 29 looses support at the end of the month, and Fedora 30 and now 31 are released. 

I know that the Fedora release cycle is quite fast, but it would be really nice if you supported the current releases of Fedora.

**Comment by Stoiker** [comment]
Second that. I recently installed the Fedora29 rpm on Fedora31 and the ulauncher setting window stays blank.

**Comment by karklinsv** [comment]
Fedora 31: Cannot open ulauncher on empty desktop and also while Files is active. Works on other applications, Chrome for example.
Cannot also open setting window from any location, just opens blank border and stuck on it.

**Comment by holmanb** [comment]
I'm happy to help if assistance is desired testing new RPMs on Fedora.

**Comment by voneAbides** [comment]
Same problem on Fedora 31. Opening settings shows blank white windows.

**Comment by karklinsv** [comment]
After switched from Wayland to X11, everything works fine on Fedora31

**Comment by gornostal** [comment]
I've updated builds for Fedora. You can download a new version from https://ulauncher.io and it should work in Fedora 30 and 31.

**Comment by voneAbides** [comment]
It's working! Good job.
