### ISSUE TITLE
Ability to rearrange shortcuts

### ISSUE THREAD

**Issue by aleksandar-todorovic** [Ulauncher/Ulauncher#463]
### Is your feature request related to a problem? Please describe

Let's say that I randomly smash my keyboard with the purpose of triggering "no results found" screen. I'll see the list of shortcuts as defined in the settings: Google search will be triggered by <kbd>Alt</kbd> + <kbd>1</kbd>, StackOverflow by <kbd>Alt</kbd> + <kbd>2</kbd>, Wikipedia by <kbd>Alt</kbd> + <kbd>3</kbd> etc.

As far as I can tell, there's no way to rearrange those shortcuts that doesn't involve re-adding the ones I want to have the higher digit associated with. So, for example, if I want to trigger them in this specific order, using <kbd>Alt</kbd> + their digit:

1. DuckDuckGo
2. Wikipedia 
3. Google 
4. StackOverflow

...I'd presumably have to delete all the shortcuts, followed by re-creating them in that specific order.

### Describe the solution you'd like

In the Settings -> Shortcuts tab, items should be drag-and-droppable. So, to achieve that list, I'd add a custom DuckDuckGo shortcut, drag it to the top, drag Wikipedia's shortcut below it and I'll be done. 

### Additional context

N/A

**Comment by gornostal** [comment]
Sorry, I'm going to close this one.

The default search feature is used very rarely and I'd prefer keeping the UI and the code as simple as possible.
