### ISSUE TITLE
Fuzzy search within custom RenderResultListAction?

### ISSUE THREAD

**Issue by iago-lito** [Ulauncher/Ulauncher#465]
## Question
If my keyword is `kw` and I return a `RenderResultListAction` from my custom extension, say the list:
- mya
- myb
- myc

I can see that typing `kw mb` in Ulauncher bar highlights my custom items like:
- __m__ y a
- __m__ y __b__
- __m__ y c

But it does not actually remove any from the list, so `mya` is selected if I hit enter.

I would expect the fuzzy search to automatically filter out my items to:
- __m__ y __b__

instead.

Is fuzzy search enabled by default on `RenderResultListAction`? Or is it my responsibility to implement it?  
If it is my responsibility, what event can I subscribe to in order to update my `RenderResultListAction` on each newly typed character?

Or maybe I have misunderstood the purpose of `RenderResultListAction`?

Thank you for this great launcher anyway :)

**Comment by gornostal** [comment]
Hi @iago-lito 

Fuzzy search doesn't work with results generated by extensions.
Extension developers choose order in which results appear.

**Comment by iago-lito** [comment]
Okay, I understand :)

If I want to do it myself then, what event should I subscribe to in order to update my custom order while the user it typing?
Is there something like a `OnNewCharacterTypedEvent` or a `Every100MsEvent`? (I probably could do it myself, but I'd rather do things right if there's a dedicated way ;)

**Comment by friday** [comment]
Sam event @iago-lito 
http://docs.ulauncher.io/en/latest/extensions/events.html#keywordqueryevent

**Comment by iago-lito** [comment]
@friday I understand that this `KeywordQueryEvent` is only triggered after the whitespace when typing `keyword<whitespace>`, is it right? It would not be triggered on every subsequent character typed.

The idea is to udpdate the list on every new keystroke when typing `keyword<space>n.e.w.k.e.y.s.`, or even few milliseconds. So I'd need an event that is triggered more frequently than `KeywordQueryEvent`. Is there such one?

**Comment by friday** [comment]
> I understand that this KeywordQueryEvent is only triggered after the whitespace when typing keyword<whitespace>, is it right?

No. It's triggered every time the query changes as long as it matches your keyword.

**Comment by friday** [comment]
Also, this extension does exactly what you describe: https://github.com/noam09/ulauncher-gnome-control-center

**Comment by gornostal** [comment]
The question has been resolved I suppose.
Closing the issue.
