### ISSUE TITLE
I had to create a new user and now a .desktop file is not showing

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [Ulauncher/Ulauncher#468]
## Question

I have a file `netflix.desktop` in `/myUsername/launchers`. Previously - with my old user account - that file would show in Ulauncher (when I typed 'netflix' into the latter). Now it does not. Please advise.

Ulauncher 5.4.0
Linux Mint 19.2 Cinnamon

**Comment by friday** [comment]
Move it to ~/.local/share/applications/ maybe?
