### ISSUE TITLE
No extensions folder

### ISSUE THREAD

**Issue by ogulec** [Ulauncher/Ulauncher#470]
I got an error when I try to add extensions, it gives me `urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>` I gave up searching solutions for this problem, I guess this is a common ssl problem for Linux Mint 18.3 because I can not install cinnamon spices applets to desktop also due to this error.
Therefore, I try to install extensions manually but there is no extensions folder in `~/.cache/ulauncher_cache/`. I created and downloaded the right version of an extension to this folder but not shown in the list. Refresh button is not working as well. I can not use any extension.
Any help is appreciated.

**Comment by brpaz** [comment]
Regarding extensions folder, extensions have moved to ```~/.local/share/ulauncher/extensions ```.
Not sure when this happened, I guess with the new Ulauncher v5. I discovered it the other day too.

**Comment by ogulec** [comment]
Thanks for the help, there was no extensions folder in `~/.local/share/ulauncher/` as well. I created and `git clone` some extensions, now it works like a charm.
Now another issue is when I command `sudo ulauncher -v` the extensions are working correctly but when I just launch ulauncher without sudo and -v parameter, the extensions are stopped or chrashed.
Any idea?

**Comment by gornostal** [comment]
@ogulec as @brpaz correctly pointed out the extension folder has been moved. Why did you expect it to be in `~/.cache/ulauncher_cache/`? Asking because I want to make sure I've updated this everywhere in  the documentation.

**Comment by gornostal** [comment]
> urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

@ogulec that sounds like an issue with invalid root certificates. Try `sudo update-ca-certificates`

If that doesn't help, you are probably using proxy or there's something else in the middle between you and Github that alters HTTPS traffic.

Please reopen if needed.
