### ISSUE TITLE
Replacement for Jira Extension

### ISSUE THREAD

**Issue by mjmayer** [Ulauncher/Ulauncher#471]
It looks like the Jira extension is for an old version of Jira. @lkc0987 has [forked](https://github.com/lkc0987/ulauncher-jira) a version of the extension that seems to work with modern versions of Jira.

What are the procedures to have the Jira extension listed on the extension pages to be updated to a different repo.

**Comment by brpaz** [comment]
You have to give a different name to the extension and upload it as a new one. Or you can try to contact the owner of the original extension and see if is willing to integrate the code or adding the author of the fork as a maintainer to original repo.

**Comment by lkc0987** [comment]
although i did fork the extension and make changes, it has a lot of stuff hard-coded in there for my use cases.. and I'm not as good at python so it might have issues too.

**Comment by gornostal** [comment]
ext.ulauncher.io is not flexible enough to solve this issue. 
I've created a separate issue for this https://github.com/Ulauncher/ext.ulauncher.io/issues/6
