### ISSUE TITLE
Is it possible twice ctrl hits to call ulauncher?

### ISSUE THREAD

**Issue by Deleted-Account** [Ulauncher/Ulauncher#472]
Thanks for your great work.

I'm just wondering is there any way to call Ulauncher with twice hits of ctrl?

**Comment by friday** [comment]
You can bind `ulauncher-toggle` with your desktop environments built in keybinder or a third party one.

**Comment by VanDeAnna** [comment]
> You can bind `ulauncher-toggle` with your desktop environments built in keybinder or a third party one.

Thanks. I'm gonna give it a try.
