### ISSUE TITLE
Allow to install extensions from a specific git branch / tag

### ISSUE THREAD

**Issue by mat1010** [Ulauncher/Ulauncher#473]
### Is your feature request related to a problem? Please describe
To be able to use different versions of an ulauncher extension, I would like to install them by using their git branch / tag name.

Trying to install an extension with their branch / tag name currently results in the following error:

`2019-12-09 09:26:37,394 | ERROR | ulauncher.ui.windows.PreferencesUlauncherDialog: on_scheme_callback() | GithubExtensionError: Invalid GithubUrl: https://github.com/user/ulauncher-extension/tree/some-branchname`

### Describe the solution you'd like
Allowing tags / branches in addition to the master repo would be great

### Additional context
With this feature it would be much easier to release testing versions of an extension and also allow easier testing of the whole installation process within a new version of an exstension

**Comment by sebw** [comment]
I would be also interested in branch support, it would ease the development process.

**Comment by gornostal** [comment]
@sebw for development and debugging it's much easier to clone your extension to `~/.local/share/ulauncher/extensions/`. Then you can switch branches easily with git

@sebw @mat1010 apart from debugging, are there any other use-cases when you would want to install extension from a specific branch?

**Comment by mat1010** [comment]
Like described initially, it would also make it easier to have users be able to use other versions of an extension without having them to clone it manually to the correct location on their system.

**Comment by gornostal** [comment]
Sorry, I'm going to close this one.

I prefer not to add new features when it's possible and especially when there's an alternative way of solving the issue, like cloning the specific branch or forking the repo.
