### ISSUE TITLE
Hotkey Cannot set Super + Space as hotkey.

### ISSUE THREAD

**Issue by nodefive** [Ulauncher/Ulauncher#475]
Super works with all a-z keys, but not in combination with space, so one can't mimic osx's behavior. If that is implemented/fixed would be great!

**Comment by nodefive** [comment]
Hey Friday! I don't know why I did thought of that. I've used  the desktop environments keybinder. Working A-OK now. Thank you brother.

**Comment by mitjafelicijan** [comment]
> Ulauncher is using libkeybinder for this. If it doesn't work it's either their concern or your keyboard can't detect those keys in combination because of ghosting.
> 
> You can use use your desktop environments own keybinder or a third party one and bind to `ulauncher-toggle` to work around any restrictions with libkeybinder.

I have tried adding it via Keyboard shortcuts in Gnome and it does trigger it but does not focus on search input of ulancuher.

![DeepinScreenshot_select-area_20200916232914](https://user-images.githubusercontent.com/296714/93394460-8c2ee600-f874-11ea-8c3c-82a8a642b92e.png)

![DeepinScreenshot_select-area_20200916233028](https://user-images.githubusercontent.com/296714/93394523-a7015a80-f874-11ea-89ca-b23b7f5ceb3f.png)

**Comment by skang0601** [comment]
FYI for future folks make sure you have wmctrl installed on your system. ulauncher-toggle relies on that to focus ulauncher when running from the ulauncher-toggle script.

**Comment by Ademking** [comment]
> FYI for future folks make sure you have wmctrl installed on your system. ulauncher-toggle relies on that to focus ulauncher when running from the ulauncher-toggle script.

Thank you! It works
