### ISSUE TITLE
Add Ulauncher to Flathub - no need rebuild for new Fedora releases

### ISSUE THREAD

**Issue by voneAbides** [Ulauncher/Ulauncher#478]
Please, add Ulauncher to Flathub. Currently app does not work on Fedora 30 and 31.

**Comment by gornostal** [comment]
Sorry, but I'm not planning on supporting Flatpak or Snap anytime soon.
The main reason is this will be yet another ulauncher distribution I need to maintain. I'd rather kepp RPM and DEB builds up-to-date.

**Comment by niyumard** [comment]
I'd like to ask you to reconsider this as not everyone is using a Debian/Redhat based distro and maintaining just a flatpak is enough for Fedora, Ubuntu, Debian, Solus, Gentoo, Arch, Manjaro, etc.
It will make the community grow, which will ultimately lead to better growth in terms of bug reports, pull requests, new extensions etc.
It would be very nice if you could reconsider this decision.
If you don't want to deal with flatpaks, an AppImage goes a long way too in terms of adding support to a whole lot of distros.

**Comment by friday** [comment]
@niyumard If you want to volunteer to help us with packaging, this is the place to discuss that:
https://github.com/Ulauncher/Ulauncher/discussions/categories/packaging

If you just have opinions about what we should do, then this helps no one. Unless you offer to help out with your time then it won't further the situation.
