### ISSUE TITLE
Open the desktop file location instead of launching the application.

### ISSUE THREAD

**Issue by Sraw** [Ulauncher/Ulauncher#484]
### Is your feature request related to a problem? Please describe
Sometimes I want to find the location of the desktop file for a specific application. It would be better to be able to directly open the desktop file or open the location.

### Describe the solution you'd like
It is surely possible to be implemented as an extension, but I think it would be easier to be implemented directly in Ulauncher as with or without this feature, Ulauncher always needs to find the desktop files.

**Comment by gornostal** [comment]
Sometimes I also want to find a location of the app, I just open it with ulauncher and then look up the path to .desktop files in ulauncher logs.

I prefer keeping ulauncher simple. I'm going to close this one. Sorry
