### ISSUE TITLE
visibility clues to window

### ISSUE THREAD

**Issue by ak1dd** [Ulauncher/Ulauncher#485]
I want to have the ulaunch window match my system theme... probably pretty common.  That said, I am only allowed to change the background to a single color - I wind up looking for the little gear icon sometimes when other windows with a matching theme are behind.   How about some kind of indicator for the window?   Maybe allow a separate border color?  Or something cool like a bracket on the outside upper left (or right) corner?  Maybe extend 50 or so pixels down and the same to the right/left?

Anyway, thanks for a big missing part of my desktop

### Is your feature request related to a problem? Please describe
A clear and concise description of what the problem is.

### Additional context
Add any other context about the feature request here.

**Comment by gornostal** [comment]
I'm not sure what problem are you asking to solve here.

The gear icon is not visible enough? Or the window doesn't match the OS theme?

**Comment by gornostal** [comment]
Could you attach a screenshot of what you have there, please?

**Comment by friday** [comment]
https://docs.ulauncher.io/en/latest/themes/themes.html and #342 should cover this
