### ISSUE TITLE
[Arch] Ulauncher crashes on start because of the missing Levenshtein library

### ISSUE THREAD

**Issue by gornostal** [Ulauncher/Ulauncher#488]
In Arch linux some python packages are installed into `/usr/lib/python3.7/site-packages` and some in `/usr/lib/python3.8/site-packages`. Levenshtein and pyinotify (mabye some others too) are installed into Python 3.8, which causes ulauncher to crash because the default python interpreter is 3.7.

**Comment by gornostal** [comment]
Fixed by adding `/usr/lib/python3.8/site-packages` to path. Not sure if it's a good solution, but it was the only one I could think of and it works

**Comment by gornostal** [comment]
Fixed in 5.4.1

**Comment by Kalagon** [comment]
That sounds suspiciously like a partial upgrade. Are you sure that you have properly upgraded your system?
All `python-` packages in the official repos have been rebuilt with Python 3.8 and you should have manually rebuilt ones from the AUR.

This fix will be borked once Python 3.9 or 3.10 comes around.

**Comment by gornostal** [comment]
> This fix will be borked once Python 3.9 or 3.10 comes around.

I know.

> Are you sure that you have properly upgraded your system?

I don't know. I'm not an expert in Arch. I did `sudo pacman -Syu`

> you should have manually rebuilt ones from the AUR.

hmm... I would never thought of that. Is this a known thing in Arch community?

**Comment by Kalagon** [comment]
> > Are you sure that you have properly upgraded your system?
>
> I don't know. I'm not an expert in Arch. I did `sudo pacman -Syu`

That _should_ have updated all your repo packages and set Python 3.8 as default interpreter. 

> > you should have manually rebuilt ones from the AUR.
> 
> hmm... I would never thought of that. Is this a known thing in Arch community?

Yup. That's the main thing differentiating the AUR from repo packages. You have to manage them yourself. This implies that you also need to remember to rebuild them if their interpreter changes.
It's the first thing noted on the AUR [Wiki Page](https://wiki.archlinux.org/index.php/Arch_User_Repository#Installing_packages).

If you are using a helper like yay, you can usually do this with a single command: `yay -Syu --devel --rebuildtree`
This will scan and rebuild _all_ AUR packages. You could also specify the `python-` packages from the AUR individually and rebuild them to save some time.

**Comment by gornostal** [comment]
Ah but ulauncher doesn't depend on any AUR packages. Does change what I would need to do to avoid the issue?

**Comment by Kalagon** [comment]
No, that's just general stuff.

Ulauncher shouldn't have this issue on a properly upgraded machine. In fact, none of my machines had this issue.
The only thing needed to rebuild in this case is Ulauncher itself.

**Comment by gornostal** [comment]
> none of my machines had this issue.

That's good to know. Then I probably misunderstood why ulauncher was flagged as `out-of-date` in AUR. I assumed it was because of the thing with python3.7 & 3.8 package situation.

Well, I'll keep the code change for now. We'll see how it will go with migration to future versions
