### ISSUE TITLE
can't build from AUR 10-01-2020

### ISSUE THREAD

**Issue by ak1dd** [Ulauncher/Ulauncher#502]
Trying to install on new install of Manjaro.   

As described on https://ulauncher.io/#Download
`Run git clone https://aur.archlinux.org/ulauncher.git && cd ulauncher && makepkg -is`

```
==> Making package: ulauncher 5.6.0-1 (Fri 10 Jan 2020 01:13:53 PM PST)
==> Checking runtime dependencies...
==> Missing dependencies:
  -> libkeybinder3
  -> python-pyinotify
  -> python-levenshtein
  -> python-websocket-client
==> Checking buildtime dependencies...
==> Missing dependencies:
  -> python-distutils-extra
==> ERROR: Could not resolve all dependencies.
```

**Comment by gornostal** [comment]
I've just tried on Manjaro and it works for me.

Did you do system upgrade recently? If not I'd suggest to do that first.

I the problem repeats, it's better to look for answers on stackexchange because it's not related to Ulauncher.
