### ISSUE TITLE
Extension item name is not displayed if it contains "&" symbol

### ISSUE THREAD

**Issue by gornostal** [Ulauncher/Ulauncher#506]
### Steps to reproduce
1. Install extension https://github.com/friday/ulauncher-gnome-settings
2. In ulauncher type in `Power`

### Current behavior
Item name is empty

### Expected behavior
Item name should say "Power & Battery Settings"

### Environment
**Ulauncher version**: 5.6.0
**Linux distro**: Ubuntu 19.10
**Desktop environment**: Gnome

**Comment by friday** [comment]
This was new to me. Haven't been using the extension in Ulauncher v5

**Comment by gornostal** [comment]
Noticed it yesterday just as I was about to make another release. Luckily the fix was quick.

Fixed in v5.6.1
