### ISSUE TITLE
User-friendly window title, instead of a placeholder

### ISSUE THREAD

**Issue by wsdfhjxc** [Ulauncher/Ulauncher#507]
This is a feature request for a minor change that could improve UX for some folks.

The title of the Ulauncher's GTK window is set to "Ulauncher window title", which looks like a placeholder, since normally it isn't supposed to be displayed anywhere, so the user can't see it.

There are some situations where the title is visible though. For example, when using extensions displaying active window title in the panel and the like. In such cases, it'd be great to see a more sophisticated window title for Ulauncher, for example "Launch an application" or something like that.

**Comment by wsdfhjxc** [comment]
Nice, thanks!

**Comment by gornostal** [comment]
Fixed in v5.6.1
