### ISSUE TITLE
GNOME Shell adds Ulauncher to the dock, top bar with 5.6.1

### ISSUE THREAD

**Issue by elcste** [Ulauncher/Ulauncher#508]
I'm using the .deb packages from the Github release on Ubuntu 19.10 (GNOME Xorg). 

Since I installed version 5.6.1, an entry for Ulauncher shows up in the Ubuntu dock when the launcher is visible. GNOME Shell also shows "Ulauncher" in the top left, like it's a focused app. Here's a screenshot:

![Screenshot from 2020-01-21 07-55-05](https://user-images.githubusercontent.com/915687/72810880-1bbbc080-3c24-11ea-80bb-5a7c504ee79b.png)

When I downgrade to 5.6.0, these issues are gone.

Thanks for Ulauncher btw :-D

**Comment by hrozan** [comment]
Hi, same problem here.
I'm using Linux Manjaro 19 with GNOME 3.34 and Ulaucher 5.6.1

![UlacucherBug](https://user-images.githubusercontent.com/16821536/74767933-7ddd0500-5266-11ea-8574-cec6483abfeb.png)

**Comment by mrbvrz** [comment]
sama problem, using elementary-os hera. 

![Screenshot from 2020-02-19 19-29-14](https://user-images.githubusercontent.com/3890123/74834536-2dd96d80-534e-11ea-8d2d-86e3f1c47688.png)

**Comment by gornostal** [comment]
The regression was introduced while fixing #444. Reverting that change now

**Comment by hrozan** [comment]
Hello, I have just update to 5.7.0 and now it's work fine, thanks :+1:

**Comment by gornostal** [comment]
Cool. Thanks for confirming @hrozan

**Comment by mrbvrz** [comment]
I just updated, and now it works. thanks :thumbsup:
