### ISSUE TITLE
Fall back to GenericName field if Comment field is missing

### ISSUE THREAD

**Issue by wsdfhjxc** [Ulauncher/Ulauncher#510]
If a .desktop file doesn't have the `Comment` field, the `GenericName` field could be used instead, as a text source for the description area of a search result item. To avoid redundancy, I think it should be used only if its value is different from the `Name` field's value. Any thoughts on this idea?

**Comment by friday** [comment]
"GenericName should state what you would generally call an application that does what this specific application offers (i.e. Firefox is a "Web Browser")." [source](https://wiki.archlinux.org/index.php/Desktop_entries)

So I think it's reasonable.

**Comment by gornostal** [comment]
Released in 5.7.3.
Thanks for the PR :+1:

**Comment by wsdfhjxc** [comment]
It seems like #546 unintentionally broke down this enhancement, as #516 touched the same code area as #514.

@gornostal Any chance of applying #514 once again, since it doesn't affect searching?

**Comment by friday** [comment]
It's in the v6 branch now @wsdfhjxc https://github.com/Ulauncher/Ulauncher/commit/01b26b8b5d9ce539712103b9b4aa44014fb77ede. I actually fully deleted the old implementation as I read it, followed the logic and found that it was never running, but you posting elsewhere reminded me.

Follow #869 if you want to be notified of v6 release plans.
