### ISSUE TITLE
Ability to disable Ulauncher in fullscreen applications (games etc.)

### ISSUE THREAD

**Issue by kgorol** [Ulauncher/Ulauncher#513]
### Is your feature request related to a problem? Please describe
When game is running and I try to use game shortcuts (such a CTRL+space) the game minimalizes and Ulauncher is showing up.

### Describe the solution you'd like
Ability to disable Ulauncher global shortcut in fullscreen apps.

### Additional context
-

**Comment by friday** [comment]
Similar to #509. The comment there might help you.

**Comment by gornostal** [comment]
Instead of detecting whether it's a fullscreen app or not, I'd prefer having a list of apps somewhere in preferences, for which ulauncher should not be triggered with a hotkey.

As @friday pointed out, there's already a feature request for that.

I'm closing this one.
