### ISSUE TITLE
Unable to register new extension

### ISSUE THREAD

**Issue by kkinder** [Ulauncher/Ulauncher#515]
### Steps to reproduce
1. Go to https://ext.ulauncher.io/new
2. Attempt to add an extension

### Current behavior

It would work.

### Expected behavior

Network error, presumably on the backend.

### Environment
N/A

### Screenshot
![image](https://user-images.githubusercontent.com/1115018/74022277-2cca3880-496b-11ea-98d9-03f95d285ce6.png)

**Comment by gornostal** [comment]
@kkinder sorry for the delayed reply. I was a temporary issue I guess. Now it seems to work.

Please reopen if it doesn't

**Comment by kkinder** [comment]
Hmmm. I am still having the same issue.

I jumped into Firefox's dev tools:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ext-api.ulauncher.io/validate-project?url=https://github.com/kkinder/timezoner. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

**Comment by kkinder** [comment]
Ping... Just wondering, certainly this isn't only happening for me? It's in both Chrome and Firefox; I just don't think the browser has permission to open the URL.
