### ISSUE TITLE
Error during install desktop file

### ISSUE THREAD

**Issue by tim77** [Ulauncher/Ulauncher#521]
Hi. I am trying to package Ulauncher for official Fedora repos but struggle with one issue on the `%install` stage:

```
ERROR: Can't find /builddir/build/BUILDROOT/ulauncher-5.6.1-1.fc31.x86_64/usr/share/applications/ulauncher.desktop
```

What i am missing or how we can fix this?

### Environment
**Ulauncher version**: 5.6.1
**Linux distro**: Fedora 31
**Desktop environment**: GNOME 3.34

### Logs
- [Full build log here](https://download.copr.fedorainfracloud.org/results/atim/playground/fedora-31-x86_64/01253485-ulauncher/builder-live.log.gz)
- [Initial Spec file](https://download.copr.fedorainfracloud.org/results/atim/playground/fedora-31-x86_64/01253485-ulauncher/ulauncher.spec)

**Comment by Hubbitus** [comment]
```
%install
# See PKGBUILD.template as reference. That file copied manually
install -Dm644 build/share/applications/ulauncher.desktop "%{buildroot}/usr/share/applications/ulauncher.desktop"
%py3_install
```

**Comment by tim77** [comment]
I seen. That's why i file a bug in the hope that upstream will fix properly build process.
