### ISSUE TITLE
Is it possible to use extensions without keywords?

### ISSUE THREAD

**Issue by Draconicrose** [Ulauncher/Ulauncher#522]
For example, the emoji extension uses em <name of  emoji> to work. I would like to be able to type just the name of the emoji into ulauncher and be given results not just from the emoji extension.

**Comment by gornostal** [comment]
hi @Draconicrose 
Nope. Currently extensions work only with keywords and for now I want to keep this explicit way of telling ulauncher which extensions users want to use.
