### ISSUE TITLE
Launch multiple applications simultaneously

### ISSUE THREAD

**Issue by papermache** [Ulauncher/Ulauncher#524]
Type two (or more) names of applications and launch all.

![ulauncherslackdiscord](https://user-images.githubusercontent.com/2126012/76007276-cbe73f00-5edb-11ea-889c-40b5a6de1a83.png)

**Comment by gornostal** [comment]
Thanks for the feature request, but I'm going to close it. Sorry.

I prefer keeping ulauncher as simple as it can be.
