### ISSUE TITLE
Is it possible to disable the hide/show animation of the launcher?

### ISSUE THREAD

**Issue by owzim** [Ulauncher/Ulauncher#526]
## Question

I'd find it very useful to disable this. It would feel may more snappier if the launcher would just show up when I need it and vanish if its work is done, without the animation.

**Comment by gornostal** [comment]
I'm pretty sure your DE configures animations on window open/close.
I could not find any animation settings in the code.
I also remember when I was using Elementary OS if I disable system animations the ulauncher window would appear without animation too.
