### ISSUE TITLE
Option to hide item description

### ISSUE THREAD

**Issue by JackKenney** [Ulauncher/Ulauncher#529]
### Is your feature request related to a problem? Please describe
_A clear and concise description of what the problem is._

When DPI scaling is on, the text preview overlaps with the title and things become unreadable.

### Describe the solution you'd like
_A clear and concise description of what you want to happen._

I would like to be able to turn off the description of the program in settings.
There could be other solutions, like turning on a scaling factor option, but I think this is the simplest solution to the issue I'm experiencing. Open to other suggestions / implementation decisions of cource.

### Additional context
_Add any other context about the feature request here._

**Comment by gornostal** [comment]
Thanks for reporting the issue.
I think it duplicates #322

IMO it's better to fix it properly rather than adding an option to hide a description.
Please subscribe to #322 for the updates. I'm closing this one.
