### ISSUE TITLE
Using 3 keys for Ulauncher hotkey

### ISSUE THREAD

**Issue by fabubaker** [Ulauncher/Ulauncher#53]
Is there someway to use 3 keys (eg: CTRL + ALT + F) as the Ulauncher hotkey?
Currently the interface only lets you input 2 keys at most for the shortcut.

**Comment by gornostal** [comment]
I was able to assign `Ctrl + Alt + F` as the hotkey.
I'm running the app from `dev` branch. If you installed using the deb package from ulauncher.io, that's the old version and it may not support 3 keys.

I'll update this ticket once the new version is released.

What OS are you running BTW?

**Comment by fabubaker** [comment]
Ah, thanks! I'll install the `dev` branch right away. 
Also, I'm running Ubuntu 16.10.

**Comment by gornostal** [comment]
I'm running Ubuntu 16.10 too. So it should work fine.
I forgot to mention that building from dev requires nodejs.
Let me know if you run into any issues.

**Comment by fabubaker** [comment]
Something came up when i ran `./install_deps`.

```
Building dependency tree       
Reading state information... Done
E: Unable to locate package gir1.2-webkit2-3.0
E: Couldn't find any package by glob 'gir1.2-webkit2-3.0'
E: Couldn't find any package by regex 'gir1.2-webkit2-3.0'
```

I installed 'gir1.2-webkit2-4.0' instead, and it seems to be working fine. I think the latter version might have been removed from the repos, I couldn't really find them.

**Comment by gornostal** [comment]
That's right.
