### ISSUE TITLE
google search opens in the wrong browser

### ISSUE THREAD

**Issue by zany130** [Ulauncher/Ulauncher#530]
### Steps to reproduce
1. launch ulauncher in any way except with verbose enabled
2.run g hello
3.will open google in the wrong browser (firefox instead of Vivaldi for me)

### Current behavior
opens firefox

### Expected behavior
opens Vivaldi

### Environment
**Ulauncher version**:5.7.0
**Linux distro**:Manjaro
**Desktop environment**:KDE

### Logs

could not get logs as runing ulaunch with verbose strangly fixes the issue

was able to get a log this time
[ulauncher.log](https://github.com/Ulauncher/Ulauncher/files/4410584/ulauncher.log)

**Comment by zany130** [comment]
I already looked at this issue here https://github.com/Ulauncher/Ulauncher/issues/223 and xdg-open opens Vivaldi like expected I also tried setting the browser env to Vivaldi like suggested but still no dice

**Comment by friday** [comment]
Try this: https://askubuntu.com/questions/788043/where-to-change-how-xdg-open-opens-urls-sync-with-kde-open

**Comment by zany130** [comment]
still didn't fix it runing this in the terminal tells me it should open vivaldi 
```xdg-settings get default-web-browser
vivaldi-stable.desktop
``` and if i do ```xdg-open www.google.com``` it will open in vivaldi so its a issue with ulauncher

**Comment by gornostal** [comment]
@zany130 I found how how it tells which browser to open: https://github.com/python/cpython/blob/master/Lib/webbrowser.py#L534

Try `xdg-settings get default-web-browser`
Do you see a browser name that you expect?

**Comment by friday** [comment]
That's what he did @gornostal. The command works from him in terminal, but not when Ulauncher is running it. It's like he's running Ulauncher as a different user.

**Comment by gornostal** [comment]
Indeed. Why didn't I read the comment above..? :see_no_evil: 

If I had the same issue I would find that `webbrowser.py` in my system and try to debug it by adding more logs to it. I don't know if you want to do that though @zany130

**Comment by zany130** [comment]
no verbose doesn't  fix it anymore that's how I was able to get the log that I added but yeah what I guess is happening is that xdg-settings get default-web-browser is returning Vivaldi when I run it on my own but for some reason when ulancher calls it. it returns firefox

**Comment by zany130** [comment]
ok so something intresting i tried runing the webbrowser.py  by its self and it just as I thought even though I'm running it as the same user that I did xdg-settings get default-web-browser and got vivialdi it returning for that script firefox

**Comment by friday** [comment]
What do you get if you run this?
```sh
python -c "import subprocess; subprocess.Popen(['xdg-settings', 'get', 'default-web-browser'])"
```

**Comment by zany130** [comment]
i get this 
```
python -c "import subprocess; subprocess.Popen(['xdg-settings', 'get', 'default-web-browser'])"
vivaldi-stable.desktop
```

**Comment by friday** [comment]
So it appears like the webbrowser library is at fault here, and while `xdg-open`/`xdg-settings` is working properly. The library is using `xdg-settings` internally, but I guess it never gets to that because of some condition overriding it.

By the look of it the library is "platform independent" as in supporting Windows, Linux and Mac (which Ulauncher doesn't need), but it then it only supports the major standard browsers. If xdg-open is more reliable for everyone it should be easy to replace this in here: https://github.com/Ulauncher/Ulauncher/blob/dev/ulauncher/api/shared/action/OpenUrlAction.py#L16

**Comment by zany130** [comment]
so it workes on the latest version just tried 👍

**Comment by jtheoof** [comment]
I am still able to reproduce this issue in a pure wayland environment (no `xwayland`). There is a bug in python `webbrowser.py` if the `DISPLAY` variable is not set. I opened a PR [here](https://github.com/python/cpython/pull/20382). Let's see how that goes.

**Comment by jtheoof** [comment]
My MR was merged. `webbrowser` now fetches proper default browser in pure Wayland environments. :tada:

**Comment by Dunky13** [comment]
I still have this issue on 5.10.0 running on manjaro with vivaldi as my default browser

**Comment by decoherencer** [comment]
> I still have this issue on 5.10.0 running on manjaro with vivaldi as my default browser

Alhtough, I am on Endeavour, I tried restarting ulauncher after checking the browser at /etc/environment and it's working now.

**Comment by linuxman** [comment]
I had a similar problem. In my case it opened Firefox instead of my default browser which is Chromium.

Following the advice of @decoherencer  I added this line to my **.zshrc** file since I use **zsh** instead of bash.

`export BROWSER="/usr/bin/chromium"`

Now it opens everything in my favorite browser.

Regards

**Comment by oxysoft** [comment]
Just adding to this issue, I had the same "wrong" browser problem in Blender as well which pushed me to properly investigate this.

There is essentially two ways to specify the default web browser on Linux

1. Using XDG, `xdg-settings set default-web-browser firefox.desktop`
2. Using an environment variable, `BROWSER=/usr/bin/firefox`

Some applications still use the old 2nd method, including ulauncher 5 (or maybe Python) and Blender. Open a shell and check what's in there with `echo $BROWSER` if you have this issue.

**Comment by friday** [comment]
Ulauncher 5 uses Python's native browser module. Ulauncher 6 will use `xdg-open`.
