### ISSUE TITLE
Reload settings.json (or "remote-control" settings)

### ISSUE THREAD

**Issue by lunaryorn** [Ulauncher/Ulauncher#532]
## Question

Hello,

can I get ulauncher to reload `settings.json`, or in some other way change settings "remotely"?  Specifically, change the theme remotely?  I'd like to switch the theme with a custom script.

Cheers.

**Comment by gornostal** [comment]
@lunaryorn no, it's not possible now.
I'm not planning on adding that possibility either. Sorry.
