### ISSUE TITLE
You should support the necessary extensions yourself

### ISSUE THREAD

**Issue by MABIY** [Ulauncher/Ulauncher#533]
ulauncher is yong,
l think it will become better,
but You should support the necessary extensions yourself.
like (kill process or switch windows ....)
if you hope other people  contribute , it not good idea.
The ecology of contributing extension plugins is worry.

sorry but i think i should say this, hope Ulauncher becomes more better.

**Comment by thomasplevy** [comment]
I disagree. I've come to this launcher because of the ecosystem. I've been using a dying launcher relying mostly on support from a single maintainer. When that maintainer has capacity issues the project stops.

A large ecosystem of many individuals is preferable to me.

**Comment by gornostal** [comment]
Supporting many extension for me is not an option.
If this was a commercial product that people would paying for, then sure.
Right now I can hardly find time to develop new features for Ulauncher, let alone creating and maintaining extensions.
I'm truly grateful for all the support from the Ulauncher community and I think they are doing a great job with the extensions.

Closing this issue.
