### ISSUE TITLE
Possible to Show Custom Icons in Ulauncher?

### ISSUE THREAD

**Issue by TheCedarPrince** [Ulauncher/Ulauncher#534]
## Question

Hi all, I am running Ulauncher 5.7.0 and was wondering if there is a way I can get my icon theme to render within Ulauncher.

I am running the numix-circle icon pack, but have had no luck with getting the icons to show up.

Anyone know how to do this?

**Comment by friday** [comment]
App icons will use your icon theme. Some icons are hard coded. Extensions mostly use their own preferred icons.

**Comment by gornostal** [comment]
Thanks for the answer @friday 
Closing this one.
