### ISSUE TITLE
Add support for Fedora 32

### ISSUE THREAD

**Issue by mybigman** [Ulauncher/Ulauncher#535]
Wont install:/

### Steps to reproduce
1. sudo dnf install ulauncher_5.7.0_fedora.rpm

### Current behavior
Error:
 Problem: conflicting requests
  - nothing provides python(abi) = 3.7 needed by ulauncher-5.7.0-1.noarch
(try to add '--skip-broken' to skip uninstallable packages)

### Expected behavior
To install

### Environment
**Ulauncher version**: 5.7 and 5.7 beta
**Linux distro**: Fedora 32
**Desktop environment**: N/A

thanks

**Comment by gornostal** [comment]
I'm going to have to adapt my build automation for Fedora 32

Thanks for reporting this.

**Comment by mybigman** [comment]
@gornostal if you get a chance to rebuild for 32 I will be happy to test for you.

**Comment by gornostal** [comment]
Added support for Fedora 32

**Comment by mybigman** [comment]
thank you sir... its working.
