### ISSUE TITLE
Preferences is blank

### ISSUE THREAD

**Issue by fl4m3x** [Ulauncher/Ulauncher#537]
Hello guys! 

I tried to use Ulaunch on Linux Mint 19.2 Cinnamon and it works very well, but there is a bug that I'm trying to solve and nothing yet ... the same is the following, when I open the preferences it appears empty, literally, as in the print that I provide **below**.

[image](https://i.imgur.com/iUmBHQ4.png)

**Comment by fl4m3x** [comment]
update: my computer freezes when closing ulauncher after that.

**Comment by gornostal** [comment]
Closing as a duplicate of #114
Please subscribe to that issue if you'd like to receive update notifications.
