### ISSUE TITLE
Cannot install in Ubuntu 20.04 beta

### ISSUE THREAD

**Issue by dellis67** [Ulauncher/Ulauncher#538]
$ sudo apt update
*
*
*
E: The repository 'http://ppa.launchpad.net/agornostal/ulauncher/ubuntu focal Release' does not have a Release file.

$ sudo apt install ulauncher
[sudo] password for ****: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ulauncher
dellis@dellis-i35:~$ 

### Steps to reproduce
1.
2.
3.

### Environment
**Ulauncher version**:
**Linux distro**:
**Desktop environment**:

**Comment by gornostal** [comment]
Now Ulauncher can be installed via PPA in Ubuntu 20.04
