### ISSUE TITLE
Ubuntu PPA is missing the Focal package

### ISSUE THREAD

**Issue by leinardi** [Ulauncher/Ulauncher#539]
Less than 2 weeks are left before 20.04 LTS is out and it would be nice to have it supported in the official Ulauncher PPA so that can easily installed and updated during the beta period.

**Comment by gornostal** [comment]
Now Ulauncher can be installed via PPA in Ubuntu 20.04

**Comment by gornostal** [comment]
Thanks for the heads up on the new Ubuntu release btw :+1:
