### ISSUE TITLE
unable to find apps by just input 2 or 3 letters

### ISSUE THREAD

**Issue by mchilli** [Ulauncher/Ulauncher#542]
Since yesterday or version 5.7.3, maybe 5.7.2 also, I could'nt find i.e. VLC Player by only typing "vl", i only find it if I type "vlc media p". Maybe ulauncher searches first in the description since the new version?
In previous versions <= 5.7.1 I find the app mostly by typing only one letter!

Update:
Ok, when I change [this line](https://github.com/Ulauncher/Ulauncher/blob/ee9e9da4a202fe88b9c309d453821ae7f6ae6389/ulauncher/search/apps/AppDb.py#L188) back to the previous one `return '%s %s' % (name, exec_name)`, ulauncher work fine again!

### Environment
**Ulauncher version**: 5.7.3
**Linux distro**: Linux Mint 19.3
**Desktop environment**: Cinnamon 4.4

**Comment by lgierth** [comment]
Same for me, it looks like #516 not just added `description` to the search, but also removed `exec_name` :)

**Comment by lgierth** [comment]
Another issue is that I can now type "LibreOffice Calc" and it won't show up, but type just "LibreOffice" and it will

**Comment by gornostal** [comment]
> Same for me, it looks like #516 not just added description to the search, but also removed exec_name

@lgierth Indeed. I'm going to create a fixed version soon

**Comment by gornostal** [comment]
After taking another look the `exec_name` is still used in search, but I'm going to revert that change anyway.

**Comment by gornostal** [comment]
Should be fixed in 5.7.4
Please reopen if needed

**Comment by Pencil4** [comment]
**Thank you** for fixing this so promptly!!

**Comment by lgierth** [comment]
Thank you :)
