### ISSUE TITLE
Unresponsive behavior for app suggestions in recent release

### ISSUE THREAD

**Issue by foxMclion** [Ulauncher/Ulauncher#544]
I recently updated from 5.1.7 and I noticed Ulauncher got a little unresponsive on its suggestions as I type. I created two gifs so you can see.

**Good behavior (5.7.1):**
https://imgur.com/kU1KCn4

**Current behavior (5.7.3):**
https://imgur.com/NDNXonL

As you can see some suggestions disappeared and I have to type almost the whole name of the software to access it. This is annoying so I rolled back to version 5.7.1.

**Comment by jeromegn** [comment]
I'm facing the same issue.

**Comment by anicetojunior** [comment]
same problem.

**Comment by gornostal** [comment]
Should be fixed in 5.7.4
Please reopen if needed
