### ISSUE TITLE
App search results sometimes incomplete

### ISSUE THREAD

**Issue by daveriedstra** [Ulauncher/Ulauncher#545]
Search results for shorter search terms are sometimes incomplete. This is similar to #542 and possibly stems from the same cause. [edit: to clarify, this is distinct from #542 because some results _are_ being shown, but they are incomplete] Two examples:

* Searching "qj" or "qja" results in suggestions for QJackRcd but not QJackCtl; searching "qjac" will show both.
* Searching "si" will suggest Sibelius, QjackRcd, and Drawing, but not Signal -- even though Signal starts with the search term (and is what I'm trying to launch). Searching "sig" shows Signal only.

![ulauncher-search-bug](https://user-images.githubusercontent.com/3504098/79284002-7b261700-7e87-11ea-8e5b-9d7885898359.gif)

### Environment
**Ulauncher version**: 5.7.3
**Linux distro**: Pop!_OS 19.10
**Desktop environment**: Gnome 3.43.3

### Logs
(none interesting)

**Comment by gornostal** [comment]
Should be fixed in 5.7.4
Please reopen if needed
