### ISSUE TITLE
transfer shortcuts while migrating install to another computer

### ISSUE THREAD

**Issue by attam** [Ulauncher/Ulauncher#555]
## Question
I have ulauncher on one computer with multiple customized shortcuts set up. Is there an easy way to copy them to my other computer without setting each one up individually?

**Comment by rdnetto** [comment]
If you copy across `~/.config/ulauncher` and `~/.local/share/ulauncher`, everything should just work.

**Comment by troycurtisjr** [comment]
let us know if for some reason that doesn't work for you.
