### ISSUE TITLE
minimum keystrokes

### ISSUE THREAD

**Issue by tulsidas** [Ulauncher/Ulauncher#559]
## Question
Is there a way to configure the minimum keystrokes to open an app?

For example, I want to open **KeePassXC**
I open Ulauncher and I have to type `keepa` in order for it to show me the application which I can choose to start.
I don't have any other applications starting with `kee` so shouldn't it with those 3 chars already show me KeePassXC? Is there a way to have a *cache* of most used apps so I can start KeePassXC with only `k`, since I open it daily?

Thanks!

**Comment by mahmadmujtaba** [comment]
Open Ulauncher app and go to shortcuts tab to define a shortcut for keepass xc eg kp.

**Comment by KuenzelIT** [comment]
@tulsidas  When I open ULauncher and type `ke` I get KeePassXC directly as the first result. Maybe the latest version already fixed this?

**Comment by tulsidas** [comment]
Tried it with 5.8.0 and works fine, thanks!
