### ISSUE TITLE
How to search for files?

### ISSUE THREAD

**Issue by orschiro** [Ulauncher/Ulauncher#56]
Dear all, 

This is fantastic. Thank you! :-)

Question: 

How can I search for files and folders?

**Comment by gornostal** [comment]
Hi @orschiro,

I recently removed search for files from the `dev` branch because it would cause performance issues.
That's definitely something that I'm going to integrate when I finish with packaging and plugin API.

You can still browse directories, though. Just type ~ or /

**Comment by orschiro** [comment]
Cool, I like the way you can browse directories! :-)

And great to hear you will bring back the search for files feature!

Thanks!

**Comment by geckolinux** [comment]
I'm really looking forward to file and folder search results too, especially if integrated as I suggest [here](https://github.com/Ulauncher/Ulauncher/issues/75#issuecomment-283984900).

**Comment by gornostal** [comment]
Sorry, I'm closing this because it is now possible to implement this feature using Extension API. 
Also I want Ulauncher to have less amount of code so it's easier to maintain it.
