### ISSUE TITLE
Configurable width

### ISSUE THREAD

**Issue by sscarduzio** [Ulauncher/Ulauncher#561]
## Sometimes results are long strings, and are not legible

How can we configure the width of the search box? Where is it defined in the themes? Is there a CSS selector? 

![image](https://user-images.githubusercontent.com/1327189/82131689-cb1e3380-97cf-11ea-86ea-0eccbaf5ca79.png)

Thank you!

**Comment by mahmadmujtaba** [comment]
You can find help from Ulauncher documentation to write extension.

http://docs.ulauncher.io/en/latest/themes/themes.html

**Comment by bjesus** [comment]
@mahmadmujtaba the page you linked to specifically says "You can only change colors in themes. Changing element sizes won’t be possible due to quirky GTK+ API.". How is this a solution to having a wider search box? 

Would be great to know if someone managed to actually have a wider widget.

**Comment by sscarduzio** [comment]
Yeah me too i gave up after asking this :(

**Comment by bjesus** [comment]
Seems like you can manually edit `/usr/share/ulauncher/ui/UlauncherWindow.ui` and change `width_request` from 604 to whatever you want.

**Comment by sscarduzio** [comment]
Worked enlarging the result box, but the title gets shortened :facepalm:
 
![jira_ulauncher_screenshot](https://user-images.githubusercontent.com/1327189/87047297-385bad00-c1f2-11ea-8265-27fceb23b9b6.png)


So I had to edit by hand another file:

```
sudo nano /usr/share/ulauncher/ui/result_item.ui
```


```xml
 <object class="GtkLabel" id="item-name">
                    <property name="width_request">410</property>  <--- changed his to 1000
                    <property name="visible">True</property>
...

and the description field too:
```xml
                <child>
                  <object class="GtkLabel" id="item-descr">
                    <property name="width_request">410</property> <--- set to 1000 too
                    <property name="visible">True</property>
                    <property name="can_focus">False</property>
                    <property name="ellipsize">middle</property>
```

So now it FINALLY looks ok

![image](https://user-images.githubusercontent.com/1327189/87050083-b8374680-c1f5-11ea-80e1-ce2ac47a71c6.png)


**please consider making title and description expand to fill the available space, and make the search box width configurable**

**Comment by LorenzoBettini** [comment]
I've just started playing with Ulauncher and experienced the same problem, in such a way that it's basically unusable due to the small width... I found this issue, so it's still not possible to configure the width of the search box? The only way is editing those two files?

**Comment by friday** [comment]
I think it would be easy to support this, but would prefer not to add a setting for it. The best thing would be if you could drag the corners to make it wider, and it remembers this.

**Comment by friday** [comment]
In Ulauncher v6 (WIP) this has been moved to: https://github.com/Ulauncher/Ulauncher/blob/46e2290a59fe2b9745eeacfa200d0da289119716/ulauncher/ui/windows/UlauncherWindow.py#L240-L241

So this uses the scaling factor and will hopefully look better for HiDPI screens (maybe will need some fixes/tweaks though).

I also created a new issue for this (#970) that should substitute this issue.
