### ISSUE TITLE
Text does not result in textarea

### ISSUE THREAD

**Issue by martindiphoorn** [Ulauncher/Ulauncher#566]
### Steps to reproduce
1. create a module
2. create in the manifest a parameter with type text
3. Try to create a multi line value

### Current behavior
The preferences view shows an single input field and it's impossible to add multiple lines.

See also this extension, which i'm trying to rewrite for api 2.0 :
https://github.com/martindiphoorn/ulauncher-2fa/blob/master/manifest.json

### Expected behavior
Show a textarea like the shortcuts parameters does

### Environment
**Ulauncher version**: 5.7.5
**Linux distro**: Budgie 20.04
**Desktop environment**: 

### Logs
There are no errors in the log

### Extra
it would be nice if an multi-line description would be available also

**Comment by yoagauthier** [comment]
Same issue on Ulauncher v5.11.0 (Extensions API v2.0.0.) !

**Comment by four43** [comment]
`textarea` isn't a valid value either in case someone was trying to get clever like me :)

**Comment by zierf** [comment]
Commands like `\n`, `\r\n`, `<br>`, `<br/>` and `<br />` aren't working either.
Unfortunately, the extension cannot be used at the moment.

**Comment by friday** [comment]
This has been fixed in the v6 branch. Will be trying to get a pre-release build out "soon", but it's a lot of work and not many volunteers. See #869
