### ISSUE TITLE
Number of "latest used apps" icons

### ISSUE THREAD

**Issue by matheusfillipe** [Ulauncher/Ulauncher#567]
I only have 3 latest used hints or whatever that would be called, would be nice to have 9. I didn't find a way to change this in the settings. 

![image](https://user-images.githubusercontent.com/24435787/83340035-f6ae1d00-a2a9-11ea-8066-8018c8337734.png)

Those are all I have in the list and I've been using for a week and should there be more than those. I think I might have some stupid problem.

**Comment by gornostal** [comment]
Implemented in v5.8.0
