### ISSUE TITLE
Adding a directory to the blacklist fails in one of two ways

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [Ulauncher/Ulauncher#568]
### Steps to reproduce
1. Open the program's settings.
2. Paste in `/home/Fred/.wine/drive_c/windows/syswow64` or paste that path and edit it.
3. Press return.

### Current behavior

Sometimes the input box disappears but the directory does not appear in the list. At other times pressing return does not close the input box.

### Expected behavior

The directory should get added or at least I should get an indication of what the problem is.

### Environment
**Ulauncher version**: 5.7.5
**Linux distro**: Mint 19
**Desktop environment**: Cinnamon

### Logs
[Link to log](https://gist.github.com/LinuxOnTheDesktop/65c171327a9caf93b0937fcf81f62117).

**Comment by friday** [comment]
This will be fixed in the Ulauncher v6 branch, as this branch has completely rewritten the part of the app the blacklist was primarily needed for.

It won't be released for a while, but we made a tracking issue if you want to be notified #869
