### ISSUE TITLE
[!] Heads up on Ulauncher development

### ISSUE THREAD

**Issue by gornostal** [Ulauncher/Ulauncher#57]

**Comment by gornostal** [comment]
@fabubaker, @Zenohm, @Cross03, @geckolinux, @aaronfranco, @orschiro 
Thanks for coming here guys. Your interest in this app is very motivating for me.

A little heads up about Ulauncher... There hasn't been any updates or releases for more than a year for several reasons. Mainly because I was disappointed in how complicated packaging for Linux is.

Now I'm trying to wrap Ulauncher into a [Snap](https://www.ubuntu.com/desktop/snappy) package. I ran into some [issues](https://bugs.launchpad.net/snapd/+bug/1661960) along the way, but I hope they will be resolved soon (or I'll find a workaround). Figuring out how to package the app for all Linux distributions is the top priority. There won't be any work on new features until that's done.

Then I'm going to focus on building a plugin API.

Meanwhile you can install all the deps manually and then run ulauncher from `dev` branch. It has some improvements and features comparing to `master`.

I would appreciate any help with building Snaps, BTW. 
Let's chat in gitter (https://gitter.im/Ulauncher) or elsewhere if you'd like to collaborate.

Thanks!

**Comment by fabubaker** [comment]
@gornostal I'm interested in the plugin system, but how is the Snap stuff coming alone?

**Comment by gornostal** [comment]
Snap is on hold while I'm trying other alternatives like AppImage. The issue with Snap is not resolved yet.

**Comment by fabubaker** [comment]
Anything I can help with? I'm busy during weekdays but I can pitch in stuff regularly on weekends.

**Comment by gornostal** [comment]
That would be great. Let's discuss that in gitter https://gitter.im/Ulauncher

**Comment by fabubaker** [comment]
Awesome! 
Although I can't find a room in the Ulauncher gitter chat...

**Comment by gornostal** [comment]
Sorry, I didn't notice it was a private room.
Here you go https://gitter.im/Ulauncher/General
