### ISSUE TITLE
Cannot launch all apps that require root

### ISSUE THREAD

**Issue by sallywoog** [Ulauncher/Ulauncher#583]
Cannot launch all apps that require root

### Steps to reproduce
1. Open ULauncher
2. Enter "gparted"
3. Enter

4. Open ULauncher
5. Enter "Software sources"
6. Enter

### Current behavior
Gparted launches and requests root password
Software Sources does nothing and does not request root password and not launch

### Expected behavior
All apps that require root to request root authentication, not just some

### Environment
**Ulauncher version**:
5.8.0

**Linux distro**:
Linux Mint 19.3
Linux Mint 20

**Desktop environment**:
Cinnamon

**Comment by friday** [comment]
I think this is the same issue as #382

**Comment by friday** [comment]
Closing as stale or duplicate.
