### ISSUE TITLE
Can't setup Super L+Spacebar hotkey

### ISSUE THREAD

**Issue by egorzot** [Ulauncher/Ulauncher#59]
Thanks for this app! It's awesome!
But when I try to setup the Ulauncher hotkey to "Super L + Spacebar" (Win+Spacebar) I get "Mod4+Super+Space" and hotkey not works.

Some in Russian: Александр, спасибо за прекрасное решение! к сожалению с питоном не сталкивался, поэтому поучаствовать не могу. Желаю развития проекта в будущем! :)

**Comment by gornostal** [comment]
That's a valid bug. I'll look into it.

P.S. Спасибо ;)

**Comment by gornostal** [comment]
@egorzot could you specify your OS and desktop environment (DE)?

You can also check out v2 Beta if you are using v1.
https://github.com/Ulauncher/Ulauncher/releases/tag/2.0.13

On Ubuntu I cannot setup Win+Spacebar either. I think that is a limitation of the DE, which is Unity on Ubuntu

**Comment by egorzot** [comment]
@gornostal 
Ubuntu 16.04.2
Unity 7.4.0
There is no this problem in 2.0.13 version. Thanks :+1:

**Comment by gornostal** [comment]
Cool. Closing this issue.

**Comment by Mouradif** [comment]
Hi, I have a similar issue with Ulauncher 5.6.1 on Ubuntu 19.10 : When I try to set Super L + Space as the hotkey, I get nothing (text field stays empty)

**Comment by gornostal** [comment]
@Mouradif this must be a limitation of the disto you are using. I'm using PopOS based on Ubuntu 19.10 and I can't use that hotkey either. It seems to be used for switching languages.

I'm closing comments in this issue to not distract other participant here. Please create a new one if you think I'm missing something here.
