### ISSUE TITLE
VERY HIGH RAM USAGE

### ISSUE THREAD

**Issue by VladimirMikulic** [Ulauncher/Ulauncher#590]
Hi!

Vanilla ULauncher is great & extremely fast but its extensions are not so great at memory usage.
On my Kubuntu 20.04 each ULauncher extension consumes ~50Mb -> 4 extensions = 200Mb of RAM!
I was thinking of adding more of them, but when I saw 50Mb per extension, I got a mini heart attack :)

![ulauncher](https://user-images.githubusercontent.com/35997844/87329498-53525800-c537-11ea-9923-e3c9f9971854.png)

Are there any optimization plans/features coming to address this issue?

Thanks.

**Comment by friday** [comment]
There's an old issue about this #285

**Comment by VladimirMikulic** [comment]
Thanks, @friday, but nothing has changed :(

**Comment by friday** [comment]
Closing as a duplicate of #285
