### ISSUE TITLE
Question / feature request gripe: is there a limit to the number of excluded folders? And: blacklisting filenames

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [Ulauncher/Ulauncher#596]
### Is your feature request related to a problem? Please describe
It is. I am trying to exclude bloomin . . Notepad (!), which exists in a frightening number of directories (because of Wine), from Ulauncher. I have add all those directories patiently to the Ulauncher exclude list. I notice though that none of them are actually getting added to the list. Is that because the list is full? The application does not mention a limit?

### Describe the solution you'd like
If you must limit the number of exclusion directories then please 1) make it clear that there is a limit, 2) allow the blacklisting of leafnames of files, such that e.g. (and especially!) notepad.exe stops appearing!

### Additional context

I never actually use Notepad. (Why would I? This is Linux.) But its name appears as soon as I press 'n' in ulauncher.

My system:

Ulauncher 5.8.0
OS: Linux Mint 20 x86_64 
Host: 20KHCTO1WW ThinkPad X1 Carbon 6th 
Kernel: 5.6.19-050619-generic 
Uptime: 2 days, 21 hours, 21 mins 
Packages: 3440 (dpkg), 11 (flatpak) 
Shell: bash 5.0.17 
Resolution: 2560x1440 @ 60.01Hz 
DE: Cinnamon 
CPU: Intel i7-8550U (8) @ 4.000GHz 
GPU: Intel UHD Graphics 620 
Memory: 3612MiB / 15907MiB 
Disk (/dev/nvme0n1p4): 17G / 40G (45%) 
Disk (/dev/nvme0n1p2): 153G / 405G (40%)

**Comment by LinuxOnTheDesktop** [comment]
Ah, [I see a way of hiding particular applications](https://github.com/Ulauncher/Ulauncher/issues/480) - and it worked for Notepad. Hooray! Still, it would be good to be able to do that from within Ulauncher, and also there remains the issue of the secret limit to excluded locations.

**Comment by LinuxOnTheDesktop** [comment]
The undeclared - and silently enforced - limit to excluded locations persists. And irritates. I am looking at alternative launchers.

**Comment by LinuxOnTheDesktop** [comment]
I find it strange that this report has received no attention whatsoever.

**Comment by friday** [comment]
Yeah, some issues have gotten no attention unfortunately. Situation improved a lot by now as more of us are involved. This is not something Ulauncher should even handle imo, so I'll close it.

**Comment by LinuxOnTheDesktop** [comment]
Thanks.

But: Ulauncher searches directories (by default, I believe). So, having a function to exclude directories makes sense.

Even if having a function to exclude directories does _not_ make sense, then surely, if nonetheless that function exists, that function should not be broken. Or do you think that the behaviour that I describe does not constitute brokenness?

**Comment by friday** [comment]
The next version will neither search directories or have this setting: #835 #834. I also found it to be buggy and a workaround we shouldn't need. The whole way this was handled before was very suboptimal. We use use the GTK APIs directly instead in v6 to get rid of all these classes and many bugs.
