### ISSUE TITLE
Strange artefact around the window

### ISSUE THREAD

**Issue by hughwilliams94** [Ulauncher/Ulauncher#60]
I am getting a a strange outline around the window when it appears. 

![screenshot_2017-02-20_10-34-43](https://cloud.githubusercontent.com/assets/15379654/23121463/69b3f456-f758-11e6-8ca5-e4cb98905b9b.png)

Running on GalliumOS, an Ubuntu derivative for Chromebooks, the desktop is XFCE. Any suggestions for a fix?

**Comment by hughwilliams94** [comment]
Just figured it out, just an issue with my compositor which doesn't like small windows!

**Comment by patrickbolle** [comment]
I'm getting the same thing, but it's just a black box instead - I don't use a compositor though.

**Comment by patrickbolle** [comment]
Hi!I'm not at my computer right now, but I'm using Debian Jessie (with i3wm).I'm using the newest version of uLauncher from the website.I installed Compton and it fixed the black box, but I'd rather not use a compositor if possible haha!

**Comment by gornostal** [comment]
Hi Patric,
I understand. I'll look into this.

**Comment by gornostal** [comment]
I'm going to have to close this issue because current version uses some effects that require compositing. Sorry.

I'm planning to refresh the UI later and I'll take into account this issue.
