### ISSUE TITLE
System theme

### ISSUE THREAD

**Issue by ema2159** [Ulauncher/Ulauncher#601]
### Is your feature request related to a problem? Please describe
I would like Ulauncher to use the system theme (GTK) as many other apps. It currently doesn't support this feature although it might not be that hard to implement.

### Describe the solution you'd like
A lot of GTK apps (Lollypop, Gimp, Inkscape etc) have an option to automatically update their theming when the system theme is updated grabbing a main color and an accent color. This should be implemented in Ulauncher.

**Comment by friday** [comment]
Duplicate (sort of) of #342 Ulauncher doesn't support system themes anywhere and it's not a small fix.
