### ISSUE TITLE
Autofocus on ulauncher window not working

### ISSUE THREAD

**Issue by leodahal4** [Ulauncher/Ulauncher#602]
### Steps to reproduce
1. When I am using any application on Full screen mode, auto focus on ulauncher stops working.

### Expected behavior
Either I am on Full screen mode or on normal mode, ulauncher window is supposed to gain auto focus

### Environment
**Ulauncher version**: 5.8.0
**Linux distro**: Arch
**Desktop environment**: Gnome

**Comment by ZarthKa** [comment]
In KDE on Manjaro I seemed to get a workaround...

In konsole I used `which ulauncher-toggle` and used the output `/usr/bin/ulauncher-toggle` in graphical Settings→Shortcuts→Own Shortcuts to create an own shortcut
![grafik](https://user-images.githubusercontent.com/10518553/147861173-a69b0a0f-c3de-4537-99e2-4e312d1daf5b.png)
Sorry, if image inapropriate, but easier to explain

**Comment by friday** [comment]
This should be fixed in the v6 beta. In v5 you need something like the "Grand Theft Focus" extension for Gnome. See #1128
