### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by GuilhermeFCO** [Ulauncher/Ulauncher#605]
### Steps to reproduce
1.
2.
3.

### Current behavior
Error #403 Forbbiden

### Environment
**Ulauncher version**:
**Linux distro**:
**Desktop environment**:

**Comment by troycurtisjr** [comment]
Where do you see this? In the application or on the webpages? Can you describe when you see it? Always or only in certain circumstances?

**Comment by GuilhermeFCO** [comment]
> ### Steps to reproduce
> 
> ### Current behavior
> Error #403 Forbbiden
> 
> ### Expected behavior
> ### Environment
> **Ulauncher version**:
> **Linux distro**:
> **Desktop environment**:
> 
> ### Logs

**Comment by GuilhermeFCO** [comment]
Hi, this create automatic
