### ISSUE TITLE
Ulauncher stopped returning results

### ISSUE THREAD

**Issue by frdrk** [Ulauncher/Ulauncher#621]
### Steps to reproduce
1. ctrl+space to activate Ulauncher
2. Type any string that would normally return results (native or from any installed extension)

### Current behavior
Nothing. No result, feedback or error message.

### Expected behavior
Matched results from app search or extensions

### Environment
**Ulauncher version**: 5.8.0
**Linux distro**: Manjaro Mikah 20.1
**Desktop environment**: Gnome 3.36.6

### Logs
[Log](https://gist.github.com/frdrk/050595a5f46d7cef64f309e4457ea3f8)

**Comment by gornostal** [comment]
Looks like `~/.config/ulauncher/shortcuts.json` may be corrupted.
Could you attach it here please?

As a workaround you can rename the file and restart ulauncher. Then ulauncher will create a new one with the default shortcuts.

**Comment by frdrk** [comment]
Mm, good catch. My shortcuts.json is in fact 0 bytes I see. Renaming it seems to have totally solved the issue. No idea how it could have happened but  I had a critically full system drive just prior so maybe that could have something to do with it?

**Comment by gornostal** [comment]
It could. It will be hard to tell what exactly caused that issue now.
If more people start reporting the same issue then I'd tell it's a bug
in Ulauncher.

**Comment by kaenovsky** [comment]
I can confirm having exactly the same issue. Also same fix did the job.` ~/.config/ulauncher/shortcuts.json` was completely blank. After mv the file, ulauncher created a new `shorcuts,json` and it was solved. Thanks a lot @gornostal 

ulauncher version: 5.8.1
distro: xubuntu 18.04 (xfce)

**Comment by NastuzziSamy** [comment]
Fixed as it was published
