### ISSUE TITLE
Calculator: 2^8 should return 256

### ISSUE THREAD

**Issue by sebastian-65** [Ulauncher/Ulauncher#623]
### Current behavior
When put `2^8` to calculator, it returns 10 as a result.

### Expected behavior
2^8 returns 256.

**Comment by sebastian-65** [comment]
Not the most required thing under the Sun, but sometimes it would be handy to quickly calculate such things.

**Comment by gornostal** [comment]
You can do it like this: `2**8`
It's because Ulauncher uses Python syntax for math evaluation.
Using `^` to raise a number to a power would be a nice improvement though.

**Comment by sebastian-65** [comment]
Oh! Thank you for letting me know :+1:

**Comment by AlwaysBeCalm** [comment]
Does Ulauncher supports modulo operator (%)?

**Comment by gornostal** [comment]
@AlwaysBeCalm nope, it does not.

Ulauncher uses Python's `ast.parse(expr, mode='eval')` to evaluate expressions and that function doesn't seem to recognize '%' sign.

**Comment by gornostal** [comment]
Released in v5.10.0

**Comment by sebastian-65** [comment]
Thank you, Sir. #salute
