### ISSUE TITLE
Search within app description

### ISSUE THREAD

**Issue by sebastian-65** [Ulauncher/Ulauncher#625]
### Expected behaviour

I would expect `Filezilla` to be found when searching for `FTP` which is present in app's description.

![image](https://user-images.githubusercontent.com/9447457/94552635-77c8f100-0257-11eb-8654-54307928ca97.png)

- I have multiple apps that I don't recall their names precisely. 
- Might help with both #270 and #558.
- User is able to customize the description / keywords in app.desktop files to match his search

### Possible solutions

Assuming that having this functionality implemented as a default one, might return some false positives or possibly make search slower, these options pop in my mind:

1. Having a checkbox in settings allowing this behavior.
2. Having some special symbol when typed in, widens the results.

**Comment by sebastian-65** [comment]
@gornostal What do you think about this one? Would it make sense to you one day?

**Comment by gornostal** [comment]
I think that's a good improvement, but requires more research on how to do that properly.
The fuzzy search I implemented is okay, but not super good (you can find multiple complains about it here).
Just enabling search in descriptions is going to cause a lot of confusion because of the current implementation.

**Comment by sebastian-65** [comment]
I do understand. Thank you for your reply!

**Comment by gornostal** [comment]
I guess that was not the answer you were hoping to get.
Basically, I'd like to see a lot of unit tests around different kinds of searches including current unit tests.
Once we have unit tests (failing, successful - doesn't matter). We can think about the implementation.

**Comment by friday** [comment]
This is now supported in the Ulauncher v6 branch with PR #938. V6 won't be released for a while, but we made a tracking issue if you want to be notified #869
