### ISSUE TITLE
Less fuzzy search, ssh and firefox bookmarks without a keyword

### ISSUE THREAD

**Issue by KuenzelIT** [Ulauncher/Ulauncher#629]
I want to say upfront that Ulauncher is amazing and I really like to use it. I'm still using Albert though too, because there are some cases that I cannot yet solve with Ulauncher.

### Is your feature request related to a problem? Please describe
There are multiple things I want to achieve with Ulauncher and I don't see a way without allowing extensions without keywords:

- by default Albert does a web search if no other result is found, while Ulauncher does a fuzzy search on applications and nearly always shows an application result (e.g. 'wreterkoptretret' results in LibreOffice Writer). Fuzzy search is great in some cases, but here it would be nice to switch to a web search if a lot of characters do not match.
- with Albert I can easily open ssh connections just by typing in the server name (e.g. 'my' results in 'my.company.com')
- with Albert I used to be able to easily open bookmarks just by typing in a part of the bookmark name. The extension for that does not work anymore, that's why I created the Firefox Bookmarks extension for Ulauncher. But in Ulauncher I always have to type the keyword ("f ") first, which does work, but I still remember how easy it was with Albert and miss that.

### Describe the solution you'd like
I'm not sure how to solve these problems, but I think some way to use extensions without keywords is the solution.

Do you have an idea? Are extensions without keywords going to be possible in some future release?

### Additional context
Extensions without keywords was already discussed multiple times (#306, #522). I still have to ask in case some things have changed. My productivity would really improve without the keywords.

**Comment by gitowiec** [comment]
I agree with fuzzy search. It is too aggressive. I'm used to flawless search of Jetbrains products. It just works all the time I need to find any item (it is no difference if it is a file, class, const or anything else). The Ulauncher's fuzzy search should comply with entered letters order. Or at last please add an option in preferences to limit the fuzziness.

**Comment by squalou** [comment]
Agreed, especially for bookmarks : having used both synapse and albert, the comparison is hard.
Always typing keywords feels wrong.

**Comment by troycurtisjr** [comment]
Improvements around fuzzy search are definitely something to consider, more in depth discussions going on in #232 . Regarding the built-in Firefox and ssh, those are unlikely to be added into the core coffee dinner the idea is keeping the core small and focused, with extensions providing additional functions as needed. Perhaps a more generalized fallback search api could be constructed such that extensions could register and provide their own suggestions in that case.

**Comment by friday** [comment]
The fuzzy search algorithm was improved a lot in 5.12.0, which was just released. Some distros will need packagers to manually update before the release will be available for their users.

You can definitely no longer write something like "wreterkoptretret" and get valid "LibreOffice Writer", but it still needs tuning and will see more improvements.

I also reopened #306, so I think this issue is covered now.
