### ISSUE TITLE
Interference with sound on Fedora 32

### ISSUE THREAD

**Issue by hyperreal64** [Ulauncher/Ulauncher#630]
### Steps to reproduce
1. Install Fedora 32.
2. Install ULauncher. Reboot.
3. Notice sound output only lists headphones; speakers output is not available.

### Current behavior
After installing ULauncher on Fedora 32, the sound output for speakers becomes unavailable, and the only available are headphones. 

A workaround is to set:
`options snd-hda-intel probe_mask=1` in `/etc/modprobe.d/alsa-base.conf`
or
`options snd_hda_intel power_save=0` in `/etc/modprobe.d/audio_powersave.conf`

Possibly related to https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1885462 ?

### Expected behavior
Sound output through speakers (default) should work.

### Environment
**Ulauncher version**: v5.8.0
**Linux distro**: Fedora 32
**Desktop environment**: GNOME on X11

### Logs
https://gist.github.com/hyperreal64/cfe84584bb0fd03f43b4a2ad2466b8e3

**Comment by troycurtisjr** [comment]
@hyperreal64  are you sure that ULauncher is related to this? As far as I can tell there is no direct interaction with the sound subsystem when using ULauncher. Also I'm running Fedora 32 with ULauncher without experiencing this issue. Can you undo your workaround and confirm that you still see the issue. Then uninstall ULauncher and see if it resolves the issue?

**Comment by hyperreal64** [comment]
Yes, I've installed Fedora 32 and 33 a few times since then, and all I can confirm is that the issue occurs after a reboot immediately after installing uLauncher. The workaround is the only thing that makes it work. Before applying the workaround, if I uninstall ULauncher, the problem goes away. This is likely hardware related because it only happens on my System76 laptop, whereas my MacBook Pro, which runs Fedora 33, is unaffected. 

But yeah, I was puzzled as to why or how ULauncher could affect the sound output device. I thought it might have been plugins I was using, but it happens on vanilla/fresh installs of ULauncher.

The workaround is a satisfactory solution for now, so this issue can be closed.
