### ISSUE TITLE
How to remove sticked shortcut?

### ISSUE THREAD

**Issue by gitowiec** [Ulauncher/Ulauncher#631]
## How to remove shortcut that sticked to the Ulancher menu?

I don't know why and don't know how that Thunderbird got sticked there. It annoys me, is it recent run? Is it most frequently run? How to remove it form there?

![image](https://user-images.githubusercontent.com/1553195/95956800-17ad7f80-0dff-11eb-9e91-b6fe0367031a.png)

**Comment by gornostal** [comment]
Set "Number of frequent apps" to 0 in Preferences.
Please reopen if that doesn't help.
