### ISSUE TITLE
Alt+Shift and Super+Shift hide the launcher

### ISSUE THREAD

**Issue by Mohammed-Taher** [Ulauncher/Ulauncher#635]
### Steps to reproduce
1. Open the launcher by hitting Ctrl+Space.
2. Hit Alt+Shift or Super+Shift

### Current behavior
The launcher hides once hitting Alt+Shift or Super+Shift.

### Expected behavior
I'm using Alt+Shift to change the input language in my system, so it is expected that the input language in Ulauncher changes accordingly.

### Environment
**5.8.0**:
**Ubuntu 20.04.1**:
**Gnome 3.36.3**:

**Comment by falke2** [comment]
Same here

**Comment by troycurtisjr** [comment]
This looks related to #364 , can you confirm the issue is the same?

**Comment by Mohammed-Taher** [comment]
Yes, it is.

**Comment by ToxaZ** [comment]
I can search using Cyrillic layout or Latin, but not both since I can't switch layout.

**Comment by gornostal** [comment]
I'm not sure what would be the best fix for this issue, but I'd rather not touch that timeout in `UlauncherWindow.py:154`.
If anyone is interested in trying to fix it, post a comment here with your idea.

**Comment by friday** [comment]
I reopened #364 in favor of this issue. Not sure we can fix this, but that issue has better info in the comments.
