### ISSUE TITLE
Fedora 33 python dependecy problem

### ISSUE THREAD

**Issue by quwisky** [Ulauncher/Ulauncher#637]
### Steps to reproduce
1. Get a Fedora 33 installation.
2. Try to install ulauncher using the official rpm packages.

### Current behavior
Currently I can not install ulauncher on a Fedora 33 machine, because of a python dependency version problem.
Ulauncher is expecting python version 3.8 but the recently released F33 provides python version 3.9.
**Error message**:
![Screenshot from 2020-11-05 08-49-55](https://user-images.githubusercontent.com/17062588/98213307-2a6e2c80-1f45-11eb-977f-81aab9a68fd0.png)

### Expected behavior
Maybe it should accept python version 3.9 if its compatible.

### Environment
**Ulauncher version**: 5.8.1
**Linux distro**: Fedora 33
**Desktop environment**: Gnome 3.38

**Comment by gornostal** [comment]
Thanks for reporting.
Related to #607

**Comment by gornostal** [comment]
Added support for Fedora 33.

**Comment by quwisky** [comment]
Thank you!
