### ISSUE TITLE
Would you consider merging support for podman?

### ISSUE THREAD

**Issue by troycurtisjr** [Ulauncher/Ulauncher#638]
I am running on Fedora which uses podman as the container engine instead of docker. In fact, some hoops need to be jumped through in order to run docker correctly considering its lack of support for cgroups2 (or at least so I've read). With very minimal tweaks I have managed to get the development build container to run correctly in podman. If I put this in a PR would you be opposed to merging it?

### Describe the solution you'd like
Allowing the build scripts to use docker or podman equally well.

**Comment by gornostal** [comment]
Merged the PR. Closing this issue now.
