### ISSUE TITLE
Ulauncher ignoring GDK_SCALE

### ISSUE THREAD

**Issue by accidentalexponential** [Ulauncher/Ulauncher#639]
## Question

I'm using awesome-wm with zsh and set GDK_SCALE=2 in xinitrc. Apps startet via terminal or menu are fine. Apps startet with Ulauncher do not acknowledge this setting. How can i scale correctly?

**Comment by friday** [comment]
As of the last release this should be fixed when not running through systemd. And with systemd you can override the systemd unit file to include them this way: https://github.com/Ulauncher/Ulauncher/issues/780#issuecomment-912982174

If still have this issue, please make a new issue or comment.
