### ISSUE TITLE
Steps to uninstall Ulauncher and npm dependencies

### ISSUE THREAD

**Issue by brunolellis** [Ulauncher/Ulauncher#64]
Hi,
Just wondering... what are the steps to uninstall Ulauncher and npm dependencies?

Thanks!

**Comment by gornostal** [comment]
It depends on how you installed it.
If you installed it from .deb or via apt-get, you can use `sudo dpkg -r ulauncher` or `apt-get remove ulauncher`.
If you installed it from git, simply remove the folder and `~/.local/share/applications/ulauncher.desktop`

**Comment by gornostal** [comment]
Please reopen if that doesn't work.
