### ISSUE TITLE
Ulauncher menu bar does not appear when enting keyboard hot key combo after upgrading to 5.90

### ISSUE THREAD

**Issue by angelomaragos** [Ulauncher/Ulauncher#644]
I have recently upgraded to 5.90.  Now when I press my keyboard hotkey combo, the Ulauncher window does not display on screen. I previously had Ulauncher working by updating the Ulauncher.desktop file to include 'Exec=env WEBKIT_DISABLE_COMPOSITING_MODE=1 GDK_BACKEND=x11 /usr/bin/ulauncher --hide-window'

I'm on Wayland so I also had to install wmctrl and setting a Keyboard shortcut in system settings but after doing that Ulauncher was working reliably. 

I should note that if I run ulauncher -v in the terminal I do see the Ulauncher menu bar thought it is off-centered.

Prior to upgrading, Ulaucher was working for me after 
### Steps to reproduce
1.Upgrade to 5.90 on Ubuntu 20.04 LTS running Gnome Wayland
2.Press Keyboard hotkey
3.Ulauncher bar does not display on screen

### Environment
**Ulauncher version**: 5.90
**Linux distro**:  Ubuntu 20.04
**Desktop environment**:  Gnome Wayland

**Comment by gornostal** [comment]
Could you run `ulauncher-toggle` from the command line. Do you see any
errors there?

**Comment by angelomaragos** [comment]
Yes, I do see an error. After running 'ulauncher-toggle' I see

bash: /usr/bin/ulauncher-toggle: /usr/bin/sh: bad interpreter: No such file or directory

**Comment by gornostal** [comment]
Ah.. right

Same as #642

As a temporary workaround, change the first line of `/usr/bin/ulauncher-toggle` to `#!/bin/bash`

**Comment by gornostal** [comment]
I introduced this bug yesterday trying to fix a build for Fedora. Didn't realize not all OSes have `/usr/bin/sh` Sorry about that.

**Comment by angelomaragos** [comment]
That worked. Thank you

**Comment by friday** [comment]
This should be fixed by now. If not let us know.
