### ISSUE TITLE
Ulauncher gives python error when selecting "Don't hide after losing mouse focus

### ISSUE THREAD

**Issue by TheSecureTux** [Ulauncher/Ulauncher#645]
### Steps to reproduce
1. Select the option in the menu

### Current behavior

![image](https://user-images.githubusercontent.com/24679987/100010906-e4c8b500-2dc8-11eb-8b84-43d2244368f3.png)

### Environment
**Ulauncher version**: 5.8.1
**Linux distro**: Arch
**Desktop environment**: i3

### Logs

Message: Route not found for path set/grab-mouse-pointer
Error Name: UnhandledError
Type: RouteNotFound

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ulauncher/utils/Router.py", line 45, in dispatch
    callback = self._callbacks[url_params['path'].strip('/')]
KeyError: 'set/grab-mouse-pointer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3.8/site-packages/ulauncher/utils/Router.py", line 47, in dispatch
    raise RouteNotFound('Route not found for path %s' % url_params['path'])
ulauncher.utils.Router.RouteNotFound: Route not found for path set/grab-mouse-pointer

```

**Comment by troycurtisjr** [comment]
Could there be a mixture of code here? That option was added in 5.9.0 release, but you mention this is 5.8.1 version. Perhaps this is a local build instead?

**Comment by TheSecureTux** [comment]
I built the package from the AUR, but I can try building it directly and I'll let you know. brb

**Comment by TheSecureTux** [comment]
Eh, whatever, I have been able to build the package after jugling a bit with pyenv  and python versions and whatnot. And now that option works. 

As this is probably casued by me trying to collect all the python versions in the same place for some reason I doubt it will help anybody else. Closing. Ty :walking_man:
