### ISSUE TITLE
Install Ulauncher extensions via command line

### ISSUE THREAD

**Issue by alexandrebarbaruiva** [Ulauncher/Ulauncher#646]
### Is your feature request related to a problem? Please describe

No, it's more of a simple solution to my problems, I have a script that installs everything on my machine, but I have no automated way to install ulauncher extensions.

### Describe the solution you'd like

A simple command to install extensions, maybe a default folder that I can git clone all my extensions and Ulauncher detects them

### Additional context

I love Ulauncher, thanks for everything <3

**Comment by gornostal** [comment]
Hi @alexandrebarbaruiva 

The way ulauncher works with extensions is it looks at `~/.config/ulauncher/extensions.json` and launches extensions one by one looking for them in `~/.local/share/ulauncher/extensions/`.
If it doesn't find one, it'll try to download it and then run.

Basically, in your case you could simply back up that `extensions.json` file somewhere and then when you install everything using a script, have that script to put the JSON file in the right place.

**Comment by alexandrebarbaruiva** [comment]
Thanks, that solves my problem!
