### ISSUE TITLE
Emacs/Shell keybindings 

### ISSUE THREAD

**Issue by troycurtisjr** [Ulauncher/Ulauncher#649]
### Is your feature request related to a problem? Please describe
I have the emacs keymap enabled in my Gnome session. The typical text editing commands work fine in ULauncher (C-b, C-f, etc), but I would also like to have C-n for down and C-p for up to scroll through the list.  

I plan on trying to add it in, but I want to make sure the PR would be accepted before bothering.

### Describe the solution you'd like
Ideally we'd be able to detect the current keymap somehow and do the right thing automatically. If that doesn't work, then I would propose adding an options to the preferences.

**Comment by friday** [comment]
If this is something that can be handled without adding new complicated settings to Ulauncher or locking in to specific key combinations supported that would be great. I'm definitely reluctant to add settings for all these keys, and also to support both emacs and vim, not to mention adding the Vim way with insert mode and normal mode in Ulauncher.

**Comment by friday** [comment]
5.13.0 is out now, so this should be fixed
