### ISSUE TITLE
Change default search engine and default file manager

### ISSUE THREAD

**Issue by Wiwi-31** [Ulauncher/Ulauncher#65]
Hi,
Is it possible to change the default search engine? Or at least, implementing the Bangs?

Like the one available in DuckDuckGo search engine:
- !yt for searching a video
- !maps for google maps 
- !a for amazaon
- !w for wikipedia
- etc.

And I also would like to know if is it possible to change the default file manager. For example, I have nautilus and nemo install on my computer, but when I want to open the file manager I Just type "File" in Ulauncher but, it is nautilus that open, I would have the opportuny to replace it by nemo in Ulauncher, is that feature available?

Thanks,

**Comment by gornostal** [comment]
Hi @Wiwi-31,
The first feature is implemented in the dev branch, where you can add shortcuts from preferences.
The second one is not implemented.

I'm working on an update that will enable users to install dev version of Ulauncher in a more straightforward way. You can follow the updates here https://twitter.com/ulauncherapp

**Comment by gornostal** [comment]
@Wiwi-31 
You can download [v2 Beta](https://github.com/Ulauncher/Ulauncher/releases/tag/2.0.13) and try adding shortcuts.
As for the second request, UL uses `xdg-open` under the hood to open and run apps, so you can applications with xdg tool like this:

```
$ xdg-mime default Thunar.desktop inode/directory
```
That will set Thunar file manager as the default one.
More info here http://unix.stackexchange.com/a/59088
