### ISSUE TITLE
The program 'ulauncher' received an X Windows System error.

### ISSUE THREAD

**Issue by AlwaysBeCalm** [Ulauncher/Ulauncher#650]
### Steps to reproduce
1. run Ulauncher through terminal
2. run some applications (no specific one causes this error)
3. 

### Current behavior
suddenly crashes with the error:
![error2](https://user-images.githubusercontent.com/54927528/100541761-0c9b9b00-3257-11eb-8fbc-782a4e3a0f8d.png)

### Expected behavior
run smoothly with no crashes

### Environment
**Ulauncher version**: 5.9.0
**Linux distro**: Linux Mint 20 Ulyana
**Desktop environment**: Cinnamon 4.6.7

**Comment by gornostal** [comment]
I see 2 errors on the screenshot.
The first one should be fixed by deleting
`~/.cache/ulauncher_cache/file_browser_queries_v2.db`. Could you try that
please?
Hopefully that'll also resolve the second error.

**Comment by AlwaysBeCalm** [comment]
@gornostal 
Thanks for replying

I've deleted the file, but unfortunately, the crash still happening...

don't care about sqlite not found, it's a test I made to see if a command not found will crash ulauncher :sweat_smile: , but no,  ulauncher worked fine, but still crashes after a while...

![image](https://user-images.githubusercontent.com/54927528/100550047-286b6500-3288-11eb-9ac5-d9082d5b782c.png)

**Comment by gornostal** [comment]
@AlwaysBeCalm did you restart ulauncher after deleting the file?
TBH, I have no idea how that error can re-occur after deleting a file. It clearly cannot read the file because it's either empty or data is corrupted. The deletion should have helped :thinking:

**Comment by AlwaysBeCalm** [comment]
@gornostal 
Yes, I did

I tried 2 situations:
1- deleted the file then restarted ulauncher
2- deleted the file without restarting ulauncher

Unfortunately, the app crashed with the same error in all situations... :sweat: :sweat:

**Comment by gornostal** [comment]
That's weird. 
Could you `cat ~/.cache/ulauncher_cache/file_browser_queries_v2.db`?
Curious what's inside.

**Comment by AlwaysBeCalm** [comment]
@gornostal Yeah sure ...
1- I've `cat` it
2- open it with sublime
(the 2 results in the same image)

and also tried to open it with DB Browser for SQLite, but the db is ciphered...
![image](https://user-images.githubusercontent.com/54927528/100658389-06ddac80-3360-11eb-99c9-9706df4258fc.png)

**Comment by gornostal** [comment]
That's not an SQLite DB file. It's a Python pickle output.
Anyway, the output looks fine. Now I don't know what else to suggest

**Comment by AlwaysBeCalm** [comment]
@gornostal 
Can I say something weird? 😅

the error occured on my Linux Mint, I don't know how and why but, it happened with me when I checked the 'Don't hide after losing mouse focus' option.

When I uncheck it, it remain running fine, but it crashes after a while from checking it. 😓😓😓

I tried with someone who is running pop_os, but he didn't face any problem either after checking or not.

**Comment by gornostal** [comment]
That's a weird behavior indeed :thinking: 

I'll check that flag myself and will use it for a couple of weeks trying to spot the same issue.
I'm running PopOS though, so chances of seeing it are probably not as great as on Mint for you.

**Comment by gornostal** [comment]
@AlwaysBeCalm Just an update on this:
I've enabled `Don't hide after loosing mouse focus` almost 2 months ago and don't see any issues with the `.db` file myself.
I suspect something is interfering with the files in `~/.cache/ulauncher_cache` on your system and I don't know what.

I'm going to close this issue, but if you find any new evidence that it could be a bug in Ulauncher, feel free to reopen.
