### ISSUE TITLE
Allow keyword search without content

### ISSUE THREAD

**Issue by SHU-red** [Ulauncher/Ulauncher#654]
### Is your feature request related to a problem? Please describe
I want to open the sites/services where i do searches, but without searching

### Describe the solution you'd like
- example: Keyword "w" is configured with this Query "https://en.wikipedia.org/wiki/%s"

- it works and i can search for stuff on wikipedia

- if i type in "w " and hit ENTER-Key (nothing happens)

- It would be nice, if Ulauncher now basically opens the link "https://en.wikipedia.org/wiki/" (because %s = "") --> This will lead me direclty to the start-page of wikipedia

### Additional context

- Not sure if this is a feature which causes problems on other topics

- Did not find a similar topic

Thanks

**Comment by friday** [comment]
You mean like this? https://github.com/Ulauncher/Ulauncher/issues/191#issuecomment-493232380

**Comment by SHU-red** [comment]
No, i dont think there is the need for using a additional setting

Just when i type in "w " and hit ENTER, the url "https://en.wikipedia.org/wiki/" shall be used

I created a fork, branch + pull-request
TO MAKE IT CLEAR: Im sorry im an absolute GitHub-beginner and tried my best to fit your Code Contribution guildeline

If i did something wrong, im very sorry you can refuse my stuff

Pull Request: [https://github.com/Ulauncher/Ulauncher/pull/656](https://github.com/Ulauncher/Ulauncher/pull/656)

**Comment by SHU-red** [comment]
See for explanation:

[https://github.com/Ulauncher/Ulauncher/pull/656#issuecomment-738787752](https://github.com/Ulauncher/Ulauncher/pull/656#issuecomment-738787752)

**Comment by friday** [comment]
I think I understand. What you are asking for is both keywordless and keyword to be handled by the same shortcut.

But with your suggestion I can add YouTube search but if I don't enter a keyword I get to "https://www.youtube.com/results?search_query=" which says "No results found. Try different keywords or remove search filters". Or the search could go to domain.com/[searchQuery]/[page] so the missing search query would go to domain.com//1 and search for "1".

What you'd actually need is to handle the keyword variant and keywordless variant separately.

Another example is IMDB. There are 12 different search result views depending on what you want to see: Ex:
https://www.imdb.com/find?q=Pedro%20Pascal&s=nm&ref_=fn_nm
https://www.imdb.com/find?q=Pedro%20Pascal&s=tt&ttype=ep&ref_=fn_ep
https://www.imdb.com/search/name-text/?bio=Pedro%20Pascal&ref_=fn_bi

Google also has several different searches (normal, images, videos, news, maps, shopping, finance etc). Google news search is https://www.google.com/search?q=[query]&tbm=nws but that isn't a "landing page" while https://news.google.com/ is.

It is better that the shortcut creator handles this explicitly if gornostal even wants the feature.

**Comment by SHU-red** [comment]
Understood.
The current behaviour of a shortcut without arguments is, that it does nothing after hitting ENTER

I just wanted to suggest a on-top-feature for using this "unused feature"

Even if you do not always open the start-page of a plaform --> You will be able to open the browser and still get to the site within a easy way through Ulauncher

Your/gornostal's decision ;-)

Thank you very much for your work!

**Comment by gornostal** [comment]
Hi @SHU-red 

Sorry, but I think it will be better without this feature.

It's difficult to be objective here, so I'll just present my opinion:
Ulauncher asks users to "Type in a query and press Enter", so the current behavior shouldn't be unexpected.
Also, there's already a solution -- you can create as many Ulauncher Shortcuts as you like, just make sure you check "Run without arguments" checkbox, and you'll get the behavior you want.

As an alternative way, you can always put `#` symbol as an argument and it'll take you to the same page as with an empty query.
