### ISSUE TITLE
an unexpected error has occurred

### ISSUE THREAD

**Issue by developer-sp** [Ulauncher/Ulauncher#657]
### Steps to reproduce
1. extensions
2. add extensions
3. paste link for installation

### Current behavior
The extension crashed because it could not import module algoliasearch. 
Try installing this module manually: pip3 install algoliasearch --user and then restart Ulauncher. 
If that doesn't help, report the issue on Github.

### Expected behavior
intallation complete with sucess 

### Environment
**Ulauncher version 5.9.0**:
**Ubuntu 20.04**:
**Gnome**:3.33.6 x11

**Comment by AnanTripathi** [comment]
Thanks

**Comment by gornostal** [comment]
@developer-sp It looks like you are having an issue with that particular extension.
Whatever the extension is, could you post this issue to their Github please?
