### ISSUE TITLE
What is the minimum python version to target?

### ISSUE THREAD

**Issue by iboyperson** [Ulauncher/Ulauncher#658]
## Question
What is the minimum version extension developers should target? API v2.0.0 specifies python 3 but not a particular minimum version of python 3. 

## Context
I am working on a feature that could benefit from the python 3.8 [walrus operator](https://docs.python.org/3.8/whatsnew/3.8.html#assignment-expressions). I couldn't find any specified minimum version of python 3 in the extension documentation so I am asking here.

**Comment by gornostal** [comment]
Good question @iboyperson.
I don't have any stats but I assume most of the users are on python 3.8. So I'd suggest targeting it.

Only distros based on Ubuntu are probably using python 3.6 or something like that. Its end of life is next April.

**Comment by iboyperson** [comment]
Alright, thanks for the input! Might be worth throwing that somewhere in the docs (I can PR that if needed). However, since this is answered i'm going to close this. I'll leave some info below for anyone who stumbles across this in the future.

**Additional Info:**
* Ubuntu 20.04 LTS and newer seem to [support 3.8](https://wiki.ubuntu.com/FocalFossa/ReleaseNotes#Python3_by_default)
* Fedora 32 and newer appear to [support it too](https://src.fedoraproject.org/rpms/python3)
* Arch Linux [does too](https://www.archlinux.org/packages/extra/x86_64/python/)
