### ISSUE TITLE
Translucent and Icon

### ISSUE THREAD

**Issue by julienmiclo** [Ulauncher/Ulauncher#660]
## Question
Hello, 
i searched and readed in documentation but i don't find answer to my ask, so.

- How can i remove translucent effect in background ?
- Can i remove or hide settings icon ?

I think it's in CSS but i don't find class name to do that.

Thank you.

**Comment by friday** [comment]
Sorry for the late response.

> How can i remove translucent effect in background ?

If you mean the shadow, you can disable it by running ulauncher with the flag `--no-window-shadow` (see the readme https://github.com/Ulauncher/Ulauncher#known-issues-and-workarounds) and #802

> Can i remove or hide settings icon ?
```
.prefs-btn {
    opacity: 0;
}
```

I'm closing this issue but if this doesn't answer your question, feel free to comment.
