### ISSUE TITLE
AutoTypeAction

### ISSUE THREAD

**Issue by mikebarkmin** [Ulauncher/Ulauncher#663]
### Is your feature request related to a problem? Please describe
Most of the time when I am copying something from ulauncher I want to directly paste it again.

### Describe the solution you'd like
A AutoTypeAction to just type out what would have been copied to the clipboard would speed up the process.

- Here is an example repository which uses xdotool underneath https://github.com/HelloWildern/auto-typer
- Or we could use the keyboard library https://pypi.org/project/keyboard/

**Comment by friday** [comment]
It's not possible to do this safely in Linux because all the tools that allow it triggers keyboard combinations for pasting such as "ctrl+v", which is not universal.

See my caverat in https://github.com/friday/ulauncher-clipboard#copy-hook

**Comment by mikebarkmin** [comment]
I though that it might be difficult to implement. Especially when considering the differences between wayland and X11. So I think it  is not worth the hassle of implementing it. I mean copy and pasting is not so bad.
