### ISSUE TITLE
"Unknown sequence number while processing queue"

### ISSUE THREAD

**Issue by friday** [Ulauncher/Ulauncher#667]
### Steps to reproduce
1. Start ulauncher from the terminal with verbose (-v) flag
2. Keep it running until the toggle command stops working

### Current behavior
See 2

### Expected behavior
No crash :)

### Environment
**Ulauncher version**: 5.9.0
**Linux distro**: Arch
**Desktop environment**: Gnome Desktop (GTK+ 3.24.24)

### Logs
```
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python: xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
[1]    5802 abort (core dumped)  ulauncher -v
➜  ~ [233907:233907:1212/143025.760540:ERROR:shared_context_state.cc(74)] Skia shader compilation error
```

**Comment by friday** [comment]
I think it happened coming out of hibernation this time, but the whole reason I've been running it from the terminal was because I had random crashes.

**Comment by gornostal** [comment]
You have mentioned two issues: random crashes and toggle command stops
working.

Have they always been bugging you or they are recent?
Thinking if some updates of system packages could've caused them.

**Comment by friday** [comment]
The process keeps running after the crash, but the toggle stops working.

This is fairly recent. And yeah, XCB is part of X11, so the culprit is almost certainly in a library rather than Ulauncher itself. I still created the issue in case it can be worked around or if other run into the same issue.

**Comment by gornostal** [comment]
I see
I doubt Ulauncher can recover from that crash, but let's keep this issue
open for other people, who may run into this.

**Comment by brandtg** [comment]
Firsly thanks @gornostal, really enjoying ulauncher. Wanted to note that I'm seeing similar crashes occasionally on Ubuntu 20.04.

ulauncher version: 5.9.0
Desktop: Gnome 3.36.8

```
ulauncher.desktop[13670]: [xcb] Unknown sequence number while processing queue
ulauncher.desktop[13670]: [xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
ulauncher.desktop[13670]: [xcb] Aborting, sorry about that.
ulauncher.desktop[13670]: python3: ../../src/xcb_io.c:260: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
```

**Comment by friday** [comment]
The latest X11 release 1.7.0 from about a month ago was supposed to fix this: https://gitlab.freedesktop.org/xorg/lib/libx11#release-170

However given that the issue started appearing recently and they changed that code recently I think it's more likely this fix actually is what created the problem.

**Comment by niraami** [comment]
This is a long post, but I hope it will be helpful. I've been playing with Ulauncher for the past two days.

I'm encountering this issue regularily, and even though this might be a heck of a coincidence, I feel like it is happening when I either:
- Switch focus between windows (maybe the speed also plays a role, as I use i3, just moving the mouse from one edge of the screen to the other end of the other screen changes focus across atleast 2-4 windows in 0.5s).
- I type something specific into the terminal (without having Ulauncher actively open

As I do these two tasks nearly at the same time, It's hard to tell which one causes it (if any of them even are)

, as there could be some delay. Though I really can't reproduce this with 100% success rate, if I wait long enough (just doing my normal everyday tasks in the foreground), it will crash at some point.

Console log output:
```
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python: xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
```

Sequence that I typed on the keyboard just as I saw the message pop up:
```
vim ~/.
```

Journal coredump:
https://gist.github.com/niraami/2d2b934eac87f0a1b6f80145874e660e

For me, this message also means the Ulauncher process is dead, as `ps -A | grep ulauncher` yields no output. Neither does a `htop` search.

Sadly, this makes ulauncher unusable for me, as this happens sporadically without any other sign of it, other than console output. Attached is my ~/.config/ulauncher folder.

Another observation is that, launching Ulauncher, focusing its initial window and pressing ESC often causes an exception - no idea if it is related, but my tendency is to press ESC after launching Ulauncher, so who knows if this puts it into some unstable state.
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 181, in on_input_key_press_event
    Search.get_instance().on_key_press_event(widget, event, self._get_user_query())
  File "/usr/lib/python3.9/site-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/ulauncher/search/Search.py", line 18, in get_instance
    file_browser_mode = FileBrowserMode()
  File "/usr/lib/python3.9/site-packages/ulauncher/search/file_browser/FileBrowserMode.py", line 20, in __init__
    self._file_queries = FileQueries.get_instance()  # type: FileQueries
  File "/usr/lib/python3.9/site-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/ulauncher/search/file_browser/FileQueries.py", line 19, in get_instance
    db.open()
  File "/usr/lib/python3.9/site-packages/ulauncher/utils/db/KeyValueDb.py", line 39, in open
    self.set_records(pickle.load(_in))
EOFError: Ran out of input
```

----
My system
ArchLinux
5.10.16-arch1-1
All packages are up to date
Ulauncher installed from AUR
Python version: 3.9

**Comment by niraami** [comment]
I've found a way to simulate it, but it has nothing to do with the previous times I've seen this occur. Simply press the keybind to display the launcher at the same time (CTRL+Space), as you are launching an application - the timing is pretty tight, but I can reproduce it quite consistently. The trick is to use an application that takes a while to launch, Discord is pretty consistent. Attached is a video recording of it.
YT: https://youtu.be/fbew334W_-Q
Zip: [video.zip](https://github.com/Ulauncher/Ulauncher/files/6016904/video.zip)

**Comment by friday** [comment]
I'm also on Arch, get this several times per day and often when switching display settings (switching to/from external screen, hibernation etc). 

However I also got it when I just used Ulauncher as a calculator, when I often Escape out of it to copy the formula instead of the result. So this fits your idea.

I think one workaround is adding a systemd job for the background process. They can be set to restart when the process dies.

**Comment by dgateley** [comment]
This is an issue for me on Arch as well. I ended up having to enable the system service for it to be usable.

**Comment by friday** [comment]
> This is an issue for me on Arch as well. I ended up having to enable the system service for it to be usable.

That's what I did as well.

**Comment by friday** [comment]
Also have been getting this many times trying to open Preferences:

```
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python: xcb_io.c:171: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.
```

I think this is the culprit:

> I think your issue is the fact that you are accessing unprotected Xlib/xcb from 2 threads - once impicitly from your Gtk+ UI and once in the thread where your [...] backend callback is executed.

https://stackoverflow.com/a/22630490/633921
https://forums.wxwidgets.org/viewtopic.php?t=45734

**Comment by troycurtisjr** [comment]
Note that in my unix socket implementation I will be getting rid of many of the threads, which I'm hoping will improve this situation.
