### ISSUE TITLE
Some apps are not indexed in ulauncher

### ISSUE THREAD

**Issue by ashishbinu** [Ulauncher/Ulauncher#669]
### Steps to reproduce
1.Installed ulauncher using yay -S ulauncher
2.Changed hotkey to super + space.
3.Searching for qutebrowser

### Current behavior
Minecraft and qutebrowser are not indexed while searching in ulauncher.

### Expected behavior
Minecraft and qutebrowser should show up  in dropdown in ulauncher.

### Environment
**Ulauncher version**: 5.9.0
**Linux distro**:  Manjaro Linux x86_64 
**Desktop environment**: Plasma 5.20.4

### Logs

The logs of ulauncher are [here](https://gist.github.com/ashishbinu/4710ef8abfd2aeec2f28a1673491d586) .

**Comment by friday** [comment]
Ulauncher can't index them unless they have desktop entries set to be indexed.

**Comment by friday** [comment]
![quotebrowser](https://user-images.githubusercontent.com/515120/103107429-746ab900-463e-11eb-893d-2373830750e6.png)

It worked for me. Not the same Distro and VM, but at least using Arch

It adds a desktop entity at
/usr/share/applications/org.qutebrowser.qutebrowser.desktop

**Comment by ashishbinu** [comment]
> It adds a desktop entity at
/usr/share/applications/org.qutebrowser.qutebrowser.desktop

![image](https://user-images.githubusercontent.com/56691622/103139646-464fac80-4704-11eb-8d34-e6442aa3b2d5.png)

@friday I do have this file in my /usr/share/applications directory.

**Comment by friday** [comment]
I see. The log actually has the error, but it's vague. Your apparently have a desktop entry in your home directory `~.local/share/applications/org.qutebrowser.qutebrowser.desktop` which overrides the application package one and isn't parsable by the GTK library Ulauncher uses. I think the application package one is never checked for this reason, so neither get indexed.

The home dir one may have been created by yourself, the application or by adding it to the list of "autostart" apps.

The error is similar to this: https://github.com/ubuntu-mate/mate-dock-applet/issues/107

You may want to compare it to the package one to see if there are any differences, and/or delete it and let ulauncher index the other one.

**Comment by ashishbinu** [comment]
Yeah , I have changed it to use custom command to run it in kde gui. Isn't there anyway to index those custom .desktop files in ulauncher.

**Comment by ashishbinu** [comment]
Doing `cp /usr/share/applications/org.qutebrowser.qutebrowser.desktop ~/.local/share/applications/org.qutebrowser.qutebrowser.desktop` have solved the issue. Now ulauncher indexes qutebrowser

**Comment by gornostal** [comment]
@ashishbinu have you figured out how to fix the other desktop file (Minecraft)?
If not, please reopen the issue and post its content here.
