### ISSUE TITLE
xsession-errors, and Ulauncher terminal output: 'show-recent-apps in settings is not a number'

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [Ulauncher/Ulauncher#674]
### Steps to reproduce
1. Run ulauncher
2. Possibly: use it search, and then launch something.

### Current behavior

Errors in `.xsessions-errors`.

### Expected behavior

No such errors. For, there could be a real problem and, if not, then this is log spam.

### Environment
**Ulauncher version**: 5.9.0
**Linux distro**: Mint 20.1
**Desktop environment**: Cinnamon

### Logs
[Terminal output](https://gist.github.com/LinuxOnTheDesktop/af8f35d93833092375ea9af1b703b854)
[xsessions excerpt](https://gist.github.com/LinuxOnTheDesktop/78d3d77ebc213f66b2b2204cb16c22d0)

**Comment by gornostal** [comment]
@LinuxOnTheDesktop that warning is not expected there.
What does this command give: `grep show-recent-apps ~/.config/ulauncher/settings.json`?

**Comment by LinuxOnTheDesktop** [comment]
@gornostal 

Thanks for looking at this.

```
$ grep show-recent-apps ~/.config/ulauncher/settings.json
    "show-recent-apps": true,
```

**Comment by gornostal** [comment]
Ah, now I remember what that is.
It's not a bug. There was a migration -- at some point we had a flag (true/false) that enabled/disabled a list of recent apps and then we change the value to a number.
If you open Ulauncher Preferences and change that setting, the warning will be gone.

**Comment by LinuxOnTheDesktop** [comment]
I do not see how that is not a bug. For, it means that upgrading Ulauncher causes a problem. Moreover, I found that the setting in question was set to a number, though when I changed that number to another number, the warning seemingly disappeared. So seemingly the ulauncher preferences window was showing false information.

**Comment by gornostal** [comment]
What problem did it cause?

**Comment by LinuxOnTheDesktop** [comment]
Presumably the numeric value showing, within the GUI, in 'recent apps' was not being honoured. Also, spurious warnings are bugs, at least in an attenuated sense. For, they clutter logs and can generate anxiety and can waste time.

**Comment by gornostal** [comment]
Sorry, I didn't quite understand what is not working exactly.

BTW, I've removed the warning. The change will be included in a next release.
