### ISSUE TITLE
Feature: Disabling / enabling extensions from preferences

### ISSUE THREAD

**Issue by Sparky1492** [Ulauncher/Ulauncher#677]
### Is your feature request related to a problem? Please describe

I thought of the idea while trying to solve an issue with two different extensions.
     _**(If needed I can create another ticket with the issue of the two different extensions in question, please let me know if I need to)_ 
The two plugins in question are [Ip Copy Extension](https://github.com/pwnyprod/ulauncher-ipcopy) and [IP Lookup Extension for ULauncher](https://github.com/munim/ulauncher-ip-lookup), both use the same keyword 'ip' to trigger their extensions.  If I changed extension 1's keyword, then extension 2's keyword would also changed to the same keyword.

### Describe the solution you'd like

This lead to the thought of having the ability to disable or enable plugins to either trace down an issue to a plugin or to keep a plugin that is not needed but wanted to be kept and can be re-enabled at a later date.  Otherwise you would have to keep a list of the extensions and re-pasting them.  If the ability to disable and enable is made available to scripting, then custom scripts could be made to disable or enable as the user would like.

### Additional context

Highlighted
![Feature-Reqeust_2021-01-14 14:27_highlited](https://user-images.githubusercontent.com/945772/104656859-a2637c00-5685-11eb-9814-4b51adb8cfc6.png)

Without Highlighting
![Feature-Reqeust_2021-01-14 14:27](https://user-images.githubusercontent.com/945772/104656916-b7d8a600-5685-11eb-8989-09a902477f42.png)

**Comment by gornostal** [comment]
Yep! It's nice to have.

I'm not a big fan of the checkboxes on the side though.
If anyone is interested in implementing this, just make the extension name grayed out (`opacity: 0.5` or something like that)

**Comment by freddii** [comment]
Just the ability do be able to disable an extension by the drop down menu would be ok for the beginning.
