### ISSUE TITLE
Support opening url shortcuts in different browsers

### ISSUE THREAD

**Issue by balazsorban44** [Ulauncher/Ulauncher#682]
First of all, thanks for this awesome utility application, it saves me so much time throughout the day! ♥
### Is your feature request related to a problem? Please describe
I have two different Chrome profiles, one for private use, and one for work. I would like to create some shortcuts for searching on websites that are work-related (and therefore should be opened in the work Chrome profile) and some that are not. (and therefore should be opened in my private Chrome profile)

Currently, what I can gather from the following source file: https://github.com/Ulauncher/Ulauncher/blob/dev/ulauncher/api/shared/action/OpenUrlAction.py

and from `webbrowser` documentation: https://docs.python.org/3/library/webbrowser.html#webbrowser.open_new_tab

calling `webbrowser.open_new_tab(self.url)` will use the default browser.

### Describe the solution you'd like
I would like it to somehow be configurable which browser profile should open a certain URL shortcut, if possible.

The best place in my opinion would be on the following screenshot, under the current options:
![image](https://user-images.githubusercontent.com/18369201/105424099-00283300-5c47-11eb-9f9b-93e769aeb9a8.png)

It could show a dropdown list of all the possible browsers. The default value should be the default browser. Changing this to another browser should open the selected browser when a URL shortcut with a query is called.

### Additional context

I am on Ubuntu 20.04, and not a Python programmer, but with some guidance, I might be able to open a PR for this just to get out of my JavaScript comfort zone. 😅

**Comment by ehsabd** [comment]
I've created this branch and added this function:
https://github.com/ehsabd/Ulauncher/tree/browser-command-setting

I'm preparing PR notes. Particularly, adding the unit test and updating the doc.

**Comment by balazsorban44** [comment]
Awesome, @ehsabd !

**Comment by ehsabd** [comment]
Can you run the branch and see how it fits to your original idea. It might be a bit different as it needs the user to specify browser command as mentioned [here](https://stackoverflow.com/a/24353812/2571422). For example it's ``/usr/bin/chromium-browser`` for my chromium but needs to be different for another OS or browser. So it's not like a dropdown that one picks the browser. But surely it's a starting point.

**Comment by balazsorban44** [comment]
thanks, I'll check that when I have the time!

**Comment by gornostal** [comment]
> I'm preparing PR notes. Particularly, adding the unit test and updating the doc.

Wait. There's an alternative approach that doesn't require any changes in Ulauncher:
![image](https://user-images.githubusercontent.com/1202543/105636984-a0629f80-5e73-11eb-82d0-3e23355063c7.png)

You can replace `google-chrome` with any browser that you want to use. You can also use `--profile-directory` flag there to tell Chrome which profile to use.

You can even go further and create a more sophisticated bash script that will read a profile name from a file (let's say ~/.my-current-chrome-profile) and by changing that file you'll be able to control what profile is used.

All that is to keep Ulauncher as simple as possible. And in this case it's definitely possible to have either `bash` shortcut or an extension to solve the problem.

**Comment by balazsorban44** [comment]
Thank you @gornostal! If Ulauncher supports this already I'm any way, I respect it. 🙂 I'll check out your suggestions. I wanted to try node (as I'm a javascript developer), but I'd didn't know how to introduce dependencies in the script. Do you maybe know how to use third party packages in the script? I tried installing them locally, but nothing happened.

I understand if you have no JS experience, then I'll just try bash.

**Comment by gornostal** [comment]
@balazsorban44 you can implement a shortcut in JS as a normal CLI command. You'll receive search queries in `process.argv`.
Then create a shortcut as I posted on the screenshot, just replaces its content with:
```
#!/bin/sh

exec node /path/to/your/shortcut.js $@
```
