### ISSUE TITLE
Is it possible to use Ulauncher as a complete dmenu replacement?

### ISSUE THREAD

**Issue by kamushadenes** [Ulauncher/Ulauncher#683]
## Question

Hello there,

Is it possible to use ULauncher as complete dmenu/rofi/wofi replacement?

What I mean by this is, can I do something like "task add $(ulauncher -p "Task Description)" to get the output of whatever the user types, as dmenu-like alternatives do?

Or may I even present scripted options, like "echo Opt 1\nOpt 2\nOpt3 | ulauncher" and get the user selection?

Currently, I'm running both ulauncher (as a launcher) and wofi (as a selection/input box), but I would like to use only ulauncher, if at all possible.

Thanks!

**Comment by gornostal** [comment]
Hi @kamushadenes 
I'm not familiar with dmenu or rofi. Could you elaborate more on the use cases?

**Comment by kamushadenes** [comment]
Hello @gornostal , sure thing!

Talking about dmenu specifically (and keeping in mind rofi/wofi are similar alternatives that do basically the same thing), dmenu is a dynamic menu that has a few modes:

- run: this mode basically displays everything on your $PATH so you can run commands
- ssh: allows you to select hosts configured in .ssh/config, and spawns a terminal connecting to that host
- drun: same as run, but for .desktop file (this is what ulauncher does by default)

Besides that, it also allows the usage on scripts, allowing the user to either input something or select an option from a dynamically-generated list. 

For example the following command:

`dmenu -p "Please input something"` 

![dmenu_1](https://user-images.githubusercontent.com/242529/105637856-6501aa00-5e4e-11eb-87d0-80a46a956289.png)

Returns whatever the user inputs.

![2021-01-24T14:09:47,999646819-03:00](https://user-images.githubusercontent.com/242529/105637793-04726d00-5e4e-11eb-9d75-19e2232b9dae.png)

Or running `echo -e 'Option 1\nOption 2\nOption 3'  | dmenu`

![2021-01-24T14:11:42,107532230-03:00](https://user-images.githubusercontent.com/242529/105637895-a1350a80-5e4e-11eb-9500-a1d8b39a1a72.png)

Returns the option the user selects between the provided ones (separated by \n).

![2021-01-24T14:11:45,375817685-03:00](https://user-images.githubusercontent.com/242529/105637832-3be11980-5e4e-11eb-8ca4-04177784e195.png)

Think of it like [zenity](https://help.gnome.org/users/zenity/stable/).

This is extremely useful for scripting, specially for users running on tilling WMs (like i3 and sway).

The reason I opened this issue is that I already use ulauncher to run .desktop files and terminal commands, and would like to also use it for those kind of scripts.

So something like `echo "The user input is: $(ulauncher -p "Type Something")"` would open ulauncher to ask the user to input something, which in turn would be return by the command, allowing the use on scripts.

Hope this made my intention clearer, let me know if anything still needs clarification.

**Comment by gornostal** [comment]
Now I see what you are looking for.
Currently Ulauncher doesn't support such things. Even with the extension API it can't really fit into those use cases.
And most likely it will never will as I wan't to keep it simple.

You'll probably want to continue using dmenu and rofi for that.
