### ISSUE TITLE
Format the calc mode output with a thousand separator

### ISSUE THREAD

**Issue by amadeusrotundo** [Ulauncher/Ulauncher#688]
Would love the output of the calculator function to add in a thousands separator.  Very hard to discern values when very large.

**Comment by nishp77** [comment]
@amadeusrotundo Would like to confirm that all you want is for the output (result of the query)?

**Comment by amadeusrotundo** [comment]
Confirmed

**Comment by friday** [comment]
I renamed this to distinguish it from the other issues with people wanting to support comma in the input (not as a thousand separator).

Formatting the output is much easier than that. I would suggest to use the user locale to do it. That way Ulauncher doesn't have to add an option to the settings specifically for this.

**Comment by BharatKalluri** [comment]
Hey @friday , let me know if I can pick this up.

Python already has a friendly function called [`locale.format_string`](https://docs.python.org/3/library/locale.html#locale.format_string) which takes in the current locale into account and groups the result by adding a comma sep. here is an example

```python
>>> locale.format_string("%d", 1231234, grouping=True)
'1,231,234'
```

on enter, the non comma separated value will be copied as suggested. If this sounds good, I'll be making a PR against the `v6` branch.

**Comment by friday** [comment]
Go ahead @BharatKalluri :+1: I think it's a perfect one. The [contributor-friendly](https://github.com/Ulauncher/Ulauncher/labels/contributor-friendly) ones are tasks that don't require deep knowledge of the Ulauncher architecture, although they might still not be "easy".

**Comment by friday** [comment]
This is now supported in the Ulauncher v6 branch (thank you @BharatKalluri). V6 won't be released for a while, but we made a tracking issue if you want to be notified #869
