### ISSUE TITLE
Feature request: Applications plugin should also index desktop files in user Desktop folder (~/Desktop)

### ISSUE THREAD

**Issue by uffejakobsen** [Ulauncher/Ulauncher#690]
Feature request: Applications plugin should also index desktop files in user Desktop folder (~/Desktop)

Within several Desktop Environments you can simply right click on an empty spot on your desktop and create a new .desktop file there. Some Desktop Environments call the context menu function "Create Launcher" others may use other names.

Rationale:
Personally I see it as a quite powerful feature for "every day" workflow situations using a Linux desktop workstation.
Creating customized .desktop shortcuts etc that quickly and always are available on your desktop is quite powerful.
It has several productivity enhancing advantages even for existing applications that already has a shared application - you can quickly and easy make your own custom launch profile for such applications supplying it with extra startup-arguments, working ir etc... creating customized script-oneliners embedded within the .desktop itself is another powerful task.

The essence of all this is that being able to reach these .desktop files from within Ulauncher would make productivity go up

It may be out of spec - I don't know - but you can - it works - and it is really powerful - and yes - the Desktop Environments places these .desktop files on your desktop - and the resulting .desktop files are located under ~/Desktop (just tested using LXQt and LXDE)

**Comment by friday** [comment]
See https://specifications.freedesktop.org/menu-spec/menu-spec-0.92.html#paths

python -c "from xdg.BaseDirectory import xdg_data_dirs; print(xdg_data_dirs)" will print these dirs. Desktop entries should only be located in subdirectories named "applications" inside of these. You can override and add your own by setting XDG_DATA_DIRS variable
