### ISSUE TITLE
Ulauncher doesn't read .desktop files form /usr/local/share/applications/ or /home/name/.local/share/applications/

### ISSUE THREAD

**Issue by echometerain** [Ulauncher/Ulauncher#694]
### Steps to reproduce
1. Install Ulauncher on Manjaro

### Current behavior
Ulauncher doesn't read .desktop files form /usr/local/share/applications/ or /home/name/.local/share/applications/, including both user created files and some of the files installed with AUR.

### Expected behavior
Ulauncher reads and launches these .desktop files, just like any other app launcher

### Environment
**Ulauncher version**: 5.9.0-1
**Linux distro**: Manjaro GNU/Linux
**Desktop environment**: KDE Plasma 5.20.5

### Logs
https://gist.github.com/rain1598/16782b23da10400321a8057242fd11f1

**Comment by friday** [comment]
I'm also on Arch and can't reproduce this, and the gist has been deleted now. If it's still happening please create a new issue.
