### ISSUE TITLE
Can't set shortcut that uses Super key

### ISSUE THREAD

**Issue by cr0sis** [Ulauncher/Ulauncher#696]
### Current behavior
Tried to use my shortcut to open the ulauncher popup - unresponsive
Opened the popup with console, tried to set a new shortcut, input isn't registering. Now the shortcut field is blank.

### Expected behavior
Expected the shortcut field to not be blank after setting one?

### Environment
**Ulauncher version**: 5.10.0
**Linux distro**: Mint 20
**Desktop environment**: Cinnamon
One thing to note, before yesterday I was on kernel 5.9, I updated to 5.11 24 hours ago and ulauncher has been like this since.

### Logs
Output running ulauncher -v from console (-v flag unnecessary, same output without and I get a similar warning for other gui apps, i've just ignored it until now):
(ulauncher:6077): Gtk-WARNING **: 17:19:57.402: Theme parsing error: gtk.css:6329:10: 'height' is not a valid property name

### Update
It's the super key causing me problems, I can set a combination of keys that don't include super and the app works fine.

**Comment by cr0sis** [comment]
I'm sorry for wasting anyones time, I discovered my keyboard has a super key disable / enable feature and somehow it was toggled.

**Comment by sirianni** [comment]
I'm not able to set the shortcut using `Super` key.  I can use `Super` key fine in other applications.

**Comment by friday** [comment]
#922

**Comment by sirianni** [comment]
Sorry, I wanted to set it to `Super + <other key>` (e.g. `Space`), not `Super` only.  I found https://github.com/Ulauncher/Ulauncher/issues/475 and seems I need to do this at the Window Manager level.
