### ISSUE TITLE
Feature request - Hotkey effect on key release 

### ISSUE THREAD

**Issue by MaxandreOgeret** [Ulauncher/Ulauncher#697]
### Is your feature request related to a problem? Please describe

When setting the hotkey to super key, the hotkey super + arrows don't work anymore for moving the windows on ubuntu.

### Describe the solution you'd like

Create option to make hotkey take affect on key release so it will not interfere with ubuntu shortcut.

**Comment by liyafe1997** [comment]
I have this problem too, once I set the super as hotkey, other hotkey based on super key doesn't work anymore...

**Comment by friday** [comment]
I'm not sure we can fix that. The library we use is kind of handling it all for us. You can use th workaround described here instead though (it works for both XOrg and Wayland): https://github.com/Ulauncher/Ulauncher/wiki/Hotkey-In-Wayland

**Comment by friday** [comment]
Going to close this is not something we can even support. I have created a new discussion page that covers this issue (same info as the wiki link pretty much): https://github.com/Ulauncher/Ulauncher/discussions/991
