### ISSUE TITLE
Wayland Fullscreen behaviour

### ISSUE THREAD

**Issue by Iss-in** [Ulauncher/Ulauncher#701]
AFAIK for now ulauncher behaves as a toolkit, ( same as other floating windows) . But in given wayland DEs are implementing their specific [layer_shell_protocol](https://github.com/swaywm/wlr-protocols/blob/master/unstable/wlr-layer-shell-unstable-v1.xml),  ( implemented in sway, and likely to be merged soon in plasma [too](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/28) ), launcher will always be hidden behind a fullscreen window.

Will it be possible to make use of this protocol and make ulauncher always use the top layer to be shown above fullscreen ?

**Comment by hhurma** [comment]
I am using a manjaro gnome. Ulauncher does not appear on the desktop. But if I open a fullscreen app it shows up.

**Comment by Jaakkonen** [comment]
https://github.com/wmww/gtk-layer-shell has a python example https://github.com/wmww/gtk-layer-shell/blob/master/examples/simple-example.py of using `wlr_layer_shell_unstable_v1` for PyGTK windows.
