### ISSUE TITLE
Broken dependencies on Debian Bullseye 

### ISSUE THREAD

**Issue by hegerdes** [Ulauncher/Ulauncher#702]
Hi,

I just tried out Debian Bullseye and wanted to install your luncher but the dependencies may have changed.

`
The following packages have unmet dependencies:
 ulauncher : Depends: gir1.2-appindicator3-0.1 but it is not installable
`

Bullseye only contains:

 * gir1.2-ayatanaappindicator-0.1 (0.5.5-2)
 * gir1.2-ayatanaappindicator3-0.1 (0.5.5-2)

As far as I know GObjects is the way to go by now because the old way is depreciated.

There is a version ob lipappindicator3-0.1 with GObject bindings but it requires changes

### Environment
**ULuncher: v5.10.0**:
**Debian Bullseye**:
**xfce**:

**Comment by gadc1996** [comment]
Try installing using
```
dkg -i <packageName>
```

You should get an output like this one:
```
(Reading database ... 189619 files and directories currently installed.)
Preparing to unpack ulauncher_5.10.0_all.deb ...
Unpacking ulauncher (5.10.0) over (5.10.0) ...
dpkg: dependency problems prevent configuration of ulauncher:
 ulauncher depends on python3-pyinotify; however:
  Package python3-pyinotify is not installed.
 ulauncher depends on libkeybinder-3.0-0; however:
  Package libkeybinder-3.0-0 is not installed. ulauncher depends on gir1.2-gtk-3.0; however:
  Package gir1.2-gtk-3.0 is not installed.
 ulauncher depends on gir1.2-keybinder-3.0 (>= 0.3); however:
  Package gir1.2-keybinder-3.0 is not installed.
 ulauncher depends on gir1.2-webkit2-4.0 | gir1.2-webkit2-3.0; however:
  Package gir1.2-webkit2-4.0 is not installed.
  Package gir1.2-webkit2-3.0 is not installed.
 ulauncher depends on gir1.2-notify-0.7; however:
  Package gir1.2-notify-0.7 is not installed.
 ulauncher depends on gir1.2-gdkpixbuf-2.0; however:
  Package gir1.2-gdkpixbuf-2.0 is not installed.
 ulauncher depends on gir1.2-appindicator3-0.1; however:
  Package gir1.2-appindicator3-0.1 is not installed.
 ulauncher depends on python3-gi-cairo; however:
  Package python3-gi-cairo is not installed.
 ulauncher depends on python3-distutils-extra; however:
  Package python3-distutils-extra is not installed.
 ulauncher depends on python3-levenshtein; however:
  Package python3-levenshtein is not installed.
 ulauncher depends on python3-websocket; however:
  Package python3-websocket is not installed.

dpkg: error processing package ulauncher (--install):
 dependency problems - leaving unconfigured
Processing triggers for mime-support (3.62) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 ulauncher
```

Then you enter this command:
```
sudo apt -f install
dpkg -i <packageName>
```

This should get things going

**Comment by hegerdes** [comment]
Thanks I tried that but i did not work.

gir1.2-appindicator3-0.1 is not installable. So it does mean it is not in the official debian bullseye repositories. And it probably wont be because it is deprecated. The new way to go is GObjects

**Comment by gornostal** [comment]
Fixed the issue by making the appindicator dependency optional. Gnome doesn't have indicators enabled by default anyway.
Feel free to reopen if you see any issues.
