### ISSUE TITLE
Ulauncher extensions crash with Gdk error (Fedora 34)

### ISSUE THREAD

**Issue by sebw** [Ulauncher/Ulauncher#703]
### Steps to reproduce
1. Install Fedora 34 PRE-RELEASE
2. Install ulauncher from Fedora repositories 
3. Enable an extension (for example https://github.com/Ulauncher/ulauncher-emoji)

### Current behavior

Extension crashes with:

2021-03-07 13:31:28,097 | ERROR | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.ulauncher.ulauncher-emoji" failed with an error: ImportError: Requiring namespace 'Gdk' version '3.0', but '4.0' is already loaded

### Expected behavior

No crash

### Environment
**Ulauncher version**: 5.10.0
**Linux distro**: Fedora 34 PRE-RELEASE
**Desktop environment**: i3wm

Red Hat bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1936182

**Comment by semka95** [comment]
Having same issue

### Extension crashes with:

$ GDK_BACKEND=wayland ulauncher --hide-window
2021-03-08 16:32:32,147 | ERROR | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.ygun.ulauncher-nm" exited instantly with code 1
2021-03-08 16:32:32,147 | ERROR | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.ygun.ulauncher-nm" failed with an error: ImportError: Requiring namespace 'Gdk' version '3.0', but '4.0' is already loaded

### Environment

Ulauncher version: 5.10.0
Linux distro: Manjaro 20.2.1
Desktop environment: sway 1.5.1

**Comment by sebw** [comment]
The problem is caused by the gtk4 package. If I uninstall it Ulauncher and all extensions start properly (but maybe create other problems elsewhere, not sure yet).

**Comment by danielhass** [comment]
This is quite severe on "up-to-date" systems/distros.
As @semka95 already indicated via Manjaro this also hits Arch Linux users.

#### Environment
Ulauncher version: 5.10.0
Linux distro: Arch Linux 5.11.11-arch1-1
Desktop environment: Xfce 4.16

Would love to see #717 being merged.

**Comment by ozls** [comment]
Same issue with up-to-date stable Arch, since gtk4 was installed as a dependency of gnome-shell 40. I support merging #717 as soon as possible.

**Comment by LJ-Court** [comment]
exactly the same also on fedora 34, please can #717 be imported as soon as possible

**Comment by tim77** [comment]
We can patch it in downstream and update Fedora package for >= f34. What do you think?

**Comment by LJ-Court** [comment]
That sounds great @tim77 looking forward to using extensions again

**Comment by friday** [comment]
Extension devs can "fix" it on thier side too like this https://github.com/friday/ulauncher-hash2/commit/7478980b8fd6d9da3454dd0fb9ec232d7457a3c6, but they shouldn't have to.

**Comment by codyfish** [comment]
> Extension devs can "fix" it on thier side too like this [friday/ulauncher-hash2@7478980](https://github.com/friday/ulauncher-hash2/commit/7478980b8fd6d9da3454dd0fb9ec232d7457a3c6) **before** the ulauncher imports, but they shouldn't have to.

Thanks alot. 
I have the same issues as mentioned above on arch, but this workaround fixed every extension.

**Comment by vincens2005** [comment]
This workaround worked for me (manjaro) but can this be fixed directly from ulauncher?

**Comment by troycurtisjr** [comment]
This has been merged to dev and will be in the next release. 

Also note that the fixed was patched in the Fedora package starting with 5.11.0-3 in both Fedora 33 (not that it matters much there) and Fedora 34.

**Comment by kskollepara** [comment]
Has this issue been solved? I get same errors after upgrading to Ubuntu 22.04.

**Comment by friday** [comment]
> Has this issue been solved? I get same errors after upgrading to Ubuntu 22.04.

Make sure you use the latest version and if you still get this issue create a new issue and if so follow the issue template closely to make a new issue.
