### ISSUE TITLE
Deleted apps still showing

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [Ulauncher/Ulauncher#704]
### Steps to reproduce
1. Open Ulauncher's search box (by any means).
2. Type something that brings up launchers that no longer exist. (For, this can happen.)

### Current behavior

See above.

### Expected behavior

If the program cannot avoid showing non-existent launchers, there needs to be a command to purge them. 

### Environment
**Ulauncher version**: 5.10.0
**Linux distro**: Mint 20.1
**Desktop environment**: Cinnamon

### Logs

[Here](https://gist.github.com/LinuxOnTheDesktop/ee292084c0f52ff10463fbdb50f2734e).

**Comment by friday** [comment]
This will be fixed in the Ulauncher v6 branch, as this branch has completely rewritten this part or the app and doesn't cache this data any more. It won't be released for a while, but we made a tracking issue if you want to be notified #869
