### ISSUE TITLE
Ulauncher can't find an app installed with flatpak(Viber)

### ISSUE THREAD

**Issue by nlukovic** [Ulauncher/Ulauncher#710]
### Steps to reproduce
1. Install an app from Flatpak, in my case it was Viber
2. Search for Viber with ULauncher
3. Viber doesn't show up

### Current behavior
Installed app from Flatpak doesn't show up when searching for it.

### Expected behavior
It should show up

### Environment
**Ulauncher version**: 5.10.0
**Linux distro**: KDE Neon 5.21
**Desktop environment**: KDE Plasma 5.21.2

### Logs
**https://gist.github.com/nlukovic/0c1929ec13e94bdd0fdfbc2e1d38b6b1**

I've installed Viber from flatpak and on my machine `.desktop` file is located here: 
```
/var/lib/flatpak/app/com.viber.Viber/x86_64/stable/9076c208a69ae2ee56d7bbd15fd85d180c2cbc5695cfa5dcbc212e1c90e82434/export/share/applications/com.viber.Viber.desktop
/var/lib/flatpak/app/com.viber.Viber/x86_64/stable/9076c208a69ae2ee56d7bbd15fd85d180c2cbc5695cfa5dcbc212e1c90e82434/files/extra/export/share/applications/com.viber.Viber.desktop
```
Restarting PC helped with the issue

**Comment by friday** [comment]
The desktop app path (something like `/var/lib/flatpak/exports/share/applications/`) must be in `XDG_DATA_DIRS` https://github.com/flatpak/flatpak/issues/1286.

This should be handled by your system. If it's not, try the default Gnome launcher (Super+A) or another Launcher. If it works there, but not in Ulauncher there's probably something we could do better.
