### ISSUE TITLE
Installation via ppa not working on debian

### ISSUE THREAD

**Issue by gadc1996** [Ulauncher/Ulauncher#711]
### Is your feature request related to a problem?  Instrucctions about installation in debian are not so straight-fordward, on the website it shows the following commands for installation

```
ppa:agornostal/ulauncher

sudo apt install ./packagename.deb

```

But this method is not working on debian due to dependencies, also, the the `ppa:agornastal/ulauncher` does not work as a command since it has to be used as `sudo apt-add-repository ppa:agornastal/ulauncher`

### Describe the solution you'd like
Add debian to the installation section of [ulauncher website](ulauncher.io) with this instrucctions:

```
sudo dpkg -i <packageName>
sudo apt -f install
sudo dpkg -i <packageName>

```
### Additional context
If you are ok with this changes i can do them myself

**Comment by kilthy** [comment]
Dude! You are a life saver! Thank you so much! Been digging deep trying to troubleshoot this exact issue.

**Comment by troycurtisjr** [comment]
seems like a good suggestion for clarification. I'm sure the ppa was simply listed since there are different ways to add them, but providing a fully working example is definitely a good idea.

**Comment by friday** [comment]
This should be fixed now.

https://ulauncher.io/#Download

New instructions say:

Install via PPA:
sudo add-apt-repository ppa:agornostal/ulauncher && sudo apt update && sudo apt install ulauncher

Alternatively, you can download the .deb file and run:
sudo apt install ./ulauncher_x.y.z_all.deb or just double click.

If these instructions don't work for anyone, please create a new issue.

**Comment by friday** [comment]
Looks like I only read half of this issue🤦.Sorry about that.

**Comment by friday** [comment]
I tried it now and the fallback in the current instructions works for debian bullseye `sudo apt install ./ulauncher_x.y.z_all.deb`. The ppa doesn't, but at least it's documented correctly and there's another issue for that.
