### ISSUE TITLE
Store extension preferences in a standardizes config format (not Pickle)

### ISSUE THREAD

**Issue by lorenzleutgeb** [Ulauncher/Ulauncher#712]
### Problem
I am developing a [Home Manager](https://github.com/nix-community/home-manager) module to configure Ulauncher. This includes specifying the contents of `$XDG_CONFIG_HOME/ulauncher/{settings,shortcuts,extensions}.json`. I saw that Ulauncher supports extension specific preferences, and that they are stored under `$XDG_CONFIG_HOME/ulauncher/ext_preferences/*/*.db` in a format specific to Python.
Nix does not support this format, but it does support JSON.

Just to get a feel for it, the configuration will look similar to:

```nix
{
  services.ulauncher = {
    enable = true;
    config = {
      extensions = {
        "com.github.rdnetto.ulauncher-sway" = pkgs.fetchFromGitHub {
          owner = "rdnetto";
          repo = "ulauncher-sway";
          rev = "ca6e8365723fd444b302236fb72eded4a1378c3e";
          sha256 = "0ac8g30wx181bjqgi2wsccdjvzybqfjalh1pn7sjb2bw3mh594cn";
        };
        # Somewhere around here, I'd like to implement passing preferences for the extension.
      };
      settings = {
        "clear-previous-query" = true;
        "hotkey-show-app" = "<Primary>space";
        "render-on-screen" = "mouse-pointer-monitor";
        "show-indicator-icon" = true;
        "show-recent-apps" = "0";
        "terminal-command" = "";
        "theme-name" = "dark";
      };
      shortcuts = {
        # Here go my shortcuts.
      };
    };
  };
}

```

### Proposed Solution
I propose to use `KeyValueJsonDb` instead of `KeyValueDb` for extension preferences, so that external tools can inspect or even provide the underlying JSON "database".

### Additional Context
[Home Manager](https://github.com/nix-community/home-manager) is closely related to the [Nix package manager](https://en.wikipedia.org/wiki/Nix_package_manager) and [NixOS](https://nixos.org), a Linux distribution.

**Comment by friday** [comment]
Does Nix support Toml? I would assume you do. I personally would favor toml over json, yml or other formats. Toml is more terse and easy to manage. It is intended for configuration files, and similar to the old ini-format that still has a lot of use.

It would add a dependency to python-toml, but that's already needed by pip, which users likely have.

**Comment by lorenzleutgeb** [comment]
> Does Nix support Toml? I would assume you do. I personally would favor toml over json, yml or other formats. Toml is more terse and easy to manage. It is intended for configuration files, and similar to the old ini-format that still has a lot of use.

Yep, sounds good. JSON was just the first candidate to come to mind since this project already uses it for other config files.

**Comment by friday** [comment]
It's not high on my list, but changing the config format is something I wanted to do, and [JSON isn't a config format](https://www.lucidchart.com/techblog/2018/07/16/why-json-isnt-a-good-configuration-language/). People just use it for that because it's everywhere.

So this question was more to add my 5c to the issue.

**Comment by friday** [comment]
This will be fixed in the Ulauncher v6 branch (see PR linked above). It won't be released for a while, but we made a tracking issue if you want to be notified #869
