### ISSUE TITLE
Handle non-writable JSON configuration files gracefully

### ISSUE THREAD

**Issue by lorenzleutgeb** [Ulauncher/Ulauncher#713]
### Is your feature request related to a problem?

My `$XDG_CONFIG_HOME/ulauncher/shortcut.json` (and other configuration files) are stored on a read-only filesystem. Even though, I did not intend to change any shortcuts (or other configuration), Ulauncher crashes:

```
2021-03-18 20:06:13,763 | ERROR | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/nix/store/14v82vqp4jwxxh0ksmm92fi4gx5jjifp-ulauncher-5.9.0/lib/python3.8/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 181, in on_input_key_press>
    Search.get_instance().on_key_press_event(widget, event, self._get_user_query())
  File "/nix/store/14v82vqp4jwxxh0ksmm92fi4gx5jjifp-ulauncher-5.9.0/lib/python3.8/site-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/nix/store/14v82vqp4jwxxh0ksmm92fi4gx5jjifp-ulauncher-5.9.0/lib/python3.8/site-packages/ulauncher/search/Search.py", line 20, in get_instance
    shortcut_search_mode = ShortcutSearchMode()
  File "/nix/store/14v82vqp4jwxxh0ksmm92fi4gx5jjifp-ulauncher-5.9.0/lib/python3.8/site-packages/ulauncher/search/shortcuts/ShortcutSearchMode.py", line 10, in __init__
    self.shortcutsDb = ShortcutsDb.get_instance()
  File "/nix/store/14v82vqp4jwxxh0ksmm92fi4gx5jjifp-ulauncher-5.9.0/lib/python3.8/site-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/nix/store/14v82vqp4jwxxh0ksmm92fi4gx5jjifp-ulauncher-5.9.0/lib/python3.8/site-packages/ulauncher/search/shortcuts/ShortcutsDb.py", line 22, in get_instance
    db.commit()
  File "/nix/store/14v82vqp4jwxxh0ksmm92fi4gx5jjifp-ulauncher-5.9.0/lib/python3.8/site-packages/ulauncher/search/shortcuts/ShortcutsDb.py", line 28, in commit
    super(ShortcutsDb, self).commit()
  File "/nix/store/14v82vqp4jwxxh0ksmm92fi4gx5jjifp-ulauncher-5.9.0/lib/python3.8/site-packages/ulauncher/utils/db/KeyValueJsonDb.py", line 31, in commit
    with open(self._name, 'w') as out:
OSError: [Errno 30] Read-only file system: '/home/lorenz/.config/ulauncher/shortcuts.json'
```

#### Proposal 1

Recover from failure to store configuration: Instead of erroring/crashing, log a warning and carry on.

#### Proposal 2

Distinguish between scenarios where the user intentionally wants to save settings, and where the system saves settings "just to be sure". The former could error/crash, while the latter might be recoverable.

#### Proposal 3

Only ever store configuration to disk when the user explicitly requests that (by click of a button, etc.).

**Comment by WhosyVox** [comment]
`ulauncher/search/shortcuts/ShortcutsDb.py:22`

We're calling `db.commit()` regardless of whether anything has changed - shouldn't this instead be added to the `is_first_run` condition above?

Additionally in `ulauncher/utils/db/keyValueJsonDb.py` there's exception handling for `open` but not `commit`.

Perhaps we ought consider how to handle error read/write issues since permission issues, drive failures and such are always going to be an issue in some edge case.

**Comment by lorenzleutgeb** [comment]
> We're calling `db.commit()` regardless of whether anything has changed - shouldn't this instead be added to the `is_first_run` condition above?

I think this would help in my case: The file exists, It's just not writable.

> Perhaps we ought consider how to handle error read/write issues since permission issues, drive failures and such are always going to be an issue in some edge case.

Yes. It's tough to distinguish cases where I/O errors and it can be handled gracefully (logging, informing the user) vs. cannot be handled gracefully (crash) in general.

**Comment by WhosyVox** [comment]
> > We're calling `db.commit()` regardless of whether anything has changed - shouldn't this instead be added to the `is_first_run` condition above?
> 
> I think this would help in my case: The file exists, It's just not writable.
> 
> > Perhaps we ought consider how to handle error read/write issues since permission issues, drive failures and such are always going to be an issue in some edge case.
> 
> Yes. It's tough to distinguish cases where I/O errors and it can be handled gracefully (logging, informing the user) vs. cannot be handled gracefully (crash) in general.
> 
> > I've had a go at trying to resolve some of the above. Could you try running from my branch over here?
> 
> I installed Ulauncher [via Nixpkgs](https://github.com/NixOS/nixpkgs/blob/nixos-20.09/pkgs/applications/misc/ulauncher/default.nix#L115) and don't have time to go through the process of setting up your fork at the moment. However, your reasoning checks our for me, so I think it would definitely improve the situation.

I'm probably to blame on this one. I'm hopeless with git and I've ended up somehow writing multiple patches to a single branch.
I wish I could just email someone the patches instead, can't seem to get this all to work.

I'll see if I can't untangle this mess and get some merge requests in. ULauncher seems to be a little lacking in development right now.

**Comment by troycurtisjr** [comment]
I think more graceful handling of the errors is definitely warranted, but I'm not sure we'd really be up for signing up for supporting running on a read-only filesystem. Without the right kinds of integrations tests, it will likely be fragile and be easy to break often. Adding code in for tracking when things are different between the in memory and on disk configuration is probably not worth the very narrow use case. What do you think @friday ?

**Comment by friday** [comment]
I'm not sure either. Adding conditions and tests for this and remembering to support them as you make changes, and to make the preferences view read only or disabled as well. This all adds complexity for a potential niche use case. Let's keep it open though. I think proposal 2 is reasonable at least. Maybe even proposal 1.

**Comment by friday** [comment]
This should be fixed in the Ulauncher v6 branch (see PR above, using your proposal #1). It won't be released for a while, but we made a tracking issue if you want to be notified #869

**Comment by lorenzleutgeb** [comment]
Thank you very much! I'll request/help to get Ulauncher 6 into Nixpkgs quickly once it's out, and then revisit the Home Manager module.
