### ISSUE TITLE
Pixbuf issue on first search

### ISSUE THREAD

**Issue by abers** [Ulauncher/Ulauncher#714]
### Steps to reproduce
1. Open ulauncher
2. Type anything

### Current behavior
Ulauncher halts for a couple of seconds before outputting the following error:
`(ulauncher:134331): Gtk-WARNING **: 11:41:23.907: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.`
After that it works as expected.

### Expected behavior
Ulauncher searches for all with minimal delay.

### Environment
**Ulauncher version**:  5.10.0
**Linux distro**: Kubuntu 20.04
**Desktop environment**: i3-gaps (Regolith repo)

### Logs

https://gist.github.com/abers/0f69fec92ae494d0bab58e0b67381ba3

**Comment by troycurtisjr** [comment]
Hi @abers looking at your logs I see:
```
2021-03-20 11:44:21,973 | DEBUG | ulauncher.ui.windows.UlauncherWindow: on_focus_in_event() | Focus in event, grabbing pointer: <enum GDK_GRAB_SUCCESS of type Gdk.GrabStatus>
```
Could you also try after disabling "Don't hide after losing mouse focus"? 

![image](https://user-images.githubusercontent.com/16273537/129128602-017c6798-caae-4f6e-be59-2a0300157191.png)

I certainly haven't been encountering the issue, but I'd like to see if it directly related to that feature or not.

**Comment by friday** [comment]
The problem is the package is providing a corrupt icon. If you try to load it in your browser it will say the same thing: https://github.com/rncbc/qmidinet/blob/e161d22858c4f9a46b931eee37e0ae3799298534/src/images/qmidinet.svg
