### ISSUE TITLE
Changing font-family

### ISSUE THREAD

**Issue by abers** [Ulauncher/Ulauncher#715]
## Question
What's the best way to change the font-family used by ulauncher within a theme.css?

**Comment by davbianchi** [comment]
Yeah i'd like to change it too

**Comment by friday** [comment]
It's using the interface font. You can change it with Gnome Tweaks
![2021-09-04_22-14](https://user-images.githubusercontent.com/515120/132106967-6d1ebc9c-7d2f-4718-8193-cf7a06d353ec.png)

Comic Sans example:

![2021-09-04_22-13](https://user-images.githubusercontent.com/515120/132107012-5d693989-5231-4b72-848f-31fe7cc22dd8.png)

Themes are for changing the colors. Themes can't provide fonts so I don't think we should support setting custom fonts with them. People would end up installing themes with fonts that are not on their system.

**Comment by friday** [comment]
Actually, this worked also: 
```
.app {
    font-family: 'Roboto Slab Medium', serif;
}
```

(remember to add the fallback if the font is missing)
