### ISSUE TITLE
File searching extensions never work

### ISSUE THREAD

**Issue by OmarShawky1** [Ulauncher/Ulauncher#725]
## Question
I tried all the file search extensions in the extensions library, non of them worked which sounds odd, i started to think that the actual issue is not by them but might be with Ulauncher instead, they all return "nothing found" despite that i am certain that it is there and i searched for multiple files not just one to ensure that the issue occurs always.

simply, how could i help you to debug this issue to further study it?

**Comment by KuenzelIT** [comment]
Hey,

I'm not the developer, but I worked a little on extensions. Maybe the debug messages show some relevant information about the problem. You can start ulauncher in debug mode very easy like this:
```
ulauncher -v
```

**Comment by friday** [comment]
Maybe you have no files? ;)

Also, Ulauncher extensions are not supported by Ulauncher, but their devs.

**Comment by vipranarayan14** [comment]
[ulauncher-file-search](https://github.com/brpaz/ulauncher-file-search) works fine (Ubuntu 20.04). You have to [install fd](https://github.com/sharkdp/fd#installation) for it to work. (It is very slow, though).


![image](https://user-images.githubusercontent.com/17687018/116787173-5adfef00-aac0-11eb-907c-eaeac12aa03f.png)

**Comment by kskollepara** [comment]
> [ulauncher-file-search](https://github.com/brpaz/ulauncher-file-search) works fine (Ubuntu 20.04). You have to [install fd](https://github.com/sharkdp/fd#installation) for it to work. (It is very slow, though).
> 
> ![image](https://user-images.githubusercontent.com/17687018/116787173-5adfef00-aac0-11eb-907c-eaeac12aa03f.png)

I installed this extension and fd on ubuntu using `apt install fd-find`. Still no luck, even if I map the command `fdfind` to `fd`

**Comment by kskollepara** [comment]
@vipranarayan14  I installed this extension and fd on ubuntu using `apt install fd-find`. Still no luck, even if I map the command `fdfind` to `fd`

**Comment by friday** [comment]
I'm going to close this.

Ulauncher itself doesn't support file searching, or any specific extensions are written by third party developers. Most of these issues happen because the extensions have dependencies that you need to manually install with steps listed on the extension repositories readme.

Ulauncher will probably look into more ways of improving the ways users see extension errors, but there are existing issues for that.
