### ISSUE TITLE
Ability to export/import settings

### ISSUE THREAD

**Issue by andradei** [Ulauncher/Ulauncher#731]
### Is your feature request related to a problem? Please describe
No.

### Describe the solution you'd like
Ability to export/import settings and extensions

### Additional context
So it is faster to set this up on a new system
or
sync settings between systems.

**Comment by friday** [comment]
Thank you for the suggestion. Your preferences are stored in `~/.config/ulauncher`, so you *can* do this already. I think it would be nicer to use a more standardized format for config files and/or not as many different files. Perhaps also being able to use CLI to set specific preferences. This is not a current priority however.

**Comment by friday** [comment]
I'm going to close this as #712 should cover it.
