### ISSUE TITLE
Add a 'releases' page to the gitHub

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [Ulauncher/Ulauncher#732]
You might want to add a 'releases' page to your gitHub. For one thing, that would enable people to check the changelog. (Just how I got an update via the PPA. The changelog included for that update mentioned only one single fix. Is that right? I do hope not.)

**Comment by friday** [comment]
Are you talking about this https://github.com/Ulauncher/Ulauncher/releases ?

**Comment by LinuxOnTheDesktop** [comment]
It turns out that I am. It might be in order for the home page to have a further - a more prominent - link to that page. Basically though it is my mistake and so I apologise and I close this issue.
