### ISSUE TITLE
All extensions crashed

### ISSUE THREAD

**Issue by kushraj** [Ulauncher/Ulauncher#736]
### Steps to reproduce
all extensions are showing crashed status in ulauncher settings

### Environment
**Ulauncher version**: 5.11.0-1
**Linux distro**: Arch
**Desktop environment**: Sway

### Logs
https://gist.github.com/kushraj/24aa529fb3694753f7f21820dd14798a

**Comment by bojanivanovic** [comment]
Same here. Manjaro Gnome, Ulauncher version 5.9.0-1

**Comment by friday** [comment]
See #703 and #717

**Comment by verajosemanuel** [comment]
Same here. Synced via Dropbox from Debian Stable. All working ok, then in Garuda Arch all crashed.

Tried installing again but to no avail.

![2021-05-08_09-21](https://user-images.githubusercontent.com/15836677/117530780-51361a00-afdf-11eb-97f6-b2b5cbd7cacc.png)

**Comment by chrislockard** [comment]
Confirming this issue in Fedora 34 / Gnome 40 / X11. 

I just installed fresh from `sudo dnf install ulauncher` which installed version 5.11.0. After installing any extension, clicking `Reload the list` or `Save` causes all extensions to crash.

**Comment by shamiv** [comment]
Confirming this on Fedora 34/ Gnome 40/ Wayland.

Running ulauncher in verbose mode shows the following errors (for all of the crashed extensions): 
```
2021-05-10 18:52:53,564 | ERROR | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.kuenzelit.ulauncher-firefox-bookmarks" failed with an error: ImportError: Requiring namespace 'Gdk' version '3.0', but '4.0' is already loaded
```

**Comment by friday** [comment]
That error is unrelated and because you didn't install the extension dependencies @chrislockard

**Comment by chrislockard** [comment]
![image](https://user-images.githubusercontent.com/2675137/118036604-4cb18e80-b35c-11eb-9c95-9e8f375754c5.png)

I cherry-picked the log from one of them. This happens whenever I install any extension and I'd be surprised if I was failing to install extension dependencies for all of them.

**Comment by friday** [comment]
Yeah. It's two separate and unrelated issues. ulauncher-dict-en needs a dependency. The actual crashes are because of missing the proper GDK3 declaration. See the other issue which has all the details.

**Comment by leodahal4** [comment]
Actually this crashes Gnome session too.

**Comment by pana1990** [comment]
I have the same issue :(

**Comment by kskalny** [comment]
Hi guys, i have workaround for your issue! :smile: 

Just add  this code in top of the `/usr/lib/<your-python-version>/site-packages/ulauncher/utils/display.py`
```python
import gi
gi.require_version('Gdk', '3.0')
```
Then everything shoud work just fine! 
@gornostal

**Comment by troycurtisjr** [comment]
This has been merged to dev and will be in the next release.
