### ISSUE TITLE
Extensions are not added

### ISSUE THREAD

**Issue by alpha-oliveira** [Ulauncher/Ulauncher#738]
### Steps to reproduce
1. Click extensions tab
2. Click ' add extension
3. Paste extension github link

### Current behavior
Doesn't add extension

### Expected behavior
Extension added 
### Environment
**Ulauncher version**: v.5.11.0
**Linux distro**: Ubuntu 
**Desktop environment**: Gnome

### Logs
https://gist.github.com/alpha-oliveira/3cca6b835413fa1c04edb5f984b8e377

**Comment by Airili** [comment]
same question
can not add extensions

**Comment by troycurtisjr** [comment]
This is due to the extensions changing their default branch from master to main without updating their versions.json file (see https://github.com/brpaz/ulauncher-dendron/pull/2/commits/d9c7038bdb32530c90f9b0598020b07bbc1dc57c as a reference).
