### ISSUE TITLE
ModuleNotFoundError: No module named 'xdg.BaseDirectory'

### ISSUE THREAD

**Issue by matty0blake** [Ulauncher/Ulauncher#751]
Hi i been using ulauncher about 2 month
on :  Linux - Kali Linux 2021.2

it was fine untill i upgraded my ( pip packages to latest ) 
then it stop lunching i tried it on the live os and it dose not work
so i thought it is the software issue so i used the older version of the software but it dose not work either 

TERMINAL OUTPUT :
-----------------------------------------------------
 ulauncher
Traceback (most recent call last):
  File "/usr/bin/ulauncher", line 27, in <module>
    from ulauncher.main import main
  File "/usr/lib/python3/dist-packages/ulauncher/main.py", line 19, in <module>
    from ulauncher.config import (get_version, get_options, is_wayland, is_wayland_compatibility_on,
  File "/usr/lib/python3/dist-packages/ulauncher/config.py", line 17, in <module>
    from xdg.BaseDirectory import xdg_config_home, xdg_cache_home, xdg_data_dirs, xdg_data_home
ModuleNotFoundError: No module named 'xdg.BaseDirectory'
-----------------------------------------------------

it ask for xdg.BaseDirectory 
the libary exist and i tried to install it 

but i also have the alternative libary with only xdg 
i edited the code to import xdg instead 
it dose not work too
![a](https://user-images.githubusercontent.com/55648361/121811890-b30b2480-cc1a-11eb-9eaa-a4bff6789625.png)

**Comment by matty0blake** [comment]
it stop working if you install ( python-is-python3 )

**Comment by SKOHscripts** [comment]
Hello everyone, 
I got the same issue and installed python-is-python3, but this is not enough…
Could you help me ?
![image](https://user-images.githubusercontent.com/63296980/148574598-1231194f-78b7-4313-a1c6-f6a497bcb7d8.png)

**Comment by SKOHscripts** [comment]
Found that it could come from pyxdg. I already have it : pyxdg (0.27)

**Comment by SKOHscripts** [comment]
I found this : https://askubuntu.com/questions/871838/xdg-basedirectory-import-error
And it appears it seems to be my case
![image](https://user-images.githubusercontent.com/63296980/148577921-91eeb4eb-3cb7-4d2c-8968-a5856fc7d5e3.png)
But I don’t know how to resolve it.

**Comment by friday** [comment]
Just keep digging. This is an issue on your end. Figure out why this line doesn't work `from xdg.BaseDirectory import xdg_config_home`. It's not a Ulauncher issue. It's a Python/system configuration issue or a module issue. Try the solution to print sys.path and find out if you have the module in the right path (you probably don't).

**Comment by friday** [comment]
If you run this `cat $(which ulauncher)`, the first line should be the shebang with the python binary. It starts with #!. Then after that it's the python binary Ulauncher uses. Run that to start a REPL. Then you can diagnostics from there.

`from xdg.BaseDirectory import xdg_config_home` should not work.

`import sys
print '\n'.join(sys.path)` should print the paths it looks for modules.

Maybe you just need to reinstall the modules after upgrading python.

**Comment by SKOHscripts** [comment]
Yes, I’ve figured out it was a problem with my Python config and not Ulauncher, but I’ve seen this issue so many that I guess it could help someone else. 

> Maybe you just need to reinstall the modules after upgrading python.
How can I do it ?
