### ISSUE TITLE
Switching activity while Ulauncher is active/open hangs Gnome

### ISSUE THREAD

**Issue by friday** [Ulauncher/Ulauncher#752]
### Steps to reproduce
1. Toggle Ulauncher (ex: CTRL+SPACE)
2. I always wrote something at the point (using Ulauncher as a calculator), and sort of forgot it was open.
3. Press switch to another app (normally ALT+TAB, cut CTRL+TAB for me).

### Current behavior
Gnome hangs.
I have to CTRL+ALT+F3 to open the console and `pkill -9 ulauncher`, then CTRL+ALT+F2 to get back.

### Expected behavior
Gnome shouldn't hang

### Environment
**Ulauncher version**: 5.11
**Linux distro**: Arch
**Desktop environment**: Gnome (40) in X11

I think this is very much related to #667

**Comment by troycurtisjr** [comment]
Is this happening anymore now that #667 is resolved? I can't reproduce on my machine.

**Comment by friday** [comment]
Great! It doesn't happen in my most recent tests, so closing :+1:
