### ISSUE TITLE
Updated instructions for Hotkey in Wayland

### ISSUE THREAD

**Issue by rickard-von-essen** [Ulauncher/Ulauncher#753]
Updated instructions for [Hotkey in Wayland](https://github.com/Ulauncher/Ulauncher/wiki/Hotkey-In-Wayland)

> Open OS Settings > Devices > Keyboard > Add Hotkey > Scroll all the way down > Click +

At least on Fedora 34 should be:

> Open Settings > Keyboard > Scroll all the way down to _Customize Shortcuts_ > Custom Shortcuts > +

**Comment by friday** [comment]
Updated. Thank you!
