### ISSUE TITLE
Killing Ulauncher kills all apps launched with Ulauncher

### ISSUE THREAD

**Issue by loserMcloser** [Ulauncher/Ulauncher#754]
### Steps to reproduce
1. Start ulauncher
2. Start some program using ulauncher
3. Kill ulauncher

### Current behavior
Program started with ulauncher gets killed when ulauncher is killed.

### Expected behavior

If Ulauncher crashes or is killed, all programs launched with Ulauncher should keep running.

To start an application, ulauncher should fork --- parent process of ulauncher keeps running, child process of ulauncher launches specified app and then exits.

### Environment
**Ulauncher version**:  5.11.0
**Linux distro**:  Archlinux
**Desktop environment**:  swaywm

**Comment by friday** [comment]
This happens for me with some apps (for example Chromium) but not all. Also using Arch, but X11.

**Comment by friday** [comment]
@loserMcloser This is fixed in my fork now, along with a bunch of other things.

https://github.com/friday/Ulauncher-Revived
https://aur.archlinux.org/packages/ulauncher-revived-git/
