### ISSUE TITLE
wmctrl not found on Fedora 34

### ISSUE THREAD

**Issue by njelich** [Ulauncher/Ulauncher#755]
I installed ulauncher on a fresh fedora install, and faced a problem with the app not getting focus when running with the hotkey (I followed the steps to fix the hotkey issue on wayland first). After running `ulauncher-toggle` from the command line, I saw the message about wmctrl not being found. I installed the package and it worked fine.

### Steps to reproduce
1. Install on Fedora using `sudo dnf install ulauncher`
2. Fix hotkey bug, so you can run it
3. Use hotkey

### Current behavior

Doesn't take focus, because the wmctrl command isn't found,

### Expected behavior

Normal operation, with focus taking

### Environment
**Ulauncher version**: 5.11.0
**Linux distro**: Fedora 34 (kernel 5.11.12-300.fc34.x86_64)
**Desktop environment**: Wayland

**Comment by troycurtisjr** [comment]
Actually, this is a bug in the Fedora package not setting the wmctl to be "recommended" as an install. I created https://bugzilla.redhat.com/show_bug.cgi?id=1985744 to track it.
