### ISSUE TITLE
crashes: apparent python library problems

### ISSUE THREAD

**Issue by tulakalbeyo** [Ulauncher/Ulauncher#756]
### Steps to reproduce
1. install ulauncher
2. launch ulauncher normally or from the commandline
3. profit?

### Current behavior
crashes: won't launch: see **logs** section

### Expected behavior
to simply launch, like it had been doing yesterday

### Environment
**Ulauncher version**: 5.11.0-0
**Linux distro**: xubuntu 20.04 focal
**Desktop environment**: xfce

### Logs
https://gist.github.com/tulakalbeyo/18de919ddc15b3ad0bcaf774e08d3bfa

thanks!

**Comment by brpaz** [comment]
@tulakalbeyo I am not related to Ulauncher development, but from your error, it seems that your settings.json file has some kind of error. Can you check the `~/.config/ulauncher/settings.json` is a valid json file?

Also, what is your Linux distro?

**Comment by tulakalbeyo** [comment]
well, the existent file was empty.. so i downloaded it again from https://github.com/Ulauncher/Ulauncher/blob/dev/.vscode/settings.json and replaced it! now it works!! thanks! 🥳🎉😊👍🏼✨

**Comment by tulakalbeyo** [comment]
issue closed, i guess!
