### ISSUE TITLE
Can't launch apps / No suggestions

### ISSUE THREAD

**Issue by sparevermicelli** [Ulauncher/Ulauncher#757]
### Steps to reproduce
1. Start ulauncher -> OK
2. type any app -> nothing happens (for example firefox)
3. other extensions are working (file search, calculator, ~, /,..)

### Current behavior
Since couple of days (I've applied latest updates) I can no longer start any software from ulauncher.
When I open it, I can type, but there are no recommendations, I can start any app.

### Expected behavior
Launch app from Ulauncher. Get list of apps after I start typing

### Environment
**Ulauncher version**: 5.11.0
**Linux distro**: Linux Mint 20.1
**Desktop environment**: Cinnamon

### Logs
No logs showed when running ulauncher -v

**Comment by WMordy** [comment]
I'm facing the same problem on ubuntu 21.04 using wayland

**Comment by criloz** [comment]
I fixed it  wiping out all the u-launcher data, there should exist a command that return the cfg to fabric.

~/.local/share/ulauncher
~/.cache/ulauncher
~/.config/ulauncher

**Comment by WMordy** [comment]
> I fixed it wiping out all the u-launcher data, there should exist a command that return the cfg to fabric.
> 
> ~/.local/share/ulauncher
> ~/.cache/ulauncher
> ~/.config/ulauncher

Thanks mate that worked like a charm.

**Comment by troycurtisjr** [comment]
Is it possible that ulauncher was launched at some prior time as root? That would have created all of these files as root owned files, and thus ulauncher running as a normal user wouldn't be able to access them. In this scenario, ulauncher also wouldn't be able to to have any form of cleanup command, as it still would not have sufficient access to the files to clean them out.

**Comment by WMordy** [comment]
> Is it possible that ulauncher was launched at some prior time as root? That would have created all of these files as root owned files, and thus ulauncher running as a normal user wouldn't be able to access them. In this scenario, ulauncher also wouldn't be able to to have any form of cleanup command, as it still would not have sufficient access to the files to clean them out.

I think you are right because ulauncher just suddenly stopped working and I think I run it from the terminal as root (I dont remember why). The extensions were appearing  as suggestion by the way but they were not working. I wish I can help more I had a hard week without using your project. Thanks again.

**Comment by sparevermicelli** [comment]
Thanks, removing the files fixed the problem.
