### ISSUE TITLE
How can I prevent my large title fonts from overlapping my subtitle fonts?

### ISSUE THREAD

**Issue by Raytle** [Ulauncher/Ulauncher#759]
![Fonts overlap one another](https://user-images.githubusercontent.com/81956552/124404344-5ec20480-dcef-11eb-848f-61f8dc12484f.png)

Obviously, I would like to prevent my large title fonts from overlapping my subtitle fonts.

### Environment
**Ulauncher version**: 5.11.0
**Linux distro**: Lubuntu 20.04 LTS
**Desktop environment**: LXQt

**Comment by friday** [comment]
Sorry for the lack of responses @Raytle. As I'm sure you figured out this is happening because Ulauncher doesn't handle HiDPI. There are no known workarounds that I know, and it's going to be complicated to fix this, but ​#322 has more info at least.

Closing this as a duplicate of that issue

**Comment by Raytle** [comment]
Thanks for letting me know. I appreciate that.
