### ISSUE TITLE
Use QT/GTK file picker

### ISSUE THREAD

**Issue by UltraBlackLinux** [Ulauncher/Ulauncher#760]
### Is your feature request related to a problem? Please describe
The GTK+ file picker is very annoying to use, when you are trying to find specific icons for your shortcuts, it takes ages to get there as you can't just paste a URI to the file

### Describe the solution you'd like
i'd love to have the qt file picker, or at least the gtk one, so I can use "GTK_USE_PORTAL=1"

### Additional information
https://superuser.com/questions/1393755/how-to-use-the-qt-file-picker-for-both-gtk-and-qt-apps

**Comment by friday** [comment]
I'm sorry, but I'm going to say no to this. We want to keep Ulauncher simple, and this is definitely a niche issue that only concerns a small number of users (maybe only you). Selecting the shortcut icon is not something you do very often.

If we eventually support flatpak #397 I guess we will indirectly support this though, so you could watch that issue maybe?
