### ISSUE TITLE
Ulauncher does not respect github symlinks

### ISSUE THREAD

**Issue by tchar** [Ulauncher/Ulauncher#769]
Hello.
Looks like that when there are symlinks in a repo, ulauncher does not follow the `git clone` method where symlinks are restored and just create files with the symlink inside

Example:
file: `US.svg`
symlink: `USD.svg` -> `US.svg`

- `git clone`: Restores `USD.svg` symlink
- Ulauncher: Creates a file named `USD.svg` with contents `US.svg` (as is showing in github)

**I have the impression though the same will happen with git submodules, haven't tested it though.**

### Steps to reproduce
1. Create a mock extension repo with
```json
[
    { "required_api_version": "^2.0.0", "commit": "master" }
]
```
2. Create a symlink as described above
3. Get the extension through Ulauncher
4. Go to cloned extension
5. cat the symlink

### Current behavior
Symlinks not cloned properly

### Expected behavior
Symlinks should be restored

### Environment
**Ulauncher version**: 5.11.0, API: 2.0.0
**Linux distro**: Ubuntu 20.04.2
**Desktop environment**: Gnome3.36.8

### Logs
Well I have fixed this issue in my repo by removing symlinks and I cannot force ulauncher to clone a specific commit of my repo
If you insist on logs I have to create a template repo to provide logs.

**Comment by friday** [comment]
Thank you for reporting this, but Ulauncher doesn't use or depend on git. It downloads the extensions as zip. See https://developercommunity.visualstudio.com/t/symbolic-links-are-lost-when-downloading-a-git-rep/653461 for another case like this.

We will not introduce a dependency just for this. The problem you were solving with symlinks can be solved in other ways. The only thing I think we can do is add a clarification to the documentation that we don't support symlinks, but I neither think this is a common problem or that people would remember reading that.

**Comment by tchar** [comment]
Hey @friday 

Although that other case may look like similar, I actually did some experiments and found the issue.
Here is a python sample code to reproduce the issue and see that actually the problem lies with python's `ZipFile` and that links are just fine within the downloaded zip.

```python
from ulauncher.api.server.ExtensionDownloader import download_zip, unzip
from shutil import move
import os

# url of my repo with svg
url = 'https://github.com/tchar/ulauncher-albert-calculate-anything/archive/65e34ded08a4d88a66ec9fcd29bec41e57b32967.zip'

# Download with ulauncher's download_zip function
filepath = download_zip(url)

filename = os.path.basename(filepath)
dest_filepath = os.path.join('.', filename)
dest_filepath = os.path.realpath(dest_filepath)

# Move extension to current dir
move(filepath, dest_filepath)

# Extract with unzip or your system's gui unzipper
# Links are there

# Extract with ulauncher's unzip
dest_extdir = os.path.realpath('./ext')
unzip(dest_filepath, dest_extdir)

# Links are not there
```
Extract the zip with `unzip` or your desktop's archive manager, the symlinks are there and they work.

I did some extra digging and actually found out that it [partially works](https://bugs.python.org/msg268562)
- For example if you extract the aforementioned directory with `zipfile.extractall()` and not `zipfile.extractall(dest_dir)` it works (at least on my machine)
- It also works if the symlinks are already there, which is not applicable for ulauncher. 

So I went and patched the `ulauncher.api.server.ExtensionDownloader.unzip` function to take into consideration symlinks that only refer to the extracted zip (i.e the extension). Did not add any dependencies and it works now with symlinks.

If you are interested let me know if you would like a pull request about it.

**Comment by friday** [comment]
If this just requires a small fix then please submit the PR :+1:

**Comment by tchar** [comment]
I defined an extra function called `extract_symlink` about 35 sloc (without comments and empty lines).

If you are ok with it I will create a mock pull request (or whatever github calls it until ready for review) and in the meantime I will download the whole repository and set it up so I can pass tests, linting etc.

If you need extra tests for the proper extraction of symlinks, please let me know so I add the tests [here](https://github.com/Ulauncher/Ulauncher/blob/ea06bc90116a1745b2314e51873beaf14855f07b/tests/api/server/test_ExtensionDownloader.py) I guess.

**Comment by tchar** [comment]
Ok I understand,

I was able to reduce it to just [this](https://github.com/tchar/Ulauncher/commit/b65f8c50330e9d3fc44cab9761a16f3d7b21ab11) ~10 sloc,  which is a pretty small fix. In any case I can make a PR and you can decide at your own time if and when you want to merge it, no rush. I guess there should be more important issues anyways.

Cheers!

**Comment by friday** [comment]
Feel free to make the PR, but it might take a while for em to get to it. Thanks!

**Comment by friday** [comment]
This happened to me many times @tchar. For example in https://github.com/tkashkin/GameHub/pull/171. I had to make the PR to prove it could be done, and hopefully it helped the maintainer make his counter-suggestion. The solution he went with was better, so I was happy that my use case was covered, and I appreciate that he did that instead of telling me how to change my code to become his code. That back and forth would have been a waste of his time and mine.

The experience definitely didn't encourage me to continue contributing to that project, but I blame my PR and limited knowledge of Vala async event handling, and not the project maintainer for doing the right thing.
