### ISSUE TITLE
Doesn't recognize installed Snaps

### ISSUE THREAD

**Issue by gornostal** [Ulauncher/Ulauncher#77]
> Works great, but it doesn't work for snaps. For example, I installed SimpleScreenRecorder as a snap and this can't find it.

**Comment by gornostal** [comment]
Fixed in v2.1.1 (Dev)

**Comment by TylerCode** [comment]
Thanks @gornostal, I was just making the comment but you had it fixed in a very short amount of time. Better support than software I've paid hundreds for.
