### ISSUE TITLE
Doesn't exist any /.config/ulauncher/user-themes directory

### ISSUE THREAD

**Issue by Dedsd** [Ulauncher/Ulauncher#781]
![image](https://user-images.githubusercontent.com/71463162/130114023-06a60c59-696b-420d-b66e-ff214e92f5fb.png)

**Comment by friday** [comment]
The documentation puts this responsibility on the user http://docs.ulauncher.io/en/latest/themes/themes.html

**Comment by Dedsd** [comment]
What i understand was to the user create the theme folder but not the user-themes. The user-themes would contain the default themes. Look at the step 3. Also, creating the user-themes folder doesn't work. I tried in other directory usr/share/ulauncher/themes and still not working.
![image](https://user-images.githubusercontent.com/71463162/130124371-1e48df97-e4ac-4fc7-86eb-b7956aa8a076.png)

**Comment by Dedsd** [comment]
I tried this in /.config/ulauncher/user-themes (created the user-themes folder, and put the default themes in there) and in usr/share/ulauncher/themes, both doesn't work.
![image](https://user-images.githubusercontent.com/71463162/130125357-68122801-355a-4346-a06f-2657a214e170.png)

**Comment by friday** [comment]
This is all you have to do:
```
mkdir -p ~/.config/ulauncher/user-themes
cd $_
git clone git@github.com:kevquirk/ulauncher-pop.git
```

Then open preferences and the new theme should be in the list.

**Comment by friday** [comment]
Documentation needs improving either way, so it's a good idea to keep this issue open.

**Comment by Dedsd** [comment]
Thanks! Keep the good work!

**Comment by Dedsd** [comment]
Could you tell me why this is not working? 
[darkblue-ice.zip](https://github.com/Ulauncher/Ulauncher/files/7017745/darkblue-ice.zip)

**Comment by friday** [comment]
Sorry. I don't have the time for that. You could install a theme similar to what you want and modify it from that state, and revert if you make any breaking changes.

**Comment by friday** [comment]
I improved the documentation so it now links to the gist with community themes and explains how to install them. I think it's good now. About your specific theme, you have to revert to a working state and figure out what broke it and why. We need to use our time to improve Ulauncher, and can't afford to help users debug themes.
