### ISSUE TITLE
5.12.0 fails to run Mint 'webapps'

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [Ulauncher/Ulauncher#784]
### Steps to reproduce
1. Have Ulauncher 5.12.10
2. Try to run either a pre-existing [webapp](https://github.com/linuxmint/webapp-manager) - which Ulauncher used to run - or a newly created webapp.
3. Find that ulauncher shows the webapp but fails to launch it (whether the browser selected in the webapp be Firefox or Chrome).

### Current behavior
See 3.

### Expected behavior

See 3.
### Environment
**Ulauncher version**: 5.12.10. (I note that `ulauncher --version` continues to flout standards, by failing.)
**Linux distro**: Mint 20.2
**Desktop environment**: Cinnamon

### Logs
[Here](https://gist.github.com/LinuxOnTheDesktop/8ab4733a464c66eb085be8761d601fa7).

**Comment by friday** [comment]
I pushed a fix, but no release yet. I think if you manually edit make the name in the desktop entry and remove trailing white spaces, this should make them run again.

**Comment by LinuxOnTheDesktop** [comment]
On one machine, 5.12.1-beta1 but also 5.12.0 work for a newly created webapp. (I had no pre-existing webapps on that machine.)

On another machine, 5.12.1-beta1 (but not 5.12.0) works for a newly created webapp and for a pre-existing webapp.

(As to manually editing any webapp files - I could not find those files.)

**Comment by friday** [comment]
5.12.1 is out now (exact same release as 5.12.1-beta1 though)
