### ISSUE TITLE
Steam won't start through Ulauncher anymore

### ISSUE THREAD

**Issue by pakro** [Ulauncher/Ulauncher#785]
Hi there,
since the last update Steam -- and according to the comments other applications like htop -- can't be started through Ulauncher anymore. It worked fine the version before and I can still start it from XFCE Whisker and Console. 

### Steps to reproduce
1. Start Ulauncher by shortcut
2. Type Steam
3. Press Enter

### Current behavior
Nothing happens

### Expected behavior
Steam starts

### Environment
**Ulauncher version**: 5.12.0
**Linux distro**: Arch Linux
**Desktop environment**: XFCE

### Logs
https://gist.github.com/pakro/851f7efc8135cda72564f348075313b8 (last Line is probably the interesting one)

**Comment by Halbjobbit** [comment]
htop seams to have the same issue

**Comment by pakro** [comment]
@Halbjobbit I updated my ticket a little bit to reflect your issue aswell, the likelihood of some installing htop before steam on his precious machine is several magnitudes higher! So thank you very much for sharing this information!

**Comment by friday** [comment]
Please try 5.12.1-beta1. On Arch you can install the ulauncher-git package

**Comment by friday** [comment]
Also see #784 for more info + workaround

**Comment by pakro** [comment]
@friday I'm using the ulauncher-git package for now. that seems to fix at least my Steam problem. Thank you very much!

**Comment by friday** [comment]
Thank you for testing that. 5.12.1 is out now (exact same release as 5.12.1-beta1). This means you can switch back to the regular ulauncher package which is safer to use and receives updates.

@Halbjobbit if you still experience the issue please make a new issue to describe it better, with the additional details in the template filled in.
