### ISSUE TITLE
Htop not launching

### ISSUE THREAD

**Issue by Halbjobbit** [Ulauncher/Ulauncher#787]
Htop doesn't launch when starting it through Ulauncher, but you can launch it through Whisker/Home menu etc. Interistingly, when launching Ulauncher with logging, Htop launches in the terminal window, that you launched Htop from instead of in a standalone window how it would be expected.

### Steps to reproduce
1. Open Ulauncher
2. Search Htop
3. Press Enter / click on it / Alt + `<number>`

### Current behavior

Nothing happens except the Ulauncher window closing.

### Expected behavior

Htop should launch in a new terminal.

### Environment
**Ulauncher version**: DEV-1 and 5.12.1-1
**Linux distro**: Arch
**Desktop environment**: KDE Plasma and XFCE

### Logs

[Logs](https://gist.github.com/Halbjobbit/7ecad2502fbe106efbcaca7868f13ab3)

**Comment by friday** [comment]
Thank you for the bug report. I can confirm that this is not the same bug as the other ones are having.

It's working for me if I run from the command line, but not when I start Ulauncher as a service

If I fill in the "Terminal command" in preferences it works for both cases though. You can try this workaround if you need those to start until this bug has been fixed. For example `gnome-terminal -- ` or `terminator -e`. You need the command for running a new command in the terminal, not just the command for the terminal.

**Comment by friday** [comment]
Could you try installing from [ulauncher-git](https://aur.archlinux.org/packages/ulauncher-git) to verify it's working there now?

**Comment by Halbjobbit** [comment]
Yes it works now. Thank you for fixing it!

**Comment by friday** [comment]
Fixed in 5.12.1 as well (so the main aur package works now)
