### ISSUE TITLE
`owncloud desktop sync client` can be found but not launched

### ISSUE THREAD

**Issue by Edenharder** [Ulauncher/Ulauncher#788]
### Steps to reproduce
1. call up `ULauncher`
2. type `owncloud` and get a list of candidates
3. click on `owncloud desktop sync client` 

### Current behavior

[`owncloud desktop sync client`](https://archlinux.org/packages/community/x86_64/owncloud-client/) cannot be launched after the click on it.

### Expected behavior

To launch `owncloud desktop sync client`

### Environment
**Ulauncher version**: 5.12.0
**Linux distro**: Manjaro 21.1.0 Pahvo 
**Desktop environment**: i3-gaps

[A similar issue has existed in `dmenu-extended` also.](https://github.com/MarkHedleyJones/dmenu-extended/issues/116)

**Comment by friday** [comment]
Already fixed in 5.12.1. See #784 and #785
