### ISSUE TITLE
python3.5(Ubuntu 16.04) not support f-strings

### ISSUE THREAD

**Issue by lxf1992521** [Ulauncher/Ulauncher#790]
### Steps to reproduce
OS: Ubuntu 16.04
Python: python3.5.2

sudo add-apt-repository ppa:agornostal/ulauncher
sudo apt-get update
sudo apt-get install ulauncher

### Current behavior
Ubuntu 16.04 with python3.5.2 not support f-strings, but below files contains few f-strings syntax:
```
ulauncher/search/apps/AppDb.py:    return f'{name}\n{exec_name}'
ulauncher/search/SortedList.py:        name, exec_name, *_ = f'{search_fields}\n'.split('\n')
ulauncher/api/shared/action/LaunchAppAction.py:                sanitized_exec = ['systemd-run', '--user', '--scope', f'--slice=app-{sanitized_app}'] + sanitized_exec
```
which will report error message when run ulauncher: ```SyntaxError: invalid syntax```

### Expected behavior
change f-strings to “Old-school” String Formatting like <code>%-formatting</code> or <code>str.format()</code>

### Environment
**Ulauncher version**: 5.12.2-0ubuntu1ppa1~xenial
**Linux distro**: Ubuntu 16.04.7
**Desktop environment**: Unity

**Comment by friday** [comment]
Sorry about that. Xenial has reached end of life and should not be supported any more. The mistake was to update the packages

I'm not sure if pulling the 5.12.x packages from Launchpad is a "good" solution, but it's the solution I propose now, so users can downgrade and not worry about it breaking.

**Comment by friday** [comment]
@lxf1992521 Could you check that 5.13.0-beta2 works for you? It can be downloaded on the releases page or you can use the [dev launchpad PPA](https://launchpad.net/~agornostal/+archive/ubuntu/ulauncher-dev) (not recommended).

We will push this as 5.13.0 in that case. We can't actually test this on our end (which is why I'd rather not make more releases for 16.04).

**Comment by lxf1992521** [comment]
Installing and Working great on my Ubuntu 16.04.7 with python3.5,
excellent!

friday ***@***.***> 于2021年9月4日周六 下午12:58写道：
