### ISSUE TITLE
Add ability to customize which desktop apps are filtered

### ISSUE THREAD

**Issue by jtheoof** [Ulauncher/Ulauncher#809]
### Is your feature request related to a problem? Please describe

Following a discussion on #343 with @friday , the behavior of ulauncher is now valid. It does filter out desktop apps that are not supposed to be shown (based on `OnlyShowIn`/`NotShowIn`).

However for some desktop environments (most probably more simple window managers such as [sway](https://github.com/swaywm/sway), i3, ...), it filters out many apps that could be useful to the environment. For example, some sway users like myself rely on gnome apps which are now filtered out with version >=5.12.0.

### Describe the solution you'd like

As I don't want to break the new (and valid) behavior, but still would like my gnome apps to be shown, a new configuration could make sense.

Something like: `show-apps-in-env=sway;gnome;kde` in `settings.json`. Basically an array (`;` separated) containing the environments (what is set in `OnlyShowIn`) that are whitelisted by the `filter_app` function.

### Additional context
Add any other context about the feature request here.

**Comment by jtheoof** [comment]
Your suggestion in [this comment](https://github.com/Ulauncher/Ulauncher/issues/343#issuecomment-913215480) would work @friday but like you said it's not ideal. I don't really want to change `XDG_CURRENT_DESKTOP` but rather whitelist some environments in `ulauncher`, if possible.

**Comment by friday** [comment]
Thank you for creating the issue. I would recommend to use a workaround until I have time to get to this. The ones I mentioned would involve changing `XDG_CURRENT_DESKTOP` for Ulauncher (which should be fine I think), and the apps opened by Ulauncher (which might be problematic), but it doesn't set it outside of this context at least.

This would add about 30 lines of code to support if we're adding it to the graphical preferences (and we always do add settings.json settings there) as well as having to check `XDG_CURRENT_DESKTOP` directly and the custom override. Currently we're just using native GTK APIs to determine if the app should show with `app.should_show()` or something which checks both OnlyShowIn and NotShowIn.

**Comment by friday** [comment]
I would make the setting `{"ShowAllApps" : true}` I think btw. From experience people don't handle settings like the custom terminal well. It's hard to explain in the limited space we have for it.

**Comment by jtheoof** [comment]
Have a look at #810 when you have some time and let me know what you think. I did some testing and does a good enough job that makes me happy. It doesn't technically display "all apps", only overrides the `app.get_show_in()` call. The non displayable, hidden, ... apps are still hidden. So maybe the name of the config can be improved.
