### ISSUE TITLE
Zombie processes created when launching apps

### ISSUE THREAD

**Issue by shaicoleman** [Ulauncher/Ulauncher#811]
### Steps to reproduce
1. Run `ulauncher -v` (no extensions)
2. Launch `ulauncher` from within ulauncher
3. `ps aux | grep -i ulauncher`

```
shai       10753  4.0  0.4 1876436 75876 pts/0   Sl+  01:24   0:00 /usr/bin/python3 /usr/bin/ulauncher -v
shai       10791  2.0  0.0      0     0 ?        Zs   01:24   0:00 [ulauncher] <defunct>
```

### Current behavior

The process is launched as a child of the ulauncher process.
When the process terminates, a zombie process is created
This for example breaks `killall --wait` 
I've only noticed it happening recently, so might be something that was introduced in 5.12.x/5.13.x.
Might be related to https://github.com/Ulauncher/Ulauncher/pull/778

### Expected behavior

Should not create zombie processes

### Environment
**Ulauncher version**: 5.13.0
**Linux distro**: Linux Mint 20.2 (Based on Ubuntu 20.04), Kernel 5.14.1
**Desktop environment**: Cinnamon

### Logs
https://gist.github.com/shaicoleman/26c199b81573ca430c43062ca979eee5

**Comment by friday** [comment]
So you started Ulauncher from Ulauncher?

**Comment by shaicoleman** [comment]
@friday , Yes, just as an easily reproducible example.
When you run ulauncher from ulauncher, it sees it's already running and quits. It happens with other applications as well
