### ISSUE TITLE
Better Fullscreen Behaviour

### ISSUE THREAD

**Issue by kushraj** [Ulauncher/Ulauncher#814]
If I launch ulauncher in fullscreen mode, I'm getting a black screen around the actual body of the ulauncher. Is there a way to set the opacity of this black padding, or better yet it can be customized using css ?

**Comment by friday** [comment]
Have you tried https://github.com/Ulauncher/Ulauncher/issues/230#issuecomment-570807951?

**Comment by kushraj** [comment]
If I understand it correctly, Its  not the same thing. I am using sway so issue doesnt occur in floating mode with --no-window-shadow  enabled 

what I want is to have ulauncher in fullscreen while the area around the box should not be opaque.  Visually it should be similar to when ulauncher is in floating mode like below 
![image](https://user-images.githubusercontent.com/36916613/133073951-1d317466-577e-4245-8caf-758e22993e06.png)

its fine if its set to floating
![image](https://user-images.githubusercontent.com/36916613/133074084-ba28b6f2-3eb4-4d9c-8219-893de8fbf013.png)

**Comment by friday** [comment]
I don't think this has anything to do with Ulauncher. It's your DE not showing the background image in fullscreen mod.

**Comment by friday** [comment]
In Gnome you can't go to fullscreen without an app open. If you do and miniminize that app you still get a background. You can't go to fullscreen mode with Ulauncher, but if you fullscreen and minimize an app and open ulauncher it looks no different from just opening Ulauncher.

**Comment by kushraj** [comment]
yeah, it does seems like the DE problem. my bad

**Comment by friday** [comment]
No worries :+1:

**Comment by kushraj** [comment]
so fullscreen is not an option. Is there any other way to achieve this ? as in an transparent overlay over the rest of the screen around ulauncher window when it is displayed ?

**Comment by troycurtisjr** [comment]
Typically for apps like ulauncher with tiling window managers you set the
application in floating mode, which is seems like you were able to get
working. That seems like the right answer, doesn't it? Ulauncher doesn't
support fullscreen, it doesn't have a provision to go full screen, so it
seems odd to try to handle something that the applications doesn't support.
Especially when the DE already has the proper support to enable the correct
behavior, right?

**Comment by kushraj** [comment]
yeah, its just that the default behaviour isn't what I want. Its a thing with apps like ulauncher, polkit authentication that you have to start them in floating mode, and its really annoying everytime you lose focus due to some mouse/window movement.

**Comment by friday** [comment]
I'm sure you know you can enable "Don't hide after losing mouse focus".

Maybe try the fix gornostal made (then reverted) for #444, or messing about with other modes. I don't know enough about these, but if you find one that works for you and doesn't break for others this could be a way forward.

You can edit the UI this way if you have the Ulauncher repo locally and the Glade app: `GLADE_CATALOG_SEARCH_PATH=./data/ui glade`

**Comment by kushraj** [comment]
thanks, I will look into it. another way to implement these changes will be to make Ulauncher use wlr-layer-shell/gtk-layer-shell protocol, I do think I added an issue about it earlier. will it be possible since it is based on gnome libraries ?

**Comment by friday** [comment]
It's a Wayland only thing, so no.
