### ISSUE TITLE
Some search results are not correct for the search query or at least not related to the name

### ISSUE THREAD

**Issue by justperfection** [Ulauncher/Ulauncher#816]
After updating to v5.13.0, Ulauncher doesn't show the search result more related to the app names. Maybe the priority is exec instead of name for the new version.

### Expected behavior

When I hit "B", I expect to see **B**rave browser in the list. I see "Icon Browser", "Disk Usage Analyzer" but not Brave Browser.
Same thing happens for "G" and **G**Musicbrowser.

https://user-images.githubusercontent.com/66198705/133515496-e453e753-8de2-43fd-ab41-96c422e62a4a.mp4

It wasn't like this before the update.

### Environment
**Ulauncher version**: v5.13.0 
**Linux distro**: Fedora 34
**Desktop environment**: GNOME Shell 40.4

### Logs

https://gist.github.com/justperfection/f54c17a9ee31bd4f05d6e17c266ecc63

**Comment by troycurtisjr** [comment]
Tuning these parameters are pretty challenging! I guess "Brave Browser" is a long enough name that the score for a single letter just can't make it to the threshold. Of course lowering the threshold might bring in increasingly unrelated matches. At least in your case though there is still room to put more matches before it reaches the max, so it definitely seems reasonable that it should at least be in the list.

Consistent behavior for single character query strings is probably going to be really challenging to do, especially as we try to score each entry independently. I know this is definitely an area we want to get better in.

**Comment by friday** [comment]
Yeah, I don't think it's possible for the fuzzy matching to ever be "perfect", especially since it has conflicting goals.

The PR that introduced this was actually improving cases like this in general, but it removed a condition that we maybe want to revert, and it needs tuning. I started working on that, but the result actually wasn't satisfactory, so I shelved it.

**Comment by friday** [comment]
This is fixed in the Ulauncher v6 branch and PR #827. It won't be released for a while, but we made a tracking issue if you want to be notified #869
