### ISSUE TITLE
Problems installing from AUR with pyenv in use

### ISSUE THREAD

**Issue by gpoole** [Ulauncher/Ulauncher#820]
This relates to https://github.com/Ulauncher/Ulauncher/issues/556 but is more generally about the fact that pyenv seems to cause a problem, so I think the issue itself could be fixed or maybe the workaround documented.

### Steps to reproduce

Using pyenv 2.0.4 on Manjaro with global version set to anything other than "system".

### Current behavior

Installing from AUR fails with the following error:

```
To build ulauncher you need "python3-distutils-extra"
```

### Expected behavior

The install completes successfully

### Environment
**Ulauncher version**: 5.14.0
**Linux distro**: Manjaro Gnome
**Desktop environment**: Gnome

### Logs

<details>
<summary>`pyenv versions`</summary>

```
  system
* 3.7.11 (set by /home/user/.pyenv/version)
  3.9.0

```

</details>

<details>
<summary>install log</summary>

```
Building ulauncher...
==> Making package: ulauncher 5.14.0-1 (Fri 24 Sep 2021 09:52:52)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading ulauncher_5.14.0.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   629  100   629    0     0   1952      0 --:--:-- --:--:-- --:--:--  1953

100 1839k  100 1839k    0     0  2376k      0 --:--:-- --:--:-- --:--:-- 2376k
==> Validating source files with sha256sums...
    ulauncher_5.14.0.tar.gz ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting ulauncher_5.14.0.tar.gz with bsdtar
==> Removing existing $pkgdir/ directory...
==> Starting build()...
To build ulauncher you need "python3-distutils-extra"
==> ERROR: A failure occurred in build().
    Aborting...
```
</details>

**Comment by gpoole** [comment]
I've noticed that in #554 the runtime dependency on distutils-extra has been removed, but [the check causing this error is still there in setup.py](https://github.com/Ulauncher/Ulauncher/blob/c629e983d136f3518fe76f599294be2e0e675488/setup.py#L8). I'm not sure if removing the check would fix the problem with pyenv or just hide a bigger one? Would it break stuff if you install ulauncher and then change the system python version? Is there a best practice way to configure pyenv so this doesn't happen?

**Comment by friday** [comment]
We are removing python3-distutils-extra completely for version 6. Now it's just a build dependency. But removing it doesn't fix the pyenv issue I think. It's just one dependency less. It can happen with the other dependencies instead I'm sure.

I don't know how to avoid this, but hopefully someone else does and can comment on this issue.

**Comment by gpoole** [comment]
Awesome, thanks for the fix and that sounds like a good solution @friday. I can confirm this fixes the issue with the installer on my system.

Just wondering, will you also need to modify the launch script as well? It looks like the [script in the repo](https://github.com/Ulauncher/Ulauncher/blob/ea06bc90116a1745b2314e51873beaf14855f07b/bin/ulauncher#L1) will use the pyenv python, but on my actual system `ulauncher` at `/usr/bin/uslauncher` seems to start with `#!/usr/bin/python` so it works as expected.

**Comment by friday** [comment]
Added the fix for the main package as well now, so you can switch back (recommended to get updates).

Thank you again :+1:
