### ISSUE TITLE
ULauncher no longer finds 'Terminal' app

### ISSUE THREAD

**Issue by whirlpion** [Ulauncher/Ulauncher#821]
### Steps to reproduce
1.  Launch ULauncher
2. Type 'term' or 'terminal' etc 

### Current behavior

Terminal application does not appear in search results, but same search query from Cinnamon's 'start' menu does. I've duplicated this issue on two systems.

This used to work, but stopped working sometime around the middle of August 2021. 

### Expected behavior

Find the Terminal application

### Environment
**Ulauncher version**: v5.12.1, v5.14.0
**Linux distro**: Linux Mint 20.2
**Desktop environment**:  Cinnamon v 5.05

### Logs

- `/usr/share/applications/org.gnome.Terminal.desktop` : https://gist.github.com/whirlpion/5a68680f7536fcc4eee6738799573b59
- `ulauncher -v` : https://gist.github.com/whirlpion/44c777c44c5a826c58cb3ca9388f1e4d

**Comment by friday** [comment]
You're using a Gnome exclusing app outside of Gnome then?

**Comment by whirlpion** [comment]
It's the default terminal that comes with Cinnamon vOv

**Comment by friday** [comment]
But it's specified as gnome-exclusive. See #343, #809 and https://gist.github.com/whirlpion/5a68680f7536fcc4eee6738799573b59#file-org-gnome-terminal-desktop-L13

**Comment by whirlpion** [comment]
Ah well there it is, enabling 'Show All Apps' does the trick. Y'all really should have enabled that by default to prevent breaking legacy installs >:[

**Comment by friday** [comment]
The old behavior and the Cinnamon Menu is breaking the spec.
