### ISSUE TITLE
Home directory filled with files named 'destination=1.XXX'

### ISSUE THREAD

**Issue by ayhon** [Ulauncher/Ulauncher#841]
### Steps to reproduce
1. Launch `ulaucher` and close it again

### Current behavior
Whenever I use `ulaucher`, it leaves a file on my home directory with the format `destination=1.XXX`, where `X` are digits.

### Expected behavior
No files generated on the home directory for every use of `ulauncher`

### Environment
**Ulauncher version**: v5.14.0
**Linux distro**: Fedora Workstation 35
**Desktop environment**: Sway

### Logs
Found over here:
https://gist.github.com/ayhon/06fa4bb948ac5a9e160488e070048819

**Comment by troycurtisjr** [comment]
This must be one of your extensions because I run in the same environment and do not get those files. Could you try uninstalling the extensions one by one to see if one of those is the culprit?

**Comment by ayhon** [comment]
It seems to be a problem of plugins in general. Whenever I have a plugin installed, whether it's [`ukil`](https://github.com/isacikgoz/ukill) or [`ulauncher-emoji`](https://github.com/Ulauncher/ulauncher-emoji), it generates these files.

**Comment by friday** [comment]
It's not Ulauncher doing this. The word "destination" is not used once in the entire Ulauncher code base. It's either an extension, or completely unrelated to Ulauncher or it's dependencies.

**Comment by ayhon** [comment]
Yeah, I know what you mean. I also checked in the project where the `destination` string was used in the project with no results, as well as in the extensions code.

 * https://github.com/rdnetto/ulauncher-sway/search?q=destination
 * https://github.com/brpaz/ulauncher-file-search/search?q=destination
 * https://github.com/Ulauncher/ulauncher-emoji/search?q=destination
 * https://github.com/isacikgoz/ukill/search?q=destination

The thing is, the only thing that's consistent is that
 1. It happens in `sway` and not GNOME (Something XWayland?)
 2. The file appears every time I upen up `ulauncher`

...

So, while I was typing this anser, I added 1 + 1 together and figured that the answer had to be in how I was toggling `ulauncher` in `sway`. I had this line on `.config/sway/config` which was messing everything up.
```config
set $menu ulauncher-toggle | xargs swaymsg exec --
```

So yeah, this had nothing to do with the project. My bad.

Thanks for the help and the replies though, who knows how much longer it would have taken me to realize if not for your help.

**Comment by friday** [comment]
Glad you could find the solution :)

**Comment by daveriedstra** [comment]
> I had this line on `.config/sway/config` which was messing everything up.

Thanks for mentioning this, I had the exact same issue somehow. For future visitors, replacing the line with

```
set $menu ulauncher-toggle
```

fixed things. Not sure where the original line came from :shrug:
