### ISSUE TITLE
Issues launching applications

### ISSUE THREAD

**Issue by friday** [Ulauncher/Ulauncher#854]
We are currently experiencing issues with Ulauncher's launching code. This is hard to debug/reproduce since it only affects some systems while others have been working perfectly.

Please be patient and if you want to help out by creating or commenting on this or related issues, please post logs and your systemd version, desktop environment and Ulauncher version. We have already received a lot of help, and are thankful about it, but most people seems to suggest solutions that are working for them and breaking for others, and that we already tested and ruled out. If you could be patient and revert things to a working state for you we will get this working very soon.

* [Wiki page on how app launching works in Ulauncher, and why it's so complicated](https://github.com/Ulauncher/Ulauncher/wiki/How-Ulauncher-launches-apps)
* Original PR introducing the new app launching logic: #778
* PR that fixed threads not being reaped after the processes exit: #813
* Most recent issue (misleading, because 5.14.0 didn't introduce this): https://github.com/Ulauncher/Ulauncher/issues/842

**Comment by mpldr** [comment]
Here are some logs and samples from trying to start mumble. Running it via the commandline works just fine.

Files:
- systemd protocol [`mumble-service.txt`](https://github.com/Ulauncher/Ulauncher/files/7531668/mumble-service.txt)
- my CLI environment [`env.txt`](https://github.com/Ulauncher/Ulauncher/files/7531709/env.txt)
- the generated systemd service: [`run-r3988b3e74a374810a48887466b004123.service`](https://github.com/Ulauncher/Ulauncher/files/7531720/run-r3988b3e74a374810a48887466b004123.service.txt)

WM is sway, Ulauncher version is 5.14.1.r0.gc1f5707-1

**Comment by mpldr** [comment]
Maybe a quick fix would be to allow using the "legacy" launch method

**Comment by mpldr** [comment]
Interestingly after writing a bisect script, it is now working just fine.
[bisect-script.sh.txt](https://github.com/Ulauncher/Ulauncher/files/7531999/bisect-script.sh.txt)

**Comment by friday** [comment]
[5.14.2](https://github.com/Ulauncher/Ulauncher/releases/tag/5.14.2) released. This release should fix the issue for most users and all users not using systemd to start Ulauncher (you would know if you use systemd for this).

Up until this point we have been moving towards switching the recommended way to run Ulauncher to systemd, because it's a more configurable and powerful way, than handles and restarts Ulauncher if it should crash and similar. This introduced a problem for us that meant we had to use `systemd-run` to launch apps, and this in turn introduced the issue with apps not launching at all for users with old systemd versions, and apparently some with newer versions were affected too (not fully sure why).

If you **had the issue on 5.14.0** and you **use systemd to run Ulauncher**, then you will still be affected by the issue. This is probably the best we can do, since we can't fix users systemd setups. You can try to fix it yourself looking at the systemd issue https://github.com/systemd/systemd/issues/3388, or just switch from systemd to using using Ulauncher's preferences to enable autostart (this option doesn't use systemd).

We will reevaluate our stance on recommending systemd and update our documentation where needed.
