### ISSUE TITLE
Sort shortcuts by name

### ISSUE THREAD

**Issue by thisdavej** [Ulauncher/Ulauncher#861]
Big fan of Ulauncher here!  I have a number of shortcuts, and it would be great if there was a way in the UI to show the shortcuts sorted alphabetically by name rather than in chronological order.

I created a Python script to sort the `$HOME/.config/ulauncher/shortcuts.json` file by name, but I could not figure out how to have the new version of the `shortcuts.json` file kick in, possibly since I was not successful in shutting down Ulancher completely.

Here's my python script for reference for sorting `shortcuts.json` by name:

```python
#!/usr/bin/env python

import json

input_file = "shortcuts.json"
output_file = "shortcuts2.json"

with open(input_file) as json_file:
    data = json.load(json_file)

sorted1 = sorted(data, key=lambda x: data[x]["name"])
sorted_dict = {k: data[k] for k in sorted1}
result = json.dumps(sorted_dict, indent=4)

with open(output_file, "w") as f:
    f.write(result)
```

**Comment by friday** [comment]
It's a reasonable request.
There are actually three places where the order would apply: The in-file order, the edit view, and the order they show up in the Ulauncher window. I think the order should be either alphabetical or based on how often you use them.

**Comment by friday** [comment]
I think #1008 is better, so I'm closing this.

This would let the user control the order default searches are suggested in, which is more important than the order they are shown in the preferences.
