### ISSUE TITLE
Preferences tabs on the right side can't be clicked with high scaling factor

### ISSUE THREAD

**Issue by friday** [Ulauncher/Ulauncher#862]
If I set my font scaling factor to 1.33 I can't click About.
If I set it to 1.50 I can't click Help or About.

It does work in dev mode (hot reload in actual browsers, and it worked when I misconfigured the foneawesome path so it wouldn't get loaded.

Happens on Ulauncher 5.14.2, but it happened in 5.11 also.
Arch with Gnome 40: Not Wayland, GTK+ 40 (but shows as 3.24.30 due to ow we load it)

**Comment by troycurtisjr** [comment]
To add some more data points.

Fedora 35, under Gnome 41 with 5.14.2 using gtk3-3.24.30-4.fc35.x86_64. In both Wayland and Xorg the help tab works fine for me, from the preference view and from the indicator icon. 

Is there any chance there could be some dev things (from `./ul init-dev-env`) that might be confusing things?

**Comment by friday** [comment]
No, but since you didn't have the issue I just figured out it was due to the font scaling factor (not strage considering it seemed fint related). Updated the topic and description.

**Comment by friday** [comment]
Fixed in the PR linked above
