### ISSUE TITLE
Browser launched when opening URLs close when Ulauncher exits

### ISSUE THREAD

**Issue by troycurtisjr** [Ulauncher/Ulauncher#863]
### Steps to reproduce
1. Don't have any browser open
2. Open a URL with ulauncher. Either using shortcuts (`wiki ...`) or from the Help preferences
3. Browser is opened to load the URL
4. Shutdown ulauncher
5. Browser windows shutdown

### Current behavior
Browser windows opened from URLs close when ulauncher exits

### Expected behavior
Browser windows remain open, independent of the the running status of ulauncher

### Environment
**Ulauncher version**: 5.14.2
**Linux distro**: Fedora 35
**Desktop environment**: Gnome 41

**Comment by troycurtisjr** [comment]
Looks like it only happens while running as a systemd service.

**Comment by friday** [comment]
Makes sense. We would need to wrap this in a conditional systemd-run call as well.

https://github.com/Ulauncher/Ulauncher/blob/ea06bc90116a1745b2314e51873beaf14855f07b/ulauncher/api/shared/action/OpenUrlAction.py#L16

**Comment by troycurtisjr** [comment]
Also, when using a shortcut (like `wiki ...`) which has to open the browser, the ulauncher window doesn't hide.

**Comment by friday** [comment]
> Also, when using a shortcut (like `wiki ...`) which has to open the browser, the ulauncher window doesn't hide.

That doesn't happen for me.

**Comment by friday** [comment]
This will also happen for OpenAction. I opened up a PR that replaces OpenURLAction with OpenAction, which makes this easier to fix, and also only one place to fix instead of two.

I don't know if this fixes https://github.com/Ulauncher/Ulauncher/issues/863#issuecomment-974670163 however.

**Comment by friday** [comment]
#953 should fix the main issue. Reopen or create a new issue if you still have the issue or the wiki shortcut issue.
