### ISSUE TITLE
Missing 'name' attribute in .ui file description

### ISSUE THREAD

**Issue by elpupi** [Ulauncher/Ulauncher#865]
User Interface (UI) files used by `Gtk.Builder` in `ulauncher` are using the attribute name `id` to set the objects' _id_.
However, in `css`, it is possible to select an object with its `#id` if the attribute name `name` is set in the `.ui` object definition.

For instance, in [`PreferencesUlauncherDialog.ui#L6`](https://github.com/Ulauncher/Ulauncher/blob/6c410ccbef1ce82747d8dc71ae5236272ec1abbe/data/ui/PreferencesUlauncherDialog.ui#L6), there is:

```xml
<object class="PreferencesUlauncherDialog" id="preferences_ulauncher_dialog">
...
</object>
```

If someone wants to select this object via `css`, the `name` attribute should be set instead:
```xml
<object class="PreferencesUlauncherDialog" id="preferences_ulauncher_dialog" name="preferences_ulauncher_dialog">
...
</object>
```
If in the source files, like in [Builder.py#L97](https://github.com/Ulauncher/Ulauncher/blob/6c410ccbef1ce82747d8dc71ae5236272ec1abbe/ulauncher/ui/windows/Builder.py#L97), you change

```name = ele_widget.attrib['id']```  by   ```name = ele_widget.attrib['name']```

you can delete the `id attribute` from the `.ui` file

### Environment
**Ulauncher version**: ulauncher 5.14.0
**Linux distro**: Ubuntu 21.10
**Desktop environment**: Gnome Shell 40

**Comment by friday** [comment]
If it doesn't break current functionality or themes you can make a PR. We're focusing on the v6 branch now, and probably won't make any releases for v5 unless it's critical fixes, and we won't make any v6 releases any time soon either, since it's not ready.

**Comment by friday** [comment]
I don't know if we even want our UI code to be easily themable, but if we do, it wouldn't hurt to get a justification why. After 3 years of development none of these files even exists.
