### ISSUE TITLE
Add Tasks and Calendars to ulauncher.

### ISSUE THREAD

**Issue by lcharles** [Ulauncher/Ulauncher#873]
### Description

HI everyone congratulations on this launcher I really like it and I would like to contribute to it.
Background:
Almost 2 years ago I ditched macOS for Windows and I till miss features from Launchbar such as the capability to add tasks that would sync with my mobile or to add events to a Calendar without switching to a full calendar app. I also run ubuntu in virtual machines all the time and this is how I discovered Ulauncher. The experience of not leaving your workflow to just add an event to a calendar or to fill your grocery list is in my opinion very enjoyable, not to mention that frontends for calendars and tasks applications are very mouse oriented which are very slow compared to a proper keyboard based ui.
Objectives:
- Create an extension to at least add events to Calendars from Ulauncher (+ list events and remove them if possible). Ideally the user would be able to choose between different calendars, before performing actions on them. (add event, list next 10 events, remove event). 
- The modifications could then be synced to Calendars online such as Google Microsoft or NextCloud.
- Create an extension to add tasks to Microsoft To-Do or Google Tasks or locally to Gnome-To-Do.

Options:
- Direct API for each provider: For the moment I have played with the Google APIs to list calendars and tasks in python. The Google API is nice but in my opinion this could really slow Ulauncher as listing calendars would require remote requests. And the app would require it's own api key which is already a burden to deal with (or users would need to their own). The Microsoft api has pretty much the same constraints. Level of difficulty to implement it: imho relatively easy but the result could be very poor. One advantage though is that these APIs tend to be relatively stable.
- Gnome comes with GOA to centralize credentials to online services, it is meant to be used by Gnome apps only to protect their api keys. This would solve the credentials problem, but I don't know if Ulauncher would be allowed to use them. This would still require every service to be implemented by hand.
- libecal: Gnome comes with the evolution data server which is already capable of syncing calendar events for all accounts registered with GOA. However I have no clue as to how it should be used from python. I've been skimming through the Gnome-Calendar code to try to understand how it is used in C, but for the moment I am still struggling. However at the moment libecal does not provide support for tasks providers, this would solve only the calendar side of the problem.
  - Gnome-To-Do can sync with google tasks however, but I don't know if they provide an API to add tasks from dbus.
  - Investing how Gnome-To-Do implements syncing is on my list for this week-end.

That is it for now, I welcome any feedback, and if anyone had prior experience with this issue I'll happily take it.

### Feature isn't already requested

- [X] I have checked the existing feature requests before suggesting this

**Comment by friday** [comment]
Thank you for taking the time to write this. We appreciate that. However, Ulauncher doesn't try to cover everyone's needs directly, but via the extension API. If it's possible to implement these extensions via Ulauncher, then our job is done.

**Comment by lcharles** [comment]
Yes it's my bad, I omitted the main reasons for me to post here, probably because I feel a bit lots with this pygobject thing.

The first reason is that I am not very familiar with pygobject and given my objective if anyone could spare 2 lines to hand wave me in the right direction I would really appreciate it. Anyone can think of a pygobject that would get me on the right track ?

The second reason is that I plan to do it from two sides at once. There is the backend side where I need to use Gnome calendars and tasks. But there is also a pure ui side, for which I will use google calendars and tasks as stubs with my own api key (+ if I fail on the backend this will work for me). But for anyone to test it I would need to make it public, which might not even be necessary if I can use the proper backends. 
So I decided that I could use my test quotas to register interested users to test the app before everything is working on the backend. Anyone would want to try that ? Is there a better place to reach the Ulaunchers users ?

There is also a third one, probably minor.
I was wondering if Ulauncher extensions were limited at 2 steps ? For instance in launchbar, you can explore the whole file tree from root as every menu returns either an action (open in finder) or other options (continue to explore other folders). 
Could this be done with Ulauncher ?

**Comment by friday** [comment]
Sorry if this come off as harsh, but you have the wrong approach to this. People don't hang around in our GitHub waiting for opportunities to help, beta test and have one-on-one to teach the API, and much less APIs unrelated to the GitHub page that they may not or even use/know themselves. You have to do all that work yourself, and get your extension shipped. Only at that point will people become involved in your project, but probably more to ask you for help or to ask you to do things for them. That's how all open source contributions work.

If you need help with PyGObject, the documentation is at https://lazka.github.io/pgi-docs/, but I don't know why you're asking that. We don't use that for our extensions.

Our extension documentation is here: http://docs.ulauncher.io/en/latest/extensions/intro.html
A more in depth tutorial can be found here: https://dev.to/brpaz/an-introduction-to-ulauncher-extension-development-1m69
You can look at existing extensions here if you find one that solves your needs or shows how you could solve part of them: https://ext.ulauncher.io/
For example there is https://ext.ulauncher.io/-/github-cmuench-ulauncher-todoist that seems to solve one of your needs, and it's using a python dependency for it, which is documented how to install on the github readme.

Ulauncher extensions can have as many steps as you want them to. They just generate a list of things and respond to activating one of the items, so you can generate a new list.

**Comment by lcharles** [comment]
> Sorry if this come off as harsh, but you have the wrong approach to this. People don't hang around in our GitHub waiting for opportunities to help, beta test and have one-on-one to teach the API, and much less APIs unrelated to the GitHub page that they may not or even use/know themselves. You have to do all that work yourself, and get your extension shipped. Only at that point will people become involved in your project, but probably more to ask you for help or to ask you to do things for them. That's how all open source contributions work.

Yes, I thought that maybe there was a community of extension writers that would hang around. But yes I should not have used the issue tracker for that. 
> If you need help with PyGObject, the documentation is at https://lazka.github.io/pgi-docs/, but I don't know why you're asking that. We don't use that for our extensions.

Because it seems to me that I will need it to interact with Gnome calendars and Tasks. I would prefer to do that as I think many people are using Google Calendar and using the Google API directly does not seem to be the right solution. You can only have a 100 users that you validate manually. After that Google requires your app to be public and they want to validate it. I would rather avoid that if I can. See [this project](https://github.com/bergercookie/taskw_gcal_sync for), the author has the same problem. And configuring a token for the Google APIs is a bit long to impose it on users.
> Our extension documentation is here: http://docs.ulauncher.io/en/latest/extensions/intro.html A more in depth tutorial can be found here: https://dev.to/brpaz/an-introduction-to-ulauncher-extension-development-1m69 You can look at existing extensions here if you find one that solves your needs or shows how you could solve part of them: https://ext.ulauncher.io/ 

> For example there is https://ext.ulauncher.io/-/github-cmuench-ulauncher-todoist that seems to solve one of your needs, and it's using a python dependency for it, which is documented how to install on the github readme.

This is something I know I can do, but I want to avoid this path. This is how I intend to start to experiment, but I would rather go through Gnome as explained before. 

> Ulauncher extensions can have as many steps as you want them to. They just generate a list of things and respond to activating one of the items, so you can generate a new list.

Great! I had a look at the doc and the sequence diagram and it did not show repetitions of event handling. So I assumed it was a 2 steps process like select the extension with the keyword then select the action and it is done.

Thank you for your time

**Comment by friday** [comment]
Ulauncher has a respectable share of users, but there's no active community page where you can "hang out" and ask for or provide help and/or feedback. We used to have a Gitter page for that but it went mostly unused. People rarely stayed to help others, and the format didn't really help us compared to asking questions here. Maybe we could find another type of community page, if people would use it, but I wouldn't know where.

**Comment by friday** [comment]
Sorry. I didn't mean to do that. I actually just opened up GitHub Discussions for Ulauncher and was trying to convert this to a "discussion", but it only locked it and gave me an error message.

**Comment by lcharles** [comment]
Ni worries, thank you for opening Github Discussions. I also think it is a more suitable way to connect a community than Gitter. 
I think you can close it anyway. I'll come back and post something there once I have something running properly.
