### ISSUE TITLE
Calculated value looks wrong when calc 2200/60

### ISSUE THREAD

**Issue by takeru1990** [Ulauncher/Ulauncher#874]
### Environment

Ubuntu 20.04

### Bug description

I'm using Ulauncher v5.14.2.

When calculating 2200/60, Ulauncher returns 36.666666666666664.
The last digit should be 7 or 6. I'm not sure where 4 comes from.🤔

Thanks.

### Issue isn't already reported

- [X] I have searched for similar issues before reporting this to avoid creating a duplicate issue

### Latest version

- [X] I am using the latest Ulauncher release

**Comment by friday** [comment]
It's very easy to fix this, but we are focusing our efforts on the new major version, and trying to avoid pushing more releases for Ulauncher v5 unless it's urgent fixes. This will be added to the v6 branch and won't be released for a while.

**Comment by friday** [comment]
This is now fixed in the Ulauncher v6 branch. It won't be released for a while, but we made a tracking issue if you want to be notified #869

**Comment by takeru1990** [comment]
I got it. Thanks!
