### ISSUE TITLE
Make a clear distinction between Ulauncher API and internals

### ISSUE THREAD

**Issue by friday** [Ulauncher/Ulauncher#920]
### Description

Currently extensions can import any part of Ulauncher. This means **any time we make any internal changes to our code it has the potential to break extensions**. Even if we only change internals not meant to be used by extensions. It also hogs up ram for no good reason, but this is secondary.

1. The Ulauncher API should be limited to `ulauncher.api`, with fatal errors if importing from another Ulauncher module [like this](https://github.com/imsakg/ulauncher-translator/blob/824037cd06fb56162c0d629020bdc4b70ce3d77e/main.py#L15).
2. `ulauncher.api` should be flattened into one directory, merging `ulauncher.api.client` and `ulauncher.api.shared`, but keeping backwards compatibility (`ulauncher.api.server` has been moves as of #917).
3. Any other part of `ulauncher.api` which is not meant to be consumed by extensions should be moved to `ulauncher.modes.extensions`
4. `ulauncher.api` should be self-contained if possible and not import Ulauncher internals or Glib (like `RenderResultListAction` in particular, but also other "actions" like `SetUserQueryAction` and `CopyToClipboardAction`) This is a big part of #285. Maybe it can import from `ulauncher.utils` though. If `ulauncher.api` is not self-contained` and has to import internal Ulauncher modules like now, __this means users have to import the ulauncher internals also to use types__, and the API documentation will "leak" Ulauncher internals, which is confusing for users. __We can't blame devs for using modules not meant for API usage__ until we fix this, because it's really our fault.
5. Actions and ResultItems don't need to be extended and have all these variants. All we need from them is a way for the extension to tell the app what to do (ex `pass this data to the "Copy" action`), but instead we now import the whole copy action, and all it's dependencies in the extension runtime, attach the data to be copied, serialize it with pickle, stream it with sockets to the server, deserialize it and run it on the other side.

### Enhancement isn't already requested

- [X] I have checked the existing Enhancement requests before suggesting this

**Comment by gornostal** [comment]
The first point is very interesting and will definitely be helpful to make sure only `api` module is used. I see how this can be implemented, although the approach will look more like a workaround. Basically, all non-`ulauncher.api` imports should register some global variable that will be read from `api.client.Extension.run()`. If the variable is set, the runner logs an error and does `sys.exit(1)`.
