### ISSUE TITLE
Implement support for any git host

### ISSUE THREAD

**Issue by petrarca-arezzo** [Ulauncher/Ulauncher#925]
### Environment

Manjaro stable, KDE Plasma

### Bug description

I just started to play around with ulauncher a bit and tried to install an extension from codeberg.org but there's nothing happening and no visual feedback on the UI at all. Could it be that ulauncher only works with github but not with other repositories like codeberg?

### Log output

```shell
file:///usr/share/ulauncher/preferences/dist/static/js/app.0dd3073b04e2c6559f28.js:4919:18: CONSOLE ERROR TypeError: e.cancel is not a function. (In 'e.cancel()', 'e.cancel' is undefined)
2021-12-10 17:25:53,656 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_extension_add() | Add extension: https://codeberg.org/Petrarca/ulauncher-ssh
2021-12-10 17:25:53,658 | ERROR | ulauncher.ui.windows.PreferencesUlauncherDialog: on_scheme_callback() | GithubExtensionError: Invalid GithubUrl: https://codeberg.org/Petrarca/ulauncher-ssh
```

### Issue isn't already reported

- [X] I have searched for similar issues before reporting this to avoid creating a duplicate issue.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension

### Latest version

- [X] I am using the latest Ulauncher release

**Comment by friday** [comment]
It's very hard coded to GitHub. Not easy to change. I want this as well, but it's very low on the prio list.

**Comment by petrarca-arezzo** [comment]
That's a pity. ulauncher actually looks quite interesting. I didn't expect this app to be so heavily dependent on Microsoft. Especially as an open source app you would think that you could offer extensions without Microsoft.
Anyway, it would be very nice if you could also use open repositories. For me that would probably be the highest priority ;-)

**Comment by petrarca-arezzo** [comment]
I just change a few small things in `GithubExtension.py` and got it to run with a Gitea instance (Codeberg in this example). In fact a few things are really hardcoded like for instance on lines 110, 144, or 151, but that could be easily changed. Attached a summary of the changes I made which might be handy in case at some point generic Git support might be implemented. Obviously the change simply replaces Github for Codeberg but doing a bit of if-then-else (switch-case) should be straighforward as well for more git instances.

```
line 15:
-DEFAULT_GITHUB_BRANCH = 'master'
+DEFAULT_GITHUB_BRANCH = 'main'

line 52:
-    url_match_pattern = r'^(https:\/\/github.com\/|git@github.com:)(([\w-]+\/[\w-]+))\/?(.git|tree\/master\/?)?$'
-    url_file_template = 'https://raw.githubusercontent.com/{project_path}/{branch}/{file_path}'
-    url_commit_template = 'https://api.github.com/repos/{project_path}/commits/{commit}'
+    url_match_pattern = r'^(https:\/\/codeberg.org\/|git@codeberg.org:)(([\w-]+\/[\w-]+))\/?(.git|tree\/main\/?)?$'
+    url_file_template = 'https://codeberg.org/{project_path}/raw/branch/{branch}/{file_path}'
+    url_commit_template = 'https://codeberg.org/api/v1/repos/{project_path}/branches/{commit}'
 
line 92:
-            'sha': resp['sha'],
-            'time': iso_to_datetime(resp['commit']['committer']['date'])
+            'sha': resp['commit']['id'],
+            'time': iso_to_datetime(resp['commit']['timestamp'], False)

line 110:
-        versions = self._read_json('master', 'versions.json')
+        versions = self._read_json( DEFAULT_GITHUB_BRANCH , 'versions.json')
 
line 144:
-        return 'https://github.com/%s/tarball/%s' % (self._get_project_path(), commit)
+        return 'https://codeberg.org/%s/archive/%s.tar.gz' % (self._get_project_path(), commit)
 
line 151:
-        return 'com.github.%s' % self._get_project_path().replace('/', '.').lower()
+        return 'org.codeberg.%s' % self._get_project_path().replace('/', '.').lower()
```

**Comment by petrarca-arezzo** [comment]
I just change a few small things in `GithubExtension.py` and got it to run with a Gitea instance (Codeberg in this example). In fact a few things are really hardcoded like for instance on lines 110, 144, or 151, but that could be easily changed. Attached a summary of the changes I made which might be handy in case at some point generic Git support might be implemented. Obviously the change simply replaces Github for Codeberg but doing a bit of if-then-else (switch-case) should be straightforward as well for more git instances.

```
line 15:
-DEFAULT_GITHUB_BRANCH = 'master'
+DEFAULT_GITHUB_BRANCH = 'main'

line 52:
-    url_match_pattern = r'^(https:\/\/github.com\/|git@github.com:)(([\w-]+\/[\w-]+))\/?(.git|tree\/master\/?)?$'
-    url_file_template = 'https://raw.githubusercontent.com/{project_path}/{branch}/{file_path}'
-    url_commit_template = 'https://api.github.com/repos/{project_path}/commits/{commit}'
+    url_match_pattern = r'^(https:\/\/codeberg.org\/|git@codeberg.org:)(([\w-]+\/[\w-]+))\/?(.git|tree\/main\/?)?$'
+    url_file_template = 'https://codeberg.org/{project_path}/raw/branch/{branch}/{file_path}'
+    url_commit_template = 'https://codeberg.org/api/v1/repos/{project_path}/branches/{commit}'
 
line 92:
-            'sha': resp['sha'],
-            'time': iso_to_datetime(resp['commit']['committer']['date'])
+            'sha': resp['commit']['id'],
+            'time': iso_to_datetime(resp['commit']['timestamp'], False)

line 110:
-        versions = self._read_json('master', 'versions.json')
+        versions = self._read_json( DEFAULT_GITHUB_BRANCH , 'versions.json')
 
line 144:
-        return 'https://github.com/%s/tarball/%s' % (self._get_project_path(), commit)
+        return 'https://codeberg.org/%s/archive/%s.tar.gz' % (self._get_project_path(), commit)
 
line 151:
-        return 'com.github.%s' % self._get_project_path().replace('/', '.').lower()
+        return 'org.codeberg.%s' % self._get_project_path().replace('/', '.').lower()
```

**Comment by petrarca-arezzo** [comment]
I just change a few small things in `GithubExtension.py` and got it to run with a Gitea instance (Codeberg in this example). In fact a few things are really hardcoded like for instance on lines 110, 144, or 151, but that could be easily changed. Attached a summary of the changes I made which might be handy in case at some point generic Git support might be implemented. Obviously the change simply replaces Github for Codeberg but doing a bit of if-then-else (switch-case) should be straightforward as well for more git instances.

```
line 15:
-DEFAULT_GITHUB_BRANCH = 'master'
+DEFAULT_GITHUB_BRANCH = 'main'

line 52:
-    url_match_pattern = r'^(https:\/\/github.com\/|git@github.com:)(([\w-]+\/[\w-]+))\/?(.git|tree\/master\/?)?$'
-    url_file_template = 'https://raw.githubusercontent.com/{project_path}/{branch}/{file_path}'
-    url_commit_template = 'https://api.github.com/repos/{project_path}/commits/{commit}'
+    url_match_pattern = r'^(https:\/\/codeberg.org\/|git@codeberg.org:)(([\w-]+\/[\w-]+))\/?(.git|tree\/main\/?)?$'
+    url_file_template = 'https://codeberg.org/{project_path}/raw/branch/{branch}/{file_path}'
+    url_commit_template = 'https://codeberg.org/api/v1/repos/{project_path}/branches/{commit}'
 
line 92:
-            'sha': resp['sha'],
-            'time': iso_to_datetime(resp['commit']['committer']['date'])
+            'sha': resp['commit']['id'],
+            'time': iso_to_datetime(resp['commit']['timestamp'], False)

line 110:
-        versions = self._read_json('master', 'versions.json')
+        versions = self._read_json( DEFAULT_GITHUB_BRANCH , 'versions.json')
 
line 144:
-        return 'https://github.com/%s/tarball/%s' % (self._get_project_path(), commit)
+        return 'https://codeberg.org/%s/archive/%s.tar.gz' % (self._get_project_path(), commit)
 
line 151:
-        return 'com.github.%s' % self._get_project_path().replace('/', '.').lower()
+        return 'org.codeberg.%s' % self._get_project_path().replace('/', '.').lower()
```

**Comment by friday** [comment]
This is just a hack to make it work for you, but overwrite them to work with Codeberg and remove support for Github. We would prefer if you could submit a PR that adds support for Codeberg and keeps it for GitHub.

There are three approaches here:
1. Implement support for **any** git remote URL: This will work for all remotes, but Ulauncher than has to depend on `git` or something like PyGit2 and clone repos rather than download tarballs. This can be very slow. Even if we can use --depth=1 it would need to clone the `.git` folder and either delete it or keep it for checking for new versions.
2. Implement support specifically for each git platform that we can/want to support like GitHub, GitLab, Gitea, Codeberg etc and use their APIs to download the tarball. All of these except GitHub support self-hosting, so if they are detected by their URLs this will fail however.
3. Do a combination of 1 and 2 which prefers to use the tarball but falls back to using `git clone` when using a custom unsupported platforms such as self-hosted.

**Comment by friday** [comment]
I ended up adding Gitea/Codeberg for it in the v6 branch (unrelreased). See the PR above and #869, so I'll close this. Follow the v6 issue for more updates (might take a while before a release).
