### ISSUE TITLE
Ulauncher doesn't start anymore with "no module named 'ulauncher'"

### ISSUE THREAD

**Issue by iago-lito** [Ulauncher/Ulauncher#930]
### Environment

$ uname -a -> Linux etak 5.15.7-arch1-1 #1 SMP PREEMPT Wed, 08 Dec 2021 14:33:16 +0000 x86_64 GNU/Linux

### Bug description

Ulauncher fails to launch with the following python error
```$ ulauncher
Traceback (most recent call last):
  File "/usr/bin/ulauncher", line 27, in <module>
    from ulauncher.main import main
ModuleNotFoundError: No module named 'ulauncher'
```

The package was installed with [yay](https://github.com/Jguer/yay) for [AUR](https://aur.archlinux.org/)
```
Name            : ulauncher
Version         : 5.14.2-1
Description     : Application launcher for Linux
Architecture    : any
URL             : https://ulauncher.io
Licenses        : GPL3
Groups          : None
Provides        : None
Depends On      : gobject-introspection-runtime  libkeybinder3  gtk3  webkit2gtk  libnotify  gdk-pixbuf2  wmctrl  python-dbus  python-levenshtein  python-pyinotify  python-websocket-client
                  python-pyxdg  python-gobject  python-cairo
Optional Deps   : libappindicator-gtk3: tray icon [installed]
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 5.79 MiB
Packager        : Unknown Packager
Build Date      : Mon 15 Nov 2021 09:18:17 AM CET
Install Date    : Mon 15 Nov 2021 09:18:26 AM CET
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : None
```

### Log output

```shell
$ ulauncher -v                                                                                                                                                                           1 ↵
Traceback (most recent call last):
  File "/usr/bin/ulauncher", line 27, in <module>
    from ulauncher.main import main
ModuleNotFoundError: No module named 'ulauncher'
```

### Issue isn't already reported

- [X] I have searched for similar issues before reporting this to avoid creating a duplicate issue.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension

### Latest version

- [X] I am using the latest Ulauncher release

**Comment by friday** [comment]
It's because Arch breaks AUR Python modules when you upgrade Python major version. You just need to rebuild ulauncher and other modules built for python 3.9

**Comment by iago-lito** [comment]
Great, reinstalling with yay and cleanBuild resolved the issue. Thanks <3

**Comment by friday** [comment]
Added to the comment above that you may wany to run this `pacman -Qo /usr/lib/python3.9/site-packages/*` to see other packages that was broken by the Python upgrade.

**Comment by ECon87** [comment]
It seems resolved but in my case I had to clean the `paru` cache as well. It seems obvious ex post, but at the time it did not.

**Comment by friday** [comment]
> It seems resolved but in my case I had to clean the `paru` cache as well. It seems obvious ex post, but at the time it did not.

Only if you don't cleanBuild.
