### ISSUE TITLE
Failed to fetch http://ppa.launchpad.net/agornostal/ulauncher

### ISSUE THREAD

**Issue by arximughal** [Ulauncher/Ulauncher#94]
I've been trying to install ulauncher for a couple of days now, but I am unable to install. 

Installing via ppa don't work at all and gives
`Failed to fetch http://ppa.launchpad.net/agornostal/ulauncher/ubuntu/dists/yakkety/main/binary-amd64/Packages  404  Not Found`

When I try to install via .deb package available on the ulauncher homepage, it don't work either!

**Comment by gornostal** [comment]
That repository is not supported. I've removed it from the site recently. 

Did instructions from the site not work for you? 
Could you give some more info please:
* OS you using
* Desktop environment
* Command you running to install the app
* Command output

We'll figure out how to fix the problem

**Comment by Cediddi** [comment]
Will you open a new ppa? It'd be much more convenient to just apt-get install ulauncher, also would keep most users up to date.

**Comment by gornostal** [comment]
I'm planning to update it next week.
I'll create a new ppa actually.
I'll post a link to this issue when it's done.

**Comment by gornostal** [comment]
Created PPA for dev releases `ppa:agornostal/ulauncher-dev`
PPA for stable releases will be available with the next stable release soon.

I would've created PPA under ulauncher name, but Launchpad give an error on login with another user :roll_eyes:

**Comment by CybVenom** [comment]
Hey @gornostal , why is it giving me a hard time to add the ulauncher repository to my kali linux machine.
ive tried "sudo add-apt-repository ppa:agornostal/ulauncher" and "sudo add-apt-repository ppa:agornostal/ulauncher-dev" but they are giving me a bunch of errors @gornostal
