### ISSUE TITLE
Keyboard shortcut to open preferences

### ISSUE THREAD

**Issue by RedBearAK** [Ulauncher/Ulauncher#942]
### Description

Desirable addition: A keyboard shortcut to access the preferences dialog. 

Suggested shortcut: `Ctrl+comma` (edit: I mistakenly put `Alt+comma`, this was wrong) 

This is the shortcut used by Albert launcher, and is similar to the nearly universal shortcut for preferences in macOS and some other Linux applications (Dolphin is the one I can think of offhand). 

I saw someone in the discussions forum also asking for this, but couldn't find an issue specifically about this. 

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing enhancement requests](https://github.com/Ulauncher/Ulauncher/labels/enhancement) before suggesting this.

**Comment by friday** [comment]
Yes #908 was asking for a way to solve the issue. I went through lots of issues and converted the ones like that which weren't concrete proposals to discussions. I think this is a good proposal to solve this issue.

**Comment by RedBearAK** [comment]
@friday 

The new GNOME Text Editor that is in development (link below) to replace Gedit has chosen the Ctrl+comma shortcut to open its preferences. I take this as a good sign this is being embraced as a general "preferences" shortcut. And it seems to be fairly common in newer GTK apps to use Ctrl+Shift+Slash (this tends to be shown as just Ctrl+? for brevity) to pull up the Keyboard Shortcuts overlay. So if that's something you wanted to enable in Ulauncher, I'd suggest that as the shortcut. 

The Keyboard Preferences overlay shortcut works for me both in the older Gedit app and the new GNOME Text Editor app, and Nautilus file manager.

You can show it as `Ctrl+?` if you want to display it visibly somewhere on the main window, but of course you should be testing for the user to press Ctrl+Shift+Slash (may vary on non-US keyboards). 

https://gitlab.gnome.org/GNOME/gnome-text-editor

**Comment by friday** [comment]
Fixed in https://github.com/Ulauncher/Ulauncher/commit/455e1c3a9e45b5303fe9fc690144e487972e4205 for the v6 branch

**Comment by friday** [comment]
About the keyboard shortcut overlay, that's a lot more work and not something we had planned to add. Sounds like a great feature, but probably best if you used a framework/library to auto generate it. We're only unpaid overworked volunteers and have to make compromises, so realistically I don't think that's ever getting added.

**Comment by RedBearAK** [comment]
@friday 

> About the keyboard shortcut overlay, that's a lot more work and not something we had planned to add. Sounds like a great feature, but probably best if you used a framework/library to auto generate it. We're only unpaid overworked volunteers and have to make compromises, so realistically I don't think that's ever getting added, but feel free to create a separate issue for it if you want.

I was about to say, "Not that important." And it's not, in the big scheme. But then I was looking in the Preferences window and was thinking, what if you just find a way to bring up the Preferences window but with the Shortcuts tab/view open if the user pressed `Ctrl-?`. It's literally a pre-existing shortcut overlay. Well, a shortcut list, anyway. And `Ctrl-?` could just be set as a faster way to get there. 

Just an idea. I have no idea if that would be a simple thing to do in GTK, the way Ulauncher is already designed. If you can call a tab/view in the Preferences window directly with a keyboard shortcut. Something like this happens in the GNOME Settings app, you can go directly to an individual "panel" within the combined app, like the Keyboard settings: 

```
gnome-control-center keyboard
```

But, absolutely not a big deal if there is no obvious, simple way to do it. 

A shortcut for the Preferences window alone is going to be a big improvement. So, thanks for that.
