### ISSUE TITLE
Ulauncher does not start anymore

### ISSUE THREAD

**Issue by MrMic** [Ulauncher/Ulauncher#945]
### Environment

Linux Ubuntu 20.04

### Bug description

Cannot launch the App anymore after the update!

- python-xdg and python3-xdg are installed ...

=== 8< --------------------------------------- >8 ===
Package: ulauncher
Priority: extra
Section: python
Installed-Size: 6132
Maintainer: Aleksandr Gornostal <ulauncher.app@gmail.com>
Architecture: all
Version: 5.14.2-0ubuntu1ppa1~focal
Recommends: gir1.2-ayatanaappindicator3-0.1
Depends: python3:any (>= 3.5~), libkeybinder-3.0-0, libgtk-3-0 (>= 3.10), gir1.2-gtk-3.0, gir1.2-keybinder-3.0 (>= 0.3), gir1.2-webkit2-4.0, gir1.2-glib-2.0, gir1.2-notify-0.7, gir1.2-gdkpixbuf-2.0, python3-gi, python3-gi-cairo, python3-dbus, python3-levenshtein, python3-pyinotify, python3-websocket, python3-xdg
Filename: pool/main/u/ulauncher/ulauncher_5.14.2-0ubuntu1ppa1~focal_all.deb
Size: 1360236
MD5sum: 9b296bb9ece8ff8b579d90f1973d6259
SHA1: e1519496dd4de5497b0dbd5a022719c39e157402
SHA256: e80b47e69ffb9b134b0f4276f9ee89297e24d19001b5ab8aaa6b681368e4f714
Description-en: Application launcher for Linux
 See https://ulauncher.io for more information
Description-md5: 3c46a92887ecf06295e7346afc9cee1e

It seems that it is looking for: xdg.BaseDirectory at the wrong place!

### Log output

```shell
Traceback (most recent call last):
  File "/bin/ulauncher", line 27, in <module>
    from ulauncher.main import main
  File "/usr/lib/python3/dist-packages/ulauncher/main.py", line 23, in <module>
    from ulauncher.config import get_version, get_options, CACHE_DIR, CONFIG_DIR, DATA_DIR
  File "/usr/lib/python3/dist-packages/ulauncher/config.py", line 17, in <module>
    from xdg.BaseDirectory import xdg_config_home, xdg_cache_home, xdg_data_dirs, xdg_data_home
ModuleNotFoundError: No module named 'xdg.BaseDirectory'
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Latest version

- [X] I am using the latest Ulauncher release.

**Comment by friday** [comment]
You must have done something to your system to remove pyxdg, install a conflicting package with pip or switch the Global Python version.

The package you need is named `python3-xdg` or `pyxdg` in pip.

**Comment by MrMic** [comment]
Saying "You must have done something to your system ...." does not solve anything.
As mentioned above: python-xdg, python3-xdg and pyxdg(with pip) are all 
installed ...

**Comment by friday** [comment]
Our package has the right dependency. It's working for everyone else and it hasn't been updated in a long time. If it's not working for you on your system that's not something we can fix. Try a reboot, uninstall and reinstall Ulauncher and the package, replace corrupted hard drives etc.

**Comment by MrMic** [comment]
How easy is it to close an issue when you do not want to dive deeper into it ...
Anyway, I notice that if I put on my shell:
$> export PYTHONPATH=/usr/lib/python3/dist-packages launcher

It works ...
But do not know how to persist with this workaround ...
