### ISSUE TITLE
Installing by command on the Debian distro.

### ISSUE THREAD

**Issue by iammrallblue** [Ulauncher/Ulauncher#946]
### Environment

Debian 11 bullseye

### Bug description

Install via PPA:
sudo add-apt-repository ppa:agornostal/ulauncher && sudo apt update && sudo apt install ulauncher

When I try to install by using PPA, the output log shows errors as below.
did anyone have the same error and share the fixing solution

### Log output

```shell
❯ sudo add-apt-repository ppa:agornostal/ulauncher && sudo apt update && sudo apt install ulauncher


Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 91, in get_sources
    raise NoDistroTemplateException(
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Debian/n/a
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Latest version

- [X] I am using the latest Ulauncher release.

**Comment by friday** [comment]
That's the Ubuntu installation instructions. See #711
