### ISSUE TITLE
Error building docker image in v6 branch

### ISSUE THREAD

**Issue by the-allanc** [Ulauncher/Ulauncher#947]
### Environment

Ubuntu 20.04

### Bug description

Ran `docker build` on my machine so that I could then make code changes, but it fails on step 8 of the build. The output ends with
```
yarn install v1.22.17
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning bootstrap-vue > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
warning webpack-hot-middleware > querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
[3/5] Fetching packages...
error @npmcli/fs@1.1.0: The engine "node" is incompatible with this module. Expected version "^12.13.0 || ^14.15.0 || >=16". Got "10.24.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c pip3 install -r requirements.txt &&     pip3 install -r docs/requirements.txt &&     yarn &&     mv node_modules /var' returned a non-zero code: 1
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Latest version

- [X] I am using the latest Ulauncher release.

**Comment by friday** [comment]
You don't need Docker for v6, but if you want to build it, you can check out the dev branch, build and check out v6 again.

**Comment by the-allanc** [comment]
> You don't need Docker for v6, but if you want to build it, you can check out the dev branch, build and check out v6 again.
I did try that, but Docker builds are deterministic, so that didn't really make a difference.

Regarding the motivation of why I'm trying it - when I was making other changes, the guidelines for pull requests mentioned that tests would be passing, and then when I tried to run tests locally, I got the following notice:

```WARNING: It's recommended to run tests in a docker container to be sure they will also pass in CI```

I don't mind either way whether I should be using Docker or not, but if we're encouraged to write tests, and the test command recommends us to use Docker, then it probably should work. :grinning:

**Comment by friday** [comment]
Oh yeah. I forgot about that. Read and ignored it so many times.

**Comment by friday** [comment]
Removed the warning. Docker is a great tool to lock things down so you make sure everyone has the same environment. For these tests, the testing dependencies will sometimes update and pylint in particular tend to add new checks to warn about that would give you more warnings on a newer version. But if the tests pass on a newer version they tend to pass on older versions. If you add code that doesn't work on Python 3.6 both mypy and pylint tends to complain.

People can develop and test locally using their version of Python, and if they get an error from the CI server, I think this is not a problem, but a time saving measure. The CI server optimally should test for all supported environments and Python versions anyway, and we definitely don't want users to have to do that.
