### ISSUE TITLE
Add Alt+0 (Alt+zero) as part of the results shortcuts

### ISSUE THREAD

**Issue by RedBearAK** [Ulauncher/Ulauncher#950]
### Description

Please consider adding the zero key at the end of the 1-9 Alt-key keyboard shortcuts to access search list results. 

Alt+1
Alt+2
Alt+3
Alt+4
Alt+5
Alt+6
Alt+7
Alt+8
Alt+9
_**Alt+0**_
Alt+a
Alt+b
Alt+c ...

Since they are just shortcuts and the numbers and letters don't actually mean anything specific, I see no obvious reason that the zero key can't be added and be a useful shortcut for the tenth item on the results list, before moving on to the a-z letter keys. 

The number key row format of 1-2-3-4-5-6-7-8-9-0 seems to be fairly standard even with international keyboards, so it should be an intuitive addition to the available keyboard shortcuts, even for non-US keyboard users. The shortcuts are displayed on each line of results, so there would be no need for any user to "learn" the new shortcut or remember it. They'll just see it displayed after the `Alt+9` and before the `Alt+a` shortcuts. 

This would also mean that the user could display up to 10 frequently used apps and all of the keyboard shortcuts shown would be numeric, all on the same keyboard row. I think some users might find that very pleasant, in a way. 

I would like to see this added to the current version of Ulauncher, but at the very least I'd like this to be considered as an addition to the v6 release. 

I tried changing the line in `ulauncher/ui/ResultItemWidget.py` that seems to be responsible for assigning the keyboard shortcuts from this: 

```
    def set_index(self, index):
        """
        Set index for the item and assign shortcut
        """
        self.index = index
        # Alt+1..9, then Alt+a..z
        index_text = index + 1 if index < 9 else chr(97 + index - 9)
        self.shortcut = 'Alt+%s' % index_text
        self.set_shortcut(self.shortcut)
```

To this: 

```
    def set_index(self, index):
        """
        Set index for the item and assign shortcut
        """
        self.index = index
        # Alt+1..9, then Alt+a..z
        index_text = index + 1 if index < 9 else index - 9 if index == 9 else chr(97 + index - 10)
        self.shortcut = 'Alt+%s' % index_text
        self.set_shortcut(self.shortcut)
```

This results in an `Alt+0` shortcut showing on the list after the `Alt+9` and before the `Alt+a` shortcut, but the line labeled with `Alt+0` still responds to `Alt+a` and the `Alt+0` shortcut does nothing. So there is obviously something I'm really not understanding about exactly how the shortcut is assigned to each line in the results window. 

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing enhancement requests](https://github.com/Ulauncher/Ulauncher/labels/enhancement) before suggesting this.

**Comment by friday** [comment]
I have no real opinion on this. Sounds good, but it's not my design originally and I don't even use these. Would like more input, so please upvote if you are reading this and agree.

**Comment by RedBearAK** [comment]
@friday 

Figured out where the functional shortcuts are actually assigned. It's in `ui/windows/UlauncherWindow.py`.

I changed this part: 

```
            elif alt and keyname.isdigit() and 0 < int(keyname) < 10:
                # on Alt+<num>
                try:
                    self.enter_result_item(int(keyname) - 1)
                except IndexError:
                    # selected non-existing result item
                    pass
            elif alt and len(keyname) == 1 and 97 <= ord(keyname) <= 122:
                # on Alt+<char>
                try:
                    self.enter_result_item(ord(keyname) - 97 + 9)
                except IndexError:
                    # selected non-existing result item
                    pass
```

To this:

```
            elif alt and keyname.isdigit() and 0 < int(keyname) < 10:
                # on Alt+<num> (digits 1-9)
                try:
                    self.enter_result_item(int(keyname) - 1)
                except IndexError:
                    # selected non-existing result item
                    pass
            elif alt and keyname.isdigit() and int(keyname) == 0:
                # on Alt+0 (digit 0/zero)
                try:
                    self.enter_result_item(int(keyname) + 9)
                except IndexError:
                    # selected non-existing result item
                    pass
            elif alt and len(keyname) == 1 and 97 <= ord(keyname) <= 122:
                # on Alt+<char> (letters a-z)
                try:
                    self.enter_result_item(ord(keyname) - 97 + 10)
                except IndexError:
                    # selected non-existing result item
                    pass
```

That seems to make everything finally work as expected, when combined with the change to `ResultItemWidget.py`. Items labeled Alt+8/9/0/a/b all seem to be activated correctly now by the corresponding shortcut. This logic turns zero into "10" to mirror the keyboard order as suggested, and then adds ten instead of nine to the letters, shifting them all down the item list by one. 

This probably doesn't mean much but pylint doesn't show any major issue on the related lines (lines 184-210 in my edited file). 

Pylint snippet: 

```
UlauncherWindow.py:178:4: C0116: Missing function or method docstring (missing-function-docstring)
UlauncherWindow.py:225:4: C0116: Missing function or method docstring (missing-function-docstring)
```

I don't know anything else to do in order to test this and make sure it won't break anything. 

Comments?

**Comment by RedBearAK** [comment]
@friday 

It appears the Ulauncher contribution requirements are not something I can figure out how to conform to just yet. I tried to do a PR based on the `v6` branch but it turned out quite weird. Possibly because I initially forked off the main branch. I deleted my fork and might try again later with a clean fork of just the `v6` branch. 

Anyway, these are the changes I would be submitting if I can ever figure out how to do the PR: 

`ulauncher/ui/ResultWidget.py`

Original: 

```
    def set_index(self, index):
        """
        Set index for the item and assign shortcut
        """
        self.index = index
        # Alt+1..9, then Alt+a..z
        index_text = index + 1 if index < 9 else chr(97 + index - 9)
        self.shortcut = f"Alt+{index_text}"
        self.set_shortcut(self.shortcut)
```

Updated: 

```
    def set_index(self, index):
        """
        Set index for the item and assign shortcut
        """
        self.index = index
        # Alt+1..9, then Alt+0 (zero), then Alt+a..z
        index_text = index + 1 if index < 9 else index - 9 if index == 9 else chr(97 + index - 10)
        self.shortcut = 'Alt+%s' % index_text
        self.set_shortcut(self.shortcut)
```

`ulauncher/ui/windows/UlauncherWindow.py`

Original: 

```
            elif alt and keyname.isdigit() and 0 < int(keyname) < 10:
                # on Alt+<num>
                try:
                    self.enter_result(int(keyname) - 1)
                except IndexError:
                    # selected non-existing result item
                    pass
            elif alt and len(keyname) == 1 and 97 <= ord(keyname) <= 122:
                # on Alt+<char>
                try:
                    self.enter_result(ord(keyname) - 97 + 9)
                except IndexError:
                    # selected non-existing result item
                    pass
```

Updated: 

```
            elif alt and keyname.isdigit() and 0 < int(keyname) < 10:
                # on Alt+<num> (digits 1-9)
                try:
                    self.enter_result_item(int(keyname) - 1)
                except IndexError:
                    # selected non-existing result item
                    pass
            elif alt and keyname.isdigit() and int(keyname) == 0:
                # on Alt+0 (digit 0/zero)
                try:
                    self.enter_result_item(int(keyname) + 9)
                except IndexError:
                    # selected non-existing result item
                    pass
            elif alt and len(keyname) == 1 and 97 <= ord(keyname) <= 122:
                # on Alt+<char> (letters a-z)
                try:
                    self.enter_result_item(ord(keyname) - 97 + 10)
                except IndexError:
                    # selected non-existing result item
                    pass
```

**Comment by friday** [comment]
Thank you for trying to implement this. If you fork from v6 it shouldn't be a problem.

I think the original code was problematic, because you need to change in two places, so I clean it up a bit first: 212530388758364ebb2a5f7d8c67fc9222081dc5, which made it way easier implement

Added to v6. As mentioned I don't think this is objectively better, but I also don't mind :)

**Comment by friday** [comment]
Actually, I was overthinking. It was even easier: https://github.com/Ulauncher/Ulauncher/commit/dfd476166b0d7c5e75ad59e516dfaf17350a812e

**Comment by RedBearAK** [comment]
@friday 

Looks like a very succinct and elegant solution. Putting the key definitions in a central place was a great idea. 

Thanks for taking some time to work on that.
