### ISSUE TITLE
Change the functionality of the "jump keys" to select, but not launch the item

### ISSUE THREAD

**Issue by friday** [Ulauncher/Ulauncher#965]
### Description

Migrated from #964

> I would also prefer if the command didn't activate the item directly, but selects them like you do with the arrow keys or tab now (or ctrl+p/n). Then you get the visual confirmation before it does something, and you can do more than just launch the main action. Currently some actions have alt actions that you trigger with alt-enter, and I would prefer to be able to add to that via #326 and #476, and also add a "delete" (or "backspace") action for where it applies.

This change is probably inevitable for forward compatibility with a planned context menu, aimed to substitute alt+enter, so you see what you do before you do it. It's also forward compatible with planned support for scrolling (I already have that working locally). You could skip to the next "page" of items outside of the visible view, but launching something in the next "page" outside of the visible view doesn't make sense.

We could still add Ctrl+Alt+jump or maybe Alt+Shift+jump for the old behavior, but that wouldn't save you any key press as compared to hitting Alt+jump then Enter.

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing enhancement requests](https://github.com/Ulauncher/Ulauncher/labels/enhancement) before suggesting this.

**Comment by RedBearAK** [comment]
@friday 

I am on board with making Ulauncher more easily able to choose different branch behaviors to perform on a results item, as opposed to a straight "launch/open". I often want to at the very least do "Open in location", or sometimes open a file with a non-default app. And that's just from a basic app launcher and file/folder search/browser perspective. 

So this sounds pretty good to me. 

>Ctrl+Alt+jump or maybe Alt+Shift+jump

From my perspective I would strongly prefer the Alt+Shift+jump physical key positions. Ctrl+Shift would automatically work in a Mac-like way for me with Kinto's basic "all GUI apps" remapping, by moving to physical Alt+Shift. Alt+Shift would be easily remappable to continue to use the physical Alt+Shift keys under Kinto. And no more collisions with the text shortcuts. 

But if you did something like Ctrl+Alt I would not like that physical key position and would probably choose to remap it to physical Alt+Shift (equivalent of Cmd+Shift on a Mac). It's much easier to use that position while maintaining a "home keys" hand position and a good touch typing flow. That would leave Ulauncher behaving differently with Kinto enabled vs disabled. 

Not that any of this would matter to anyone but Kinto users. But that is actually a swiftly growing group. A lot of people actually like the macOS keyboard shortcut scheme, and are very happy that there is finally something that works really well to bring that to Windows and Linux. It would be fantastic if one of the best equivalents to Spotlight for Linux worked well with Kinto without a lot of remapping fuss.

**Comment by friday** [comment]
I think if we don't add any keyboard combination for the jump behavior people will likely request one, and we can see the consensus on which combination they prefer. Or if it turns out people can get used to Alt+jump+Enter that's better imo.

**Comment by friday** [comment]
Implemented in the v6 branch (see commit)
