### ISSUE TITLE
can't install gir1.2-webkit2-3.0, only gir1.2-webkit2-4.0

### ISSUE THREAD

**Issue by SevenWalnut** [Ulauncher/Ulauncher#97]
I try dpkg-deb to repackage the deb, changing  gir1.2-webkit2-3.0 to gir1.2-webkit2-4.0 in control file.
And it works! Everything is fun.
by the way, well done!

**Comment by gornostal** [comment]
Thanks @SevenWalnut.

What OS are you using?

**Comment by SevenWalnut** [comment]
Ubuntu 17.04 Daily Build on 2017-02-28.

**Comment by gornostal** [comment]
Hm... I haven't tested on 17.04. I'll look into it

**Comment by HealingTek** [comment]
I have the same issue on Debian Testing.

**Comment by 0versun** [comment]
The same problem on Deepin 15.4 beta(based on debian )

**Comment by gornostal** [comment]
This should be fixed soon.
Installing Deepin 15.4 to verify

**Comment by gornostal** [comment]
Should be fixed now.
https://github.com/Ulauncher/Ulauncher/releases/download/2.0.30.r3/ulauncher_2.0.30.r3_all.deb

**Comment by 0versun** [comment]
Hi, I do confirm, its fix now. Thanks a lot!
