### ISSUE TITLE
Warning in .xsession-errors file: 'Gtk was imported without specifying a version first'

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [Ulauncher/Ulauncher#98]
`/usr/lib/python2.7/dist-packages/ulauncher/__init__.py:6: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.`

OS: Linux Mint 18.1 xenial x86_64 
Kernel: 4.8.0-39-generic 
DE: Cinnamon 
WM: Mutter (Muffin) 
CPU: Intel 2 Duo T7500 (2) @ 2.2GHz 
GPU: Intel Integrated Graphics 

Ulauncher 2.0.13

**Comment by gornostal** [comment]
Warnings like this week remain appearing in the logs because I don't want to hardcode versions. 
Different OSs may have different WebkitGtk2 for example
