### ISSUE TITLE
Hotkey

### ISSUE THREAD

**Issue by AnuragDixitt** [Ulauncher/Ulauncher#980]
### Environment

linux mint 20.3

### Bug description

I am not able to set the default key as alt+space

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Latest version

- [X] I am using the latest Ulauncher release.

**Comment by friday** [comment]
Please check #100 and use the issue search for "hotkey" and/or "alt+space" if you still need help after that.
